#!/usr/bin/env bash
# shellcheck disable=SC2015,SC2039,SC2166,SC3043
VERBOSITY=0
TEMP_D=""

stderr() { echo "$@" 1>&2; }
fail() { local r=$?;  [ $r -eq 0 ] && r=1; failrc "$r" "$@"; }

Usage() {
    cat <<EOF
Usage: ${0##*/} [ options ] cloud out-dir

   cloud is one of 'aws', 'azure', 'gcp', 'qemu'

   options:
      --test-arch ARCH     install deps needed for testing ARCH
                           [x86_64, aarch64, ALL] - default ALL

      --wolfi-vm DIR       where is the wolfi-vm top level dir
                           [required] used for finding output and other things.
EOF
}

bad_Usage() { Usage 1>&2; [ $# -eq 0 ] || stderr "$@"; return 1; }
cleanup() {
    [ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
}

main() {
    local short_opts="hv"
    local long_opts="help,test-arch:,wolfi-vm:,verbose"
    local getopt_out=""
    getopt_out=$(getopt --name "${0##*/}" \
        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { bad_Usage; return; }

    local cur="" next="" testarches="" arch="" outd="" cloud="" wolfivmd=""

    while [ $# -ne 0 ]; do
        # shellcheck disable=SC2034
        { cur="$1"; next="$2"; }
        case "$cur" in
            -h|--help) Usage ; exit 0;;
               --wolfi-vm) wolfivmd=$next; shift;;
               --test-arch) testarches=$next; shift;;
            -v|--verbose) VERBOSITY=$((VERBOSITY+1));;
            --) shift; break;;
        esac
        shift;
    done

    [ $# -eq 2 ] || { bad_Usage "got $# args [$*], expected 2"; return 1; }
    cloud="$1"
    outd="$2"

    [ -n "$wolfivmd" ] || { bad_Usage "--wolfi-vm is required"; return 1; }
    [ -d "$wolfivmd" ] || { stderr "--wolfi-vm '$wolfivmd' is not a dir"; return 1; }

    if [ "$testarches" = "" -o "$testarches" = "ALL" ]; then
        testarches="x86_64 aarch64"
    fi

    for arch in $testarches; do
        case "$arch" in
            x86_64|aarch64) continue;;
            *) fail "unknown arch $arch";;
        esac
    done

    [ -d "$outd" ] || mkdir -p "$outd" ||
        fail "could not create $outd"

    echo "Testing for cloud=$cloud with wolfi-vm dir at $wolfivmd"
    echo "Does not do anything just yet"
}

main "$@"
# vi: ts=4 expandtab
