#!/usr/bin/env bash
# shellcheck disable=SC2015
# To be sourced by test-wolfi-vm

bad_gcp_usage() { gcp_usage 1>&2; [ $# -eq 0 ] || stderr "$@"; return 1; }

gcp_usage() {
    cat <<EOF
Usage: ${0##*/} [ options ] cloud out-dir -- [ gcp options ]

    gcp options:
        --disk-size SIZE                     size of the boot disk in Gb, default 10
        --disk-type TYPE                     GCE disk type to use, default pd-balanced
        --image-name NAME                    name of image under test
        --image-project NAME                 GCP project where the image is hosted
        --image-version VERSION              image version under test
        --label LABEL                        label to apply to resources
        --machine-type TYPE                  GCE machine type, default e2-standard-2
        --name NAME                          name of the instance
        --project PROJECT                    GCP project ID
        --service-account ACCOUNT            service account to attach to the VM
        --source-image-uri URI               image or image family URI (can be used in place of image-project, image-name, and image-version)
        --ssh-user USER                      ssh user to connect with, default root
        --vpc-network NETWORK                VPC network to use for the VM
        --zone ZONE                          GCE zone for resources

EOF
}

cleanup_gcp() {
    runner="$TOP_D/runner/gcp"
    vr "$runner" teardown
}

setup_gcp() {
    runner="$TOP_D/runner/gcp"
    vr "$runner" setup
}

test_gcp() {
    local short_opts="h"
    local long_opts="help,disk-size:,disk-type:,image-name:,image-project:,image-version:,label:,machine-type:,name:,project:,service-account:,source-image-uri:,ssh-user:,vpc-network:,zone:"
    local getopt_out=""
    getopt_out=$(getopt --options "${short_opts}" \
        --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { bad_gcp_usage; return; }

    local cur="" next=""
    local disk_size="10" disk_type="pd-balanced" image_name="" image_project="" image_version="" label="test" machine_type="e2-standard-2" name="" project="" service_account="default" source_image_uri="" ssh_user="root" vpc_network="default" zone="us-central1-a"
    while [ $# -ne 0 ]; do
        { cur="$1"; next="$2"; }
        case "$cur" in
               --help) gcp_usage ; exit 0;;
               --disk-size) disk_size="$next"; shift;;
               --disk-type) disk_type="$next"; shift;;
               --image-name) image_name="$next"; shift;;
               --image-project) image_project="$next"; shift;;
               --image-version) image_version="$next"; shift;;
               --label) label="$next"; shift;;
               --machine-type) machine_type="$next"; shift;;
               --name) name="$next"; shift;;
               --project) project="$next"; shift;;
               --service-account) service_account="$next"; shift;;
               --source-image-uri) source_image_uri="$next"; shift;;
               --ssh-user) ssh_user="$next"; shift;;
               --vpc-network) vpc_network="$next"; shift;;
               --zone) zone="$next"; shift;;
            --) shift; break;;
        esac
        shift;
    done

    [ -n "$image_name" ] || { bad_gcp_usage "--image-name is required"; return 1; }
    [ -n "$image_project" ] || { bad_gcp_usage "--image-project is required"; return 1; }
    [ -n "$image_version" ] || { bad_gcp_usage "--image-version is required"; return 1; }
    [ -n "$project" ] || { bad_gcp_usage "--project is required"; return 1; }
    [ -n "$zone" ] || { bad_gcp_usage "--zone is required"; return 1; }

    # wolfivmd is unused for now
    # shellcheck disable=SC2034
    local wolfivmd="$1" outd="$2" testarches="$3"
    shift 3

    setup_gcp || return 1
    # shellcheck disable=SC2064
    # Expanding now is fine, these are static
    trap "cleanup_gcp '$name' '$project' '$zone'" EXIT

    TEMP_D=$(mktemp -d) || return
    runner="$TOP_D/runner/gcp"
    rund="$TEMP_D/run"
    mkdir "$rund" || return

    key="$rund/id_ed25519"
    rq ssh-keygen -t ed25519 -N '' -f "$key" ||
        { stderr "failed creating ssh key"; return 1; }

    local vmnames="$image_name-$image_version"
    local vmname="" arch=""
    # shellcheck disable=SC2034
    local tfile="" tname="" vfails="" voutd="" fails="" serialconsolepid=
    for arch in $testarches; do
            if [ "$arch" = "x86_64" ]; then
                local image_arch="amd64"
            elif [ "$arch" = "aarch64" ]; then
                local image_arch="arm64"
            fi
        for vmname in $vmnames; do
            vfails=""
            voutd="$outd/$arch/$vmname"
            if [ "$source_image_uri" = "" ]; then
                local source_image_uri="projects/$image_project/global/images/$image_name-$image_arch-$image_version"
            fi
            rq mkdir -p "$voutd" || { stderr "failed creating $voutd"; return 1; }
            # Start VM
            vr "$runner" launch --disk-size="$disk_size" --disk-type="$disk_type" --name="$vmname" \
                --label="$label" --machine-type="$machine_type" --project="$project" --public-key="$key.pub" \
                --service-account="$service_account" --source-image-uri="$source_image_uri" --ssh-user="$ssh_user" \
                --vpc-network="$vpc_network" --zone="$zone"
            local launch_code=$?

            if [ $launch_code -eq 0 ]; then
                vr "$runner" --timeout="${WAIT_SSH_TIMEOUT}" wait-for-ssh --name="$vmname" --project "$project" --zone="$zone" || {
                    # If we do fail here, we still want to continue on so the VM can be cleaned up
                    log "failed to wait for ssh"
                    vfails="$vfails $arch-$vmname/wait-for-ssh"
                }

                log "started testing $arch/$vmname"
                # Run tests, collect metrics
                for tfile in "${TOP_D}/test/$arch"/*; do
                    tname=${tfile##*/}
                    vrl "$voutd/test-$tname" "$runner" run-remote --name="$vmname" --file="$tfile" --private-key="$key" \
                        --project="$project" --user="$ssh_user" --zone="$zone" -- -test.v -metric-tags "arch:$arch,$METRIC_TAGS" ||
                           vfails="$vfails $arch-$vmname/test-$tname"

                    "$runner" ssh --name="$vmname" --private-key="$key"  --project="$project" --user="$ssh_user" --zone="$zone" \
                        "cat $METD/$tname" \
                           > "$voutd/$tname-metrics.json" ||
                           vfails="$vfails $arch-$vmname/$tname-metrics"
                done
                log "finished testing $arch/$vmname"
            else
                log "vm launch failed"
                vfails="$vfails $arch-$vmname/launch"
            fi

            # Save console log output
            vr "$runner" console-log --name="$vmname" --project="$project" --zone="$zone" > "$voutd/console.log" || {
                log "failed to get console log"
                vfails="$vfails $arch-$vmname/console-log"
            }

            # Terminate VM
            vr "$runner" terminate --name="$vmname" --project="$project" --zone="$zone" || {
                log "failed to terminate vm"
                vfails="$vfails $arch-$vmname/terminate"
            }

            vfails=${vfails# }
            if [ -z "$vfails" ]; then
                log "finished $arch/$vmname PASS"
            else
                log "finished $arch/$vmname FAIL - $vfails"
            fi
        done
        fails="${fails:+$fails }$vfails"

    done

    if [ -z "$fails" ]; then
        log "PASS - no failures"
        return 0
    fi
    log "FAIL - $fails"
    return 1
}
