#!/usr/bin/env bash
# shellcheck disable=SC2015,SC2039,SC2166,SC3043
VERBOSITY=0
TEMP_D=""
TOP_D=$(cd "${0%/*}/.." && pwd)
WAIT_SSH_TIMEOUT=${WAIT_SSH_TIMEOUT:-5m}
METD="/tmp/chainguard-vmtest-metrics"

stderr() { echo "$@" 1>&2; }
fail() { local r=$?;  [ $r -eq 0 ] && r=1; failrc "$r" "$@"; }

Usage() {
    cat <<EOF
Usage: ${0##*/} [ options ] cloud out-dir

   cloud is one of 'aws', 'azure', 'gcp', 'qemu'

   options:
      --test-arch ARCH     install deps needed for testing ARCH
                           [x86_64, aarch64, ALL] - default ALL

      --wolfi-vm DIR       where is the wolfi-vm top level dir
                           [required] used for finding output and other things.
EOF
}

bad_Usage() { Usage 1>&2; [ $# -eq 0 ] || stderr "$@"; return 1; }
cleanup() {
    [ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
}

cleanup_qemu() {
    [ -z "$RUNNERPID" ] || kill "$RUNNERPID"
    cleanup
}

log() {
    local now=""
    now=$(date -R)
    echo "$now:" "$@" >> "$LOG"
    echo "$now:" "$@"
}

# vr(cmd) - run cmd, log execution and result. stdout and stderr unmodified.
vr() {
    local rc="" sstart=$SECONDS
    log "execute: $*"
    "$@"
    rc=$?
    log ":: exit $rc [$((SECONDS-sstart))s]"
    return $rc
}

# vrl(output, cmd) - verbose run log.
#   run cmd with output to output.stdout and output.stderr
vrl() {
    local output="$1" rc="" sstart=$SECONDS
    shift
    log "execute: $*"
    "$@" >"$output.stdout" 2>"$output.stderr"
    rc=$?
    log ":: exit $rc [$((SECONDS-sstart))s]"
    return $rc
}

# rq(cmd) - run cmd quietly unless it fails
rq() {
    local rc="" out=""
    out=$("$@" 2>&1) && return 0
    rc=$?
    stderr "failed [$rc]: $*"
    printf "%s\n" "$out" | sed -e 's,^,> ,' 1>&2
    return $rc
}

test_qemu() {
    RUNNERPID=""
    local wolfivmd="$1" outd="$2" arch="" rund="" key="" vmname
    local runner="${TOP_D}/runner/qemu"
    shift 2
    local vmnames=generic arches=""
    arches=( "$@" )

    TEMP_D=$(mktemp -d) || return
    trap cleanup_qemu EXIT

    rund="$TEMP_D/run"
    mkdir "$rund" || return

    log "making builder/ovmf-<arch>.fd for ${arches[*]}"
    for arch in "${arches[@]}"; do
        rq make -C "$wolfivmd" "builder/ovmf-$arch.fd" || {
            stderr "failed creating builder/ovmf-$arch in $wolfivmd"
            return 1
        }
    done

    key="$rund/id_ed25519"
    rq ssh-keygen -t ed25519 -N '' -f "$key" ||
        { stderr "failed creating ssh key"; return 1; }

    local vmd="" tfile="" tname="" vfails="" voutd="" fails=""
    for arch in "${arches[@]}"; do
        for vmname in $vmnames; do
            vfails=""
            voutd="$outd/$arch/$vmname"
            vmd="$rund/$arch/$vmname"
            mkdir -p "$voutd" "$vmd" || { stderr "failed creating dir"; return 1; }

            vr "$runner" create --fwcode="$wolfivmd/builder/ovmf-$arch.fd" \
                "$vmd" "$wolfivmd/output/$arch/generic/disk.raw" || {
                    stderr "failed $runner create";
                    vfails="$arch-$vmname/create"
                    continue
                }

            set -- "$runner" start "--arch=$arch" --public-key="$key.pub" "$vmd"
            log "starting $*"
            "$@" > "$voutd/vm-start.log" 2>&1 &
            RUNNERPID=$!

            vr "$runner" --timeout="${WAIT_SSH_TIMEOUT}" wait-for-ssh "$vmd" || {
                stderr "failed runner wait-for-ssh $arch-$vmname"
                vfails="$vfails $arch-$vmname/wait-for-ssh"
                if [ ! -f "$vmd/ttyS0.log" ]; then
                    stderr "[$arch-$vmname] FATAL wait-for-ssh timeout." \
                        "console log missing."
                else
                    sed -e 's,^,> ,' "$vmd/ttyS0.log" 2>&1
                    stderr "[$arch-$vmname] FATAL wait-for-ssh timeout." \
                        "console log above"
                fi
                continue
            }

            for tfile in "${TOP_D}/test/$arch"/*; do
                tname=${tfile##*/}
                vrl "$voutd/test-$tname" "$runner" run-remote \
                    --private-key="$key" --file="$tfile" "$vmd" -- -test.v ||
                       vfails="$vfails $arch-$vmname/test-$tname"
                "$runner" ssh --private-key="$key" "$vmd" \
                    "cat $METD/$tname" >  "$voutd/$tname-metrics.json" ||
                    vfails="$vfails $arch-$vmname/$tname-metrics"
            done

            kill "$RUNNERPID"
            wait "$RUNNERPID"
            RUNNERPID=""

            if [ ! -f "$vmd/ttyS0.log" ]; then
                vfails="$vfails $arch-$vmname/console-log"
                stderr "$vmd/ttyS0.log did not exist"
            elif ! cp "$vmd/ttyS0.log" "$voutd/console.log"; then
                vfails="$vfails $arch-$vmname/console-log"
                stderr "failed copy of $vmd/ttyS0.log"
            fi

            vfails=${vfails# }
            if [ -z "$vfails" ]; then
                log "finished $arch/$vmname PASS"
            else
                log "finished $arch/$vmname FAIL - $vfails"
            fi
        done
        fails="${fails:+$fails }$vfails"
    done
    if [ -z "$fails" ]; then
        log "PASS - no failures"
        return 0
    fi
    log "FAIL - $fails"
    return 1
}

source "$TOP_D/helpers/test-wolfi-vm-azure"

main() {
    local short_opts="hv"
    local long_opts="help,test-arch:,wolfi-vm:,verbose"
    local getopt_out=""
    getopt_out=$(getopt --name "${0##*/}" \
        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { bad_Usage; return; }

    local cur="" next="" testarches="" arch="" outd="" cloud="" wolfivmd=""

    while [ $# -ne 0 ]; do
        { cur="$1"; next="$2"; }
        case "$cur" in
            -h|--help) Usage ; exit 0;;
               --wolfi-vm) wolfivmd=$next; shift;;
               --test-arch) testarches=$next; shift;;
            -v|--verbose) VERBOSITY=$((VERBOSITY+1));;
            --) shift; break;;
        esac
        shift;
    done

    [ $# -ge 2 ] || { bad_Usage "got $# args [$*], expected min. 2"; return 1; }
    cloud="$1"
    outd="$2"
    LOG="$outd/test-wolfi-vm.log"

    [ -n "$wolfivmd" ] || { bad_Usage "--wolfi-vm is required"; return 1; }
    [ -d "$wolfivmd" ] || { stderr "--wolfi-vm '$wolfivmd' is not a dir"; return 1; }

    if [ "$testarches" = "" -o "$testarches" = "ALL" ]; then
        testarches="x86_64 aarch64"
    fi

    for arch in $testarches; do
        case "$arch" in
            x86_64|aarch64) continue;;
            *) fail "unknown arch $arch";;
        esac
    done

    [ -d "$outd" ] || mkdir -p "$outd" ||
        fail "could not create $outd"

    #shellcheck disable=SC2086
    case "$cloud" in
        qemu)  test_qemu  "$wolfivmd" "$outd" $testarches;;
        azure) test_azure "$wolfivmd" "$outd" "$testarches" "$@";;
        *)
           echo "Testing for cloud=$cloud with wolfi-vm dir at $wolfivmd"
           echo "Does not do anything just yet"
           ;;
    esac
}

main "$@"
# vi: ts=4 expandtab
