# Save the output of "cabal freeze" somewhere from which syft can pick it up.
#
name: 'Save "cabal freeze" output'

needs:
  packages:
    - build-base
    - busybox
    - cabal-install

inputs:
  project-file:
    description: "Name of Cabal project file"
    default: "cabal.project"

pipeline:
  - runs: |
      if [ "${{inputs.project-file}}" = cabal.project ]; then
        cabal freeze
      else
        cabal freeze --project-file="${{inputs.project-file}}"
      fi
      install -D -m644 "${{inputs.project-file}}.freeze" "${{targets.destdir}}/usr/lib/haskell/${{package.name}}-${{package.full-version}}/cabal.project.freeze"
