archs:
  - amd64
  - arm64
contents:
  build_repositories:
    - https://apk.cgr.dev/chainguard-private
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - https://packages.cgr.dev/extras
  packages:
    - apk-tools
    - apko
    - atuin
    - bash-binsh
    - bash-completion
    - bind-tools
    - bubblewrap
    - build-base
    - byobu
    - cg
    - chainctl
    - chainguard-baselayout
    - chainguard-workstation-configs
    - claude
    - containerd-service
    - coreutils
    - crane
    - curl
    - dbus
    - docker
    - docker-cli
    - docker-compose
    - docker-config-mirror-gcr
    - docker-credential-cgr
    - docker-credential-gcr
    - dockerd
    - dockerd-service
    - emacs
    - fd
    - findutils
    - fish
    - fzf
    - gawk
    - gcsfuse
    - gh
    - git
    - git-completion
    - gitsign
    - gitsign-config
    - gitsign-credential-cache
    - gke-gcloud-auth-plugin
    - glibc-locale-en
    - gnutar
    - go
    - google-cloud-sdk
    - google-compute-engine-oslogin
    - google-guest-agent
    - google-guest-config
    - grep
    - grype
    - gzip
    - helix
    - helm
    - iproute2
    - iputils
    - jq
    - just
    - k3d
    - k9s
    - kind
    - kmod
    - kmod-libs
    - kubectl-latest
    - lazygit
    - less
    - libselinux
    - libsemanage
    - libsepol
    - linux-gcp-generic-boot-installed
    - man-db
    - melange
    - mount
    - neovim
    - net-tools
    - opendoas
    - openssh-client
    - openssh-pam-config
    - openssh-server
    - openssh-service
    - openssh-sftp-server
    - opentofu
    - pax-utils
    - policycoreutils
    - polkit
    - psmisc
    - qemu
    - ripgrep
    - scanelf
    - screen
    - sed
    - shadow
    - ssh-import-id
    - sudo
    - systemd-boot
    - systemd-boot-installed
    - systemd-default-network
    - systemd-init
    - systemd-logind-service
    - systemd-repart-rootfs
    - terraform
    - terraform-docs
    - tmux
    - tree
    - udev
    - umount
    - unzip
    - util-linux-misc
    - uv
    - vim
    - wolfi-baselayout
    - wolfictl
    - workstation-v2-home-mounter
    - xfsprogs
    - yam
    - yazi
    - yq
    - zellij
    - zsh
