// This code was originally generated by cue, which required patching the apko
// code to better match with cue's heuristics. In the future it will be fully
// managed by cue <-> go generation.
package apko

#User: {
	// Required: The name of the user
	username!: string @go(UserName)

	// Required: The user ID
	uid!: uint32 @go(UID)

	// Required: The user's group ID
	gid!: uint32 @go(GID)

	// Optional: The user's shell
	shell?: string @go(Shell)

	// Optional: The user's home directory
	homedir?: string @go(HomeDir)
}

#Group: {
	// Required: The name of the group
	groupname?: string @go(GroupName)

	// Required: The group ID
	gid?: uint32 @go(GID)

	// Required: The list of members of the group
	members?: [...string] @go(Members,[]string)
}

#PathMutation: {
	// The target path to mutate
	path?: string @go(Path)

	// The type of mutation to perform
	//
	// This can be one of: directory, empty-file, hardlink, symlink, permissions
	type?: string @go(Type)

	// The mutation's desired user ID
	uid?: uint32 @go(UID)

	// The mutation's desired group ID
	gid?: uint32 @go(GID)

	// The permission bits for the path
	permissions?: uint32 @go(Permissions)

	// The source path to mutate
	source?: string @go(Source)

	// Toggle whether to mutate recursively
	recursive?: bool @go(Recursive)
}

#BaseImageDescriptor: {
	// Required: Path to the base image OCI layout. Right now only local files are supported.
	image?: string @go(Image)

	// Required: Path to file representing installed packages in the base image in APKINDEX format.
	// (Assumes regular Alpine repository layout, that is: set /foo/bar if the index is /foo/bor/{aarch64|x86_64}/APKINDEX
	apkindex?: string @go(APKIndex)
}

#ImageContents: {
	build_repositories?: [...string]
	runtime_repositories?: [...string]
	repositories?: [...string]
	keyring?: [...string]
	packages?: [...string]
	baseimage?: #BaseImageDescriptor
}

#ImageEntrypoint: {
	// Optional: The type of entrypoint. Only "service-bundle" is supported.
	type?: string @go(Type)

	// Required: The command of the entrypoint
	command?: string @go(Command)

	// Optional: The shell fragment of the entrypoint command
	"shell-fragment"?: string @go(ShellFragment)
	services?: {[string]: string} @go(Services,map[string]string)
}

#ImageAccounts: {
	// Required: The user to run the container as. This can be a username or UID.
	"run-as"?: string @go(RunAs)

	// Required: List of users to populate the image with
	users?: [...#User] @go(Users,[]User)

	// Required: List of groups to populate the image with
	groups?: [...#Group] @go(Groups,[]Group)
}

#ImageConfiguration: {
	// Required: The apk packages in the container image
	contents?: #ImageContents @go(Contents)

	// Required: The entrypoint of the container image
	//
	// This typically is the path to the executable to run. Since many of
	// images do not include a shell, this should be the full path
	// to the executable.
	entrypoint?: #ImageEntrypoint @go(Entrypoint)

	// Optional: The command of the container image
	//
	// These are the additional arguments to pass to the entrypoint.
	cmd?: string @go(Cmd)

	// Optional: The stop signal used to suspend the execution of the containers process
	"stop-signal"?: string @go(StopSignal)

	// Optional: The working directory of the container
	"work-dir"?: string @go(WorkDir)

	// Optional: Account configuration for the container image
	accounts?: #ImageAccounts @go(Accounts)

	// Optional: List of CPU architectures to build the container image for
	//
	// The list of supported architectures is: 386, amd64, arm64, arm/v6, arm/v7, ppc64le, riscv64, s390x, loong64
	archs?: [...#Architecture] @go(Archs,[]Architecture)

	// Optional: Envionment variables to set in the container image
	environment?: {[string]: string} @go(Environment,map[string]string)

	// Optional: List of paths mutations
	paths?: [...#PathMutation] @go(Paths,[]PathMutation)

	// Optional: The link to version control system for this container's source code
	"vcs-url"?: string @go(VCSUrl)

	// Optional: Annotations to apply to the images manifests
	annotations?: {[string]: string} @go(Annotations,map[string]string)

	// Optional: Path to a local file containing additional image configuration
	//
	// The included configuration is deep merged with the parent configuration
	include?: string @go(Include)

	// Optional: A list of volumes to configure
	//
	// This is _not_ the same as Paths, but refers to the OCI spec "volumes"
	// field used by some container runtimes (docker) to create volumes at
	// runtime. For most use cases, this is not needed, but consider using this
	// when the image requires special volume configuration at runtime for
	// supported container runtimes.
	volumes?: [...string] @go(Volumes,[]string)

	// Optional: Configuration to control layering of the OCI image.
	layering?: #Layering @go(Layering,*Layering)
}

#Layering: {
	budget:   int
	strategy: "origin"
} | null

// Architecture represents a CPU architecture for the container image.
// TODO(kaniini): Maybe this should be its own package at this point?
#Architecture: string

#Architecture: "amd64" | "arm64"

#Hash: {
	Algorithm: string
	Hex:       string
}

#SBOM: {
	Arch:   string
	Path:   string
	Format: string
	Digest: #Hash
}
