#!/bin/sh
#
# -nostdinc will cause clang to omit *standard* system include paths
# (like /usr/include), but it will not omit user-configured system include
# paths. We use this wrapper to do so.
#
if [ -z "${CCC_OVERRIDE_OPTIONS+set}" ]; then
  nostdinc_found=0
  for arg in "$@"; do
    case "$arg" in
      -nostdinc)
        nostdinc_found=1
        break
	;;
      *)
        ;;
    esac
  done
  # It would be nice if -ibuiltininc actually worked, but it doesn't
  # Instead, we construct the builtin include path based on the version.
  clangver="$(/usr/bin/${0##*/} -dumpversion)"
  clangmaj="${clangver%%.*}"
  if [ $nostdinc_found -eq 0 ]; then
    export CCC_OVERRIDE_OPTIONS="#+-nostdinc +-idirafter +/usr/lib/llvm-${clangmaj}/lib/clang/${clangmaj}/include +-idirafter +/usr/lib/oldglibc/usr/include +-idirafter +/usr/include"
  fi
fi

exec /usr/bin/${0##*/} "$@"
