#!/bin/sh

if [ -z "$GCC_SPEC_FILE" ] && [ -f "/etc/gcc_spec_file" ]; then
       GCC_SPEC_FILE="/etc/gcc_spec_file"
fi
# manylinux-2.28 from pypa use
# system glibc 2.28 (we have that)
# system libgcc from gcc 8 (we do not have it)
# system libstdc++ from gcc 8 (we do not have it)
# with gcc-14 (we have that)
# using linker scripts to use as many symbols from system libgcc & libstdc++
# whilst picking up the rest of the sybmols from a custom nonshared static libgcc & libstdc++
# instead of maintaining such non-upstream builds of nonshared static libgcc & libstdc++
# just statically link up to date libgcc & libstdc++
# another approach is to use a custom auditwheel policy to vendor-in shared libgcc & libstdc++
static=-static-libgcc
if [ "${0##*++}" != "${0}" ]; then
  static="$static -static-libstdc++"
fi

# Used to populate include paths in /usr/lib/oldglibc/gcc.spec
export OLDGLIBC_GCC_MAJOR_VER="$(/usr/bin/${0##*/} -dumpversion)"

exec /usr/bin/${0##*/} $static -specs "${GCC_SPEC_FILE:-openssf.spec}" "$@"
