# Update with `pre-commit autoupdate --freeze` which
# pins all repos using commit hashes, not mutable references
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^uefivars/LoaderConfigTimeout-menu-force\.aws$
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/chainguard-dev/yam
    rev: fdb5b8c7c09513ca1ed6a88dba5951e4e52be1a7
    hooks:
      - id: yam
        files: |
          (?x)(
            ^configs/
          )
  - repo: local
    hooks:
      - id: go-fmt
        name: go-fmt
        files: "[.]go$"
        language: system
        entry: sh -c '[ -z "$(for f in "$@"; do go fmt "$f"; done)" ]' --
      - id: go-imports
        name: go-imports
        files: "[.]go$"
        language: system
        entry: sh -c 'command -v goimports >/dev/null && [ -z "$(for f in "$@"; do goimports -w "$f"; done)" ]' --
