package:
  name: acpica
  version: "20250807"
  epoch: 0
  description: "The ACPI Component Architecture (ACPICA) project provides an open-source operating system-independent implementation of the Advanced Configuration and Power Interface specification (ACPI)"
  copyright:
    - license: Intel-ACPI

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - flex
      - m4

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/acpica/acpica
      expected-commit: aa98db3bd149fc1f8d2a3017cb05b6b1982c3296
      tag: ${{package.version}}

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

test:
  pipeline:
    - runs: |
        acpibin -v | grep ${{package.version}}
        acpidump -v 2>&1 | grep ${{package.version}}
        acpiexamples -v | grep ${{package.version}}
        acpiexec -v | grep ${{package.version}}
        acpihelp -v | grep ${{package.version}}
        acpisrc -v | grep ${{package.version}}
        acpixtract -v | grep ${{package.version}}
        iasl -v | grep ${{package.version}}

update:
  enabled: true
  github:
    identifier: acpica/acpica
