package:
  name: amazon-ec2-net-utils
  version: "2.7.1"
  epoch: 2
  description: set of utilities for managing elastic network interfaces on Amazon EC2
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - coreutils
      - curl
      - iproute2
      - logger
      - systemd
      - udev

environment:
  contents:
    packages:
      - build-base
      - busybox
      - coreutils

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/amazonlinux/amazon-ec2-net-utils
      tag: v${{package.version}}
      expected-commit: 82d7743ee4b592f033ec72c96368accf98121db2

  - runs: |
      # We don't yet have /lib-usr-merge
      sed -i 's|/lib/systemd/systemd-networkd-wait-online|/usr/lib/systemd/systemd-networkd-wait-online|' bin/setup-policy-routes.sh

      # systemd-networkd sets the hostname from the DHCP lease already during
      # interface configuration, there is no need to set it twice.
      mkdir -p ${{targets.destdir}}/usr/lib/systemd/system-preset
      cat <<EOF >${{targets.destdir}}/usr/lib/systemd/system-preset/50-${{package.name}}.preset
      disable set-hostname-imds.service
      EOF

  - uses: autoconf/make-install
    with:
      opts: PREFIX=/usr

test:
  pipeline:
    - runs: |
        # There are no help nor version options
        setup-policy-routes two args

update:
  enabled: true
  github:
    identifier: amazonlinux/amazon-ec2-net-utils
    strip-prefix: v
    tag-filter: v
