#nolint:valid-pipeline-git-checkout-tag
package:
  name: amazon-ecs-cni-plugins
  version: "2024.9.0_git20250908"
  epoch: 0
  description: Amazon ECS CNI Plugins is a collection of CNI plugins used on Amazon ECS
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/amazon-ecs-cni-plugins
      branch: master
      expected-commit: 7b4ec6016ab221469fa3abfc00ea7c05f236c26c

  - runs: |
      rm -r ./vendor

  - uses: go/build
    with:
      ldflags: -X pkg/version/version.Version=${{package.version}} -X pkg/version.GitShortHash=$(git rev-parse --short=8 HEAD)
      output: ecs-bridge
      packages: ./plugins/ecs-bridge

  - uses: go/build
    with:
      ldflags: -X pkg/version/version.Version=${{package.version}} -X pkg/version.GitShortHash=$(git rev-parse --short=8 HEAD)
      output: ecs-eni
      packages: ./plugins/eni

  - uses: go/build
    with:
      ldflags: -X pkg/version/version.Version=${{package.version}} -X pkg/version.GitShortHash=$(git rev-parse --short=8 HEAD)
      output: ecs-ipam
      packages: ./plugins/ipam

update:
  enabled: true
  git: {}
  schedule:
    period: weekly
    reason: Upstream does not maintain tags and releases, last change was ~11 months ago.

test:
  pipeline:
    - runs: |
        ecs-bridge -version
        ecs-eni -version
        ecs-ipam -version
