package:
  name: asciidoctor
  version: 2.0.23
  epoch: 0
  description: Asciidoctor is a fast, open source, Ruby-based text processor.
  copyright:
    - license: MIT

vars:
  ruby-version: 3.4

environment:
  contents:
    packages:
      - build-base
      - ruby-${{vars.ruby-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/asciidoctor/asciidoctor
      tag: v${{package.version}}
      expected-commit: 2c03d22eb9fe83d04ee452939581d1b842f6d8b4

  - uses: ruby/build
    with:
      gem: asciidoctor
      dir: .

  - uses: ruby/install
    with:
      gem: asciidoctor
      dir: .
      version: ${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: asciidoctor/asciidoctor
    strip-prefix: v

test:
  pipeline:
    - runs: asciidoctor --help
    - uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
