package:
  name: aws-k8s-cni-fips
  version: 1.18.3
  epoch: 0
  description: Networking plugin repository for pod networking in Kubernetes using Elastic Network Interfaces on AWS
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-fips
      - oldglibc
  environment:
    CGO_CFLAGS: "-I/usr/lib/oldglibc/include"
    CGO_LDFLAGS: "-L/usr/lib/oldglibc/lib"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/amazon-vpc-cni-k8s
      tag: v${{package.version}}
      expected-commit: 128a08e41001e81ed317410bd386954022b941af

  - name: Copy conflist
    runs: |
      cp -r misc/10-aws.conflist ${{targets.destdir}}

data:
  - name: binaries
    items:
      aws-cni: routed-eni-cni-plugin
      aws-k8s-agent: aws-k8s-agent
      aws-vpc-cni: aws-vpc-cni
      egress-cni: egress-cni-plugin
      grpc-health-probe: grpc-health-probe

subpackages:
  - range: binaries
    name: "aws-k8s-cni-${{range.key}}-fips"
    description: "${{range.key}} binary for aws-cni"
    pipeline:
      - uses: go/build
        with:
          go-package: go-fips
          ldflags: -X pkg/version/info.Version=${{package.version}} -X pkg/awsutils/awssession.version=${{package.version}}
          output: ${{range.key}}
          packages: ./cmd/${{range.value}}

update:
  enabled: true
  github:
    identifier: aws/amazon-vpc-cni-k8s
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - aws-k8s-cni-compat
        - aws-k8s-cni-aws-cni-fips
        - aws-k8s-cni-aws-k8s-agent-fips
        - aws-k8s-cni-aws-vpc-cni-fips
        - aws-k8s-cni-egress-cni-fips
        - aws-k8s-cni-grpc-health-probe-fips
  pipeline:
    - name: Verify installation
      runs: |
        aws-cni 2>&1 | grep -q 'CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0, 1.1.0'
        aws-vpc-cni 2>&1 | grep -q 'Failed to install CNI binaries" error="Failed to install /host/opt/cni/bin/aws-cni: failed to copy file: stat aws-cni: no such file or directory'
        egress-cni 2>&1 | grep -q 'CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0, 1.1.0'
        grpc-health-probe 2>&1 | grep -q '"caller":"github.com/aws/amazon-vpc-cni-k8s/cmd/grpc-health-probe/main.go:59","msg":"error: --addr not specified"'
