package:
  name: aws-ebs-csi-driver-1.18
  version: 1.18.0
  epoch: 11
  description: CSI driver for Amazon EBS.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - mount
      - lsblk
      - blkid
      - blockdev
      - xfsprogs
      - e2fsprogs
      - e2fsprogs-extra
    provides:
      - aws-ebs-csi-driver=1.18

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle
      - mount
      - umount

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
      tag: v${{package.version}}
      expected-commit: cfe3673b921dd2f50e023371d54fdb2dd219c7a0

  - runs: |
      # Mitigate GHSA-hw7c-3rfg-p46j
      go get google.golang.org/protobuf@v1.29.1

      # Mitigate CVE-2023-39325, CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      # Mitigate GHSA-m425-mq94-257g
      go get google.golang.org/grpc@v1.56.3

      # Mitigate CVE-2023-5528
      go get k8s.io/kubernetes@v1.26.11
      go mod edit -replace=k8s.io/apiserver=k8s.io/apiserver@v0.26.11

      go mod tidy

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      make ARCH=$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      cp bin/aws-ebs-csi-driver ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: false
