package:
  name: aws-ebs-csi-driver-1.19
  version: 1.19.0
  epoch: 12
  description: CSI driver for Amazon EBS.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - blkid
      - blockdev
      - e2fsprogs
      - e2fsprogs-extra
      - lsblk
      - mount
      - xfsprogs
    provides:
      - aws-ebs-csi-driver=1.19

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - mount
      - umount
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
      tag: v${{package.version}}
      expected-commit: a0ec0da261f9d24aecdec98448c63a38e7ae2cf3

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      # This is needed for the "go get k8s.io/kubernetes" below or it
      # will fail because k8s.io/kms has a version of v0.0.0 in its go.mod
      go mod edit -replace k8s.io/kms=k8s.io/kms@v0.27.1

      # Mitigate CVE-2023-39325, CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      # Mitigate GHSA-m425-mq94-257g
      go get google.golang.org/grpc@v1.56.3

      # Mitigate CVE-2023-5528
      go get k8s.io/kubernetes@v1.27.8
      go mod edit -replace=k8s.io/apiserver=k8s.io/apiserver@v0.27.8

      go mod tidy

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      make ARCH=$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      cp bin/aws-ebs-csi-driver ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: false
