package:
  name: azure-cloud-node-manager-fips
  version: 1.31.1
  epoch: 1
  description: Node manager for Azure Cloud
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/cloud-provider-azure
      tag: v${{package.version}}
      expected-commit: 301bb5195472aa76bb36e24726c197ccbb19cfca

  - uses: go/build
    with:
      packages: .
      modroot: cmd/cloud-node-manager
      output: cloud-node-manager
      ldflags: -X sigs.k8s.io/cloud-provider-azure/pkg/version.gitVersion=v${{package.version}}-$(git rev-parse HEAD)
      go-package: go-fips

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cloud-provider-azure
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        cloud-node-manager --version | grep v${{package.version}}
