package:
  name: cabal-install-3.14
  version: "3.14.2.0"
  epoch: 0
  description: "Command-line interface to Haskell package management"
  copyright:
    - license: "BSD-3-Clause"
  dependencies:
    runtime:
      - ghc~9.12
    provides:
      - cabal-install=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cabal-install~3.12
      - libffi-dev
      - zlib-dev

vars:
  project-file: "cabal.release.project"

pipeline:
  - runs: ghc-pkg recache --global

  - uses: git-checkout
    with:
      repository: "https://github.com/haskell/cabal"
      destination: "${{package.name}}"
      tag: "cabal-install-v${{package.version}}"
      expected-commit: "d265cc2d02f7d4a6b114a9ee6f903cc0a5984608"

  # cabal-install 3.14.2.0 shipped with an index-state configuration that's
  # incompatible with GHC 9.10.2.  It's safe to remove that, since we're
  # locking dependencies in our own way anyway.
  - working-directory: "${{package.name}}"
    runs: sed -i 's/^index-state:/-- &/' cabal.release.project

  # When updating to a new version, uncomment this and follow its instructions:
  # - working-directory: "${{package.name}}"
  #   uses: haskell/record-dependencies
  #   with:
  #     project-file: "${{vars.project-file}}"
  #
  - uses: haskell/fetch-dependencies

  - working-directory: "${{package.name}}"
    runs: cabal install -j"$(nproc)" --project-file="${{vars.project-file}}" --installdir="${{targets.destdir}}/usr/bin" --install-method=copy cabal-install

  - uses: strip

update:
  enabled: true
  manual: true
  exclude-reason: "Requires manual updates using haskell/record-dependencies"
  github:
    identifier: haskell/cabal
    strip-prefix: "cabal-install-v"
    tag-filter-prefix: "cabal-install-v3.14."

test:
  pipeline:
    - runs: cabal --version
    - uses: test/tw/ldd-check
