package:
  name: camunda-keycloak-fips-26.3-iamguarded-fips
  version: "26.3.4"
  epoch: 0
  description: Camunda fork of Keycloak
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - keycloak-fips-${{vars.major-minor-version}}-iamguarded-fips~${{package.version}}
    provides:
      - camunda-keycloak-fips-iamguarded-fips=${{package.full-version}}
    replaces:
      - keycloak-fips-${{vars.major-minor-version}}-iamguarded-fips

# this is a replacement of keycloak-iamguarded-compat for camunda keycloak, which is a fork of bitnami-keycloak
# the "upstream repo" for this package can be found at https://github.com/camunda/camunda-keycloak
# we do not clone it becaue there is no new code to build, we just copy the built code from other packages
# this package MUST be built after keycloak-iamguarded-compat is built, so that the versions will line up
# if there are any vulnerabilities in this package, it should be enough to fix them in keycloak-iamguarded-compat, then trigger a rebuild of this package
var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version
  - from: ${{package.version}}
    match: ^(\d+)\.(\d+).*
    replace: $1.$2
    to: major-minor-version

vars:
  java-version: 21

environment:
  contents:
    packages:
      - aws-advanced-jdbc-wrapper
      - aws-sdk-java-v2
      - busybox
      - dash-binsh
      - keycloak-fips-${{vars.major-minor-version}}-iamguarded-fips~${{package.version}}
      - keycloak-metrics-spi
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-${{vars.java-version}}-openjdk

pipeline:
  - runs: |
      export KC_DB=postgres
      cd /opt/iamguarded/keycloak
      cp /usr/share/java/aws-advanced-jdbc-wrapper.jar ./providers
      cp /usr/share/java/aws-sdk-v2/* ./providers
      cp /usr/share/java/keycloak-metrics-spi/keycloak-metrics-spi.jar ./providers
      ./bin/kc.sh build

      mkdir -p ${{targets.contextdir}}/opt/iamguarded/keycloak/providers
      cp -r /opt/iamguarded/keycloak/providers/* ${{targets.contextdir}}/opt/iamguarded/keycloak/providers

      mkdir -p ${{targets.contextdir}}/opt/iamguarded/keycloak/lib/quarkus
      cp -r /opt/iamguarded/keycloak/lib/quarkus/* ${{targets.contextdir}}/opt/iamguarded/keycloak/lib/quarkus

test:
  environment:
    contents:
      packages:
        - curl
        - postgresql
        - postgresql-client
        - glibc-locale-posix # Adding locales to prevent test failure on aarch64
        - shadow
        - sudo-rs
        - jq
    accounts:
      groups:
        - groupname: bn_keycloak
          gid: 65532
      users:
        - username: bn_keycloak
          gid: 65532
          uid: 65532
      run-as: 0
    environment:
      PGDATA: /tmp/test_db
      PGUSER: bn_keycloak
      PGDB: iamguarded_keycloak
      ALLOW_EMPTY_PASS: true
      LANG: C.UTF-8 # Adding locales to prevent test failure on aarch64
      LC_ALL: C.UTF-8 # Adding locales to prevent test failure on aarch64
      KC_CACHE: ispn
      KC_CACHE_CONFIG_FILE: cache-ispn.xml
      KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD:-}
      KC_BOOTSTRAP_ADMIN_PASSWORD: $KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD
      KC_HTTP_MANAGEMENT_RELATIVE_PATH: /
  pipeline:
    - uses: iamguarded/test-compat
      with:
        package: keycloak
        version: ${{vars.major-version}}
    - working-directory: /tmp
      pipeline:
        - name: "Test database creation"
          with:
            setup: echo "127.0.0.1 postgresql" >> /etc/hosts
          runs: |
            sudo -u $PGUSER initdb -D $PGDATA
            sudo -u $PGUSER pg_ctl -D $PGDATA -l /tmp/logfile start
            sudo -u $PGUSER createdb $PGDB
            sudo -u $PGUSER psql -lqt | cut -d \| -f 1 | grep -qw $PGDB
        - name: "start daemon on localhost"
          uses: test/daemon-check-output
          with:
            setup: |
              #!/bin/sh -e
              echo "127.0.0.1 postgresql" >> /etc/hosts
              echo "$(hostname) postgresql" >> /etc/hosts
            start: |
              env "IAMGUARDED_APP_NAME=keycloak" \
                "APP_VERSION=${{package.version}}" \
                "PATH=/opt/iamguarded/keycloak/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
                "KEYCLOAK_ADMIN=admin" \
                "KEYCLOAK_ADMIN_PASSWORD=PASSWORD-FOR-ADMIN-USER" \
                "KEYCLOAK_EXTRA_ARGS=--features=fips --fips-mode=non-strict --https-key-store-password=LongKeystorePassword" \
                "KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true" \
                /opt/iamguarded/scripts/keycloak/entrypoint.sh \
                /opt/iamguarded/scripts/keycloak/run.sh
            timeout: 120
            # NOTE: We ignore spurious ERROR logs here that stem from the
            # additional complexity fully configuring Keycloak for BCFIPS.
            # There is additional coverage in the image test + a stricter
            # version of this test for the non-FIPS iamguarded keycloak
            # package.
            error_strings: |
              FATAL
              FAIL
            expected_output: |
              Welcome to the Iamguarded image for Keycloak
              keycloak setup finished!
              server listening on
              Keycloak ${{package.version}}
              Profile dev activated.
            post: |
              #!/bin/sh -e
              url=http://localhost:9000/health/ready
              response=$(curl -fsS --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 "$url") || {
                echo "curl ${url} failed $?"
                exit 1
              }
              echo "$response" | jq .status | grep -q UP || {
                echo "response from $url did not contain \"UP\""
                echo "response: $response"
                exit 1
              }
              echo "$url had expected output: $response"

update:
  # The upstream repos releases contains a 'nightly' release. Which we want to
  # exclude from discovery.
  ignore-regex-patterns:
    - ".*nightly.*"
  enabled: true
  github:
    identifier: keycloak/keycloak
    tag-filter: 26.3.
