package:
  name: camunda-keycloak
  version: "2025.07.21.001"
  epoch: 3
  description: "Camunda Keycloak"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - aws-sdk-java-v2
      - busybox
      - keycloak-metrics-spi

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: "-"
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/camunda/keycloak
      tag: ${{vars.mangled-package-version}}
      expected-commit: 653fe212c625ae00551db6e97a63d19992d6d039

subpackages:
  - name: "${{package.name}}-compat"
    dependencies:
      runtime:
        - aws-sdk-java-v2
        - keycloak-metrics-spi
    description: "Compatibility package to place jars in the location expected by upstream"
    pipeline:
      - runs: |
          AWS_SDK_VERSION=$(ls /usr/share/java/aws-sdk-v2/aws-sdk-java-annotations-*.jar | sed 's/.*aws-sdk-java-annotations-\(.*\)\.jar/\1/')
          KEYCLOAK_METRICS_SPI_VERSION=$(ls /usr/share/java/keycloak-metrics-spi/keycloak-metrics-spi-*.jar | sed 's/.*keycloak-metrics-spi-\(.*\)\.jar/\1/')

          mkdir -p ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/
          mkdir -p ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/log
          mkdir -p ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/tmp

          # aws sdk
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-annotations-$AWS_SDK_VERSION.jar               ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/annotations-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-apache-client-$AWS_SDK_VERSION.jar             ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/apache-client-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-auth-$AWS_SDK_VERSION.jar                      ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/auth-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-aws-core-$AWS_SDK_VERSION.jar                  ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/aws-core-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-aws-query-protocol-$AWS_SDK_VERSION.jar        ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/aws-query-protocol-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-checksums-$AWS_SDK_VERSION.jar                 ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/checksums-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-checksums-spi-$AWS_SDK_VERSION.jar             ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/checksums-spi-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-endpoints-spi-$AWS_SDK_VERSION.jar             ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/endpoints-spi-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-http-auth-aws-eventstream-$AWS_SDK_VERSION.jar ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/eventstream-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-http-auth-$AWS_SDK_VERSION.jar                 ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/http-auth-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-http-auth-aws-$AWS_SDK_VERSION.jar             ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/http-auth-aws-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-http-auth-spi-$AWS_SDK_VERSION.jar             ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/http-auth-spi-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-http-client-spi-$AWS_SDK_VERSION.jar           ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/http-client-spi-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-identity-spi-$AWS_SDK_VERSION.jar              ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/identity-spi-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-json-utils-$AWS_SDK_VERSION.jar                ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/json-utils-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-metrics-spi-$AWS_SDK_VERSION.jar               ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/metrics-spi-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-netty-nio-client-$AWS_SDK_VERSION.jar          ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/netty-nio-client-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-profiles-$AWS_SDK_VERSION.jar                  ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/profiles-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-protocol-core-$AWS_SDK_VERSION.jar             ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/protocols-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-rds-$AWS_SDK_VERSION.jar                       ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/rds-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-regions-$AWS_SDK_VERSION.jar                   ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/regions-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-sdk-core-$AWS_SDK_VERSION.jar                  ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/sdk-core-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-sts-$AWS_SDK_VERSION.jar                       ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/sts-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-sts-$AWS_SDK_VERSION.jar                       ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/sts-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-third-party-jackson-core-$AWS_SDK_VERSION.jar  ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/third-party-jackson-core-$AWS_SDK_VERSION.jar

          # these not in the camunda-keycloak image but are in the aws-sdk-java-v2 package
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-imds-$AWS_SDK_VERSION.jar                      ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/imds-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-arns-$AWS_SDK_VERSION.jar                      ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/arns-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-http-auth-aws-crt-$AWS_SDK_VERSION.jar         ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/http-auth-aws-crt-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-crt-core-$AWS_SDK_VERSION.jar                  ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/crt-core-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-retries-$AWS_SDK_VERSION.jar                   ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/retries-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-auth-crt-$AWS_SDK_VERSION.jar                  ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/auth-crt-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-retries-spi-$AWS_SDK_VERSION.jar               ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/retries-spi-$AWS_SDK_VERSION.jar
          ln -sf /usr/share/java/aws-sdk-v2/aws-sdk-java-utils-$AWS_SDK_VERSION.jar                     ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/utils-$AWS_SDK_VERSION.jar

          # keycloak metrics spi
          ln -sf /usr/share/java/keycloak-metrics-spi/keycloak-metrics-spi-$KEYCLOAK_METRICS_SPI_VERSION.jar         ${{targets.subpkgdir}}/opt/iamguarded/keycloak/providers/keycloak-metrics-spi-$KEYCLOAK_METRICS_SPI_VERSION.jar

update:
  enabled: true
  version-transform:
    - match: "-"
      replace: "."
  github:
    identifier: camunda/keycloak
