package:
  name: cert-manager-webhook-pdns-fips
  version: "2.5.3"
  epoch: 1
  description: A PowerDNS webhook for cert-manager
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/zachomedia/cert-manager-webhook-pdns
      tag: v${{package.version}}
      expected-commit: 4af2c5474aacfedea8d682af613343c0cbd4bc1a

  - name: Downgrade Go to 1.23 for FIPS
    runs: |
      # we are using go 1.23 because go-fips-1.24 is not available yet
      sed -i 's/go 1\.24\(\.[0-9]*\)\?/go 1.23/' go.mod
      go mod tidy

  - uses: go/build
    with:
      output: webhook
      packages: .
      go-package: go-fips

update:
  enabled: true
  github:
    identifier: zachomedia/cert-manager-webhook-pdns
    strip-prefix: v
  ignore-regex-patterns:
    - "cert-manager-webhook-pdns-"

test:
  environment:
    environment:
      GROUP_NAME: "acme.zacharyseguin.ca"
      KUBERNETES_SERVICE_HOST: "127.0.0.1"
      KUBERNETES_SERVICE_PORT: 32764
    contents:
      packages:
        - mkcert
  pipeline:
    - uses: test/go-fips-check
    - uses: test/kwok/cluster
      with:
        serviceaccount: true
    - runs: |
        kubectl create rolebinding default-get-configmap \
        --clusterrole=view \
        --serviceaccount=default:default \
        --namespace=kube-system

        mkcert example.com
        export CA_OTHER="$(cat ~/.local/share/mkcert/rootCA.pem)"
        kubectl create configmap extension-apiserver-authentication \
        --from-literal=client-ca-file="$CA_OTHER" \
        --from-literal=requestheader-client-ca-file="$CA_OTHER" \
        -n kube-system \
        --dry-run=client -o yaml | kubectl apply -f -

        webhook > /tmp/webhook.log 2>&1 &
        sleep 5
        if ! grep -q "Starting controller" /tmp/webhook.log; then
          echo "Webhook server did not start correctly"
          exit 1
        fi

        echo "Webhook server started successfully"
