package:
  name: chainctl
  version: 0.1.323
  epoch: 0
  description: Chainguard CLI
  copyright:
    - license: custom

environment:
  contents:
    packages:
      - wolfi-base
      - curl

pipeline:
  - runs: |
      # https://edu.chainguard.dev/chainguard/administration/how-to-install-chainctl/#install-with-curl
      curl -o chainctl "https://dl.enforce.dev/chainctl/${{package.version}}/chainctl_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/aarch64/arm64/')"
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m 0755 chainctl ${{targets.destdir}}/usr/bin

update:
  enabled: false

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        ls -lh /usr/bin/chainctl
        HOME=/home/user chainctl version | grep "^GitVersion:.*${{package.version}}$"
