package:
  name: chainguard-workstation-configs
  version: "0.0.1"
  epoch: 0
  description: Configuration files for the Chainguard Workstation
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - curl

pipeline:
  - name: "Chainguard workstation config"
    runs: |
      mkdir -p ${{targets.destdir}}/etc/profile.d/
      # Install 01-setup-chainctl.sh
      cp 01-setup-chainctl.sh ${{targets.destdir}}/etc/profile.d/

test:
  pipeline:
    - runs: |
        ls /etc/profile.d/01-setup-chainctl.sh

update:
  enabled: false
  exclude-reason: No upstream
