package:
  name: chart-iamguarded-rabbitmq
  version: "16.0.9"
  epoch: 0
  description: rabbitmq iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: rabbitmq/${{package.version}}
      expected-commit: 31f65af3c533a97ee52328f1a055f03e7f6d7efb

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/rabbitmq

  - uses: charts/package
    with:
      chart-path: iamguarded/rabbitmq

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: rabbitmq/
    use-tag: true
    tag-filter-prefix: rabbitmq/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /rabbitmq
