package:
  name: chart-iamguarded-mariadb
  version: "23.0.1"
  epoch: 0
  description: MariaDB iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: mariadb/${{package.version}}
      expected-commit: c414d935017cac1c1d683115df2d919cf92c530c

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/mariadb

  - uses: charts/package
    with:
      chart-path: iamguarded/mariadb

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: mariadb/
    use-tag: true
    tag-filter-prefix: mariadb/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /mariadb
