package:
  name: chart-iamguarded-nginx-ingress-controller
  version: "12.0.7"
  epoch: 2
  description: nginx-ingress-controller iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: nginx-ingress-controller/${{package.version}}
      expected-commit: 398bfbf8296b54343952039efbb83055a7c3cc71

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/nginx-ingress-controller

  - uses: charts/package
    with:
      chart-path: iamguarded/nginx-ingress-controller

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: nginx-ingress-controller/
    use-tag: true
    tag-filter-prefix: nginx-ingress-controller/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /nginx-ingress-controller
