package:
  name: chart-iamguarded-argocd
  version: 11.0.2
  epoch: 0
  description: Argo CD iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common
      - chart-iamguarded-redis

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: argo-cd/${{package.version}}
      expected-commit: a08e2cdcf1f7299111e3863a2c41d5f869ddd4b7

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: patch
    with:
      patches: chart-dependencies.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/argo-cd

  - uses: charts/package
    with:
      chart-path: iamguarded/argo-cd

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: argo-cd/
    use-tag: true
    tag-filter-prefix: argo-cd/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /argo-cd
