package:
  name: chart-iamguarded-common
  version: "2.30.2"
  epoch: 0
  description: Common iamguarded library chart
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: ecosystems/auth
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: common/${{package.version}}
      expected-commit: 4e35d6016945db7b9fd4eef72b177d4826d69ece

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/common

  - uses: charts/package
    with:
      chart-path: iamguarded/common

update:
  enabled: false
  manual: true
  schedule:
    period: daily
    reason: Update automation doesn't yet support automating from private repos.
  git:

test:
  pipeline:
    - uses: ecosystems/auth
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: common
