package:
  name: chart-iamguarded-flux
  version: "2.4.26"
  epoch: 8
  description: flux iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: flux/${{package.version}}
      expected-commit: 567a03feffb557f8a0268636bb37070e7cd630aa

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/flux

  - uses: charts/package
    with:
      chart-path: iamguarded/flux

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: flux/
    use-tag: true
    tag-filter-prefix: flux/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /flux
