package:
  name: chart-iamguarded-cert-manager
  version: "1.5.14"
  epoch: 2
  description: cert-manager iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: cert-manager/${{package.version}}
      expected-commit: 70b7ac2358de7c069e91be504c1c7bd6fe2ecc96

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/cert-manager

  - uses: charts/package
    with:
      chart-path: iamguarded/cert-manager

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: cert-manager/
    use-tag: true
    tag-filter-prefix: cert-manager/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /cert-manager
