package:
  name: chart-iamguarded-fluentd
  version: "7.2.2"
  epoch: 0
  description: Fluentd iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: fluentd/${{package.version}}
      expected-commit: a85496ed73f248785575019bfef78af8552e5f9d

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/fluentd

  - uses: charts/package
    with:
      chart-path: iamguarded/fluentd

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: fluentd/
    use-tag: true
    tag-filter-prefix: fluentd/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /fluentd
