package:
  name: chart-iamguarded-zookeeper
  version: "13.8.7"
  epoch: 2
  description: Zookeeper iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: zookeeper/${{package.version}}
      expected-commit: 3d774dece09376a094d4f214c2834bc942760771

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/zookeeper

  - uses: charts/package
    with:
      chart-path: iamguarded/zookeeper

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: zookeeper/
    use-tag: true
    tag-filter-prefix: zookeeper/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /zookeeper
