package:
  name: chart-iamguarded-common
  version: "2.31.6"
  epoch: 0
  description: Common iamguarded library chart
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: common/${{package.version}}
      expected-commit: f25c8f4fbabdf66fa9094311cb94304a16fb698d

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/common

  - uses: charts/package
    with:
      chart-path: iamguarded/common

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: common/
    use-tag: true
    tag-filter-prefix: common/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /common
