package:
  name: chart-iamguarded-memcached
  version: "7.8.6"
  epoch: 1
  description: Memcached iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: memcached/${{package.version}}
      expected-commit: 2cde47a374bf489f218ec2f22ebfe3158ed96d4e

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/memcached

  - uses: charts/package
    with:
      chart-path: iamguarded/memcached

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: memcached/
    use-tag: true
    tag-filter-prefix: memcached/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /memcached
