package:
  name: chart-iamguarded-contour
  version: "20.0.1"
  epoch: 1
  description: Contour iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: contour/${{package.version}}
      expected-commit: c9f826269ec2ef6c8b94305568bbc1988f7a6929

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/contour

  - uses: charts/package
    with:
      chart-path: iamguarded/contour

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: contour/
    use-tag: true
    tag-filter-prefix: contour/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /contour
