package:
  name: chart-iamguarded-mongodb
  version: 16.5.5
  epoch: 0
  description: mongodb iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: mongodb/${{package.version}}
      expected-commit: c084df377f1cb009a149dd58fa9eb691aa3d635c

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/mongodb

  - uses: charts/package
    with:
      chart-path: iamguarded/mongodb

update:
  enabled: false
  manual: true
  schedule:
    period: daily
    reason: Update automation doesn't yet support automating from private repos.
  git:

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /mongodb
