package:
  name: clamav-fips-config
  version: "1.5.1"
  epoch: 2
  description: FIPS config files for clamav
  copyright:
    - license: GPL-2.0-only
  dependencies:
    replaces:
      - clamav-1.5-daemon
      - clamav-1.5-freshclam

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Cisco-Talos/clamav
      tag: clamav-${{package.version}}
      expected-commit: 0a6802e88ac2efc194d1feb26e912a313ab85f81

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/clamav
      cp etc/freshclam.conf.sample "${{targets.destdir}}"/etc/clamav/freshclam.conf
      cp etc/clamd.conf.sample "${{targets.destdir}}"/etc/clamav/clamd.conf

      # set fips defaults
      sed -i -e "s:^\(Example\):\# \1:" \
        -e "s:.*\(PidFile\) .*:\1 /run/clamav/freshclam.pid:" \
        -e "s:.*\(DatabaseOwner\) .*:\1 clamav:" \
        -e "s:^\#\(UpdateLogFile\) .*:\1 /var/log/clamav/freshclam.log:" \
        -e "s:^\#\(NotifyClamd\).*:\1 /etc/clamav/clamd.conf:" \
        -e "s:^\#\(ScriptedUpdates\).*:\1 yes:" \
        -e "s:^\#\(AllowSupplementaryGroups\).*:\1 yes:" \
        -e "s:^\#\(FIPSCryptoHashLimits\).*:\1 yes:" \
        "${{targets.destdir}}"/etc/clamav/freshclam.conf

      # set fips defaults
      sed -i -e "s:^\(Example\):\# \1:" \
        -e "s:.*\(PidFile\) .*:\1 /run/clamav/clamd.pid:" \
        -e "s:.*\(LocalSocket\) .*:\1 /run/clamav/clamd.sock:" \
        -e "s:.*\(TCPSocket\) .*:\1 3310:" \
        -e "s:.*\(User\) .*:\1 clamav:" \
        -e "s:^\#\(LogFile\) .*:\1 /var/log/clamav/clamd.log:" \
        -e "s:^\#\(LogTime\).*:\1 yes:" \
        -e "s:^\#\(AllowSupplementaryGroups\).*:\1 yes:" \
        -e "s:^\#\(FIPSCryptoHashLimits\).*:\1 yes:" \
        "${{targets.destdir}}"/etc/clamav/clamd.conf

update:
  enabled: true
  github:
    identifier: Cisco-Talos/clamav
    strip-prefix: clamav-
    tag-filter-prefix: clamav-

test:
  pipeline:
    - uses: test/tw/contains-files
      with:
        dir: "/etc/clamav/"
        name: "*.conf"
