package:
  name: claude
  version: 0.2.74
  epoch: 0
  description: Claude Code Research Preview
  copyright:
    - license: Commercial
  dependencies:
    runtime:
      - bash
      - busybox
      - coreutils
      - git
      - openssh-client
      - nodejs
      - npm

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - runs: |
      # The first time the user runs 'claude', it will download and install itself over this helper script
      mkdir -p ${{targets.destdir}}/usr/local/bin/
      cat <<EOF >${{targets.destdir}}/usr/local/bin/claude
      #!/bin/sh
      set -e
      npm install -g @anthropic-ai/claude-code --force
      exec claude
      EOF
      chmod 755 ${{targets.destdir}}/usr/local/bin/claude

update:
  enabled: false

test:
  pipeline:
    - runs: |
        claude --help
        claude --version
