package:
  name: claude
  version: "0.2.107"
  epoch: 0
  description: Claude Code Research Preview
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - bash
      - busybox
      - coreutils
      - git
      - nodejs-23
      - openssh-client
      - ripgrep

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - node-gyp
      - nodejs-23
      - npm
      - python3

pipeline:
  - runs: |
      # Install the binary, proprietary claude-code from npm
      mkdir -p ${{targets.destdir}}/usr/
      npm install -g @anthropic-ai/${{package.name}}-code@${{package.version}} -prefix ${{targets.destdir}}/usr
      # Drop the vendored ripgrep (which we have packaged and thus CVE-remediated)
      rm -rf ${{targets.destdir}}/usr/lib/node_modules/@anthropic-ai/claude-code/vendor

update:
  enabled: true
  release-monitor:
    identifier: 377805

test:
  pipeline:
    - runs: |
        claude --help
        claude --version
