package:
  name: cluster-autoscaler-1.27
  version: 1.27.8
  epoch: 0
  description: Autoscaling components for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cluster-autoscaler=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/autoscaler
      tag: cluster-autoscaler-${{package.version}}
      expected-commit: 06465a3810efc303249b0881c6dc6e8a3307d914

  - uses: go/bump
    with:
      deps: github.com/docker/distribution@v2.8.2 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0 go.opentelemetry.io/otel/sdk@v1.21.0 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0
      replaces: k8s.io/cloud-provider-aws=k8s.io/cloud-provider-aws@v1.27.6 sigs.k8s.io/cloud-provider-azure=sigs.k8s.io/cloud-provider-azure@v1.27.17
      modroot: cluster-autoscaler

  - uses: go/build
    with:
      modroot: cluster-autoscaler
      packages: .
      output: cluster-autoscaler
      vendor: true

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          # The upstream helm chart assumes the binary is in /.
          ln -sf /usr/bin/cluster-autoscaler ${{targets.subpkgdir}}/cluster-autoscaler
    dependencies:
      provides:
        - cluster-autoscaler-compat=${{package.full-version}}

update:
  enabled: true
  github:
    identifier: kubernetes/autoscaler
    strip-prefix: cluster-autoscaler-
    use-tag: true
    # There are other tags like "cluster-autoscaler-chart-FOO"
    tag-filter: cluster-autoscaler-1.27.
