package:
  name: crac-criu
  version: 1.4.3
  epoch: 0
  description: A project to implement checkpoint/restore functionality for Linux
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - asciidoc
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - docbook-xml
      - gnutls-dev
      - iproute2
      - libaio-dev
      - libbpf-dev
      - libbsd-dev
      - libcap-dev
      - libdrm
      - libdrm-dev
      - libnet-dev
      - libnl3
      - libnl3-dev
      - libnl3-static
      - libprotobuf
      - libxml2-utils
      - nftables
      - nftables-dev
      - pkgconf-dev
      - protobuf-c-dev
      - protobuf-dev
      - protoc
      - py3-future
      - py3-ipaddress
      - py3-protobuf
      - py3-pyyaml
      - python3
      - python3-dev
      - xmlto

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 352e2c730905bfca240a5e0f3e8085b6c27f606c
      repository: https://github.com/canonical/crac-criu
      tag: ${{package.version}}

  - runs: |
      make DESTDIR=${{targets.destdir}} PREFIX=/usr install-criu V=1

  - uses: strip

update:
  enabled: true
  github:
    identifier: canonical/crac-criu

test:
  pipeline:
    - runs: |
        # check at least if the binary is there in usr/sbin/criu
        if [ ! -f "/usr/sbin/criu" ]; then
          echo "criu binary not found"
          exit 1
        fi
