package:
  name: databricks-cli
  version: "0.258.0"
  epoch: 0
  description: Databricks CLI for interacting with Databricks services
  copyright:
    - license: custom

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/databricks/cli
      tag: v${{package.version}}
      expected-commit: 4b32ca94e5bb0dd53e3599a8d0d24edb7d24b7e2

  - uses: go/build
    with:
      packages: .
      ldflags: |
        -X github.com/databricks/cli/internal/build.buildProjectName=databricks
        -X github.com/databricks/cli/internal/build.buildVersion=${{package.version}}
        -X github.com/databricks/cli/internal/build.buildBranch=$(git rev-parse --abbrev-ref HEAD)
        -X "github.com/databricks/cli/internal/build.buildTimestamp=$(date -u -d "@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%s)"
      output: databricks

update:
  enabled: true
  git:
    strip-prefix: v
  ignore-regex-patterns:
    - snapshot

subpackages:
  - name: ${{package.name}}-compat
    description: Compatibility package for databricks CLI
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/app
          ln -sf /usr/bin/databricks ${{targets.contextdir}}/app/databricks
    test:
      pipeline:
        - runs: |
            test "$(readlink -fv /app/databricks)" = "/usr/bin/databricks"

test:
  pipeline:
    - runs: |-
        databricks --version
        databricks --help
