package:
  name: ding-libs
  version: 0.6.2
  epoch: 0
  description: Helper libraries for SSSD and FreeIPA
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - check-dev
      - gettext-dev
      - libtool
      - pkgconf-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SSSD/ding-libs.git
      tag: ${{package.version}}
      expected-commit: 6a856ccc8dc151dddb6f1f9f11467875ea3d2206

  - uses: autoconf/configure
    with:
      opts: |
        --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: ding-libs-

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development files
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

test:
  pipeline:
    - uses: test/tw/ldd-check
