#nolint:git-checkout-must-use-github-updates
package:
  name: dotnet-9
  version: 9.0.200
  epoch: 0
  description: ".NET SDK"
  copyright:
    - license: MIT
  resources:
    cpu: 2
    memory: 32Gi
  dependencies:
    runtime:
      - icu

environment:
  environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  contents:
    packages:
      - bash
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-15
      - clang-15-default
      - cmake
      - curl
      - dotnet-bootstrap-9
      - glibc-locale-en
      - icu-dev
      - krb5-dev
      - libunwind
      - libunwind-dev
      - llvm15
      - llvm15-cmake-default
      - llvm15-dev
      - llvm15-tools
      - lttng-ust-dev
      - ncurses-dev
      - nodejs-22
      - openssl-dev
      - python3
      - rapidjson-dev
      - samurai
      - wolfi-base
      - zlib-dev

# FIXME: This is a workaround to fix the version number. The version is 9.0.200 but the tag is 9.0.2
# It captures the final number segment: if it ends in "00" (like in "9.0.200"), the "00" is removed, leaving just "2".
# Otherwise (e.g., "9.0.201"), the entire number is kept unchanged.
var-transforms:
  - from: ${{package.version}}
    match: '\.(?:(\d+?)00|(\d+))$'
    replace: ".$1$2"
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dotnet/dotnet
      tag: v${{vars.mangled-package-version}}
      expected-commit: c4e5fd73fe5d8c004bf46cb4f1ded77ca8124b1a
      destination: /home/build/src

  - working-directory: /home/build/src
    pipeline:
      - runs: |
          ln -sf /usr/share/dotnet-bootstrap-9/dotnet .dotnet
          mkdir -p prereqs/packages/archive/
          ln -sf /usr/share/dotnet-bootstrap-9/Private.SourceBuilt.Artifacts.Bootstrap.tar.gz prereqs/packages/archive/Private.SourceBuilt.Artifacts.Bootstrap.tar.gz
      - runs: |
          ./build.sh --clean-while-building --source-only \
            -- \
            /v:minimal \
            /p:LogVerbosity=minimal \
            /p:ContinueOnPrebuiltBaselineError=true \
            /p:MinimalConsoleLogOutput=true \
            /p:SkipPortableRuntimeBuild=true \
            /p:UseSystemLibs=brotli+rapidjson+zlib+libunwind
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/share/dotnet
          mkdir -p "${{targets.destdir}}"/usr/bin

          cp -R /home/build/src/artifacts/obj/extracted-dotnet-sdk/* "${{targets.destdir}}"/usr/share/dotnet
      - runs: |
          ln -s /usr/share/dotnet/dotnet "${{targets.destdir}}"/usr/bin/dotnet

  - uses: strip

subpackages:
  - name: dotnet-9-runtime
    description: "The .NET Core Runtime, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/dotnet/shared
          mv "${{targets.destdir}}"/usr/share/dotnet/shared/Microsoft.NETCore.App "${{targets.contextdir}}"/usr/share/dotnet/shared/
    dependencies:
      runtime:
        - dotnet-9

  - name: dotnet-9-runtime-default
    dependencies:
      runtime:
        - dotnet-9-runtime
      provides:
        - dotnet-runtime=9

  - name: aspnet-9-runtime
    description: "The ASP.NET Core Runtime, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/dotnet/shared
          mv "${{targets.destdir}}"/usr/share/dotnet/shared/Microsoft.AspNetCore.App "${{targets.contextdir}}"/usr/share/dotnet/shared/
    dependencies:
      runtime:
        - dotnet-9-runtime
        - libexpat1
        - libbrotlidec1

  - name: aspnet-9-runtime-default
    dependencies:
      runtime:
        - aspnet-9-runtime
      provides:
        - aspnet-runtime=9

  - name: dotnet-9-targeting-pack
    description: "The .NET Core targeting pack, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/dotnet/packs
          mv "${{targets.destdir}}"/usr/share/dotnet/packs/NETStandard.Library.* "${{targets.contextdir}}"/usr/share/dotnet/packs/
          mv "${{targets.destdir}}"/usr/share/dotnet/packs/Microsoft.NETCore.App.* "${{targets.contextdir}}"/usr/share/dotnet/packs/

  - name: aspnet-9-targeting-pack
    description: "The ASP.NET targeting pack, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/dotnet/packs
          mv "${{targets.destdir}}"/usr/share/dotnet/packs/Microsoft.AspNetCore.App.* "${{targets.contextdir}}"/usr/share/dotnet/packs/
    dependencies:
      runtime:
        - dotnet-9-targeting-pack

  - name: dotnet-9-sdk
    description: "The .NET Core SDK, version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/dotnet

          for i in sdk sdk-manifests templates; do
            mv "${{targets.destdir}}"/usr/share/dotnet/$i "${{targets.contextdir}}"/usr/share/dotnet/
          done
    dependencies:
      runtime:
        - dotnet-9-runtime
        - aspnet-9-runtime
        - dotnet-9-targeting-pack
        - aspnet-9-targeting-pack

  - name: dotnet-9-sdk-default
    dependencies:
      runtime:
        - dotnet-9-sdk
        - dotnet-9-runtime-default
        - aspnet-9-runtime-default
      provides:
        - dotnet-sdk=9

  - name: dotnet-9-aot
    description: "Ahead-of-Time (AOT) support for the .NET SDK version 9"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/dotnet/packs
          mv "${{targets.destdir}}"/usr/share/dotnet/packs/runtime.*.Microsoft.DotNet.ILCompiler "${{targets.contextdir}}"/usr/share/dotnet/packs/
    dependencies:
      runtime:
        - dotnet-9-targeting-pack

# FIXME: Used ReleaseMonitor here since they cut 9.0.2 tag instead of 9.0.200 on GitHub so we can't use the GitHub updater
update:
  enabled: true
  release-monitor:
    identifier: 141853

test:
  environment:
    contents:
      packages:
        - dotnet-9-sdk
  pipeline:
    - name: Basic .NET command test
      runs: |
        dotnet --info
    - name: Compile and run a simple .NET application
      runs: |
        cat <<'EOF' > HelloWorld.cs
        using System;

        class Program
        {
            static void Main()
            {
                Console.WriteLine("Hello, World!");
            }
        }
        EOF
        dotnet new console -o HelloWorldApp --force
        mv HelloWorld.cs HelloWorldApp/Program.cs
        dotnet run --project HelloWorldApp
    - name: Compile and run a .NET application with arguments
      runs: |
        cat <<'EOF' > ArgumentEcho.cs
        using System;

        class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine("Arguments: " + String.Join(", ", args));
            }
        }
        EOF
        dotnet new console -o ArgumentEchoApp --force
        mv ArgumentEcho.cs ArgumentEchoApp/Program.cs
        dotnet run --project ArgumentEchoApp -- arg1 arg2 arg3
