package:
  name: dragonfly
  version: "1.30.1"
  epoch: 0
  description: A modern replacement for Redis and Memcached
  copyright:
    - license: BUSL-1.1
  resources:
    cpu: 8
    memory: 16Gi

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bison
      - boost
      - boost-dev
      - boost-fiber
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libtool
      - libunwind-dev
      - liburing-dev
      - libxml2-dev
      - ninja
      - openssl-dev
      - patch
      - python3
      - zstd-dev
  environment:
    # https://github.com/wolfi-dev/os/issues/34075
    CXXFLAGS: -fdelete-null-pointer-checks
  accounts:
    groups:
      - groupname: dfly
        gid: 10000
    users:
      - username: dfly
        uid: 10000

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dragonflydb/dragonfly
      tag: v${{package.version}}
      expected-commit: fd4f7027f77fbe49e79d0b94e2f892234e388208
      recurse-submodules: true

  - working-directory: helio
    uses: patch
    with:
      patches: ../fix-build-force-to-use-system-liburing.patch

  - runs: |
      ./helio/blaze.sh -release

  - runs: |
      ninja -v -C build-opt dragonfly

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mv build-opt/dragonfly ${{targets.destdir}}/usr/bin

  - uses: strip

subpackages:
  - name: dragonfly-oci-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv tools/docker/entrypoint.sh ${{targets.subpkgdir}}/usr/bin
          chmod +x ${{targets.subpkgdir}}/usr/bin/entrypoint.sh

          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          mv tools/docker/healthcheck.sh ${{targets.subpkgdir}}/usr/local/bin
          chmod +x ${{targets.subpkgdir}}/usr/local/bin/healthcheck.sh
    dependencies:
      runtime:
        - busybox
        - openssl
        # needed for the healthcheck.sh script
        - netcat-openbsd
        - net-tools
        - redis-cli
        - redis-benchmark-7.2
        - su-exec

update:
  enabled: true
  github:
    identifier: dragonflydb/dragonfly
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - dragonfly-oci-compat
  pipeline:
    - runs: |
        dragonfly --help | grep "dragonfly: a modern in-memory store."
    - runs: |
        # Start in the background
        dragonfly&
        sleep 2
        if pgrep -x "dragonfly" > /dev/null
        then
            echo "Dragonfly is running correctly."
        else
            echo "Dragonfly its not running."
        fi
