package:
  name: ec2-instance-connect
  version: "1.1.17"
  epoch: 0
  description: ssh daemon configuration and necessary EC2 instance scripting to enable EC2 Instance Connect
  url: https://github.com/aws/aws-ec2-instance-connect-config
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - curl
      - coreutils
      - openssh-server
      - openssl
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/aws-ec2-instance-connect-config
      tag: ${{package.version}}
      expected-commit: a6dbf0b77ec2cfcea11d35554a079ac670906111
      cherry-picks: |
        master/086f148e3e2c34759ecf203f6b13a4d726572975: Update curl command to not fail silently on HTTP server error
        master/551c73e8ec1f5ade4c8b1f52cf616e75b47879b4: Remove references to harvest-hostkeys

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      cp src/bin/* ${{targets.destdir}}/usr/bin/

      mkdir -p ${{targets.destdir}}/etc/ssh/sshd_config.d/
      cp 50-ec2-instance-connect.conf ${{targets.destdir}}/etc/ssh/sshd_config.d/

      mkdir -p ${{targets.destdir}}/usr/lib/sysusers.d/
      cp ec2-instance-connect.conf ${{targets.destdir}}/usr/lib/sysusers.d/

test:
  pipeline:
    - runs: |
        ssh-keygen -A -q -N ""
        eic_cmd="$(sshd -T | grep "authorizedkeyscommand " | cut -d\  -f2)"
        # No --help available
        [ -x "$eic_cmd" ]

update:
  enabled: true
  github:
    identifier: aws/aws-ec2-instance-connect-config
