#nolint:git-checkout-must-use-github-updates,valid-pipeline-git-checkout-tag
package:
  name: ecosystems-test
  version: 0.0.1
  epoch: 2
  description: Demonstrates that we can pull private ecosystems repos.
  copyright:
    - license: PROPRIETARY

environment:
  contents:
    packages:
      - google-cloud-sdk

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/ecosystems-cassandra

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/ecosystems-cassandra
      branch: fips-4.0.15
      expected-commit: 4d3362860d2b42bc270daba45b1abed81b7ce10d

  - runs: |
      gcloud auth list
      gcloud artifacts files download --project=prod-enforce-fabc \
          --location=us \
          --repository=prod-java-rebuilds \
          --destination=. \
          --local-filename=mockito.jar \
          org/mockito/mockito-core/4.5.1/mockito-core-4.5.1.jar

update:
  manual: true
  exclude-reason: Only for testing.

# Based on package contents inspection, it was found that this origin package is empty apart from its own SBOM and this test was added to confirm it is empty and will fail if the package is no longer empty (contains more than an SBOM)
test:
  pipeline:
    - uses: test/emptypackage
