#nolint:valid-pipeline-git-checkout-tag
package:
  name: edk2
  version: "202511"
  epoch: 0
  description: "A modern, feature-rich, cross-platform firmware development environment for UEFI"
  copyright:
    - license: BSD-2-Clause-Patent
  resources:
    cpu: 16
    memory: 16Gi

environment:
  contents:
    packages:
      - acpica
      - bash
      - build-base
      - busybox
      - coreutils
      - nasm
      - perl
      - perl-json
      - python3
      - util-linux-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tianocore/edk2
      expected-commit: 46548b1adac82211d8d11da12dd914f41e7aa775
      tag: edk2-stable${{package.version}}

  - uses: git-checkout
    with:
      repository: https://gitlab.com/kraxel/edk2-build-config
      expected-commit: 46548b1adac82211d8d11da12dd914f41e7aa775
      branch: master
      destination: edk2-build-config

  - runs: |
      git submodule update --init

      # Build both arches when we have cross-compilers
      case "${{build.arch}}" in
        "aarch64")
          match=armvirt
          ;;
        "x86_64")
          match=ovmf.4m
          ;;
      esac

      # Change to RELEASE build type
      sed -i 's|DEBUG|RELEASE|' edk2-build-config/bin/edk2-build.py

      # Build firmware
      edk2-build-config/bin/edk2-build.py --jobs $(nproc) --config chainguard.build-config --silent --version-override ${{package.full-version}} --match $match
      # Matching filepaths with Fedora
      mkdir -p ${{targets.destdir}}/usr/share/edk2
      cp -r Chainguard/* ${{targets.destdir}}/usr/share/edk2/

update:
  enabled: true
  github:
    identifier: tianocore/edk2
    strip-prefix: edk2-stable
    tag-filter: edk2-stable
