package:
  name: elixir
  version: 1.16.2
  epoch: 0
  description: General-purpose programming language and runtime environment
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - erlang

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - erlang
      - erlang-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: f53d06f3e4041c50e65b750e5d56fec9cc7c6a44510786937c6a5bb0666a7207
      uri: https://github.com/elixir-lang/elixir/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '.*rc.*'
  github:
    identifier: elixir-lang/elixir
    strip-prefix: v

test:
  pipeline:
    - runs: |
        elixir --version

        cat <<'EOF' >> /tmp/hello.exs
        IO.puts("Hello, Wolfi!")
        EOF

        elixir /tmp/hello.exs
