#nolint:git-checkout-must-use-github-updates
package:
  name: ffmpeg-cuda
  version: "8.0"
  epoch: 0
  description: ffmpeg multimedia library
  copyright:
    - license: GPL-3.0-or-later AND LGPL-3.0-or-later
  dependencies:
    provider-priority: 1
  resources:
    cpu: 16
    memory: 16Gi

environment:
  contents:
    packages:
      - aom
      - aom-dev
      - aom-libs
      - build-base
      - busybox
      - ca-certificates-bundle
      - dav1d-dev
      - expat-dev
      - ffnvcodec
      - fontconfig-dev
      - harfbuzz-dev
      - lame-dev
      - libogg-dev
      - libsdl2-dev
      - libsodium-dev
      - libsrt
      - libssh-dev
      - libtheora
      - libtheora-dev
      - libvorbis-dev
      - libwebp-dev
      - libxml2-dev
      - nasm
      - nvidia-codec-sdk
      - openjpeg-dev
      - openssl-dev
      - opus-dev
      - snappy-dev
      - soxr-dev
      - speex-dev
      - svt-av1-dev
      - wolfi-baselayout
      - x264-dev
      - x265-dev
      - yasm
      - zeromq-dev
  environment:
    LIBRARY_PATH: /usr/lib/nvidia-codec-sdk/stubs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/FFmpeg/FFmpeg
      expected-commit: 140fd653aed8cad774f991ba083e2d01e86420c7
      tag: n${{package.version}}

  - runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --enable-shared \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libaom \
        --enable-libtheora \
        --enable-ffnvcodec \
        --enable-gpl \
        --enable-version3 \
        --enable-openssl \
        --enable-libmp3lame \
        --enable-ffplay \
        --enable-libdav1d \
        --enable-libharfbuzz \
        --enable-libopus \
        --enable-libsnappy \
        --enable-libsrt \
        --enable-libssh \
        --enable-libsvtav1 \
        --enable-libvorbis \
        --enable-libwebp \
        --enable-libxml2 \
        --enable-lzma \
        --enable-libfontconfig \
        --enable-libfreetype \
        --enable-libopenjpeg \
        --enable-libspeex \
        --enable-libsoxr \
        --enable-libzmq

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-static
    pipeline:
      - uses: split/static
    description: ffmpeg static libraries

  - name: ${{package.name}}-dev
    dependencies:
      runtime:
        - ${{package.name}}
        - ${{package.name}}-static
    pipeline:
      - uses: split/dev
    description: ffmpeg development headers
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
    description: ffmpeg manpages

update:
  enabled: true
  release-monitor:
    identifier: 5405

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        ffmpeg --help
        ffprobe --help
        ffplay --help
    - uses: test/tw/ldd-check
