package:
  name: flux-image-automation-controller-fips
  version: "1.0.4"
  epoch: 2 # GHSA-j5w8-q4qc-rx2x
  description: GitOps Toolkit controller that patches container image tags in Git
  copyright:
    - license: Apache-2.0

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-16
      - gcc
      - go-fips
      - lld-16
  environment:
    CGO_ENABLED: 1

pipeline:
  - uses: git-checkout
    with:
      expected-commit: bb63e16a96d52de5fa40d96007cfae3134f45017
      repository: https://github.com/fluxcd/image-automation-controller
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/crypto@v0.45.0

  - runs: |
      export CGO_LDFLAGS="-fuse-ld=lld"
      # disable PIE on arm64, because is producing an unexpected binary execution error
      if [[ "${{build.arch}}" == "aarch64" ]]; then
        export CGO_LDFLAGS="${CGO_LDFLAGS} -no-pie"
      fi

      mkdir -p "${{targets.destdir}}"/usr/bin
      go build -tags 'netgo,osusergo,static_build' -trimpath \
        -o "${{targets.destdir}}"/usr/bin/image-automation-controller .

  - uses: strip

subpackages:
  - name: flux-image-automation-controller-fips-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          # The upstream helm chart assumes the binary is in /.
          ln -sf /usr/bin/image-automation-controller ${{targets.subpkgdir}}/usr/local/bin/image-automation-controller
          ln -sf /usr/bin/image-automation-controller ${{targets.subpkgdir}}/image-automation-controller
    dependencies:
      runtime:
        - flux-image-automation-controller-fips
    test:
      pipeline:
        - runs: |
            readlink -v /usr/local/bin/image-automation-controller
            readlink -v /image-automation-controller

update:
  enabled: true
  ignore-regex-patterns:
    - api/
  github:
    identifier: fluxcd/image-automation-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
        - curl
  pipeline:
    - runs: image-automation-controller -h
    - uses: test/go-fips-check
    - uses: test/kwok/cluster
    - name: Launch controller with kwok cluster
      uses: test/daemon-check-output
      with:
        setup: |
          kubectl apply -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml
        start: image-automation-controller --metrics-addr :8080 --health-addr :8081
        timeout: 30
        expected_output: |
          Starting Controller
          Starting workers
        post: |
          curl --silent --fail localhost:8080/metrics
          curl --silent --fail localhost:8081/healthz
