package:
  name: flux-helm-controller-fips
  version: "1.4.4"
  epoch: 2 # GHSA-j5w8-q4qc-rx2x
  description: The GitOps Toolkit Helm reconciler, for declarative Helming
  copyright:
    - license: Apache-2.0

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2c4a7567cd3913e3134d239bb8dd9d6a16a3e3b4
      repository: https://github.com/fluxcd/helm-controller
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/crypto@v0.45.0

  - uses: go/build
    with:
      ldflags: -X main.Version=${{package.version}}
      output: helm-controller
      packages: .
      go-package: go-fips

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - api/
  github:
    identifier: fluxcd/helm-controller
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/go-fips-check
    - uses: test/kwok/cluster
    - name: Launch controller with kwok cluster
      uses: test/daemon-check-output
      with:
        setup: |
          kubectl apply -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml
          kubectl wait --for=condition=Ready nodes --all
        start: helm-controller --health-addr :9441 --metrics-addr :8081
        timeout: 30
        expected_output: |
          Starting Controller
          Starting workers
        post: |
          curl --silent --fail localhost:8081/metrics
          curl --silent --fail localhost:9441/healthz
