# This is flux v2 pinned at exactly the v2.0.1 version to fulfil a specific
# request from JAMF to support their upgrade path. All components released as
# part of this tag are also suffixed with `-2.0` to indicate they belong as
# part of the same image commitment.
# Ref: # https://github.com/fluxcd/flux2/releases/tag/v2.0.1
#
# It will never be updated, and is only kept around long enough to fulfill the
# upgrade path since it will accrew CVE's indefinitely.
package:
  name: flux-2.0
  version: 2.0.1
  epoch: 2
  description: Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - build-base
      - bash
      - curl
      - go
      - kustomize
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluxcd/flux2
      tag: v${{package.version}}
      expected-commit: 9b3162495ce1b99b1fcdf137c553f543eafe3ec7

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.19.0 github.com/docker/docker@v24.0.7 github.com/cyphar/filepath-securejoin@v0.2.4 golang.org/x/crypto@v0.17.0 github.com/go-git/go-git/v5@v5.11.0 github.com/cloudflare/circl@v1.3.7

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      VERSION=${{package.version}} make build
      install -Dm755 bin/flux ${{targets.destdir}}/usr/bin/flux

  - runs: |
      ${{targets.destdir}}/usr/bin/flux version --client| grep "flux: v${{package.version}}"

  - uses: strip

update:
  enabled: false
