package:
  name: fulcio-fips
  version: 1.4.4
  epoch: 1
  description: Sigstore OIDC PKI
  copyright:
    - license: Apache-2.0

environment:
  contents:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/fulcio
      tag: v${{package.version}}
      expected-commit: 5c9ae3ccebc6430309ea4c0181db9642b21f449f

  - uses: go/build
    with:
      packages: ./
      modroot: .
      output: fulcio
      ldflags: -w
      go-package: go-fips

  - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/fulcio
    strip-prefix: v
