package:
  name: ghc-stage0
  version: 9.12.2
  epoch: 0
  description: "Stage 0 for the Glasgow Haskell Compiler."
  copyright:
    - license: BSD-3-Clause
  options:
    no-provides: true
  dependencies:
    runtime:
      - gcc
      - gmp-dev
      - libbsd-dev
      - libffi-dev
      - llvm-${{vars.llvm-version}}
      - ncurses-dev
      - numactl-dev

vars:
  llvm-version: '20'

environment:
  contents:
    # Need cabal, happy, and alex
    packages:
      - busybox
      - gcc
      - ghc-bootstrap
      - gmp-dev
      - libbsd-dev
      - libffi-dev
      - llvm-${{vars.llvm-version}}
      - ncurses-dev
      - numactl-dev

pipeline:
  - uses: git-checkout
    with:
      uri: https://github.com/ghc/ghc.git
      expected-commit: 383be28ffdddf65b57b7b111bfc89808b4229ebc

  - runs: ghc-pkg recache

update:
  enabled: false
  exclude-reason: This is a staged compiler and should not be updated
  github:
    identifier: ghc/ghc
    strip-prefix: ghc-
    strip-suffix: -release
    tag-filter-contains: -release
    tag-filter-prefix: ghc-
