package:
  name: gitlab-cng-ee-17.3
  version: 17.3.0
  epoch: 2
  description: Cloud Native container images per component of GitLab
  copyright:
    - license: MIT
  dependencies:
    provides:
      - gitlab-cng-ee=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

environment:
  contents:
    packages:
      - busybox
      - py3-pip
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/build/CNG.git
      tag: v${{package.version}}-ee
      expected-commit: a2ceb21a7fc187baee0875311581c50906fd4aa3

data:
  # Used to create all of the *-scripts subpackages from the CNG repo.
  - name: scripts
    items:
      rails: ./gitlab-rails
      sidekiq: ./gitlab-sidekiq
      webservice: ./gitlab-webservice
      workhorse: ./gitlab-workhorse

subpackages:
  - range: scripts
    name: gitlab-${{range.key}}-ee-scripts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - gitlab-${{range.key}}-ee-scripts=${{package.full-version}}
    pipeline:
      - runs: |
          cd ${{range.value}}
          for x in $(find scripts/ -type f); do
            mkdir -p ${{targets.subpkgdir}}/$(dirname $x)
            cp -r $x ${{targets.subpkgdir}}/$x
          done

  - name: gitlab-toolbox-ee-scripts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - gitlab-toolbox-ee-scripts=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          mkdir -p ${{targets.subpkgdir}}/usr/lib/ruby/vendor_ruby
          cp -r ./gitlab-toolbox/scripts/bin/* ${{targets.subpkgdir}}/usr/local/bin
          cp -r ./gitlab-toolbox/scripts/lib/* ${{targets.subpkgdir}}/usr/lib/ruby/vendor_ruby

  - name: gitlab-toolbox-ee-${{vars.major-minor-version}}
    dependencies:
      provides:
        - gitlab-toolbox-ee=${{package.full-version}}
      runtime:
        - gitaly-backup-${{vars.major-minor-version}}
        - py3-wheel
        - azcopy
        - s3cmd
        - aws-cli-v1
    pipeline:
      - name: Install gsutil
        runs: |
          python -m venv .venv --system-site-packages
          source .venv/bin/activate
          pip install gsutil

          mkdir -p ${{targets.subpkgdir}}/usr/share/gsutil
          mv .venv ${{targets.subpkgdir}}/usr/share/gsutil/

          # edit the venv paths
          sed -i "s|/home/build|/usr/share/gsutil|g" ${{targets.subpkgdir}}/usr/share/gsutil/.venv/bin/*
      - name: Symlink gsutil
        runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          ln -s /usr/share/gsutil/.venv/bin/gsutil ${{targets.subpkgdir}}/usr/bin/gsutil
      - name: Move provided scripts
        runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/ruby/vendor_ruby
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          cp -rf gitlab-toolbox/scripts/lib/* ${{targets.subpkgdir}}/usr/lib/ruby/vendor_ruby/
          cp -rf gitlab-toolbox/scripts/bin/* ${{targets.subpkgdir}}/usr/bin/
    test:
      pipeline:
        - name: Verify tools from gitlab-toolbox
          runs: |
            aws --version
            s3cmd --version
            azcopy --version
            gsutil --version

update:
  enabled: true
  release-monitor:
    identifier: 373190
