package:
  name: go-ipfs-fips
  version: 0.30.0
  epoch: 0
  description: An IPFS implementation in Go
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kubo-fips

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - fuse3
      - go-fips
      - openssl # significantly reduces background CPU usage, but requires CGO and gcc

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 846c5ccf679eeda58e626969bee8e80685be4812
      repository: https://github.com/ipfs/kubo
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/rs/cors@v1.11.0 google.golang.org/grpc@v1.64.1

  - runs: |
      CGO_ENABLED=1 GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) GOFLAGS=-buildvcs=false make build GOTAGS=openssl
      install -m755 -D ./cmd/ipfs/ipfs "${{targets.destdir}}"/usr/bin/ipfs

  - runs: |
      # create fs-repo directory
      mkdir -p /data/ipfs
      # create mount points
      mkdir /ipfs /ipns

  - uses: strip

update:
  enabled: true
  github:
    identifier: ipfs/kubo
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
