package:
  name: gomplate-fips
  version: 3.11.7
  epoch: 0
  description: A go templating utility.
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6e709cfad7d3b8fe81c17e3392d8fde790c50a2c
      repository: https://github.com/hairyhenderson/gomplate
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/go-git/go-git/v5@v5.11.0 google.golang.org/protobuf@v1.33.0 github.com/golang/protobuf@v1.5.4 golang.org/x/net@v0.23.0
      replaces: github.com/cloudflare/circl=github.com/cloudflare/circl@v1.3.7

  - uses: go/build
    with:
      go-package: go-fips
      modroot: .
      packages: "github.com/hairyhenderson/gomplate/v3/cmd/gomplate"
      output: "gomplate"
      ldflags: "-X github.com/hairyhenderson/gomplate/v3/version.Version=${{package.version}} -X github.com/hairyhenderson/gomplate/v3/version.GitCommit=$(git rev-parse --short HEAD)"

  - uses: strip

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - name: verify execution
      runs: |
        # Test that the binary can be run, since there have been issues with the
        # Go version used by the tool that only manifest at runtime.
        set -x
        gomplate -i 'the answer is: {{ mul 6 7 }}'
    - uses: test/go-fips-check

update:
  enabled: true
  github:
    identifier: hairyhenderson/gomplate
    strip-prefix: v
