# https://github.com/GoogleCloudPlatform/guest-oslogin/blob/master/packaging/google-compute-engine-oslogin.spec
package:
  name: google-compute-engine-oslogin
  version: "20250123.00"
  epoch: 0
  description: "google compute engine oslogin"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - systemd
      - policycoreutils

environment:
  contents:
    packages:
      - autoconf
      - automake
      - busybox
      - boost-dev
      - boost-regex
      - build-base
      - curl-dev
      - json-c-dev
      - linux-pam-dev
      - make
      - systemd

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleCloudPlatform/guest-oslogin.git
      tag: ${{package.version}}
      expected-commit: 4e69460014aa8a03258cfce07530d9878d85dde9

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  - name: "Fixup location for usr merge"
    runs: |
      mv ${{targets.destdir}}/lib/systemd ${{targets.destdir}}/usr/lib/

update:
  enabled: true
  github:
    identifier: GoogleCloudPlatform/guest-oslogin
    use-tag: true

test:
  pipeline:
    - runs: |
        # Check critical files existence
        test -f /usr/lib/systemd/system/google-oslogin-cache.service
        test -f /usr/bin/google_oslogin_nss_cache
        test -f /usr/lib/security/pam_oslogin_admin.so
        test -f /usr/lib/security/pam_oslogin_login.so

        # Validate binary execution
        google_oslogin_nss_cache --help

        # Check if systemd unit file is properly formatted
        systemd-analyze verify /usr/lib/systemd/system/google-oslogin-cache.service
