package:
  name: gotenberg
  version: 8.12.0
  epoch: 0
  description: A developer-friendly API for converting numerous document formats into PDF files, and more!
  copyright:
    - license: Apache-2.0
  # since chromium is only built for x86_64
  target-architecture:
    - x86_64
  dependencies:
    runtime:
      - busybox
      - chromium
      - culmus
      - exiftool
      - font-abyssinica
      - font-amiri
      - font-ipa
      - font-ipafont-gothic
      - font-ipafont-mincho
      - font-liberation
      - font-linux-libertine
      - font-lklug
      - font-lohit-beng-assamese
      - font-lohit-beng-bengali
      - font-lohit-beng-extra
      - font-lohit-guru
      - font-lohit-knda
      - font-noto-cjk
      - font-noto-emoji
      - font-padauk
      - font-samyak-devanagari
      - font-samyak-gujarati
      - font-samyak-malayalam
      - font-samyak-oriya
      - font-samyak-tamil
      - font-tlwg
      - font-unfonts-core
      - font-wqy-zenhei
      - gnupg
      - libreoffice
      - msttcorefonts-installer
      - pdftk
      - pdfcpu
      - python3
      - qpdf
      - tini
      - ttf-arphic-ukai
      - ttf-arphic-uming
      - unoconverter

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - exiftool
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gotenberg/gotenberg
      tag: v${{package.version}}
      expected-commit: 8ff9d3bcf113a938fcfb16eb3838e107360c1014

  - uses: go/bump
    with:
      deps: github.com/mholt/archiver/v3@v3.5.1
      replaces: github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2

  # https://github.com/gotenberg/gotenberg/blob/main/build/Dockerfile#L27C5-L27C129
  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/gotenberg/main.go
      output: gotenberg
      ldflags: "-s -w -X 'github.com/gotenberg/gotenberg/v8/cmd.Version=${{package.version}}'"

  - runs: |
      mkdir -p ${{targets.destdir}}/etc/fonts/conf.d
      cp build/fonts.conf ${{targets.destdir}}/etc/fonts/conf.d/100-gotenberg.conf

  - uses: strip

update:
  enabled: true
  github:
    identifier: gotenberg/gotenberg
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
        - curl
  pipeline:
    - runs: |
        export EXIFTOOL_BIN_PATH=/usr/bin/exiftool
        export CHROMIUM_BIN_PATH=/usr/bin/chromium
        export LIBREOFFICE_BIN_PATH=/usr/lib/libreoffice/program/soffice.bin
        export UNOCONVERTER_BIN_PATH=/usr/bin/unoconv
        export PDFTK_BIN_PATH=/usr/bin/pdftk
        export QPDF_BIN_PATH=/usr/bin/qpdf
        export PDFCPU_BIN_PATH=/usr/bin/pdfcpu
        gotenberg &
        sleep 5
        curl -i http://localhost:3000/health
