package:
  name: gpu-operator-fips-25.3
  version: "25.3.0"
  epoch: 3
  description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - gpu-operator-fips=${{package.full-version}}
    runtime:
      - busybox
      - kubectl-fips
      - nvidia-cuda-cccl-${{vars.cuda-version}}
      - nvidia-cuda-nvml-dev-${{vars.cuda-version}}
      - nvidia-cuda-profiler-api-${{vars.cuda-version}}
      - nvidia-cudnn-8-cuda-12
      - nvidia-nccl-cuda-${{vars.cuda-version}}
  
vars:
# Based on the base image used in upstream dockerfile: https://github.com/NVIDIA/gpu-operator/blob/main/docker/Dockerfile#L17
    cuda-version: 12.8

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NVIDIA/gpu-operator
      tag: v${{package.version}}
      expected-commit: b5479aaa85c72a3f67090e9cb205dfefd6c7b010

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.38.0

  - uses: go/build
    with:
      go-package: go-fips
      modroot: .
      packages: ./cmd/gpu-operator
      output: gpu-operator
      ldflags: -X github.com/NVIDIA/gpu-operator/internal/info.gitCommit=$(git rev-list -1 HEAD) -X github.com/NVIDIA/gpu-operator/internal/info.version=v${{package.version}}
      vendor: true

  - runs: |
      mkdir -p ${{targets.destdir}}/opt/${{package.name}}
      mkdir -p ${{targets.destdir}}/opt/${{package.name}}/manifests
      mkdir -p ${{targets.destdir}}/licenses

      cp -r ./assets/* ${{targets.destdir}}/opt/${{package.name}}
      cp -r ./manifests/* ${{targets.destdir}}/opt/${{package.name}}/manifests
      cp hack/must-gather.sh ${{targets.destdir}}/usr/bin/gather

      cp deployments/gpu-operator/crds/nvidia.com_clusterpolicies.yaml ${{targets.destdir}}/opt/${{package.name}}/nvidia.com_clusterpolicies.yaml
      cp deployments/gpu-operator/charts/node-feature-discovery/crds/nfd-api-crds.yaml ${{targets.destdir}}/opt/${{package.name}}/nfd-api-crds.yaml
      cp deployments/gpu-operator/crds/nvidia.com_nvidiadrivers.yaml ${{targets.destdir}}/opt/${{package.name}}/nvidia.com_nvidiadrivers.yaml

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        gpu-operator --help
    - uses: test/kwok/cluster
    - uses: test/daemon-check-output
      with:
        setup: |
          mkdir -p /opt/gpu-operator/manifests/state-driver
          echo "{}" > /opt/gpu-operator/manifests/state-driver/dummy.yaml
        start: /usr/bin/gpu-operator
        timeout: 30
        expected_output: |
          starting manager
          Starting metrics server
          starting server
          Serving metrics server
        post: |
          sleep 3
          STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" http://localhost:8081/healthz)
          # Check if the status code is 200, if so exit 0, otherwise exit 1
          if [ "$STATUS" -eq 200 ]; then
              echo "Health check passed with status code 200"
              exit 0
          else
              echo "Health check failed with status code $STATUS"
              exit 1
          fi

update:
  enabled: true
  github:
    identifier: NVIDIA/gpu-operator
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v25.3.
