package:
  name: grafana-9
  version: 9.5.21
  epoch: 2
  description: The open and composable observability and data visualization platform.
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - bash
    provides:
      - grafana=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - findutils
      - git
      - go
      - nodejs-16
      - posix-libc-utils
      - py3-setuptools
      - python3
      - yarn

pipeline:
  - uses: git-checkout
    with:
      expected-commit: dd4eea5e9a9cbd5cc26e45a8cdf9782f80e4826a
      repository: https://github.com/grafana/grafana
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/elazarl/goproxy@v0.0.0-20231117061959-7cc037d33fb5 github.com/go-jose/go-jose/v3@v3.0.3 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 google.golang.org/grpc@v1.64.1

  - runs: |
      yarn install
      yarn run build
      yarn run plugins:build-bundled

      # Bump the version of wire used, the old version panics with new Go
      # https://github.com/google/wire/issues/400
      sed -i "s/v0.5.0/v0.6.0/g" .bingo/wire.mod
      # this file uses type aliases which are supported on or after go1.9
      sed -i "s/go1.3/go1.9/g" pkg/web/macaron.go

      make build

      mkdir -p ${{targets.destdir}}/usr/bin
      mv ./bin/linux-*/* ${{targets.destdir}}/usr/bin/

  - name: package
    runs: |
      mkdir -p ${{targets.destdir}}/usr/share/grafana/plugins-bundled
      mkdir -p ${{targets.destdir}}/usr/share/grafana/scripts
      mkdir -p ${{targets.destdir}}/usr/share/grafana/bin

      mv ./conf ${{targets.destdir}}/usr/share/grafana/
      mv ./plugins-bundled/internal ${{targets.destdir}}/usr/share/grafana/plugins-bundled/
      mv ./public ${{targets.destdir}}/usr/share/grafana/
      mv ./scripts/*.sh ${{targets.destdir}}/usr/share/grafana/scripts/

      mkdir -p ${{targets.destdir}}/etc/grafana/
      cp ${{targets.destdir}}/usr/share/grafana/conf/sample.ini ${{targets.destdir}}/etc/grafana/grafana.ini

subpackages:
  - name: grafana-oci-compat-9
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/grafana
          mv ./packaging/docker/run.sh ${{targets.subpkgdir}}/opt/grafana/

update:
  enabled: true
  github:
    use-tag: true
    identifier: grafana/grafana
    tag-filter-prefix: v9.
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - bash
        - curl
        - jq
        - procps
        - shadow
  pipeline:
    - name: "Check Grafana version"
      runs: |
        grafana -v
    - name: "Check Grafana CLI version"
      runs: |
        grafana-cli -v
    - name: "Check Grafana server version"
      runs: |
        grafana-server -v
    - name: "Test Grafana server startup"
      uses: test/daemon-check-output
      with:
        start: |
          grafana-server \
            --config /etc/grafana/grafana.ini \
            --homepath /usr/share/grafana \
            --packaging=wolfi
        timeout: 60
        expected_output: |
          Starting Grafana
          HTTP Server Listen
        setup: |
          mkdir -p /var/lib/grafana
          chown -R root:root /var/lib/grafana
        post: |
          curl -s http://localhost:3000/api/health
          curl -s http://localhost:3000/api/org
          curl -s http://localhost:3000/api/dashboards/home
    - name: "Check configuration file"
      runs: |
        grep -q "app_mode = production" /etc/grafana/grafana.ini
    - name: "Test Grafana CLI commands"
      runs: |
        grafana-cli plugins list-remote
