package:
  name: grub
  version: "2.12"
  epoch: 0
  description: "the grand unified bootloader"
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - device-mapper-libs
      - flex
      - fuse3-libs
      - gawk
      - gettext
      - gettext-dev
      - libtool
      - patch
      - pkgconf
      - pkgconf-dev
      - python3
      - wolfi-base
      - xz-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.savannah.gnu.org/git/grub.git
      tag: grub-${{package.version}}
      expected-commit: 5ca9db22e8ed0dbebb2aec53722972de0680a463

  - runs: |
      set -x
      # TODO: We should probably create separate subpackages for bios and uefi grub, as well for different architectures
      ./bootstrap
      # Build bios grub
      case $(uname -m) in
        x86_64)
          ./configure --target=i386 --with-platform=pc --prefix=${{targets.destdir}}/usr
        ;;
        aarch64)
          ./configure --target=aarch64 --prefix=${{targets.destdir}}/usr
        ;;
      esac
      # Build efi grub
      # ./configure --target=x86_64 --with-platform=efi --disable-werror
      make -j $(nproc)
      make install

test:
  pipeline:
    - runs: |
        # Make sure our main file is installed an executable
        grub-install --help

update:
  enabled: true
  release-monitor:
    identifier: 1257
