package:
  name: gst-plugins-good
  version: "1.27.2"
  epoch: 0
  description: GStreamer streaming media framework good plug-ins
  copyright:
    - license: LGPL-2.1

environment:
  contents:
    packages:
      - alsa-lib-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - cdparanoia-dev
      - cmake
      - expat-dev
      - gdk-pixbuf
      - glib-dev
      - glib-gir
      - gobject-introspection-dev
      - graphene-dev
      - gst-plugins-base-dev
      - gstreamer
      - gstreamer-dev
      - gtk-3-dev
      - libdrm-dev
      - libice-dev
      - libjpeg-turbo-dev
      - libogg-dev
      - libpng-dev
      - libsm-dev
      - libtheora-dev
      - libvorbis-dev
      - libxv-dev
      - mesa-dev
      - mesa-gbm
      - mesa-glx
      - mesa-libgallium
      - meson
      - opus-dev
      - orc-compiler
      - orc-dev
      - perl
      - pulseaudio-dev
      - python3
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GStreamer/gstreamer
      tag: ${{package.version}}
      expected-commit: 285de3cf1de94b5b370a1af39446a7d1498d7c2c

  - working-directory: subprojects/gst-plugins-good
    pipeline:
      - uses: meson/configure
        with:
          opts: |
            -Db_lto=true \
            -Dpackage-origin="https://github.com/chainguard-dev" \
            -Dpackage-name="GStreamer good plug-ins (Wolfi-Linux)" \
            -Dpulse=enabled \
            -Dcairo=enabled \
            -Dgtk3=enabled \
            -Djpeg=enabled \
            -Dpng=enabled \
            -Dgdk-pixbuf=enabled \
            -Dtests=disabled
      - uses: meson/compile
      - uses: meson/install
      - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - uses: split/dev
    description: ${{package.name}} dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
          with:
            packages: ${{subpkg.name}}

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
    description: ${{package.name}} manpages

update:
  enabled: true
  git:
    tag-filter-prefix: "1."

test:
  pipeline:
    - name: Verify gst-plugins-good elements present
      runs: |
        # Grab all elements w/ source module of 'gst-plugins-good'
        elements="$(
          gst-inspect-1.0 --print-all \
          | awk -F: '/gst-plugins-good/ {gsub(/^[ \t]+|[ \t]+$/, "", $1); print $1}' \
          | sort -u
        )"

        # Verify gst-plugins-good elements exist
        for element in $elements; do
          gst-inspect-1.0 $element | grep -Eq "$element"
        done
    - uses: test/tw/ldd-check
