package:
  name: hubble-ui-backend-fips
  version: "0.13.3"
  epoch: 2 # CVE-2025-61729
  description: "Observability & troubleshooting for Kubernetes services"
  copyright:
    - license: "Apache-2.0"
  dependencies:
    runtime:
      - ca-certificates-bundle
      - gops

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/hubble-ui
      tag: v${{package.version}}
      destination: hubble-ui
      expected-commit: 3ef88cd8b72b698c3643e7c2f584165b613659a5

  - uses: go/build
    with:
      packages: .
      output: backend
      modroot: hubble-ui/backend
      go-package: go-fips

update:
  enabled: true
  github:
    identifier: cilium/hubble-ui
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        # This is a component of a larger system, ensure it fails to start as
        # expected
        /usr/bin/backend 2>&1 | grep "stat ${HOME}/.kube/config: no such file or directory"
