package:
  name: hubble-ui-backend-fips
  version: 0.13.0
  epoch: 8
  description: "Observability & troubleshooting for Kubernetes services"
  copyright:
    - license: "Apache-2.0"
  dependencies:
    runtime:
      - ca-certificates-bundle
      - gops

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/hubble-ui
      tag: v${{package.version}}
      destination: hubble-ui
      expected-commit: 0ffa10324c1e609b8a3620f41c73692c209045f0

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 github.com/golang/protobuf@v1.5.4 github.com/cilium/cilium@v1.15.3 golang.org/x/net@v0.23.0
      modroot: ./hubble-ui/backend

  - uses: go/build
    with:
      packages: .
      output: backend
      modroot: hubble-ui/backend
      go-package: go-fips

update:
  enabled: true
  github:
    identifier: cilium/hubble-ui
    strip-prefix: v
