package:
  name: immutable-usr
  version: 0.0.2
  epoch: 0
  description: Systemd unit to remount /usr read-only
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - systemd

environment:
  contents:
    packages:
      - busybox
      - systemd

pipeline:
  - runs: |
      # Construct the systemd-escaped filename for the local CA mount unit.
      # Directly writing it into code invites all kinds of parsing bugs and
      # differences between shells and their native or POSIX modes. Refer to
      # https://github.com/chainguard-dev/enterprise-packages/pull/36894#issuecomment-3445417855
      # for all disturbing details.
      # Will be: usr-local-share-ca\x2dcertificates.mount
      certs_mount="$(systemd-escape --path /usr/local/share/ca-certificates).mount"

      install -Dm644 ./usr.mount \
          "${{targets.destdir}}/usr/lib/systemd/system/usr.mount"
      install -Dm644 ./usr-local-share-ca-certificates.mount \
          "${{targets.destdir}}/usr/lib/systemd/system/$certs_mount"

test:
  pipeline:
    - runs: |
        certs_mount=$(printf '%s' 'usr-local-share-ca' '\' 'x2d' 'certificates.mount')

        test -f /usr/lib/systemd/system/usr.mount
        test -f "/usr/lib/systemd/system/$certs_mount"

update:
  enabled: false
  exclude-reason: |
    This is the upstream for this package
