package:
  name: influxd-2.7
  version: "2.7.12"
  epoch: 6 # CVE-2025-47907
  description: Scalable datastore for metrics, events, and real-time analytics
  copyright:
    - license: MIT
  dependencies:
    provides:
      - influxd=${{package.full-version}}
    runtime:
      - merged-usrsbin
      - wolfi-baselayout

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - curl
      - gcc-14-default
      - go
      - rust

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+)\.\d+\.\d+$
    replace: "$1"
    to: major-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/influxdata/influxdb
      tag: v${{package.version}}
      expected-commit: ec9dcde5d6f0e1c4d15ff2332127987a42ca30fc
      destination: influxdb

  - uses: go/bump
    with:
      deps: |-
        github.com/hashicorp/go-retryablehttp@v0.7.7
        golang.org/x/oauth2@v0.27.0
      modroot: influxdb

  - runs: |
      cd influxdb
      unset LDFLAGS

      make generate-web-assets

      make influxd
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/linux/influxd ${{targets.destdir}}/usr/bin

      mkdir -p ${{targets.destdir}}/etc/defaults/influxdb2/
      mv ../default-config.yml ${{targets.destdir}}/etc/defaults/influxdb2/config.yml

  - uses: strip

subpackages:
  - name: influxd-oci-entrypoint
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
    dependencies:
      runtime:
        - bash
        - busybox
        - merged-usrsbin
        - wolfi-baselayout
        - yq

  - name: ${{package.name}}-iamguarded-compat
    description: "compat package with iamguarded/influxdb image"
    dependencies:
      runtime:
        - bash
        - coreutils
        - curl
        - findutils
        - grep
        - influx
        - influxd
        - libgcc
        - merged-usrsbin
        - procps
        - sed
        - wait-for-port
        - wolfi-baselayout
    pipeline:
      - uses: iamguarded/build-compat
        with:
          package: influxdb
          version: ${{vars.major-version}}
      - runs: |
          mkdir -p /opt/iamguarded/influxdb/bin
          ln -sf /usr/bin/influxd /opt/iamguarded/influxdb/bin/influxd
          ln -sf /usr/bin/influx /opt/iamguarded/influxdb/bin/influx

          # copy etc to influxdb/etc.default
          mkdir -p /opt/iamguarded/influxdb/etc.default
          install -m755 -Dt /opt/iamguarded/influxdb/etc.default/defaults/influxdb2 ${{targets.destdir}}/etc/defaults/influxdb2/config.yml
          chmod -R g+rwX /opt/iamguarded/

          mkdir -p /iamguarded/influxdb
          chmod -R g+rwX /iamguarded/influxdb

          mkdir -p ${{targets.subpkgdir}}/docker-entrypoint-initdb.d/

          /opt/iamguarded/scripts/influxdb/postunpack.sh
      - uses: iamguarded/finalize-compat
        with:
          package: influxdb
          version: ${{vars.major-version}}
    test:
      pipeline:
        - name: Test influxdb binaries through symlinks
          runs: |
            /opt/iamguarded/influxdb/bin/influxd version
            /opt/iamguarded/influxdb/bin/influx version
        - uses: iamguarded/test-compat
          with:
            package: influxdb
            version: ${{vars.major-version}}

update:
  enabled: true
  github:
    identifier: influxdata/influxdb
    strip-prefix: v
    tag-filter: v2.7.

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        influxd --help
        influxd version
