package:
  name: inshellisense
  version: 0.0.1-rc7
  epoch: 0
  description: IDE style command line auto complete
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - node-gyp
      - nodejs
      - python3

# Drop mangled version when stable release is available
var-transforms:
  - from: ${{package.version}}
    match: rc
    replace: rc.
    to: mangled-package-version

pipeline:
  - name: npm install
    runs: |
      npm install -g @microsoft/${{package.name}}@${{vars.mangled-package-version}} -prefix ${{targets.destdir}}/usr

update:
  enabled: true
  github:
    identifier: microsoft/inshellisense
