package:
  name: jsoncpp
  version: 1.9.5
  epoch: 1
  description: "C++ library for parsing JSON"
  copyright:
    - license: 'CC-PDDC OR MIT'

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-source-parsers/jsoncpp
      tag: ${{package.version}}
      expected-commit: 5defb4ed1a4293b8e2bf641e16b156fb9de498cc

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: jsoncpp-static
    description: "C++ library for parsing JSON - static libraries"
    pipeline:
      - uses: split/static

  - name: jsoncpp-dev
    description: "C++ library for parsing JSON - development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: open-source-parsers/jsoncpp
