package:
  name: k6-fips
  version: "1.3.0"
  epoch: 0 # CVE-2025-47907
  description: A modern load testing tool, using Go and JavaScript (FIPS compliant version)
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - bash-binsh
      - coreutils
      - curl
      - grep
      - openssl-config-fipshardened

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/k6
      tag: v${{package.version}}
      expected-commit: 5870e99ae8a690a2b0bfc9a7dd2b5feb7c9851bb

  - uses: patch
    with:
      patches: 0001-patch-switch-md5-usage-to-sha256.patch

  - uses: go/build
    with:
      packages: .
      output: k6
      go-package: go-fips

update:
  enabled: true
  github:
    identifier: grafana/k6
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - name: "test out k6-fips version"
      runs: |
        k6 version | grep "${{package.version}}"
        k6 --version | grep "${{package.version}}"
        k6 --help | grep -e "Grafana" -e "k6" -e "Available Commands"
    - name: "run a demo test"
      runs: |
        k6 new | grep "New script created"
        k6 run script.js --duration=1.5s
    - name: "run an md5 test"
      runs: |
        tee test.js <<EOF
        import crypto from 'k6/crypto';

        export default function () {
            let hash1 = crypto.hmac('sha256', 'mysecret', 'hello world!', 'hex');
            let hash2 = crypto.hmac('md5', 'mysecret', 'hello world!', 'hex');

            const binArray = [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 33];

            hash1 = crypto.hmac('sha256', 'mysecret', new Uint8Array(binArray).buffer, 'hex');
            hash2 = crypto.hmac('md5', 'mysecret', new Uint8Array(binArray).buffer, 'hex');
            console.log(hash1);
            console.log(hash2);

        }
        EOF
        k6 run test.js 2>&1 | grep 'invalid algorithm: md5'
