package:
  name: k8ssandra-operator-fips
  version: "1.29.0"
  epoch: 1
  description: The Kubernetes operator for K8ssandra
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8ssandra/k8ssandra-operator
      tag: v${{package.version}}
      expected-commit: 42e1e75b654f03824432115192d7c753752ec086

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: ${{package.name}}-manager
      go-package: go-fips
      ldflags: |
        -X "main.version=${{package.version}}"
        -X "main.commit=$(git rev-parse HEAD)"
        -X "main.date=$(date -d@${SOURCE_DATE_EPOCH} +%FT%T)"

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          ln -sf /usr/bin/${{package.name}}-manager ${{targets.subpkgdir}}/usr/bin/manager
          ln -sf /usr/bin/${{package.name}}-manager ${{targets.subpkgdir}}/manager

update:
  enabled: true
  github:
    identifier: k8ssandra/k8ssandra-operator
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
        - k8ssandra-operator-fips-compat
        - openssl
    environment:
      WATCH_NAMESPACE: default
  pipeline:
    - uses: test/go-fips-check
    # check /usr/bin/manager presence
    - runs: |
        /usr/bin/manager --help
        /usr/bin/manager 2>&1 | grep -qi "try setting KUBERNETES_MASTER environment variable"
        k8ssandra-operator-fips-manager --help
    # check /manager presence
    - runs: |
        /manager --help
        /manager 2>&1 | grep -qi "try setting KUBERNETES_MASTER environment variable"
    - uses: test/kwok/cluster
      with:
        serviceaccount: true
    - name: Launch operator with kwok cluster
      uses: test/daemon-check-output
      with:
        setup: |
          mkdir -p /tmp/k8s-webhook-server/serving-certs
          openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
            -keyout /tmp/k8s-webhook-server/serving-certs/tls.key \
            -out /tmp/k8s-webhook-server/serving-certs/tls.crt \
            -subj "/CN=k8ssandra-operator-webhook-service.default.svc" \
            -addext "subjectAltName=DNS:k8ssandra-operator-webhook-service.default.svc"
          kubectl apply --server-side=true -f https://raw.githubusercontent.com/k8ssandra/k8ssandra-operator/v${{package.version}}/charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml
          sleep 1
        start: k8ssandra-operator-fips-manager --metrics-bind-address ":8080" --health-probe-bind-address ":8081"
        timeout: 30
        expected_output: |
          Starting Controller
          Starting workers
        post: |
          curl --silent --fail http://127.0.0.1:8080/metrics
          curl --silent --fail http://127.0.0.1:8081/healthz
