package:
  name: kaniko-ca-certificates-bundle
  # Update this when ca-certificates is updated.
  version: "20251003"
  epoch: 0
  copyright:
    - license: MPL-2.0 AND MIT

environment:
  contents:
    packages:
      - busybox
      # The ca-certificates=VERSION dependency ensures we only successfully build the package if
      # we already successfully built the ca-certificates equivalent.
      - ca-certificates-bundle=${{package.version}}

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}"/kaniko/ssl/certs
      mv /etc/ssl/certs/ca-certificates.crt "${{targets.destdir}}"/kaniko/ssl/certs

test:
  pipeline:
    - name: test for certs directory
      runs: |
        if [ -d "/kaniko/ssl/certs" ]; then
          echo "certs directory exists"
        else
          echo "certs directory does not exist"
          exit 1
        fi

update:
  enabled: true
  release-monitor:
    identifier: 332224
