package:
  name: karpenter-fips-0.35
  version: 0.35.5
  epoch: 2
  description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - karpenter-fips=${{package.full-version}}
    runtime:
      - ca-certificates-bundle
      # for fips config & fips-provider
      - openssl-config-fipshardened
      # either melange SCA should provide these
      # or we should make go-fips shared link on these
      - so:libcrypto.so.3
      - so:libssl.so.3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/karpenter
      tag: v${{package.version}}
      expected-commit: 132cf791fbd943fa883c6f3302698e264ed9dc76

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      go-package: go-fips
      packages: ./cmd/controller
      output: controller

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/karpenter
    strip-prefix: v
    tag-filter: v0.35.
