package:
  name: karpenter-fips-0.36
  version: 0.36.2
  epoch: 2
  description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - karpenter-fips=${{package.full-version}}
    runtime:
      - ca-certificates-bundle
      # either melange SCA should provide these
      # or we should make go-fips shared link on these
      - so:libcrypto.so.3
      - so:libssl.so.3
      # for fips config & fips-provider
      - openssl-config-fipshardened

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/karpenter
      tag: v${{package.version}}
      expected-commit: e719109d2de6a43047b330cd7278ce610da22da5

  - uses: go/build
    with:
      go-package: go-fips
      packages: ./cmd/controller
      output: controller

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/karpenter
    strip-prefix: v
    tag-filter: v0.36.
