package:
  name: kubernetes-csi-external-snapshotter-fips-8.2
  version: "8.2.1"
  epoch: 9 # CVE-2025-47907
  description: Sidecar container that watches Kubernetes Snapshot CRD objects and triggers CreateSnapshot/DeleteSnapshot against a CSI endpoint
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kubernetes-csi-external-snapshotter-fips=${{package.full-version}}
      - kubernetes-csi-external-csi-snapshotter-fips=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-snapshotter
      tag: v${{package.version}}
      expected-commit: a6a3d9d6b5f6f1e6fa0d311148b696556e4499e8

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.27.0
        golang.org/x/net@v0.38.0

  - uses: go/build
    with:
      packages: ./cmd/csi-snapshotter
      output: csi-snapshotter
      ldflags: -X main.version=$(git describe --long --tags --match="v*" --dirty 2>/dev/null || git rev-list -n1 HEAD)
      go-package: go-fips

  - uses: strip

subpackages:
  - name: kubernetes-csi-external-snapshot-controller-fips-${{vars.major-minor-version}}
    dependencies:
      provides:
        - kubernetes-csi-external-snapshot-controller-fips=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/snapshot-controller
          output: snapshot-controller
          ldflags: -X main.version=$(git describe --long --tags --match="v*" --dirty 2>/dev/null || git rev-list -n1 HEAD)
          go-package: go-fips
      - uses: strip
    test:
      pipeline:
        - uses: test/go-fips-check
          with:
            package-match: kubernetes-csi-external-snapshot-controller-fips-${{vars.major-minor-version}}
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: kubernetes-csi-external-snapshot-controller-fips
            real-pkg-name: ${{subpkg.name}}

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-snapshotter
    strip-prefix: v
    tag-filter: v8.2

test:
  environment:
    contents:
      packages:
        - kubernetes-csi-external-snapshot-controller-fips-${{vars.major-minor-version}}
        - curl
        - kubernetes-csi-driver-hostpath
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        csi-snapshotter --version
    - runs: |
        csi-snapshotter --help
        snapshot-controller --help
    - uses: test/kwok/cluster
    - runs: |
        mkdir -p /csi
        hostpathplugin --v=5 --endpoint="unix:///csi/csi.sock" --nodeid="node-000000" > hostpathplugin.log 2>&1 & sleep 5
        csi-snapshotter --v=5 --csi-address "/csi/csi.sock" --kubeconfig ~/.kube/config --http-endpoint ":8080" > csi-attacher.log 2>&1 & sleep 10
        sleep 10
        curl -Lk localhost:8080/metrics
