package:
  name: kubernetes-csi-external-resizer-1.9
  version: 1.9.4
  epoch: 5
  description: Sidecar container that watches Kubernetes PersistentVolumeClaims objects and triggers controller side expansion operation against a CSI endpoint
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kubernetes-csi-external-resizer=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-resizer
      tag: v${{package.version}}
      expected-commit: 630c501f4a8dcfe87047aaa37eed7a5a31bfc9f4

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0 google.golang.org/protobuf@v1.33.0 github.com/golang/protobuf@v1.5.4

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/csi-resizer ${{targets.destdir}}/usr/bin/csi-resizer

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-resizer
    strip-prefix: v
    tag-filter: v1.9.

test:
  pipeline:
    - runs: csi-resizer --version
