package:
  name: kuma-2.8
  version: 2.8.2
  epoch: 2
  description: A multi-zone service mesh for containers, Kubernetes and VMs.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kuma=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kumahq/kuma
      tag: ${{package.version}}
      expected-commit: ffb0a135b8320cd474c503b785b43627d77a1338

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      go-version: "1.22.0"

subpackages:
  - name: kuma-cp-${{vars.major-minor-version}}
    dependencies:
      provides:
        - kuma-cp=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          packages: ./app/kuma-cp
          output: kuma-cp
          ldflags: |
            -X github.com/kumahq/kuma/pkg/version.version=${{package.version}}
            -X github.com/kumahq/kuma/pkg/version.gitTag=$(git name-rev --tags --name-only $(git rev-parse HEAD))
            -X github.com/kumahq/kuma/pkg/version.gitCommit=$(git rev-parse HEAD)
            -X github.com/kumahq/kuma/pkg/version.buildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
            -X github.com/kumahq/kuma/pkg/version.Envoy=$(cat ./mk/dev.mk | grep "ENVOY_VERSION ?= " | sed "s/ENVOY_VERSION ?= //g")
    test:
      pipeline:
        - name: Test kuma control plane
          runs: |
            kuma-cp help
            kuma-cp version | grep ${{package.version}}

update:
  enabled: true
  github:
    identifier: kumahq/kuma
    tag-filter: 2.8
    use-tag: true
