package:
  name: kyverno-policy-reporter-fips
  version: "3.0.1"
  epoch: 1
  description: Monitoring and Observability Tool for the PolicyReport CRD with an optional UI.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-fips

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kyverno/policy-reporter
      tag: policy-reporter-${{package.version}}
      expected-commit: 182924da331a71f619fd3eb39c1115854c780a6d

  - uses: go/build
    with:
      go-package: go-fips
      tags: sqlite_unlock_notify
      output: policyreporter
      packages: .

  - runs: |
      mkdir -p ${{targets.destdir}}/app/templates
      cp -R ./templates ${{targets.destdir}}/app/templates

test:
  pipeline:
    - runs: |
        policyreporter version
        policyreporter --help
    - uses: test/go-fips-check

subpackages:
  - name: kyverno-policy-reporter-fips-compat
    description: compatibility symlinks package for policyreporter Dockerfile
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /app/
          mkdir -p ${{targets.subpkgdir}}/app
          ln -sf /usr/bin/policyreporter ${{targets.subpkgdir}}/app/policyreporter

update:
  enabled: true
  github:
    identifier: kyverno/policy-reporter
    strip-prefix: policy-reporter-
    tag-filter: policy-reporter
  ignore-regex-patterns:
    - preview
