package:
  name: kyverno-policy-reporter-plugins-trivy-fips
  version: "0.4.10"
  epoch: 0
  description: Policy Reporter Plugin Trivy
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kyverno/policy-reporter-plugins
      tag: trivy-plugin-v${{package.version}}
      expected-commit: 8abcb030dc833c01446cb2308610383a3515c3d9

  - uses: go/build
    with:
      go-package: go-fips
      output: trivy
      packages: .
      modroot: plugins/trivy

test:
  pipeline:
    - runs: |
        trivy help
    - uses: test/go-fips-check

update:
  enabled: true
  git:
    strip-prefix: trivy-plugin-v
    tag-filter-prefix: trivy
