package:
  name: kyverno-policy-reporter-plugins-trivy-fips
  version: 0.4.9
  epoch: 0
  description: Policy Reporter Plugin Trivy
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kyverno/policy-reporter-plugins
      tag: trivy-plugin-v${{package.version}}
      expected-commit: 0c7b5b46d661eb65660db47804f699f4b3dc17fe

  - uses: go/bump
    with:
      modroot: plugins/trivy
      deps: |-
        github.com/go-viper/mapstructure/v2@v2.4.0

  - uses: go/build
    with:
      go-package: go-fips
      output: trivy
      packages: .
      modroot: plugins/trivy

test:
  pipeline:
    - runs: |
        trivy help
    - uses: test/go-fips-check

update:
  enabled: true
  git:
    strip-prefix: trivy-plugin-v
    tag-filter-prefix: trivy
