package:
  name: linux
  version: 6.11.4
  epoch: 0
  description: "the linux kernel"
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - diffutils
      - elfutils
      - elfutils-dev
      - findutils
      - flex
      - openssl-dev
      - perl
      - python3
      - wolfi-base
      - gmp
      - gmp-dev
      - mpc
      - mpc-dev
      - mpfr
      - mpfr-dev
      - zstd

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{package.version}}
      expected-commit: 17365d66f1c6aa6bf4f4cb9842f5edeac027bcfb

  - runs: |
      set -x
      # Make a kernel
      # TODO: Much work to be done, tailoring a kernel config (or, more likely, a set of kernel configs)
      # TODO: But as a starting point, let's start with the default config, plus kvm_guest, plus hardening options
      make defconfig
      make hardening.config
      make kvm_guest.config
      make xen.config

      # Remove early warnings for missing /etc/target
      sed -i 's|CONFIG_TARGET_CORE=y|# CONFIG_TARGET_CORE is not set|g' .config

      # Enable hyperv stuff for Azure to work
      cat .config-azure >> .config

      cat .config

      #echo CONFIG_VERSION_SIGNATURE=\"Chainguard Wolfi Linux $(uname -m)-${{package.full-version}}\" >> .config
      # Build the Linux Kernel
      make -j $(nproc)
      mkdir -p ${{targets.destdir}}/boot
      cp -a .config ${{targets.destdir}}/boot/config-$(uname -m)-${{package.full-version}}
      chmod 644 ${{targets.destdir}}/boot/config-$(uname -m)-${{package.full-version}}
      cp -a $(find . -type f \( -name bzImage -or -name Image.gz \) -print -quit) ${{targets.destdir}}/boot/vmlinuz-$(uname -m)-${{package.full-version}}
      chmod 644 ${{targets.destdir}}/boot/vmlinuz-$(uname -m)-${{package.full-version}}
      ( cd ${{targets.destdir}}/boot && ln -sf vmlinuz-$(uname -m)-${{package.full-version}} vmlinuz )

test:
  environment:
    contents:
      packages:
        - qemu
  pipeline:
    - runs: |
        # Just a dumb test for now...see if we have a file at /boot/vmlinuz
        [ -e /boot/vmlinuz ]
        # Launch qemu, point to our kernel, put kernel boot console on standard out, exit on panic,
        # don't reboot, and make sure we get to the step where we're trying to mount a rootfs
        # TODO: we could go even further if we built an initrd and maybe ran the LTP...
        arch=$(uname -m)
        case "$arch" in
          x86_64)
            qemu-system-x86_64 -kernel /boot/vmlinuz -nographic -append "console=ttyS0 panic=1" -no-reboot | grep -q "Unable to mount root fs"
          ;;
          aarch64)
            qemu-system-aarch64 -kernel /boot/vmlinuz -cpu max -machine virt -nographic -no-reboot -append "panic=1" | grep -q "Unable to mount root fs"
          ;;
        esac

update:
  enabled: true
  github:
    identifier: gregkh/linux
    use-tag: true
    strip-prefix: v
    tag-filter: v
