package:
  name: linux
  version: 6.8.4
  epoch: 0
  description: The Linux kernel
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - findutils
      - flex
      - openssl-dev
      - perl

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e9013a3be222b740c9fc1be0dc8e96f9bbf17e33
      repository: git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux
      tag: v${{package.version}}

  - runs: |
      # Create installation directory
      export INSTALL_PATH=${{targets.contextdir}}/boot
      mkdir -p $INSTALL_PATH

      # Expected arch for aarch64 is arm64
      if [[ "${{build.arch}}" == "aarch64" ]]; then
        export ARCH=arm64
      else
        export ARCH=${{build.arch}}
      fi

      # Remove generated files, if they exist
      make mrproper

      # Generate kernel config
      make defconfig

      # Build the kernel
      make -j$(nproc)

      # Install kernel to INSTALL_PATH
      make install

  - uses: strip

# Needs to track linux-stable
update:
  manual: true
