package:
  name: linux-raspberry-pi-firmware
  version: "1.20250127"
  epoch: 0
  description: "firmware required by raspberry pi to boot"
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      # Ensure we get Chainguard branding in our VMs.
      - chainguard-baselayout
  target-architecture:
    - aarch64 # This kernel is specific to the raspberry pi hardware

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/raspberrypi/firmware
      tag: ${{package.version}}
      expected-commit: 39a2813a75827b3a4d104a97e8f872df5d4f7e54

  - runs: |
      set -x
      # TODO: Figure out how to build these from source...
      # TODO: Until then, the raspberrypi github repo provides these pre-built
      mkdir -p ${{targets.destdir}}/boot/firmware/
      cp -a boot/start*.elf ${{targets.destdir}}/boot/firmware/
      cp -a boot/fixup*.dat ${{targets.destdir}}/boot/firmware/
      # FYI: This is the proprietary only raspberrypi bootloader
      cp -a boot/bootcode.bin ${{targets.destdir}}/boot/firmware/

test:
  pipeline:
    - name: Ensure files are installed
      runs: |
        ls -alF /boot/firmware/start*.elf
        ls -alF /boot/firmware/fixup*.dat
        ls -alF /boot/firmware/bootcode.bin

update:
  enabled: true
  github:
    identifier: raspberrypi/firmware
    use-tag: true
