package:
  name: linux-jitterentropy-6.12
  version: "6.12.52"
  epoch: 1
  description: "linux jitterentropy object files 6.12 LTS"
  copyright:
    - license: GPL-2.0

vars:
  objects: crypto/jitterentropy.o crypto/sha3_jitterentropy.o
  # Make sure these objects build, but don't install them.
  build-objects: crypto/jitterentropy-testing.o crypto/jitterentropy-shim.o crypto/jitterentropy-kcapi.o
  object-cmds: crypto/.jitterentropy.o.cmd crypto/.sha3_jitterentropy.o.cmd
  sources: crypto/jitterentropy.c crypto/jitterentropy-kcapi.c crypto/jitterentropy-testing.c crypto/sha3_jitterentropy.c crypto/jitterentropy-shim.c
  headers: crypto/jitterentropy.h include/crypto/sha3_jitterentropy.h crypto/jitterentropy-shim.h

var-transforms:
  # linux-jitterentropy-6.12
  # selects the right config snippet
  - from: ${{package.name}}
    match: 'linux-(.*)'
    replace: '$1'
    to: flavor
  # linux-jitterentropy-6.12.X-rY
  # as opposed to
  # linux-jitterentropy-6.12-6.12.X-rY
  # this is the version that shows up in
  # uname
  - from: ${{package.name}}
    match: 'linux-(.*)-.*'
    replace: '${{package.full-version}}-$1'
    to: version-flavor
  # Turn "6.12.0" into "6.12", but keep "6.12.51" as "6.12.51"
  - from: ${{package.version}}
    match: '^(\d+[.]\d+)(?:[.]0|([.][1-9]\d*))$'
    replace: '$1$2'
    to: mangled-package-version
  - from: ${{package.version}}
    match: '^(\d+\.\d+)\.\d+$'
    replace: '$1'
    to: mangled-kernel-major-version

environment:
  environment:
    KBUILD_BUILD_USER: noreply
    KBUILD_BUILD_HOST: chainguard.dev
    KBUILD_BUILD_VERSION: Chainguard

pipeline:
  - uses: kernel/version-check
    with:
      moniker: longterm

  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{vars.mangled-package-version}}
      expected-commit: 2b2cbdcede3878c424b7937c83660ec9e9a232a2

  - uses: patch
    with:
      patches: |
        0001-crypto-reusable-jitterentropy-${{vars.mangled-kernel-major-version}}.patch
        0002-crypto-reusable-jitterentropy-${{vars.mangled-kernel-major-version}}.patch
        0003-crypto-reusable-jitterentropy-${{vars.mangled-kernel-major-version}}.patch

  - uses: kernel/config
    with:
      make-targets: hardening.config
      flavor: ${{vars.flavor}}
      version-flavor: ${{vars.version-flavor}}

  - uses: kernel/build
    with:
      make-targets: REBUILD_JITTERENTROPY=1 ${{vars.objects}} ${{vars.build-objects}}
      version-flavor: ${{vars.version-flavor}}

  - runs: |
      for i in ${{vars.objects}} ${{vars.object-cmds}} ${{vars.sources}} ${{vars.headers}}; do
        install -Dm 0644 "$i" "${{targets.destdir}}/usr/lib/${{package.name}}/$i"
      done
      install -Dm 0644 "config-${{vars.flavor}}" "${{targets.destdir}}/usr/lib/${{package.name}}/config"

test:
  environment:
    contents:
      packages:
        - binutils
        - grep
  pipeline:
    - runs: |
        strings /usr/lib/${{package.name}}/crypto/jitterentropy.o | grep "${{package.version}}"
        strings /usr/lib/${{package.name}}/crypto/jitterentropy.o | grep "${{package.version}}" | grep -vE "(dirty|\+)$"

update:
  enabled: true
  github:
    identifier: gregkh/linux
    use-tag: true
    strip-prefix: v
    tag-filter: v6.12.
  ignore-regex-patterns:
    # skip mainline (x.y) release tags, wait for stable (x.y.z) release tags
    - ^\d+[.]\d+$
  version-transform:
    # mainline release tag x.y to kernel version x.y.0
    - match: ^(\d+[.]\d+)$
      replace: $1.0
