package:
  name: linux
  version: "6.13.3"
  epoch: 3
  description: "the linux kernel"
  copyright:
    - license: GPL-2.0
  resources:
    cpu: 8
    memory: 24Gi
  dependencies:
    runtime:
      # Ensure we get Chainguard branding in our VMs.
      - chainguard-baselayout

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - diffutils
      - elfutils
      - elfutils-dev
      - findutils
      - flex
      - openssl-dev
      - perl
      - python3
      - wolfi-base
      - gmp
      - gmp-dev
      - mpc
      - mpc-dev
      - mpfr
      - mpfr-dev
      - zstd
  environment:
    KBUILD_BUILD_USER: noreply
    KBUILD_BUILD_HOST: chainguard.dev
    KBUILD_BUILD_VERSION: Chainguard

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{package.version}}
      expected-commit: 4e3ac4150cbd02585dc5cd1b4a25b8519a57c6a2

  - runs: |
      set -x
      # Make a kernel
      # TODO: Much work to be done, tailoring a kernel config (or, more likely, a set of kernel configs)
      # TODO: But as a starting point, let's start with the default config, plus kvm_guest, plus hardening options
      make defconfig
      make hardening.config
      make kvm_guest.config
      make xen.config

      # Branding
      cat .config-branding >> .config
      version=${{package.version}}
      fullversion=${{package.full-version}}
      suffix=${fullversion##$version}
      echo "LOCALVERSION=$suffix-generic" >> .config

      # Enable fuse and overlayfs stuff for dockerd to work
      cat .config-fuse >> .config

      # Enable iptables stuff for dockerd to work
      cat .config-iptables >> .config

      # Enable ip6tables stuff for dockerd to work
      cat .config-ip6tables >> .config

      # More iptables/nftables firewall support
      cat .config-netfilter >> .config

      # Enable hyperv stuff for Azure to work
      cat .config-azure >> .config

      # Enable XFS
      cat .config-xfs >> .config

      # Enable NVME block devices as boot (AWS)
      cat .config-nvme >> .config

      # Enable accelerated networking (AWS)
      cat .config-ena >> .config

      # Google Compute Engine items
      cat .config-gce >> .config

      # Enable Systemd kernel requirements
      cat .config-systemd >> .config

      # Remove early warnings for missing /etc/target
      sed -i 's|CONFIG_TARGET_CORE=y|# CONFIG_TARGET_CORE is not set|g' .config

      # No modules
      sed -i 's|=m|=y|g' .config

      #echo CONFIG_VERSION_SIGNATURE=\"Chainguard Wolfi Linux $(uname -m)-${{package.full-version}}\" >> .config
      # Build the Linux Kernel
      make -j $(nproc)
      mkdir -p ${{targets.destdir}}/boot
      cp -a .config ${{targets.destdir}}/boot/config-$(uname -m)-${{package.full-version}}
      chmod 644 ${{targets.destdir}}/boot/config-$(uname -m)-${{package.full-version}}
      cp -a $(find . -type f \( -name bzImage -or -name Image.gz \) -print -quit) ${{targets.destdir}}/boot/vmlinuz-$(uname -m)-${{package.full-version}}
      chmod 644 ${{targets.destdir}}/boot/vmlinuz-$(uname -m)-${{package.full-version}}
      ( cd ${{targets.destdir}}/boot && ln -sf vmlinuz-$(uname -m)-${{package.full-version}} vmlinuz )

subpackages:
  - name: "linux-boot-installed"
    description: "Linux kernel (installed for EFI)"
    dependencies:
      runtime:
        # Ensure we get Chainguard branding in our VMs.
        - chainguard-baselayout
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/boot/efi/chainguard/${{package.version}}/
      - if: ${{build.arch}} == 'aarch64'
        runs: |
          # Apparently on aarch64 the kernel cannot be compressed, so we forcibly decompress it here.
          gunzip --stdout ${{targets.destdir}}/boot/vmlinuz > ${{targets.subpkgdir}}/boot/efi/chainguard/${{package.version}}/linux
      - if: ${{build.arch}} == 'x86_64'
        runs: |
          cp ${{targets.destdir}}/boot/vmlinuz ${{targets.subpkgdir}}/boot/efi/chainguard/${{package.version}}/linux

  - name: "linux-boot-configuration"
    description: "Linux kernel (installed for EFI)"
    dependencies:
      runtime:
        # Use the installed systemd boot-loader, the installed kernel,
        # and then this package configures the boot-loader to launch
        # this version of the installed kernel.
        # TODO: Should this be its own package, or should we fold it into
        # linux-boot-installed?
        - systemd-boot-installed
        - linux-boot-installed
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/boot/efi/loader/entries/
          cat > ${{targets.subpkgdir}}/boot/efi/loader/entries/chainguard-${{package.version}}.conf <<EOF
          # Boot Loader Specification type#1 entry
          title      Chainguard
          version    ${{package.version}}
          sort-key   chainguard
          # The root argument must match the form documented (only) here:
          # https://github.com/torvalds/linux/blob/3022e9d0/block/early-lookup.c#L217
          options    root=PARTLABEL=Chainguard console=ttyS0 rw
          linux      /chainguard/${{package.version}}/linux
          EOF

          # In addition to noting the root partition above, configure /etc/fstab as well.
          mkdir -p ${{targets.subpkgdir}}/etc
          echo "/dev/gpt-auto-root / auto defaults,x-systemd.growfs 0 1" > "${{targets.subpkgdir}}/etc/fstab"

test:
  pipeline:
    - name: Test Basic Boot
      uses: kernel/test/console_grep
      with:
        string: "Unable to mount root fs"
    - name: Test for XFS
      uses: kernel/test/console_grep
      with:
        string: "xfs"
    - name: Test for NVME
      uses: kernel/test/console_grep
      with:
        string: "nvme nvme0: pci function"
    - name: Test for ip6tables
      uses: kernel/test/console_grep
      with:
        string: "Segment Routing with IPv6"

update:
  enabled: true
  github:
    identifier: gregkh/linux
    use-tag: true
    strip-prefix: v
    tag-filter: v
