package:
  name: linux-gcp-64k
  version: "6.14.6"
  epoch: 0
  description: "the GCP 64K pages linux kernel"
  copyright:
    - license: GPL-2.0
  resources:
    cpu: 8
    memory: 24Gi
  dependencies:
    runtime:
      - ${{package.name}}-modules=${{package.full-version}}
      # Ensure we get Chainguard branding in our VMs.
      - chainguard-baselayout
  target-architecture:
    - aarch64 # 64K pages only work on certain arm64 platforms.

environment:
  environment:
    KBUILD_BUILD_USER: noreply
    KBUILD_BUILD_HOST: chainguard.dev
    KBUILD_BUILD_VERSION: Chainguard

var-transforms:
  - from: ${{package.name}}
    match: 'linux-(.*)'
    replace: '$1'
    to: flavor
  - from: ${{package.name}}
    match: 'linux-(.*)'
    replace: '${{package.full-version}}-$1'
    to: version-flavor

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{package.version}}
      expected-commit: e2d3e1fdb530198317501eb7ded4f3a5fb6c881c

  - uses: kernel/config
    with:
      flavor: ${{vars.flavor}}
      make-targets: hardening.config kvm_guest.config
      config-snippets: config-gce
      version-flavor: ${{vars.version-flavor}}

  - uses: kernel/build
    with:
      version-flavor: ${{vars.version-flavor}}

subpackages:
  - name: "${{package.name}}-boot-installed"
    description: "Linux kernel (installed for EFI)"
    dependencies:
      runtime:
        # Ensure we get Chainguard branding in our VMs.
        - chainguard-baselayout
        - systemd-boot-installed
        - ${{package.name}}-modules=${{package.full-version}}
      provides:
        - ${{package.name}}-boot-configuration=${{package.full-version}}
    pipeline:
      - uses: kernel/boot-installed
        with:
          version-flavor: ${{vars.version-flavor}}

  - name: "${{package.name}}-modules"
    description: "Linux kernel modules"
    pipeline:
      - uses: kernel/modules
        with:
          version-flavor: ${{vars.version-flavor}}

test:
  pipeline:
    - uses: kernel/test/kconfig/systemd
    - name: Test Basic Boot
      uses: kernel/test/console_grep
      with:
        string: "Unable to mount root fs"
    - name: Test for XFS
      uses: kernel/test/console_grep
      with:
        string: "xfs"
    - name: Test for NVME
      uses: kernel/test/console_grep
      with:
        string: "nvme nvme0: pci function"
    - name: Test for ip6tables
      uses: kernel/test/console_grep
      with:
        string: "Segment Routing with IPv6"

update:
  enabled: true
  github:
    identifier: gregkh/linux
    use-tag: true
    strip-prefix: v
    tag-filter: v
