package:
  name: linux-azure-generic
  version: "6.16.9"
  epoch: 2
  description: "the Azure generic linux kernel"
  copyright:
    - license: GPL-2.0
  resources:
    cpu: 16
    memory: 24Gi
  dependencies:
    runtime:
      - ${{package.name}}-modules=${{package.full-version}}
      # Ensure we get Chainguard branding in our VMs.
      - chainguard-baselayout
      - merged-lib
      - wolfi-baselayout

environment:
  environment:
    KBUILD_BUILD_USER: noreply
    KBUILD_BUILD_HOST: chainguard.dev
    KBUILD_BUILD_VERSION: Chainguard

var-transforms:
  - from: ${{package.name}}
    match: "linux-(.*)"
    replace: "$1"
    to: flavor
  - from: ${{package.name}}
    match: "linux-(.*)"
    replace: "${{package.full-version}}-$1"
    to: version-flavor
  - from: ${{package.version}}
    match: '^(\d+[.]\d+)[.]0$'
    replace: '$1'
    to: mangled-package-version
  - from: ${{package.version}}
    match: '^(\d+\.\d+)\.\d+$'
    replace: '$1'
    to: mangled-kernel-major-version

pipeline:
  - uses: kernel/version-check
    with:
      moniker: stable

  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{vars.mangled-package-version}}
      expected-commit: b0d8acc711981d712a59ee20b073cbc52a4109c5

  - uses: patch
    with:
      patches: 0001-crypto-fix-hkdf-tests-${{vars.mangled-kernel-major-version}}.patch

  - uses: kernel/config
    with:
      flavor: ${{vars.flavor}}
      make-targets: hardening.config
      version-flavor: ${{vars.version-flavor}}

  - uses: kernel/build
    with:
      version-flavor: ${{vars.version-flavor}}

subpackages:
  - name: "${{package.name}}-boot-installed"
    description: "Linux kernel (installed for EFI)"
    dependencies:
      runtime:
        # Ensure we get Chainguard branding in our VMs.
        - ${{package.name}}-modules=${{package.full-version}}
        - chainguard-baselayout
        - merged-lib
        - systemd-boot-installed
        - wolfi-baselayout
      provides:
        - ${{package.name}}-boot-configuration=${{package.full-version}}
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        uses: kernel/boot-installed
        with:
          version-flavor: ${{vars.version-flavor}}
          extra-args: "earlyprintk=ttyS0"
      - if: ${{build.arch}} == 'aarch64'
        uses: kernel/boot-installed
        with:
          version-flavor: ${{vars.version-flavor}}
          extra-args: "earlyprintk=ttyAMA0"

  - name: "${{package.name}}-fips-boot-installed"
    description: "FIPS Linux kernel (installed for EFI)"
    dependencies:
      runtime:
        # Ensure we get Chainguard branding in our VMs.
        - ${{package.name}}-modules=${{package.full-version}}
        - chainguard-baselayout
        - systemd-boot-installed
      provides:
        - ${{package.name}}-boot-configuration=${{package.full-version}}
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        uses: kernel/boot-installed
        with:
          version-flavor: ${{vars.version-flavor}}
          extra-args: "fips=1 earlyprintk=ttyS0"
      - if: ${{build.arch}} == 'aarch64'
        uses: kernel/boot-installed
        with:
          version-flavor: ${{vars.version-flavor}}
          extra-args: "fips=1 earlyprintk=ttyAMA0"

  - name: "${{package.name}}-modules"
    description: "Linux kernel modules"
    pipeline:
      - uses: kernel/modules
        with:
          version-flavor: ${{vars.version-flavor}}
    dependencies:
      runtime:
        - merged-lib
        - wolfi-baselayout

  - name: hyperv-daemons
    description: Userspace daemons for hyperv
    pipeline:
      - uses: autoconf/make
        with:
          opts: -C tools/hv
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cp ./tools/hv/hv_kvp_daemon ${{targets.subpkgdir}}/usr/bin
          cp ./tools/hv/hv_vss_daemon ${{targets.subpkgdir}}/usr/bin
          if [ ${{build.arch}} != "aarch64" ]; then
            cp ./tools/hv/hv_fcopy_uio_daemon ${{targets.subpkgdir}}/usr/bin
          fi

          mkdir -p ${{targets.subpkgdir}}/usr/lib/systemd/system
          cp hyperv/hv*.service ${{targets.subpkgdir}}/usr/lib/systemd/system

          mkdir -p ${{targets.subpkgdir}}/usr/lib/udev/rules.d
          cp hyperv/hv*.rules ${{targets.subpkgdir}}/usr/lib/udev/rules.d
    test:
      pipeline:
        - runs: |
            hv_kvp_daemon --help
            hv_vss_daemon --help
            if [ ${{build.arch}} != "aarch64" ]; then
              set +e
              hv_fcopy_uio_daemon -h
              res=$?
              set -e
              [ $res -eq 234 ]
            fi
    dependencies:
      runtime:
        - merged-lib
        - wolfi-baselayout

test:
  pipeline:
    - uses: kernel/test/kconfig/systemd
    - uses: kernel/test/config-snippet
      with:
        snippet: ${{vars.flavor}}
        aarch64_exclude: |
          # Defined only for x86
          KVM_HYPERV
          HYPERV_IOMMU
          HYPERV_TIMER
    - uses: kernel/test/kconfig/bpftrace
    - name: Test Basic Boot
      uses: kernel/test/console_grep
      with:
        string: "Unable to mount root fs"
    - name: Test for XFS
      uses: kernel/test/console_grep
      with:
        string: "xfs"
    - name: Test for NVME
      uses: kernel/test/console_grep
      with:
        string: "nvme nvme0: pci function"
    - name: Test for ip6tables
      uses: kernel/test/console_grep
      with:
        string: "Segment Routing with IPv6"

update:
  enabled: true
  github:
    identifier: gregkh/linux
    use-tag: true
    strip-prefix: v
    tag-filter: v
  ignore-regex-patterns:
    # skip mainline (x.y) release tags, wait for stable (x.y.z) release tags
    - ^\d+[.]\d+$
  version-transform:
    # mainline release tag x.y to kernel version x.y.0
    - match: ^(\d+[.]\d+)$
      replace: $1.0
