#nolint:update-identifier-must-match-git-repository
package:
  name: longhorn-manager-1.8
  version: 1.8.2
  epoch: 7 # GHSA-r6j8-c6r2-37rr
  description: Manager for Longhorn.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - longhorn-manager=${{package.full-version}}
    runtime:
      - bind
      - blkid
      - blockdev
      - cifs-utils
      - e2fsprogs
      - e2fsprogs-extra
      - iproute2
      - iputils
      - kmod
      - mount
      - nfs-utils
      - umount
      - unzip
      - util-linux-misc
      - xfsprogs
      - xfsprogs-extra
      - zip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/longhorn/longhorn-manager.git
      tag: v${{package.version}}
      expected-commit: 5859e849c445b6144e8ab12db1472e26dc1ad4bd

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.27.0
        golang.org/x/crypto@v0.45.0
        k8s.io/kubernetes@v1.32.10

  - uses: go/build
    with:
      packages: .
      output: longhorn-manager
      ldflags: |
        -X github.com/longhorn/longhorn-manager/meta.Version=v${{package.version}}
        -X github.com/longhorn/longhorn-manager/meta.GitCommit=$(git rev-parse HEAD)
        -X github.com/longhorn/longhorn-manager/meta.BuildDate=$(date -d@${SOURCE_DATE_EPOCH} -u +'%Y-%m-%dT%H:%M:%SZ')

subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for ${{package.name}}
    dependencies:
      provides:
        - longhorn-manager-compat=${{package.full-version}}
      runtime:
        - coreutils
        - bash
        - curl
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/local/sbin
          ln -s /usr/bin/longhorn-manager "${{targets.contextdir}}"/usr/local/sbin/longhorn-manager
          cp ./package/launch-manager "${{targets.contextdir}}"/usr/local/sbin
          cp ./package/nsmounter "${{targets.contextdir}}"/usr/local/sbin
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
          with:
            allow-absolute: true

# Skipping further functional testing since privileged host mounts (/host/proc) and open-iscsi are unavailable during package-level tests
test:
  pipeline:
    - name: "Test binary help"
      uses: test/tw/help-check
      with:
        bins: longhorn-manager
    - name: "Test binary version"
      uses: test/tw/ver-check
      with:
        bins: longhorn-manager
    - uses: test/kwok/cluster
    # binary behaves the same as upstream, we will add more functional test at image level
    - name: Test manager startup
      uses: test/daemon-check-output
      with:
        start: |
          longhorn-manager daemon
        timeout: 30
        expected_output: |
          require engine-image

update:
  enabled: true
  github:
    identifier: longhorn/longhorn
    tag-filter-prefix: v1.8
    strip-prefix: v
    use-tag: true
  ignore-regex-patterns:
    - '.*-rc\d+$'
    - ".*-dev-.*"
    - ".*-hotfix-.*"
