package:
  name: mattmoor-chainit
  version: 0.0.5
  epoch: 0
  description: Experimental init system implementing apko semantics.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mattmoor/chainit
      tag: v${{package.version}}
      expected-commit: a09ab6edda794182b4dc460e8a0072addb2b5924

  - uses: go/build
    with:
      packages: .
      output: chainit

  - uses: strip

  - runs: |
      mkdir -p ${{targets.destdir}}/etc
      ln -s /usr/bin/chainit ${{targets.destdir}}/init

update:
  enabled: true
  github:
    identifier: mattmoor/chainit
    strip-prefix: v
