package:
  name: mattmoor-chainit
  version: "0.0.7"
  epoch: 0
  description: Experimental init system implementing apko semantics.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mattmoor/chainit
      tag: v${{package.version}}
      expected-commit: bdd94ed2485a3af6220477110f29a2b7d4bbb670

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.33.0

  - uses: go/build
    with:
      packages: .
      output: chainit

  - uses: strip

  - runs: |
      mkdir -p ${{targets.destdir}}/etc ${{targets.destdir}}/sbin
      ln -s /usr/bin/chainit ${{targets.destdir}}/init
      ln -s /usr/bin/chainit ${{targets.destdir}}/sbin/init

update:
  enabled: true
  github:
    identifier: mattmoor/chainit
    strip-prefix: v
