package:
  name: mc-fips
  version: 0.20240131.085940
  epoch: 9
  description: Simple Fast tool to manage MinIO clusters
  copyright:
    - license: AGPL-3.0-or-later

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/mc
      tag: RELEASE.2024-01-31T08-59-40Z
      expected-commit: 62b12a2770828f9d35ee7c5614d900b95ff6e6ab

  - uses: go/bump
    with:
      deps: github.com/lestrrat-go/jwx@v1.2.29 google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      go-package: go-fips
      packages: .
      ldflags: $(go run buildscripts/gen-ldflags.go | sed 's|-s -w ||')
      output: mc

test:
  pipeline:
    - uses: test/go-fips-check

update:
  enabled: false # uses strange versioning
