package:
  # body-type-number
  name: NIST-ESV-266
  # v1 of nist meta-packages
  version: 1
  epoch: 0
  # Many SCA tools know how to read APK URL
  # URL to the certificate
  url: https://csrc.nist.gov/projects/cryptographic-module-validation-program/entropy-validations/certificate/266
  # Some tools use description
  # body, type, number, certificate name, standard
  description: "NIST #E266 Jentropy Engine (SP 800-90B)"
  copyright:
    # NIST information is all public
    - license: NIST-PD
  dependencies:
    runtime:
      - bouncycastle-rng-jent

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    with:
      # Sadly the download URL has timestamps, meaning it has unstable checksum
      # Note this URL will make it into package SPDX SBOM, and will also make it into APKO SBOM
      uri: https://csrc.nist.gov/projects/cryptographic-module-validation-program/entropy-validations/certificate/266
      # This package will be rarely rebuilt, and it's ok if the webpage checksum needs to change
      expected-sha256: 0000000000000000000000000000000000000000000000000000000000000000
      expected-none: true
      extract: false
      delete: true

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: false
  exclude-reason: "This is an empty NIST certificate SBOM indicator"
