#nolint:valid-pipeline-fetch-digest
package:
  # body-type-number
  name: NIST-CMVP-4759
  # v1 of nist meta-packages
  version: 1
  epoch: 2
  # Many SCA tools know how to read APK URL
  # URL to the certificate
  url: https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4759
  # Some tools use description
  # body, type, number, certificate name, standard
  description: "NIST CMVP 4759 AWS-LC Cryptographic Module (dynamic) (FIPS 140-3) metapackage"
  copyright:
    # NIST information is all public
    - license: NIST-PD
  dependencies:
    runtime:
      # Strict dependency on the actual module
      - aws-lc-fips~2.0.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    with:
      # Sadly the download URL has timestamps, meaning it has unstable checksum
      # Note this URL will make it into package SPDX SBOM, and will also make it into APKO SBOM
      uri: https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4759
      # This package will be rarely rebuilt, and it's ok if the webpage checksum needs to change
      expected-none: true
      extract: false
      delete: true

test:
  pipeline:
    - uses: test/tw/metapackage
    - uses: test/cmvp-fips-certification-check
      with:
        certificate-number: 4759

update:
  enabled: false
  exclude-reason: "This is an empty NIST CMVP certificate SBOM indicator"
