package:
  name: nmap
  version: "7.98"
  epoch: 0
  description: "network discovery and security auditing tool"
  # Custom license, but we can distribute under the 'mere aggregation' GPL
  # clause. Ref: https://github.com/nmap/nmap/issues/2199#issuecomment-2127278266
  copyright:
    - license: LicenseRef-Nmap-Public-Source-License
      license-path: LICENSE

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libcap-utils
      - openssl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://nmap.org/dist/nmap-${{package.version}}.tar.bz2
      expected-sha256: ce847313eaae9e5c9f21708e42d2ab7b56c7e0eb8803729a3092f58886d897e6

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  - runs: |
      setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip "${{targets.destdir}}"/usr/bin/nmap

update:
  enabled: true
  release-monitor:
    identifier: 2096

subpackages:
  - name: nmap-doc
    description: nmap documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

test:
  environment:
  pipeline:
    - runs: |
        ncat --version
        nping --version
        ncat --help
        nping --help
