package:
  name: nrdot-collector-k8s
  version: "1.5.0"
  epoch: 0
  description: Custom distributions of the OpenTelemetry Collector for New Relic
  copyright:
    - license: Apache-2.0

vars:
  build_folder: _build

environment:
  contents:
    packages:
      - go
      - opentelemetry-collector-ocb

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0a58b96fb6406240c3c760d30924b3d9b1ba39f6
      repository: https://github.com/newrelic/nrdot-collector-releases
      tag: ${{package.version}}

  - runs: |
      mkdir -p ${{targets.contextdir}}/${{vars.build_folder}}
      CGO_ENABLED=0 ocb --skip-compilation=true --config ./distributions/nrdot-collector-k8s/manifest.yaml > ${{targets.contextdir}}/${{vars.build_folder}}/build.log 2>&1

test:
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: nrdot-collector-k8s

update:
  enabled: true
  github:
    identifier: newrelic/nrdot-collector-releases
    strip-prefix: v
    use-tag: true
