package:
  name: nri-mongodb-fips
  version: "2.10.2"
  epoch: 0
  description: New Relic Infrastructure mongodb Integration (FIPS)
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-mongodb
      expected-commit: 2cc1dc310b9a9968f1613f6367ed8be82a170132
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-mongodb
      go-package: go-fips-md5
      ldflags: |
        -X main.integrationVersion=${{package.version}}
        -X main.gitCommit=$(git rev-parse HEAD)
        -X main.buildDate=$(date -u -d "@$SOURCE_DATE_EPOCH" "+%Y-%m-%dT%H:%M:%SZ")

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/nri-mongodb ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin/nri-mongodb
          install -Dm644 legacy/mongodb-definition.yml ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/mongodb-definition.yml
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
          with:
            allow-absolute: "true"

update:
  enabled: true
  github:
    identifier: newrelic/nri-mongodb
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - uses: test/tw/help-check
      with:
        bins: nri-mongodb
    - uses: test/tw/ver-check
      with:
        bins: nri-mongodb
        version-flag: "-show_version"
    - name: Test binary execution
      uses: test/daemon-check-output
      with:
        start: |
          nri-mongodb -mongodb_cluster_name=my-mongos.company.localnet
        expected_output: |
          no reachable servers
        error_strings: |
          FAIL
          Traceback.*most.recent.call
