package:
  name: nri-elasticsearch-fips
  version: "5.4.5"
  epoch: 1
  description: New Relic Infrastructure elasticsearch Integration (FIPS)
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-elasticsearch
      expected-commit: 03711b4a553d8de727373be21b0c854831e58baa
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-elasticsearch
      go-package: go-fips-md5
      ldflags: |
        -X main.integrationVersion=${{package.version}}
        -X main.gitCommit=$(git rev-parse HEAD)
        -X main.buildDate=$(date -u -d "@$SOURCE_DATE_EPOCH" "+%Y-%m-%dT%H:%M:%SZ")

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/nri-elasticsearch ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin/nri-elasticsearch
          install -Dm644 legacy/elasticsearch-definition.yml ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/elasticsearch-definition.yml
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
          with:
            allow-absolute: "true"

update:
  enabled: true
  github:
    identifier: newrelic/nri-elasticsearch
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - uses: test/tw/help-check
      with:
        bins: nri-elasticsearch
    - uses: test/tw/ver-check
      with:
        bins: nri-elasticsearch
        version-flag: "-show_version"
    - name: "Test binary execution"
      uses: test/daemon-check-output
      with:
        start: |
          nri-elasticsearch
        expected_output: |
          com.newrelic.elasticsearch
          protocol_version
          integration_version
        error_strings: |
          "FAIL"
          "Traceback.*most.recent.call"
