package:
  name: nvidia-cuda-nvprune-12.1
  version: 12.1.55
  epoch: 1
  description: CUDA nvprune
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-cuda-nvprune=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/linux-sbsa/cuda_nvprune-linux-sbsa-12.1.55-archive.tar.xz"
          expected-sha256: "aa6555b40597b2b84e8c1bcb91af1c432070afcad5d47fe225508d6b3034d30e"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/linux-x86_64/cuda_nvprune-linux-x86_64-12.1.55-archive.tar.xz"
          expected-sha256: "c0766b464eb5f3cb0ddf72e5d97568d90b7e5b994561dc85274b3e95fc093078"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-12.1/
      mv bin ${{targets.destdir}}/usr/local/cuda-12.1/
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-12.1/${{package.name}}.LICENSE

update:
  enabled: false
