package:
  name: nvidia-libcufft-12.4
  version: 11.2.1.3
  epoch: 1
  description: CUDA cuFFT
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-libcufft=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcufft/linux-sbsa/libcufft-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "4087e27f2429d5f1f820ec49ac400391cbfe84c4abfadb95aaf90705ae84e725"
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcufft/linux-x86_64/libcufft-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "0963b4b57fb7fe9217e97b494159ff4719f1abdc407b2dc215d71bae0576bb02"

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda/
      mv include ${{targets.destdir}}/usr/local/cuda/
      mv lib ${{targets.destdir}}/usr/local/cuda/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda/${{package.name}}.LICENSE

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - nvidia-libcufft-12.4

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false
