package:
  name: nvidia-nsight-compute-12.8
  version: "2025.1.1.2"
  epoch: 1
  description: Nsight Compute
  copyright:
    - license: PROPRIETARY
  options:
    no-depends: true
  dependencies:
    provides:
      - nvidia-nsight-compute=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/linux-sbsa/nsight_compute-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "6070766fda9094b8556208e76140420d80f2759a49dd76f9ace15a580059226f"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/linux-x86_64/nsight_compute-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "6f55f6dfb33abe15b25a5f0c656ae8d9b6a6f33e55f0337b9b6a017daf8ad610"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
      mv docs ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv extras ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv host ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv ncu* ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv sections ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv target ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/

test:
  environment:
    contents:
      packages:
        - bash
  pipeline:
    - name: Verify installation and binaries
      runs: |
        test -x /usr/local/cuda-${{vars.cuda-version}}/nsight-compute/ncu
        test -x /usr/local/cuda-${{vars.cuda-version}}/nsight-compute/ncu-ui
    - name: Test binary functionality
      runs: |
        # Create symlinks for the nsight-compute version
        ln -s /usr/local/cuda-${{vars.cuda-version}}/nsight-compute/2025.1.1 /usr/local/cuda-${{vars.cuda-version}}/nsight-compute-2025.1.1

        /usr/local/cuda-${{vars.cuda-version}}/nsight-compute/ncu --version
        /usr/local/cuda-${{vars.cuda-version}}/nsight-compute/ncu --list-sections

update:
  enabled: false
