package:
  name: nvidia-cuda-nvcc-12.9
  version: "12.9.86"
  epoch: 1
  description: CUDA NVCC
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-sbsa/cuda_nvcc-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "0aa1fce92dbae76c059c27eefb9d0ffb58e1291151e44ff7c7f1fc2dd9376c0d"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-x86_64/cuda_nvcc-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "7a1a5b652e5ef85c82b721d10672fc9a2dbaab44e9bd3c65a69517bf53998c35"
          timeout: 30

  # Without this patch nvcc will not work with glibc 2.41 an newer, as their
  # recently added C23 math functions conflict with CUDA header definitions.
  - uses: patch
    with:
      patches: math_functions_glibc_2.41.patch

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv nvvm ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/

  - runs: |
      # Symlink the binaries onto the normal path
      mkdir -p ${{targets.destdir}}/usr/bin/
      for i in ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nvcc/bin/*; do
        [ -f "$i" ] && [ -x "$i" ] && ln -sf /usr/local/cuda-${{vars.cuda-version}}/nvcc/bin/$(basename "$i") ${{targets.destdir}}/usr/bin/
      done

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false

test:
  pipeline:
    - uses: test/tw/ldd-check
