package:
  name: nvidia-580
  version: 580.105.08
  epoch: 0
  description: NVIDIA Linux open GPU kernel module
  copyright:
    - license: MIT AND GPL-2.0

environment:
  environment:
    NV_BUILD_USER: noreply
    NV_BUILD_HOST: chainguard.dev
    KBUILD_BUILD_USER: noreply
    KBUILD_BUILD_HOST: chainguard.dev
    KBUILD_BUILD_VERSION: Chainguard
  contents:
    packages:
      - linux-aws-6.12-headers
      - linux-azure-6.12-headers
      - linux-gcp-6.12-headers
      - linux-qemu-6.12-headers
      - linux-vmware-6.12-headers

data:
  - name: kernels
    items:
      linux-aws-6.12: aws-6.12
      linux-azure-6.12: azure-6.12
      linux-gcp-6.12: gcp-6.12
      linux-qemu-6.12: qemu-6.12
      linux-vmware-6.12: vmware-6.12

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NVIDIA/open-gpu-kernel-modules
      tag: ${{package.version}}
      expected-commit: 2af9f1f0f7de4988432d4ae875b5858ffdb09cc2

  - uses: patch
    with:
      patches: modules/${{package.name}}/objtool-rethunk-sls-orc.patch

subpackages:
  - range: kernels
    name: ${{package.name}}-${{range.value}}
    description: NVIDIA Linux open GPU kernel module for ${{range.key}}
    pipeline:
      - uses: kernel/out-of-tree-module
        with:
          headers: ${{range.value}}
          chdir: false
          clean: true
    test:
      environment:
        contents:
          packages:
            - kmod
            - ${{range.key}}-headers
            # Only relevant because of PR to withdraw 580.119.02, can be removed after that.
            - ${{package.name}}-${{range.value}}=${{package.full-version}} # work around https://github.com/chainguard-dev/melange/issues/2194
      pipeline:
        - runs: |
            set -o pipefail
            modinfo /usr/lib/modules/*/extra/nvidia.ko.zst | grep vermagic | grep "${{range.value}}"
        - uses: kernel/test/module-signature
          with:
            module: 'nvidia*.ko*'
            certificate: nvidia-580.x509
        - uses: kernel/test/modprobe
          with:
            modprobe: nvidia
            # TODO(a-crate): fix oot module signing in tests
            # we have a signature but it's kind of difficult to get it into the keyring
            # in the microvm
            args: 'module.sig_enforce=0'
            # Nvidia module refuses to load if there is no hardware present. If
            # we reached the hardware scan it's probably OK.
            error: No such device

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: false
  exclude-reason: |
    Releases in the NVIDIA/open-gpu-kernel-modules repository include both data
    center driver releases and consumer display driver releases with no way to
    distinguish them. Tesla (data center) driver releases can be fetched from
    https://docs.nvidia.com/datacenter/tesla/drivers/releases.json

    This differs still from the CUDA userspace releases archived here
    https://developer.download.nvidia.com/compute/cuda/redist/nvidia_driver/linux-x86_64/
    which have their own versioning which does not align with either tesla releases
    or display driver releases.

    To check for the latest release, run ./linux-common/modules/nvidia-update.sh --version 580 --latest
