package:
  name: nvidia-cuda-nvprune-13.0
  version: "13.0.39"
  epoch: 0
  description: CUDA nvprune
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-cuda-nvprune=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/linux-sbsa/cuda_nvprune-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "d1ce1496aaef62af1ded7eda8b37b3d08d467f154ffebc23f0d5d8ed39f4ecc9"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/linux-x86_64/cuda_nvprune-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "3667f056c8b5955fd22022c36c0492fe4c482daa8d5b1afca3825f413f2b1e91"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

update:
  enabled: false

test:
  pipeline:
    - runs: |
        /usr/local/cuda-${{vars.cuda-version}}/bin/nvprune --version
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-cuda-nvprune
        real-pkg-name: ${{package.name}}
