package:
  name: nvidia-libcusolver-13.0
  version: "12.0.3.29"
  epoch: 0
  description: CUDA cuSOLVER
  copyright:
    - license: PROPRIETARY
  options:
    no-depends: true
  dependencies:
    provides:
      - nvidia-libcusolver=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}
      - nvidia-libcublas-${{vars.cuda-version}}
      - nvidia-libcusparse-${{vars.cuda-version}}
      - nvidia-libnvjitlink-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcusolver/linux-sbsa/libcusolver-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "4c8450862a909f3c275b903f277b48711fb2c89f027fe8d4b832b3d72a9ecf20"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcusolver/linux-x86_64/libcusolver-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "768e61f3b2448d5f05fa8f5465f9b22d7c186f2ec3418697f507d1b9855e8dbf"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    test:
      pipeline:
        - uses: test/pkgconf

test:
  pipeline:
    - name: Verify installation and license
      runs: |
        test -d /usr/local/cuda-${{vars.cuda-version}}
        test -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
        test -d /usr/local/cuda-${{vars.cuda-version}}/lib64
    - uses: test/tw/ldd-check
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-libcusolver
        real-pkg-name: ${{package.name}}

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false
