package:
  name: nvidia-libcufile-12.8
  version: "1.13.1.3"
  epoch: 0
  description: CUDA cuFile
  copyright:
    - license: PROPRIETARY
  options:
    no-depends: true
  dependencies:
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcufile/linux-sbsa/libcufile-linux-sbsa-${{package.version}}-archive.tar.xz" #
          expected-sha256: "3664a21fad7b7bb4424beec650fe4d1bee77062d4038427ba90bf4f5edf364fe"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcufile/linux-x86_64/libcufile-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "34a4bfe8fe98cb97e7631dfd29969284287f7cf8e19b372d49a4ee8f1e7ed797"
          timeout: 30

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - nvidia-libcufile-${{vars.cuda-version}}
    test:
      pipeline:
        - uses: test/pkgconf

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false

test:
  pipeline:
    - name: Verify libcufile installation and license
      runs: |
        # Verify basic directory structure
        test -d /usr/local/cuda-${{vars.cuda-version}}
        test -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
