package:
  name: nvidia-cuda-nvdisasm-11.4
  version: 11.4.152
  epoch: 1
  description: CUDA nvdisasm
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-cuda-nvdisasm=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/linux-sbsa/cuda_nvdisasm-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "68743913c877014b4f9a6d7267cc117d443c9990ea583ea837a1c51df1676d7d"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/linux-x86_64/cuda_nvdisasm-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "6ab9bd7c31a54529762fddc9ebfc4d331a912bf97b47318b0b75bfbd3b8a5551"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

update:
  enabled: false

test:
  pipeline:
    - runs: |
        /usr/local/cuda-${{vars.cuda-version}}/bin/nvdisasm --version
