package:
  name: cuda_cccl
  version: 12.3.101
  epoch: 0
  description: CXX Core Compute Libraries
  copyright:
    - license: PROPRIETARY
environment:
  contents:
    packages:
      - busybox
pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cccl/linux-sbsa/cuda_cccl-linux-sbsa-12.3.101-archive.tar.xz"
          expected-sha256: "77b22b4b5c54d7649edd62253979e7290314de73f268df152c1c21811ae20084"
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cccl/linux-x86_64/cuda_cccl-linux-x86_64-12.3.101-archive.tar.xz"
          expected-sha256: "dabd433bbef5f6d1b79f9a7eea909a3c273e20641f07a6a8667f42577462e34d"
  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/
      ln -s /usr/local/cuda-12.3 ${{targets.destdir}}/usr/local/cuda-12
      ln -s /usr/local/cuda-12.3 ${{targets.destdir}}/usr/local/cuda
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-12.3/
      mv include ${{targets.destdir}}/usr/local/cuda-12.3/
      mv lib ${{targets.destdir}}/usr/local/cuda-12.3/
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-12.3/
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*
update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false
