package:
  name: nvidia-libnvjitlink-12.6
  version: 12.6.20
  epoch: 0
  description: NVIDIA compiler library for JIT LTO functionality
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-libnvjitlink=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libnvjitlink/linux-sbsa/libnvjitlink-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "a25199ea3a109f216e14bb55c5043feac237f6c5adfdc28e709cbad0a6783317"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libnvjitlink/linux-x86_64/libnvjitlink-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "7e57521fc4065f264bd7fd118d267636c2cdf0e542465f281e767e206cf5a794"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false
