package:
  name: nvidia-libcurand-12.1
  version: 10.3.2.106
  epoch: 2
  description: CUDA cuRAND
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-libcurand=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcurand/linux-sbsa/libcurand-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "525d997d74b391a3484f9c71e7a6e51a136267b8a2dddbfef1420134f3011827"
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcurand/linux-x86_64/libcurand-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "9941216fad2d419e6172dbd2ee431d77effe671065c08490782fc286ebb364de"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-12.1/
      mv include ${{targets.destdir}}/usr/local/cuda-12.1/
      mv lib ${{targets.destdir}}/usr/local/cuda-12.1/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-12.1/${{package.name}}.LICENSE

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - nvidia-libcurand-12.1
    test:
      pipeline:
        - uses: test/pkgconf

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false

var-transforms:
  - from: ${{package.name}}
    match: .*-(\d+\.\d+).*
    replace: $1
    to: cuda-version

test:
  pipeline:
    - uses: test/tw/ldd-check
