package:
  name: nvidia-cuda-sanitizer-api-12.2
  version: 12.2.140
  epoch: 2
  description: CUDA Compute Sanitizer API
  copyright:
    - license: PROPRIETARY
  options:
    no-depends: true
  dependencies:
    provides:
      - nvidia-cuda-sanitizer-api=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_sanitizer_api/linux-sbsa/cuda_sanitizer_api-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "a16ca8a7283b4eb074ee878fc44c85dab8946ed6d2ff6a8893c409ebff3c8e3e"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_sanitizer_api/linux-x86_64/cuda_sanitizer_api-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "1d02913ab7a1389a13b4f66479be73fe6391df29a53123cf86efba5f88e991d2"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv compute-sanitizer ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

subpackages:
  - name: ${{package.name}}-docs
    description: ${{package.name}} docs
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/local/cuda-${{vars.cuda-version}}/compute-sanitizer
          mv ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/compute-sanitizer/docs ${{targets.contextdir}}/usr/local/cuda-${{vars.cuda-version}}/compute-sanitizer

  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}

test:
  pipeline:
    - name: Run --help and --version
      runs: |
        /usr/local/cuda-${{vars.cuda-version}}/compute-sanitizer/compute-sanitizer --help
        /usr/local/cuda-${{vars.cuda-version}}/compute-sanitizer/compute-sanitizer --version
    - name: Verify the license
      runs: |
        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE ]; then
          echo "License file not found"
          exit 1
        fi

update:
  enabled: false
