package:
  name: nvidia-nsight-compute-12.3
  version: 2023.3.1.1
  epoch: 1
  description: Nsight Compute
  copyright:
    - license: LicenseRef-NVIDIA-SLA
      license-path: LICENSE
  options:
    no-depends: true
  dependencies:
    provides:
      - nvidia-nsight-compute=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/linux-sbsa/nsight_compute-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "20023f701cc9a79fbe3c42f7b2fb3d3e30a562fae9ced2c5c4a2e707caecf4ab"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/linux-x86_64/nsight_compute-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "78934c8cc402401814ad6f0046173fdb4f0d2875c7bc70b99d472856d0d525b8"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv nsight-compute ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/

update:
  enabled: false
