package:
  name: nvidia-cuda-profiler-api-12.1
  version: 12.1.105
  epoch: 2
  description: CUDA Profiler API
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-cuda-profiler-api=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/linux-sbsa/cuda_profiler_api-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "f7e0a26f39e65b8ccdac72ee37b74cd91ca6a02dad5e37eb95d6fb916fdfae2f"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/linux-x86_64/cuda_profiler_api-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "3fff6cb6eb0e04f96b0b5fca26d97486cacd1ea6d3d0d2fcf8d2982bf0b3eda0"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

test:
  pipeline:
    - name: Verify license exists
      runs: |
        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE ]; then
          echo "License file not found!"
          exit 1
        fi
    - name: Verify header files exist
      runs: |
        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/include/cudaProfiler.h ]; then
          echo "cudaProfiler.h header file not found!"
          exit 1
        fi
        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/include/cuda_profiler_api.h ]; then
          echo "cuda_profiler_api.h header file not found!"
          exit 1
        fi

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false
