package:
  name: nvidia-nsight-compute-12.6
  version: 2024.3.1.2
  epoch: 0
  description: Nsight Compute
  copyright:
    - license: PROPRIETARY
  options:
    no-depends: true
  dependencies:
    provides:
      - nvidia-nsight-compute=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/linux-sbsa/nsight_compute-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "fc6519f2e5ab340a6d4f5d0ae3842b6c54bedb24964eba0e5bd04aa497f1138a"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/linux-x86_64/nsight_compute-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "244e39cfc2c0ac02eaa8db20eb5fd45ec0ce31edf5481febb10acb5d144ce6da"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
      mv docs ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv extras ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv host ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv ncu* ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv sections ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/
      mv target ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/nsight-compute/

update:
  enabled: false
