package:
  name: nvidia-libnvjpeg-12.8
  version: "12.3.5.92"
  epoch: 1
  description: high-performance GPU-accelerated library for decoding, encoding and transcoding JPEG format images.
  copyright:
    - license: LicenseRef-NVIDIA-CUDA
      license-path: LICENSE
  dependencies:
    provides:
      - nvidia-libnvjpeg=${{package.version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libnvjpeg/linux-sbsa/libnvjpeg-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "716c38829983bca34a2c5c294237ded0f423597adc0fdce9fcd954a23c283909"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libnvjpeg/linux-x86_64/libnvjpeg-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "9f4cfb4a293c329b5b902790814bdf6a652b162fd17510b7ea7d141c123e7bbc"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    test:
      pipeline:
        - uses: test/pkgconf

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false

test:
  pipeline:
    - uses: test/tw/ldd-check
