package:
  name: onednn
  version: "3.9"
  epoch: 0
  description: oneAPI Deep Neural Network Library (oneDNN) is an open-source cross-platform performance library of basic building blocks for deep learning applications
  copyright:
    - license: Apache-2.0
  target-architecture:
    - x86_64

vars:
  abi: 3
  py-version: 3.13

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - py${{vars.py-version}}-build-base
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/uxlfoundation/oneDNN
      tag: v${{package.version}}
      expected-commit: d2a5702ac2903cf447fc0c469b255639336f1ed7

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

test:
  pipeline:
    - uses: test/emptypackage

subpackages:
  - name: libdnnl${{vars.abi}}
    description: oneAPI Deep Neural Network Library (oneDNN) is an open-source cross-platform performance library of basic building blocks for deep learning applications
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr
          mv ${{targets.destdir}}/usr/lib ${{targets.contextdir}}/usr
          mv ${{targets.destdir}}/usr/include ${{targets.contextdir}}/usr
      - name: empty out main package
        runs: |
          # explicitly remove only the things we expect to be left over.
          # this way, if anything new gets added, test/emptypackage will
          # fail and alert us.
          rm -rf ${{targets.destdir}}/usr/share/doc
          rmdir ${{targets.destdir}}/usr/share
          rmdir ${{targets.destdir}}/usr
      - name: Check that ABI has not changed
        runs: |
          test -e ${{targets.contextdir}}/usr/lib/libdnnl.so.${{vars.abi}}

  - name: libdnnl-dev
    description: libdnnl dev
    dependencies:
      runtime:
        - libdnnl${{vars.abi}}=${{package.full-version}}
    pipeline:
      - uses: split/dev
        with:
          package: libdnnl${{vars.abi}}

update:
  enabled: true
  github:
    identifier: uxlfoundation/oneDNN
    strip-prefix: v
