package:
  name: onepassword-operator
  version: "1.10.0"
  epoch: 1 # CVE-2025-61725
  description: The 1Password Connect Kubernetes Operator provides the ability to integrate Kubernetes Secrets with 1Password.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/1Password/onepassword-operator
      tag: v${{package.version}}
      expected-commit: 8d21a950ac53656770d16f4649892d648a1dca27

  - uses: go/build
    with:
      packages: ./cmd
      output: manager
      ldflags: -X github.com/1Password/onepassword-operator/version.Version=${{package.version}}

  - runs: |
      mkdir -p ${{targets.contextdir}}/config/connect
      cp -r config/connect/* ${{targets.contextdir}}/config/connect/

subpackages:
  - name: ${{package.name}}-compat
    description: Compatibility package for ${{package.name}}
    pipeline:
      - runs: |
          # Create symlink at /manager for compatibility
          mkdir -p ${{targets.contextdir}}/
          ln -s ./usr/bin/manager ${{targets.contextdir}}/manager
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
        - runs: |
            /manager --help

update:
  enabled: true
  github:
    identifier: 1Password/onepassword-operator
    strip-prefix: v

test:
  pipeline:
    - runs: |
        # we cannot automate the tests for operator right now since operator needs to be connected to 1password
        # so we have to have at least 1password account and setup the operator with that account
        manager -h
