package:
  name: onnxruntime
  version: "1.23.1"
  epoch: 1
  description: Cross-platform, high performance ML inferencing and training accelerator
  copyright:
    - license: MIT
  resources:
    cpu: 20
    memory: 50Gi

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - bash
      - cmake-3
      - eigen-dev
      - flatbuffers
      - openvino
      - openvino-dev
      - patch
      - protobuf
      - protobuf-dev
      - py3-build-base-dev
      - py3.13-numpy-2.2
      - python3
      - zlib-dev
  environment:
    # This seems to be required to compile `abseil`
    # FIXME: remove this eventually
    CXXFLAGS: "-fdelete-null-pointer-checks"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/microsoft/onnxruntime.git
      tag: v${{package.version}}
      expected-commit: d9b2048791efb5804fe3d53a04b4971256addebf
      recurse-submodules: true
      cherry-picks: |
        main/d6e712c5b7b6260a61e54d1fe40107cf5366ee77: Update semver.h to fix compilation error under linux

  # NOTE: this sets some 'magic' apparently, otherwise we would use the 'cmake/build' pipeline.
  # review in future upstream releases
  - name: "build using upstream wrapper script"
    runs: |
      ./build.sh --build --update --config Release --build_shared_lib --parallel --compile_no_warning_as_error \
        --skip_submodule_sync --enable_training_apis --allow_running_as_root --skip_tests \
        --cmake_extra_defines \
          CMAKE_POLICY_VERSION_MINIMUM=3.5 \
          CMAKE_INSTALL_PREFIX=/usr \
          onnxruntime_ENABLE_PYTHON=ON \
          onnxruntime_BUILD_SHARED_LIB=ON \
          onnxruntime_BUILD_UNIT_TESTS=OFF \
          BUILD_TESTING=OFF \
          onnxruntime_ENABLE_TRAINING=ON \
          onnxruntime_ENABLE_LAZY_TENSOR=OFF \
          onnxruntime_USE_MPI=ON \
          onnxruntime_USE_DNNL=OFF \
          onnxruntime_USE_PREINSTALLED_EIGEN=ON \
          CMAKE_CXX_STANDARD=17 \
          onnxruntime_USE_OPENVINO=ON \
          onnxruntime_USE_OPENVINO_GPU=ON \
          onnxruntime_USE_OPENVINO_CPU=ON \
          onnxruntime_USE_OPENVINO_NPU=ON

  - uses: cmake/install
    with:
      output-dir: build/Linux/Release

  # NOTE: I haven't found any way to tell cmake to change this,
  # may be because the upstream build.sh script is too smart
  - name: "change /lib64/ in the path to just /lib/"
    runs: mv ${{targets.destdir}}/usr/lib64 ${{targets.destdir}}/usr/lib

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

update:
  enabled: true
  github:
    identifier: microsoft/onnxruntime
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-dev
        - build-base
  pipeline:
    - uses: test/tw/ldd-check
    - name: Ensure libraries link and are functional
      runs: |
        set -o pipefail
        tee orttest.cpp <<'EOF'
        #include <iostream>
        #include "onnxruntime_cxx_api.h"
        int main(){
          //check providers
          auto providers = Ort::GetAvailableProviders();
          for (auto provider : providers) {
            std::cout << provider << std::endl;
          }
          std::cout <<  Ort::GetVersionString() << std::endl;
          return 0;
        }
        EOF
        c++ orttest.cpp -o ort_version $(pkgconf --libs libonnxruntime) $(pkgconf --cflags libonnxruntime)
        ldd ./ort_version | grep -F -e "libonnxruntime"
        ./ort_version | grep -F -e "${{package.version}}" -e "CPU"
