package:
  name: open-vm-tools
  version: "13.0.5"
  epoch: 0
  description: Open VM Tools for VMWare guests
  copyright:
    - license: GPL-2.0 AND LGPL-2.1-only AND X11 AND OLDAP-2.8
  dependencies:
    runtime:
      - bash
      - coreutils
      - iproute2
      - procps
      - xmlsec-openssl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - doxygen
      - fuse3-dev
      - gettext-dev
      - glib-dev
      - gtk-3-dev
      - icu-dev
      - libdrm-dev
      - libmspack-dev
      - libsigcplusplus-dev
      - libtirpc-dev
      - libtool
      - libudev
      - libxtst-dev
      - linux-headers
      - linux-pam-dev
      - openssl-dev
      - pkgconf-dev
      - rpcsvc-proto
      - xmlsec-dev
      - xmlsec-openssl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vmware/open-vm-tools.git
      expected-commit: fbc80ffbd226b4a61bb8ea1c9a682b5c7614e3fd
      tag: stable-${{package.version}}

  - uses: patch
    with:
      patches: |
        0001-PATCH-lib-misc-Recognize-Chainguard-Wolfi.patch

  - runs: |
      # Move the source directory so it is easier to deal with
      mv open-vm-tools/* .
      rm -r open-vm-tools

  - uses: autoconf/configure
    with:
      opts: |
        --sbindir=/usr/bin \
        --with-udev-rules-dir=/usr/lib/udev/rules.d \
        --without-kernel-modules \
        --disable-glibc-check \
        --without-dnet \
        --without-gtk2 \
        --without-gtkmm3 \
        --without-gtkmm \
        --enable-servicediscovery=yes \
        --enable-containerinfo=no

  - uses: autoconf/make-install

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/systemd/system
      install -p -m 0644 vgauthd.service ${{targets.destdir}}/usr/lib/systemd/system
      install -p -m 0644 vmtoolsd.service ${{targets.destdir}}/usr/lib/systemd/system

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv ${{targets.destdir}}/usr/share/doc ${{targets.subpkgdir}}/usr/share

  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev

  - name: ${{package.name}}-debug
    pipeline:
      - uses: split/debug

test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        vmwgfxctrl --help
        vmware-hgfsclient --help
        vmware-vmblock-fuse --help

update:
  enabled: true
  github:
    identifier: vmware/open-vm-tools
    strip-prefix: stable-
    tag-filter-prefix: stable-
