#nolint:valid-pipeline-git-checkout-tag
package:
  name: open-liberty
  version: 24.0.0.11
  epoch: 1
  description: "Open Liberty is a highly composable, fast to start, dynamic application server runtime environment"
  resources:
    cpu: 32
    memory: 32Gi
  copyright:
    - license: EPL-2.0

vars:
  open-liberty-home: "/usr/share/java/open-liberty"

data:
  - name: variants
    items:
      full: "full"
      slim: "kernel-slim"

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - findutils
      - libarchive-tools
      - openjdk-21
      - openjdk-21-default-jvm
      - sed
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-21-openjdk

pipeline:
  - uses: git-checkout
    with:
      expected-commit: daad205e2831f1d46bdb56781f75a0f17eaf9e3d
      repository: https://github.com/OpenLiberty/open-liberty
      tag: gm-${{package.version}}

  - working-directory: dev
    runs: |
      ./gradlew --parallel cnf:initialize
      ./gradlew --parallel assemble
      ./gradlew --parallel releaseNeeded

      mkdir -p ${{targets.contextdir}}/${{vars.open-liberty-home}}
      bsdtar xvf cnf/release/dev/openliberty/${{package.version}}*/openliberty-${{package.version}}*.zip --strip-components=1 -C ${{targets.contextdir}}/${{vars.open-liberty-home}}

      # Remove Windows batch scripts and executables
      find ${{targets.contextdir}} -name "*.bat" -exec rm -rf '{}' +
      find ${{targets.contextdir}} -name "*.exe" -exec rm -rf '{}' +

  - uses: strip

  # Tags aren't cut, a branch specific to the version of Open Liberty is created before release
  - uses: git-checkout
    with:
      expected-commit: e4fb041438e51f86133be5ad296214e8a4e196d7
      repository: https://github.com/OpenLiberty/ci.docker
      branch: ${{package.version}}-release

subpackages:
  - range: variants
    name: ${{package.name}}-docker-${{range.key}}
    description: Configuration and scripts for running Open Liberty in Docker - ${{range.key}}
    dependencies:
      runtime:
        - ${{package.name}}
        - bash
        - busybox
        - dumb-init
        - glibc-locale-en
        - openssl
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/${{vars.open-liberty-home}}
          mv releases/${{package.version}}/${{range.value}}/helpers \
            ${{targets.contextdir}}/${{vars.open-liberty-home}}/helpers

          # Create server config directories
          mkdir -p ${{targets.contextdir}}/config/configDropins/defaults
          mkdir -p ${{targets.contextdir}}/config/configDropins/overrides

          # Use correct paths
          find ${{targets.contextdir}} -type f -exec sed -i 's|/opt/ol/wlp|${{vars.open-liberty-home}}|g' {} +
          find ${{targets.contextdir}} -type f -exec sed -i 's|/opt/ol|${{vars.open-liberty-home}}|g' {} +

update:
  enabled: true
  github:
    identifier: OpenLiberty/open-liberty
    strip-prefix: gm-
    tag-filter: gm-

test:
  environment:
    contents:
      packages:
        - openjdk-21-default-jvm
  pipeline:
    - runs: |
        export PATH="/usr/share/java/open-liberty/bin:$PATH"
        server help
        client help
        server create
        server start
        client create
        server stop
