package:
  name: open-liberty
  version: 24.0.0.10
  epoch: 0
  description: "Open Liberty is a highly composable, fast to start, dynamic application server runtime environment"
  copyright:
    - license: EPL-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - gradle
      - openjdk-21
      - openjdk-21-default-jvm
      - unzip
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-21-openjdk

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9413bdccccd24746b89a1c3637bd627b3288fad3
      repository: https://github.com/OpenLiberty/open-liberty
      tag: gm-${{package.version}}

  - runs: |
      cd dev
      ./gradlew cnf:initialize
      ./gradlew assemble
      ./gradlew releaseNeeded

      mkdir -p ${{targets.contextdir}}/usr/share/java/openliberty
      cp -r cnf/release/dev/openliberty/${{package.version}}*/openliberty-${{package.version}}*.zip ${{targets.contextdir}}/usr/share/java/openliberty/openliberty-${{package.version}}.zip

      unzip -q ${{targets.contextdir}}/usr/share/java/openliberty/openliberty-${{package.version}}.zip -d ${{targets.contextdir}}/usr/share/java/openliberty
      rm ${{targets.contextdir}}/usr/share/java/openliberty/openliberty-${{package.version}}.zip

  - uses: strip

update:
  enabled: true
  github:
    identifier: OpenLiberty/open-liberty
    strip-prefix: gm-
    tag-filter: gm-

test:
  environment:
    contents:
      packages:
        - openjdk-21
        - openjdk-21-default-jvm
        - busybox
  pipeline:
    - runs: |
        /usr/share/java/openliberty/wlp/bin/server help
        /usr/share/java/openliberty/wlp/bin/client help
