package:
  name: open-liberty
  version: 24.0.0.10
  epoch: 0
  description: "Open Liberty is a highly composable, fast to start, dynamic application server runtime environment"
  copyright:
    - license: EPL-2.0
  dependencies:
    provider-priority: 0

data:
  - name: openjdk-versions
    items:
      8: "java-1.8-openjdk"
      11: "java-11-openjdk"
      17: "java-17-openjdk"
      21: "java-21-openjdk"

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - gradle
      - openjdk-11
      - openjdk-17
      - openjdk-21
      - openjdk-8
      - unzip
  environment:
    LANG: en_US.UTF-8

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9413bdccccd24746b89a1c3637bd627b3288fad3
      repository: https://github.com/OpenLiberty/open-liberty
      tag: gm-${{package.version}}

subpackages:
  - range: openjdk-versions
    name: open-liberty-openjdk-${{range.key}}
    description: "Open Liberty is a highly composable, fast to start, dynamic application server runtime environment for OpenJDK ${{range.key}}"
    dependencies:
      runtime:
        - openjdk-${{range.key}}-default-jvm
      provides:
        - ${{package.name}}
      provider-priority: ${{range.key}}
    pipeline:
      - working-directory: dev
        runs: |
          export JAVA_HOME="/usr/lib/jvm/${{range.value}}"

          ./gradlew cnf:initialize
          ./gradlew assemble
          ./gradlew releaseNeeded

          mkdir -p ${{targets.contextdir}}/usr/share/java/openliberty
          unzip -q cnf/release/dev/openliberty/${{package.version}}*/openliberty-${{package.version}}*.zip -d ${{targets.contextdir}}/usr/share/java/openliberty
      - uses: strip

update:
  enabled: true
  github:
    identifier: OpenLiberty/open-liberty
    strip-prefix: gm-
    tag-filter: gm-

test:
  pipeline:
    - runs: |
        export PATH="/usr/share/java/openliberty/wlp/bin:$PATH"
        server help
        client help
        server create
        server start
        client create
        server stop
