package:
  name: os-shell-iamguarded
  version: 1.0.0
  epoch: 0
  description: "Meta package for OS Shell for Iamguarded Helm Charts"
  dependencies:
    runtime:
      - bash
      - ca-certificates
      - ca-certificates-bundle
      - coreutils
      - curl
      - dash
      - dash-binsh
      - diffutils
      - findutils
      - gpgv
      - grep
      - gzip
      - jq
      - mount
      - openssl
      - procps
      - sed
      - tzdata
      - util-linux
      - util-linux-misc

environment:
  contents:
    packages:
      - busybox

pipeline:
  - runs: mkdir -p ${{targets.contextdir}}

update:
  enabled: false
  exclude-reason: |
    This is a meta package for use in Helm charts.

test:
  pipeline:
    # Test both bash and dash.
    # Our test wrapper loads 'busybox' by default! so a /bin/sh -c "pwd" check
    # would always pass.
    - name: Ensure package provides both bash and dash
      runs: |
        /bin/bash -c "pwd"
        apk info | grep "dash"
