package:
  name: ostree
  version: "2025.7"
  epoch: 0
  description: Operating system and container binary deployment and upgrades
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - bison
      - build-base
      - composefs-dev
      - curl-dev
      - e2fsprogs-dev
      - fuse3-dev
      - glib-dev
      - gpgme-dev
      - libarchive-dev
      - libselinux-dev
      - libtool
      - pkgconf-dev
      - systemd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ostreedev/ostree
      tag: v${{package.version}}
      expected-commit: 134d144cb52ff018cfedfb936b661189bccc76e6

  - runs: env NOCONFIGURE=1 ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --disable-silent-rules \
        --enable-gtk-doc \
        --with-selinux \
        --with-curl \
        --with-openssl \
        --without-soup \
        --with-composefs \
        --with-dracut=yesbutnoconf

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ostree-dev
    description: Headers and dev libraries from ostree
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/verify-service
    - runs: |
        set -o pipefail
        ostree --help | grep -F -e "Commands for managing a host system booted with ostree"
        ostree --version | grep -F -e "${{package.version}}"
    - name: Ensure expected modules are installed
      runs: |
        expected="composefs
        ex-fsverity
        gpgme
        initial-var
        inode64
        libarchive
        libcurl
        libmount
        openssl
        p2p
        selinux
        sign-ed25519
        sign-spki
        systemd
        "
        # TODO: enable this one libsoup is packaged
        # grep_file "libsoup3"

        MODULES_OUTPUT=$(mktemp)
        ostree --version > "$MODULES_OUTPUT" 2>&1 ||
            { echo "FATAL: 'ostree --version' exited $?"; exit 1; }
        echo "$ ostree --version"
        cat "$MODULES_OUTPUT"

        missing=""
        for e in $expected; do
          grep -q -F -e "$e" "$MODULES_OUTPUT" && continue
          echo "did not find $e in output of 'ostree --version'";
          missing="${missing} $e"
        done
        if [ -n "$missing" ]; then
           echo "FATAL: ostree --version output did not contain: ${missing# }"
           exit 1
        fi

update:
  enabled: true
  github:
    identifier: ostreedev/ostree
    strip-prefix: v
