package:
  name: packer-fips
  version: "1.13.0"
  epoch: 0
  copyright:
    - license: BUSL-1.1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/packer
      tag: v${{package.version}}
      expected-commit: b5ed1784c2520976e511e40480d5514d7a15e61a

  - uses: go/build
    with:
      go-package: go-fips
      packages: .
      output: packer
      ldflags: -X github.com/packer/version.GitCommit=$(git rev-parse HEAD)

update:
  enabled: true
  github:
    identifier: hashicorp/packer
    strip-prefix: v

test:
  pipeline:
    - name: Verison Check
      runs: |
        packer version
        packer --version
        packer --help
    - uses: test/go-fips-check
