package:
  name: packer-fips
  version: "1.14.3"
  epoch: 1 # GHSA-j5w8-q4qc-rx2x
  copyright:
    - license: BUSL-1.1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/packer
      tag: v${{package.version}}
      expected-commit: bbdb7581bb900fb1ccd56080bd6b4916fff07f41

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/crypto@v0.45.0
      modroot: packer_test/common/plugin_tester

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/crypto@v0.45.0

  - uses: go/build
    with:
      go-package: go-fips
      packages: .
      output: packer
      ldflags: -X github.com/packer/version.GitCommit=$(git rev-parse HEAD)

update:
  enabled: true
  github:
    identifier: hashicorp/packer
    strip-prefix: v

test:
  pipeline:
    - name: Verison Check
      runs: |
        packer version
        packer --version
        packer --help
    - uses: test/go-fips-check
