package:
  name: perl-xml-libxml
  version: "2.0210"
  epoch: 0
  description: The XML-LibXML CPAN Distribution for Processing XML using the libxml2 library
  copyright:
    - license: Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-xml-namespacesupport
      - perl-xml-sax
      - perl-xml-sax-base

environment:
  contents:
    packages:
      - build-base
      - libxml2-dev
      - perl-alien-build
      - perl-alien-libxml2
      - perl-dev
      - perl-xml-namespacesupport
      - perl-xml-sax
      - perl-xml-sax-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/shlomif/perl-XML-LibXML
      tag: XML-LibXML-${{package.version}}
      expected-commit: e400c9d2d4a063d1ab827d3b0fe5447cd77b3a2f

  - uses: patch
    with:
      patches: |
        fix-test-suite-libxml2.patch
        fix-html-encoding-libxml2-2.14.patch

  - uses: perl/make

  - uses: autoconf/make

  - runs: make test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: XML-LibXML-

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: ${{package.name}} docs
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - name: Smoke test
      runs: |
        set -euo pipefail
        perl -e 'use XML::LibXML; print "XML::LibXML loaded successfully\n"'
