package:
  name: plog
  version: 1.1.10
  epoch: 0
  description: "Portable, simple and extensible C++ logging library"
  copyright:
    - license: 'MIT'

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SergiusTheBest/plog
      tag: ${{package.version}}
      expected-commit: e21baecd4753f14da64ede979c5a19302618b752

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: plog-static
    description: "Portable, simple and extensible C++ logging library - static libraries"
    pipeline:
      - uses: split/static

  - name: plog-dev
    description: "Portable, simple and extensible C++ logging library - development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: SergiusTheBest/plog
