package:
  name: prometheus-alertmanager-fips
  version: 0.27.0
  epoch: 9
  description: Prometheus Alertmanager
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm

vars:
  PKG: "github.com/prometheus/common"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/alertmanager
      tag: v${{package.version}}
      expected-commit: 0aa3c2aad14cff039931923ab16b26b7481783b5

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0

  - runs: |
      # These targets build the ui/react-app/embed.go and the compressed static assets
      make build-react-app assets-compress

  - uses: go/build
    with:
      go-package: go-fips
      packages: ./cmd/alertmanager
      output: alertmanager
      ldflags: -X ${{vars.PKG}}/version.Revision=$(git rev-parse --short HEAD) -X ${{vars.PKG}}/version.BuildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -X ${{vars.PKG}}/version.Branch=$(git branch --show-current) -X ${{vars.PKG}}/version.Version=v${{package.version}}

  - uses: go/build
    with:
      go-package: go-fips
      packages: ./cmd/amtool
      output: amtool
      ldflags: -X ${{vars.PKG}}/version.Revision=$(git rev-parse --short HEAD) -X ${{vars.PKG}}/version.BuildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -X ${{vars.PKG}}/version.Branch=$(git branch --show-current) -X ${{vars.PKG}}/version.Version=v${{package.version}}

  - runs: |
      install -Dm644 examples/ha/alertmanager.yml "${{targets.destdir}}"/etc/alertmanager/alertmanager.yml

  - uses: strip

test:
  pipeline:
    - uses: test/go-fips-check

update:
  enabled: true
  github:
    identifier: prometheus/alertmanager
    strip-prefix: v
