package:
  name: prometheus-postgres-exporter-fips
  version: 0.15.0
  epoch: 3
  description: Prometheus Exporter for Postgres server metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go-fips

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 68c176b8833b7580bf847cecf60f8e0ad5923f9a
      repository: https://github.com/prometheus-community/postgres_exporter
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - runs: |
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make build

  - runs: |
      install -Dm755 postgres_exporter "${{targets.destdir}}"/usr/bin/postgres_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus-community/postgres_exporter
    strip-prefix: v
