package:
  name: prometheus-mongodb-exporter-fips
  version: 0.41.0
  epoch: 0
  description: A Prometheus exporter for MongoDB including sharding, replication and storage engines
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6dcda3afa6dbcd1bae93e755c8bfee5e1530b201
      repository: https://github.com/percona/mongodb_exporter
      tag: v${{package.version}}

  - uses: go/build
    with:
      go-package: go-fips
      packages: .
      output: mongodb_exporter
      ldflags: -X main.version=$(git describe --abbrev=0 --always) -X main.buildDate=$(date +%FT%T%z) -X main.commit=$(git rev-parse HEAD) -X main.Branch=$(git describe --always --contains --all)

test:
  pipeline:
    - uses: test/go-fips-check

update:
  enabled: true
  github:
    identifier: percona/mongodb_exporter
    strip-prefix: v
