package:
  name: prometheus-jmx-exporter-iamguarded
  version: "1.5.0"
  epoch: 0
  dependencies:
    runtime:
      - merged-usrsbin
      - openjdk-17-default-jdk
      - wolfi-baselayout
  description: "Prometheus JMX Exporter for iamguarded"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates
      - curl
      - maven
      - openjdk-${{vars.java-version}}-default-jdk
      - procps
      - zlib

var-transforms:
  # Extract the major version from the package version.
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

vars:
  java-version: 17

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/jmx_exporter
      tag: ${{package.version}}
      expected-commit: 72ad343795ce3e32651bd1810c4d3ed8395b3816

  - name: build-intall-jars
    # Build the project using Maven
    runs: |
      ./mvnw clean package -DskipTests

  - name: create-required-dirs
    # Create the required directories for a iamguarded-like layout
    runs: |
      mkdir -p /opt/iamguarded
      mkdir -p /opt/iamguarded/jmx-exporter
      mkdir -p /opt/iamguarded/java
      mkdir -p /opt/iamguarded/jmx-exporter/licenses
      mkdir -p /tmp/iamguarded/pkg/cache/

  - name: copy-files-to-dest
    # Don't use symlinks for old reasons
    runs: |
      cp -R ./examples /opt/iamguarded/jmx-exporter/

      # Create symlinks for all files and directories in /usr/lib/jvm/java-${{vars.java-version}}-openjdk/
      for item in /usr/lib/jvm/java-${{vars.java-version}}-openjdk/*; do
        # Get the base name of the item (file or directory)
        base_item=$(basename "$item")
        ln -s "$item" /opt/iamguarded/java/$base_item
      done

      # Copy built JARs for agent and standalone server
      cp ./jmx_prometheus_javaagent/target/jmx_prometheus_javaagent-${{package.version}}.jar \
          /opt/iamguarded/jmx-exporter/jmx_prometheus_javaagent.jar
      cp ./jmx_prometheus_standalone/target/jmx_prometheus_standalone-${{package.version}}.jar \
          /opt/iamguarded/jmx-exporter/jmx_prometheus_standalone.jar

  - uses: iamguarded/build-compat
    with:
      package: jmx-exporter
      version: ${{vars.major-version}}

  - uses: iamguarded/finalize-compat
    with:
      package: jmx-exporter
      version: ${{vars.major-version}}

test:
  environment:
    contents:
      packages:
        - curl
        - openjdk-bcfips-policy-140-3-j${{vars.java-version}}
        - maven
    environment:
      JAVA_HOME: /opt/iamguarded/java
      CLASSPATH: /usr/share/java/bouncycastle-fips/*:./*:.
      JAVA_TOOL_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips
      JDK_JAVAC_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips --add-exports=java.base/sun.security.internal.spec=ALL-UNNAMED --add-exports=java.base/sun.security.provider=ALL-UNNAMED
      JDK_JAVA_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips -Djavax.net.ssl.trustStoreType=FIPS -Djava.security.properties=/usr/lib/jvm/default-jvm/conf/security/java.security -Dorg.bouncycastle.fips.approved.only=true --add-exports=java.base/sun.security.internal.spec=ALL-UNNAMED --add-exports=java.base/sun.security.provider=ALL-UNNAMED
  pipeline:
    - uses: git-checkout
      with:
        repository: https://github.com/prometheus/jmx_exporter
        tag: ${{package.version}}
        expected-commit: 72ad343795ce3e32651bd1810c4d3ed8395b3816
    - name: Test JavaAgent with non-SSL
      runs: |
        set -ex
        cd integration_test_suite
        mvn clean package -pl !integration_tests -DskipTests
        cd ..

        # Create a minimal config for the JMX Exporter in standalone mode.
        mkdir -p /tmp/jmx-exporter-test
        cat <<EOF > /tmp/jmx-exporter-test/config.yaml
        rules:
          - pattern: ".*"
        EOF

        java \
           -javaagent:/opt/iamguarded/jmx-exporter/jmx_prometheus_javaagent.jar=8888:/tmp/jmx-exporter-test/config.yaml \
           -jar ./integration_test_suite/integration_tests/src/test/resources/common/jmx_example_application.jar > out.log 2>&1 &
        STANDALONE_PID=$!

        # Allow the exporter time to start
        sleep 15

        # Verify the JMX Exporter is still running
        kill -0 "$STANDALONE_PID" 2>/dev/null \
          || (echo "Error: JMX Exporter (standalone) failed to start." >&2; exit 1)

        # Check that /metrics is available and contains a known metric
        curl -s http://localhost:8888/metrics | grep -q "jvm_memory_pool_used_bytes" \
          || (echo "Error: Expected metric 'jvm_memory_pool_used_bytes' not found." >&2; exit 1)

        kill "$STANDALONE_PID"
    - name: Test JavaAgent with SSL and FIPS enabled
      runs: |
        set -ex
        keytool -genkeypair \
            -alias jmx-exporter \
            -keyalg RSA \
            -keysize 2048 \
            -storetype BCFKS \
            -keystore /tmp/jmx_exporter.bcfks \
            -storepass changeit \
            -keypass changeit \
            -dname "CN=localhost" \
            -validity 365

        # Create a minimal config for the JMX Exporter in standalone mode.
        mkdir -p /tmp/jmx-exporter-test
        cat <<EOF > /tmp/jmx-exporter-test/config.yaml
        ssl: true
        sslKeyStore: "/tmp/jmx_exporter.bcfks"
        sslKeyStorePassword: "changeit"
        sslTrustStore: "/tmp/jmx_exporter.bcfks"
        sslTrustStorePassword: "changeit"

        lowercaseOutputName: true
        rules:
          - pattern: ".*"

        httpServer:
          ssl:
            keyStore:
              filename: /tmp/jmx_exporter.bcfks
            certificate:
              alias: jmx-exporter
        EOF

        java -cp "/usr/share/java/bouncycastle-fips/*" \
        -Djavax.net.ssl.trustStoreType=BCFKS \
        -Djavax.net.ssl.keyStoreType=BCFKS \
        -Djavax.net.ssl.trustStore=/tmp/jmx_exporter.bcfks \
        -Djavax.net.ssl.trustStorePassword=changeit \
        -Djavax.net.ssl.keyStore=/tmp/jmx_exporter.bcfks \
        -Djavax.net.ssl.keyStorePassword=changeit \
        -javaagent:/opt/iamguarded/jmx-exporter/jmx_prometheus_javaagent.jar=8889:/tmp/jmx-exporter-test/config.yaml \
        -jar ./integration_test_suite/integration_tests/src/test/resources/common/jmx_example_application.jar > out.log 2>&1 &
        STANDALONE_PID=$!

        sleep 15

        # Verify the JMX Exporter is still running
        kill -0 "$STANDALONE_PID" 2>/dev/null \
          || (echo "Error: JMX Exporter (standalone) failed to start." >&2; exit 1)

        # Check that /metrics is available and contains a known metric
        curl -sk https://localhost:8889/metrics | grep -q "jvm_memory_pool_used_bytes" \
          || (echo "Error: Expected metric 'jvm_memory_pool_used_bytes' not found." >&2; exit 1)

        kill "$STANDALONE_PID"
    - name: Test Standalone with non-SSL
      runs: |
        set -ex

        # Create a minimal config for the JMX Exporter in standalone mode.
        mkdir -p /tmp/jmx-exporter-test
        cat <<EOF > /tmp/jmx-exporter-test/config.yaml
        hostPort: application:9999
        rules:
          - pattern: ".*"
        EOF

        java -jar /opt/iamguarded/jmx-exporter/jmx_prometheus_standalone.jar \
             8890 /tmp/jmx-exporter-test/config.yaml > out.log 2>&1 &
        STANDALONE_PID=$!

        # Allow the exporter time to start
        sleep 15

        # Verify the JMX Exporter is still running
        kill -0 "$STANDALONE_PID" 2>/dev/null \
          || (echo "Error: JMX Exporter (standalone) failed to start." >&2; exit 1)

        # Check that /metrics is available and contains a known metric
        curl -s http://localhost:8890/metrics | grep -q "jmx_exporter_build_info" \
          || (echo "Error: Expected metric 'jmx_exporter_build_info' not found." >&2; exit 1)

        kill "$STANDALONE_PID"
    - name: Test Standalone with SSL and FIPS enabled
      runs: |
        set -ex
        keytool -genkeypair \
            -alias jmx-exporter \
            -keyalg RSA \
            -keysize 2048 \
            -storetype BCFKS \
            -keystore /tmp/jmx_exporter.bcfks2 \
            -storepass changeit \
            -keypass changeit \
            -dname "CN=localhost" \
            -validity 365

        # Create a minimal config for the JMX Exporter in standalone mode.
        mkdir -p /tmp/jmx-exporter-test
        cat <<EOF > /tmp/jmx-exporter-test/config.yaml
        hostPort: "application:9999"
        ssl: true
        sslKeyStore: "/tmp/jmx_exporter.bcfks2"
        sslKeyStorePassword: "changeit"
        sslTrustStore: "/tmp/jmx_exporter.bcfks2"
        sslTrustStorePassword: "changeit"

        lowercaseOutputName: true
        rules:
          - pattern: ".*"

        httpServer:
          ssl:
            keyStore:
              filename: /tmp/jmx_exporter.bcfks2
            certificate:
              alias: jmx-exporter
        EOF

        java -cp "/usr/share/java/bouncycastle-fips/*" \
        -Djavax.net.ssl.trustStoreType=BCFKS \
        -Djavax.net.ssl.keyStoreType=BCFKS \
        -Djavax.net.ssl.trustStore=/tmp/jmx_exporter.bcfks2 \
        -Djavax.net.ssl.trustStorePassword=changeit \
        -Djavax.net.ssl.keyStore=/tmp/jmx_exporter.bcfks2 \
        -Djavax.net.ssl.keyStorePassword=changeit \
        -jar /opt/iamguarded/jmx-exporter/jmx_prometheus_standalone.jar 8891 /tmp/jmx-exporter-test/config.yaml > out.log 2>&1 &
        STANDALONE_PID=$!

        sleep 15

        # Verify the JMX Exporter is still running
        kill -0 "$STANDALONE_PID" 2>/dev/null \
          || (echo "Error: JMX Exporter (standalone) failed to start." >&2; exit 1)

        # Check that /metrics is available and contains a known metric
        curl -sk https://localhost:8891/metrics | grep -q "jmx_exporter_build_info" \
          || (echo "Error: Expected metric 'jmx_exporter_build_info' not found." >&2; exit 1)

        kill "$STANDALONE_PID"

update:
  enabled: true
  github:
    identifier: prometheus/jmx_exporter
    tag-filter: 1.
