package:
  name: psqlodbc
  version: "17.00.0007"
  epoch: 0
  description: A library to talk to the PostgreSQL DBMS using ODBC
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - unixodbc

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - libtool
      - make
      - postgresql-dev
      - unixodbc-dev

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+)\.(\d+)\.(\d+)$
    replace: "${1}_${2}_${3}"
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/postgresql-interfaces/psqlodbc
      expected-commit: 8038cee43d6dff468320008ea928f3eaa1186726
      tag: "REL-${{vars.mangled-package-version}}"

  - uses: autoconf/configure

  - uses: autoconf/make

  - runs: |
      make install DESTDIR="${{targets.destdir}}"

test:
  environment:
    contents:
      packages:
        - postgresql
        - postgresql-client
        - shadow
        - sudo-rs
        - glibc-locales
    environment:
      PGDATA: /tmp/test_db
      PGUSER: wolfi
  pipeline:
    - name: "Test database creation"
      runs: |
        useradd $PGUSER
        sudo -u $PGUSER initdb -D /tmp/test_db
        sudo -u $PGUSER pg_ctl -D /tmp/test_db -l /tmp/logfile start
        createdb testdb
    - name: "Create odbc configs"
      runs: |
        cat <<EOF > /etc/odbc.ini
        [PostgreSQL-TestDB-Unicode]
        Driver = PostgreSQL Unicode
        Servername = localhost
        Database = testdb
        Username = wolfi
        Trace = Yes
        Debug = 1
        [PostgreSQL-TestDB-ANSI]
        Driver = PostgreSQL ANSI
        Servername = localhost
        Database = testdb
        Username = wolfi
        Trace = Yes
        Debug = 1
        EOF
    - name: "another config"
      runs: |
        cat <<EOF > /etc/odbcinst.ini
        [PostgreSQL Unicode]
        Description=PostgreSQL ODBC Driver
        Driver=/usr/lib/psqlodbcw.so
        [PostgreSQL ANSI]
        Description=PostgreSQL ODBC Driver
        Driver=/usr/lib/psqlodbca.so
        EOF
    - name: "Test isql can connect using ansi and unicode adapters"
      runs: |
        printf 'SELECT usename FROM pg_user;'  | isql -v 'PostgreSQL-TestDB-ANSI' wolfi | grep wolfi
        printf 'SELECT usename FROM pg_user;'  | isql -v 'PostgreSQL-TestDB-Unicode' wolfi | grep wolfi
    - uses: test/tw/ldd-check

update:
  enabled: true
  version-transform:
    - match: ^(\d+)\_(\d+)\_(\d+)$
      replace: "${1}.${2}.${3}"
  ignore-regex-patterns:
    - "-mimalloc"
  github:
    identifier: postgresql-interfaces/psqlodbc
    strip-prefix: REL-
    tag-filter: REL-
    use-tag: true
