package:
  name: py3-torchprofile-cuda-13.0
  version: "0.0.4"
  epoch: 0
  description: A general and accurate MACs / FLOPs profiler for PyTorch models
  copyright:
    - license: MIT

vars:
  pypi-package: torchprofile
  import: torchprofile

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-build-base
      - py3-supported-torch-cuda-${{vars.cuda-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/zhijian-liu/torchprofile
      tag: v${{package.version}}
      expected-commit: f3b5a05d4d864236188cf4ac54ee4175e352ce2f

  - runs: |
      if [ "${{package.version}}" = "0.0.4" ]; then
        exit 0
      fi
      # https://github.com/zhijian-liu/torchprofile/issues/26
      echo "ERROR: *** Please remove hardcoded tag from git-checkout ***" 1>&2
      exit 1

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      runtime:
        - py${{range.key}}-numpy-2.2
        - py${{range.key}}-torch-cuda-${{vars.cuda-version}}
        - py${{range.key}}-torchvision-cuda-${{vars.cuda-version}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.11-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.12-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.13-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: zhijian-liu/torchprofile
    strip-prefix: v
