package:
  name: py3-pdm-backend
  version: 2.4.5
  epoch: 0
  description: The build backend used by PDM that supports latest packaging standards.
  copyright:
    - license: MIT

vars:
  pypi-package: pdm-backend
  import: "pdm.backend"

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pdm-project/pdm-backend.git
      tag: ${{package.version}}
      expected-commit: 713f6fa84fa0aaa9bddf61bc9e51fb7ab13eef21

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      environment:
        contents:
          packages:
            - py${{range.key}}-build-base
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}
        - runs: |
            tee pyproject.toml <<'EOF'
            [build-system]
            requires = ["pdm-backend"]
            build-backend = "pdm.backend"

            [project]
            name = "my-project"
            version = "0.1.0"
            description = "A project built with PDM-Backend"
            authors = [{name = "John Doe", email="me@johndoe.org"}]
            dependencies = ["requests"]
            requires-python = ">=3.9"
            license = "MIT"
            EOF
            python${{range.key}} -m build | tee out.log
            grep -F -e "Successfully built" out.log

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

update:
  enabled: true
  git: {}

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python3.13
        import: ${{vars.import}}
