package:
  name: py3-configparser
  version: 7.2.0
  epoch: 0
  description: Backport of configparser from Python's stdlib
  copyright:
    - license: MIT

vars:
  pypi-package: configparser

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jaraco/configparser.git
      tag: v${{package.version}}
      expected-commit: 196691a5900488f11cdf276af745e36776e2209a

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}
        - runs: |
            tee user.ini <<'EOF'
            [data]
            name = "Linky"
            EOF
            python${{range.key}} <<'EOF' | grep -F -e 'name: "Linky"'
            import configparser

            config = configparser.ConfigParser()

            config.read("user.ini")
            name = config["data"]["name"]
            print(f"name: {name}")
            EOF

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.pypi-package}}

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - uses: test/emptypackage
