package:
  name: py3-captum-cuda-12.9
  version: 0.8.0
  epoch: 0
  description: Model interpretability and understanding for PyTorch
  copyright:
    - license: BSD-3-Clause

vars:
  pypi-package: captum

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: "$1"
    to: cuda-version

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pytorch/captum.git
      tag: v${{package.version}}
      expected-commit: fc17d5070c5447593749ce28f9602c7ae58d54ac

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-matplotlib
        # - py${{range.key}}-numpy
        - py${{range.key}}-packaging
        - py${{range.key}}-torch-cuda-${{vars.cuda-version}}
        - py${{range.key}}-tqdm
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - uses: test/emptypackage
