package:
  name: py3-bidict
  version: 0.23.1
  epoch: 0
  description: The bidirectional mapping library for Python.
  copyright:
    - license: MPL-2.0

vars:
  pypi-package: bidict

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: fetch
    with:
      expected-sha512: fd0d1b72a19cfa7d3705c550005a346b14ba0c2196ef8f3e72377ff130e5d234009823d24d2613adf0cf75b5482810e6aa7a3b3d22021024ad274663a67d43ac
      uri: https://files.pythonhosted.org/packages/source/b/bidict/bidict-${{package.version}}.tar.gz

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      environment:
        contents:
          packages:
            - tw
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.pypi-package}}

update:
  enabled: true
  release-monitor:
    identifier: 114352

test:
  pipeline:
    - uses: test/emptypackage
