package:
  name: py3-nvidia-cudnn-frontend-12.9
  version: "1.14.0"
  epoch: 0
  description: The cuDNN FrontEnd(FE) API is a C++ header-only library and python frontend to the cuDNN C backend API.
  copyright:
    - license: Apache-2.0

vars:
  pypi-package: nvidia_cudnn_frontend
  import: nvidia_cudnn_frontend

var-transforms:
  - from: ${{package.name}}
    match: '.*frontend-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake-3
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - ninja
      - nvidia-cudnn-8-cuda-12-dev
      - py3-supported-build-base-dev
      - py3-supported-pybind11
      - py3-supported-setuptools
      - py3-supported-wheel
  environment:
    CUDAToolkit_ROOT: /usr/local/cuda-${{vars.cuda-version}}
    CUDNN_PATH: /usr/local/cudnn-8

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NVIDIA/cudnn-frontend
      tag: v${{package.version}}
      expected-commit: a7e19aea36d8cdd9d053acf73f90400af41866d7

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: NVIDIA/cudnn-frontend
    strip-prefix: v
