package:
  name: py3-augeas
  version: 1.2.0
  epoch: 0
  description: Python bindings for Augeas
  copyright:
    - license: LGPL-2.1-only

vars:
  pypi-package: python-augeas

environment:
  contents:
    packages:
      - augeas-dev
      - py3-supported-build-base-dev
      - py3-supported-cffi
      - py3-supported-pycparser

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hercules-team/python-augeas.git
      tag: v${{package.version}}
      expected-commit: a1e84a7e58e535658f681731b66eca7b71c095a2

subpackages:
  - range: py-versions
    name: py${{range.key}}-augeas
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-cffi
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: augeas

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - uses: test/emptypackage
