package:
  name: py3-ldap
  version: 3.4.4
  epoch: 0
  description: LDAP client API for Python
  copyright:
    - license: MIT
    - license: PSF-2.0

vars:
  pypi-package: ldap

environment:
  contents:
    packages:
      - openldap-dev
      - py3-supported-build-base-dev

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-ldap/python-ldap.git
      tag: python-ldap-${{package.version}}
      expected-commit: 73872c015f987281d18f17617bb49e2a7196548a

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-pyasn1
        - py${{range.key}}-pyasn1-modules
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      environment:
        contents:
          packages:
            - openldap
            - openldap-back-mdb
            - tw
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}
        - uses: test/daemon-check-output
          with:
            start: |
              slapd -d 1 -h 'ldap:/// ldapi:///'
            expected_output: |
              slapd starting
            post: |
              python${{range.key}} <<'EOF' | grep -F -e "ldap.ldapobject.SimpleLDAPObject object"
              import ldap
              l = ldap.initialize("ldap://127.0.0.1")
              l.simple_bind_s("","")
              print(l)
              EOF

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.pypi-package}}

update:
  enabled: true
  git:
    strip-prefix: python-ldap-

test:
  pipeline:
    - uses: test/emptypackage
