package:
  name: py3-identify
  version: "2.6.14"
  epoch: 0
  description: File identification library for Python.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - py3-supported-build-base

vars:
  pypi-package: identify
  import: identify

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "313"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pre-commit/identify
      tag: v${{package.version}}
      expected-commit: 6667ae3392c3e2178469779352012d4518c8cdc0

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-bin
    description: Commands for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}
    pipeline:
      - uses: split/bin
    test:
      pipeline:
        - runs: |
            identify-cli --help || {
              echo "FAIL: identify-cli --help exited non-zero [$?]"
            }

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: pre-commit/identify
    strip-prefix: v
    use-tag: true
