package:
  name: py3-multi-model-server
  version: 1.1.11
  epoch: 0
  description: Multi Model Server (MMS) is a flexible and easy to use tool for serving deep learning models trained using any ML/DL framework.
  copyright:
    - license: Apache-2.0

vars:
  pypi-package: multi-model-server
  java-version: 8

environment:
  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.${{vars.java-version}}-openjdk
  contents:
    packages:
      - bash
      - openjdk-${{vars.java-version}}-default-jdk
      - py3-supported-build-base-dev
      - py3-supported-mxnet
      - py3-supported-psutil
      - py3-supported-python-dev
      - python3

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/awslabs/multi-model-server.git
      tag: v${{package.version}}
      expected-commit: 440759888ac63b97274ac21b72371187950970fe

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - uses: test/emptypackage
