package:
  name: py3-triton-cuda-12.9
  version: "3.3.1"
  epoch: 0
  description: A language and compiler for writing highly efficient custom Deep-Learning primitives
  copyright:
    - license: MIT
  resources:
    cpu: 64
    memory: 128Gi

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

vars:
  pypi-package: triton
  import: triton

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake-3
      - libxml2-dev
      - py3-supported-build-base-dev
      - py3-supported-pybind11
      - py3-supported-torch-cuda-${{vars.cuda-version}}
      - samurai
      - zlib-dev
  environment:
    MAX_JOBS: 32

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/triton-lang/triton
      tag: v${{package.version}}
      expected-commit: d654e0f2d91f07496454e0fcbec2a9b97df37d47

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      runtime:
        - py${{range.key}}-setuptools
    pipeline:
      - working-directory: python
        uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: test/tw/ldd-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}-bin
    description: Commands for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py${{range.key}}-pandas
    pipeline:
      - uses: split/bin
    test:
      pipeline:
        - runs: |
            proton --help
            # We currently don't have all of proton-viewer's runtime deps
            # proton-viewer --help

  - name: py3-supported-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.11-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.12-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.13-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: triton-lang/triton
    strip-prefix: v
    use-tag: true
