package:
  name: py3-audioop-lts
  version: 0.2.2
  epoch: 0
  description: An LTS port of the Python builtin module audioop which was deprecated since version 3.11 and removed in 3.13.
  copyright:
    - license: PSF-2.0

vars:
  pypi-package: audioop-lts
  import: audioop

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

data:
  - name: py-versions
    items:
      # Support starts with python 3.13 as this library got removed from the python3 stdlib on 3.13
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/AbstractUmbra/audioop.git
      tag: ${{package.version}}
      expected-commit: 14791a05b7f01bbc6e161ab47aa213a0583f8b3b

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}
        - runs: |
            python${{range.key}} <<'EOF' | grep -F -e "[-1000, -500, 2000, 1000]"
            import audioop
            import struct

            samples = [1000, 2000, -500, -1000]
            raw_fragment = struct.pack('<4h', *samples)

            SAMPLE_WIDTH = 2 # 2 bytes per sample
            reversed_fragment = audioop.reverse(raw_fragment, SAMPLE_WIDTH)
            print("Reversed Raw Data (Bytes):", reversed_fragment)
            reversed_samples = struct.unpack('<4h', reversed_fragment)
            print("Reversed Sample Values:", list(reversed_samples))
            EOF

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

update:
  enabled: true
  git: {}

test:
  pipeline:
    - uses: test/emptypackage
