package:
  name: py3-numba
  version: 0.62.1
  epoch: 0
  description: Just-In-Time Compiler for Numerical Functions in Python
  copyright:
    - license: BSD-2-Clause

vars:
  pypi-package: numba

environment:
  contents:
    packages:
      - py3-supported-build-base-dev
      - py3-supported-numpy

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/numba/numba.git
      tag: ${{package.version}}
      expected-commit: e6a4027937dea8337b669b00e85ee703fbe496ac

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-llvmlite
        - py${{range.key}}-numpy-2.2
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}
        - runs: |
            python${{range.key}} <<'EOF' | sha256sum | grep -F -e "56a38e2b5939a6879778077f024ec14d4b65120a6e0937174dc892d9fb8da2b9"
            from numba import jit
            import numpy as np

            # Create a sample NumPy array
            x = np.arange(100).reshape(10, 10)

            @jit(nopython=True) # Use nopython=True for best performance
            def go_fast(a):
                """
                This function calculates the trace of a matrix after applying
                the hyperbolic tangent function to its diagonal elements,
                and then adds this trace to the original matrix.
                """
                trace = 0.0
                for i in range(a.shape[0]):
                    trace += np.tanh(a[i, i])
                return a + trace

            # Call the Numba-decorated function
            result = go_fast(x)
            print(result)
            EOF

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
        - py3-${{vars.pypi-package}}-bin
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}
        # diagnostic tool on `numba -s`
        - py${{range.key}}-pip
        - py${{range.key}}-psutil
        # GDB info tool on `numba -g`
        - py${{range.key}}-numpy-2.2
        - gdb
    pipeline:
      - uses: split/bin
    test:
      pipeline:
        - runs: |
            numba --help | grep -F -e "usage: numba [-h]"
            numba -s | tee stats.txt
            grep -E -e "numpy" ./stats.txt | grep -E -e "[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*"
            grep -E -e "numba" ./stats.txt | grep -E -e "[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*"
            tee example.py <<'EOF'
            import numpy as np

            # Create a sample NumPy array
            x = np.arange(100).reshape(10, 10)

            def go_fast(a):
                """
                This function calculates the trace of a matrix after applying
                the hyperbolic tangent function to its diagonal elements,
                and then adds this trace to the original matrix.
                """
                trace = 0.0
                for i in range(a.shape[0]):
                    trace += np.tanh(a[i, i])
                return a + trace

            # Call the Numba-decorated function
            result = go_fast(x)
            print(result)
            EOF
            numba example.py | sha256sum | grep -F -e "56a38e2b5939a6879778077f024ec14d4b65120a6e0937174dc892d9fb8da2b9"

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.pypi-package}}

update:
  enabled: true
  ignore-regex-patterns:
    - .*b\d*
    - .*rc\d*
    - .*dev\d*
  git: {}

test:
  pipeline:
    - uses: test/emptypackage
