package:
  name: py3-cuda-core-cuda-12.9
  version: "0.4.0"
  epoch: 0
  description: offers idiomatic, pythonic access to CUDA runtime and other functionalities
  copyright:
    - license: Apache-2.0

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

vars:
  import: cuda.core
  pypi-package: cuda-core

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - nvidia-cuda-profiler-api-${{vars.cuda-version}}
      - py3-supported-build-base-dev
      - py3-supported-cuda-python-cuda-${{vars.cuda-version}}
      - py3-supported-cython
  environment:
    CUDA_HOME: /usr/local/cuda-${{vars.cuda-version}}
    LIBRARY_PATH: /usr/local/cuda-${{vars.cuda-version}}/lib64

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NVIDIA/cuda-python
      tag: cuda-core-v${{package.version}}
      expected-commit: 84f5aaeb3cfbab0a262b97689b94ba060e80b2f0

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: python${{range.key}} version of ${{vars.import}}
    dependencies:
      runtime:
        - py${{range.key}}-numpy-2.2
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
        working-directory: cuda_core
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}
        - uses: test/tw/ldd-check

  - name: py3-supported-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.11-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.12-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.13-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: NVIDIA/cuda-python
    tag-filter-prefix: cuda-core-v
    strip-prefix: cuda-core-v
