#nolint:valid-pipeline-git-checkout-commit,valid-pipeline-git-checkout-tag
package:
  name: py3-rancher-client-python
  version: "0.1.0.0_git20250320"
  epoch: 3
  description: A Python client for Rancher APIs
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

vars:
  pypi-package: client-python

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "313"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/client-python
      branch: master
      expected-commit: f617457722f95eded2a74b301ab08d79502a5c3f

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-requests
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: rancher

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage

update:
  enabled: false
  exclude-reason: No releases since 2018.

# Based on package contents inspection, it was found that this origin package is empty apart from its own SBOM and this test was added to confirm it is empty and will fail if the package is no longer empty (contains more than an SBOM)
test:
  pipeline:
    - uses: test/emptypackage
