package:
  name: py3-pooch
  version: 1.8.2
  epoch: 0
  description: Python library that can manage data by downloading files from a server
  copyright:
    - license: BSD-3-Clause

vars:
  pypi-package: pooch

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fatiando/pooch.git
      tag: v${{package.version}}
      expected-commit: dfc69386753e3793b6960301a00c90b71656bf6f

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-packaging
        - py${{range.key}}-platformdirs
        - py${{range.key}}-requests
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - uses: test/emptypackage
