package:
  name: py3.9-numpy
  version: 1.26.5
  epoch: 2
  description: "The fundamental package for scientific computing with Python."
  copyright:
    - license: BSD-3-Clause
  options:
    no-provides: true
  dependencies:
    runtime:
      - python-3.9

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - gfortran
      - git
      - openblas-dev
      - py3.9-build
      - py3.9-cython<3.1
      - py3.9-installer
      - py3.9-meson
      - py3.9-meson-python
      - py3.9-pip
      - py3.9-setuptools
      - py3.9-wheel
      - python-3.9
      - python-3.9-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/numpy/numpy
      tag: v${{package.version}}
      expected-commit: 93fdebfcb4bc4cd53c959ccd0117a612d5f13f1a
      recurse-submodules: true

  - uses: py/pip-build-install
    with:
      python: python3.9
      dest: ${{targets.contextdir}}

test:
  pipeline:
    - uses: python/import
      with:
        python: python3.9
        import: numpy
      runs: |
        f2py --version
        f2py --help
    - runs: |
        f2py -v

update:
  enabled: true
  git:
    # Some reverse dependencies don't work with v2
    tag-filter-prefix: v1
    strip-prefix: v
    strip-suffix: .dev0
  ignore-regex-patterns:
    - post2 # Bad tag
