package:
  name: py3.10-vllm-cuda-12.6
  version: "0.8.5"
  epoch: 0
  description: A high-throughput and memory-efficient inference and serving engine for LLMs
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 16
    memory: 16Gi
  target-architecture:
    - x86_64
  options:
    no-depends: true
  dependencies:
    runtime:
      - cuda-toolkit-${{vars.cuda-version}}
      - nvidia-libcuda-${{vars.cuda-version}}
      - py${{vars.py-version}}-setuptools
      - python-${{vars.py-version}}-base

vars:
  cudnn-major-version: 9
  gcc-major-version: 12
  import: vllm

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version
  - from: ${{package.name}}
    match: '.*cuda-(\d+)\.\d+$'
    replace: '$1'
    to: cuda-major-version
  - from: ${{package.name}}
    match: '^py(\d+\.\d+)-.*'
    replace: '$1'
    to: py-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils # part of workaround for 12.6's ptxas
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - gcc-${{vars.gcc-major-version}}
      - gperftools-dev
      - ninja-build
      - numactl-dev
      - nvidia-cuda-cccl-${{vars.cuda-version}}
      - nvidia-cuda-nvcc-12.8 # part of workaround for 12.6's ptxas
      - nvidia-cuda-profiler-api-${{vars.cuda-version}}
      - nvidia-cudnn-${{vars.cudnn-major-version}}-cuda-${{vars.cuda-major-version}}-dev
      - nvidia-driver
      - nvidia-libnvidia-ml-${{vars.cuda-version}}
      - nvidia-nccl-cuda-${{vars.cuda-version}}-dev
      - py${{vars.py-version}}-build-base-dev
      - samurai
      - tcmalloc-minimal
  environment:
    CUDA_HOME: /usr/local/cuda-${{vars.cuda-version}}
    LIBRARY_PATH: /usr/local/cuda-${{vars.cuda-version}}/lib64/stubs
    MAX_JOBS: 16
    NVCC_APPEND_FLAGS: -ccbin gcc-${{vars.gcc-major-version}}
    TORCH_CUDA_ARCH_LIST: 7.0 7.5 8.0 8.6 8.9 9.0+PTX

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vllm-project/vllm.git
      tag: v${{package.version}}
      expected-commit: dcbac4cb4bd565f964104911b5fac7a5cb837b3b

  - name: install workaround for https://github.com/chainguard-dev/internal-dev/issues/10782
    runs: |
      # this workaround comprises multiple changes in this file.
      # when it is time to remove it, please revert the entire
      # commit to make sure it is entirely cleaned up
      mkdir -p cuda-home
      for path in "$CUDA_HOME"/*; do
        base="$(basename $path)"
        [ "$base" != "bin" ] || continue
        ln -r -f -s $path cuda-home
      done
      mkdir -p cuda-home/bin
      for path in "$CUDA_HOME"/bin/*; do
        base="$(basename $path)"
        [ "$base" != "ptxas" ] || continue
        ln -r -f -s $path cuda-home/bin
      done
      ln -r -f -s /usr/local/cuda-12.8/bin/ptxas cuda-home/bin

  - runs: |
      export CUDA_HOME=$(pwd)/cuda-home # part of workaround for 12.6's ptxas
      export PATH="$CUDA_HOME/bin:$PATH"

      pip${{vars.py-version}} install -r requirements/cuda.txt
      pip${{vars.py-version}} install build wheel packaging aiohttp>=3.10.2
      pip${{vars.py-version}} install -r requirements/build.txt

      python${{vars.py-version}} setup.py bdist_wheel
      python${{vars.py-version}} setup.py build_ext --inplace
      pip${{vars.py-version}} install --verbose \
        --no-index --no-build-isolation --no-deps \
        --force-reinstall --no-compile --prefix=/usr "--root=${{targets.contextdir}}" dist/vllm-*.whl
      sitepkgd=$(python${{vars.py-version}} -c 'import site; print(site.getsitepackages()[0])')
      pip${{vars.py-version}} install --verbose \
        --requirement=requirements/cuda.txt --force-reinstall\
        --prefix=/usr --root="${{targets.contextdir}}"
      python${{vars.py-version}} -m compileall --invalidation-mode=unchecked-hash -r100 ${{targets.contextdir}}/$sitepkgd

      # The psutil tests trigger mal failures
      rm -rf ${{targets.contextdir}}/usr/lib/python${{vars.py-version}}/site-packages/psutil/tests

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - post
    - test
    - submission
  github:
    identifier: vllm-project/vllm
    strip-prefix: v
    use-tag: true

test:
  environment:
    environment:
  pipeline:
    - name: Verify vllm installation
      uses: python/import
      with:
        python: python${{vars.py-version}}
        import: ${{vars.import}}
