package:
  name: py3.10-vllm-cuda-12.6
  version: "0.7.2"
  epoch: 0
  description: A high-throughput and memory-efficient inference and serving engine for LLMs
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 16
    memory: 16Gi
  target-architecture:
    - x86_64
  options:
    no-depends: true
  dependencies:
    runtime:
      - python-${{vars.py-version}}-base
      - py${{vars.py-version}}-setuptools
      - cuda-toolkit-${{vars.cuda-version}}
      - nvidia-libcuda-${{vars.cuda-version}}

vars:
  cudnn-major-version: 9
  gcc-major-version: 12

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version
  - from: ${{package.name}}
    match: '.*cuda-(\d+)\.\d+$'
    replace: '$1'
    to: cuda-major-version
  - from: ${{package.name}}
    match: '^py(\d+\.\d+)-.*'
    replace: '$1'
    to: py-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gcc-${{vars.gcc-major-version}}
      - samurai
      - ninja-build
      - numactl-dev
      - tcmalloc-minimal
      - gperftools-dev
      - py${{vars.py-version}}-build-base-dev
      - nvidia-driver
      - nvidia-cuda-cccl-${{vars.cuda-version}}
      - nvidia-cuda-profiler-api-${{vars.cuda-version}}
      - nvidia-cudnn-${{vars.cudnn-major-version}}-cuda-${{vars.cuda-major-version}}-dev
      - nvidia-nccl-cuda-${{vars.cuda-version}}-dev
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - nvidia-libnvidia-ml-${{vars.cuda-version}}
  environment:
    CUDA_HOME: /usr/local/cuda
    NVCC_APPEND_FLAGS: -ccbin gcc-${{vars.gcc-major-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vllm-project/vllm.git
      tag: v${{package.version}}
      expected-commit: 0408efc6d0c17fba17b2be38d0d0f02e96d2bf9d

  - runs: |
      ln -sf /usr/local/cuda-${{vars.cuda-version}} $CUDA_HOME
      export PATH=$CUDA_HOME/bin:$PATH
      export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
      export TORCH_CUDA_ARCH_LIST='7.0 7.5 8.0 8.6 8.9 9.0+PTX'
      export MAX_JOBS=16

      pip${{vars.py-version}} install -r requirements-cuda.txt
      pip${{vars.py-version}} install build wheel packaging aiohttp>=3.10.2
      pip${{vars.py-version}} install -r requirements-build.txt

      python${{vars.py-version}} setup.py bdist_wheel
      python${{vars.py-version}} setup.py build_ext --inplace
      pip${{vars.py-version}} install --verbose \
        --no-index --no-build-isolation --no-deps \
        --force-reinstall --no-compile --prefix=/usr "--root=${{targets.contextdir}}" dist/vllm-*.whl
      sitepkgd=$(python${{vars.py-version}} -c 'import site; print(site.getsitepackages()[0])')
      pip${{vars.py-version}} install --verbose \
        --requirement=requirements-cuda.txt --force-reinstall\
        --prefix=/usr --root="${{targets.contextdir}}"
      python${{vars.py-version}} -m compileall --invalidation-mode=unchecked-hash -r100 ${{targets.contextdir}}/$sitepkgd

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - post
    - test
    - submission
  github:
    identifier: vllm-project/vllm
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - name: Verify vllm installation
      runs: |
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-${{vars.cuda-version}}/lib:/usr/local/cuda-${{vars.cuda-version}}/lib64:/usr/local/cudnn-${{vars.cudnn-major-version}}/lib64"
        python${{vars.py-version}} -c "import vllm"
