package:
  name: py3.9-meson
  version: "1.9.2"
  epoch: 0
  description: Fast and user friendly build system
  copyright:
    - license: Apache-2.0
  options:
    no-provides: true
  dependencies:
    runtime:
      - python-3.9
      - samurai

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3.9-setuptools
      - python-3.9
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: 3499b59bb23982496e01e57b4103ac2f826f9c3a3f59e507a0a832487fe55e3d
      uri: https://github.com/mesonbuild/meson/releases/download/${{package.version}}/meson-${{package.version}}.tar.gz

  - runs: python3.9 setup.py build

  - runs: python3.9 setup.py install --prefix=/usr --root=${{targets.destdir}} --skip-build

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
    description: meson manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  release-monitor:
    identifier: 6472

test:
  environment:
    contents:
      packages:
        - build-base
  pipeline:
    - runs: |
        meson --version | grep ${{package.version}}
        meson --help
    - runs: |
        mkdir -p /tmp
        cd /tmp
        cat <<'EOF' >> /tmp/main.c
        #include <stdio.h>

        //
        // main is where all program execution starts
        //
        int main(int argc, char **argv) {
        printf("Hello Wolfi.\n");
        return 0;
        }

        EOF
        cat <<'EOF'>> /tmp/meson.build
        project('tutorial', 'c')
        executable('demo', 'main.c')
        EOF

        CC=gcc meson setup builddir
        cd builddir
        meson compile
        ./demo
