package:
  name: py3.9-gpep517
  version: "19"
  epoch: 0
  description: "PEP517 build system support for distros"
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - py3.9-installer
      - py3.9-tomli
      - python-3.9

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python-3.9
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/mgorny/gpep517/archive/v${{package.version}}/gpep517-v${{package.version}}.tar.gz
      expected-sha256: 17879b79edbb5a21d3dca6cfae997bda8e4c99254caf16616a6ae70d15a43c09

  - runs: |
      _site_pkgs="$(python3.9 -c 'import site; print(site.getsitepackages()[0])')"
      _py3ver=$(python3.9 -c 'import sys; print("{}.{}".format(sys.version_info.major, sys.version_info.minor))')

      mkdir -p "${{targets.destdir}}"/"$_site_pkgs"
      cp -a gpep517 "${{targets.destdir}}"/$_site_pkgs/

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 255912

test:
  pipeline:
    - uses: python/import
      with:
        import: gpep517
