package:
  name: py3.12-torchaudio-cuda-12.4
  version: 2.3.1
  epoch: 0
  description: Data manipulation and transformation for audio signal processing, powered by PyTorch
  copyright:
    - license: BSD-2-Clause
  target-architecture:
    - x86_64
  resources:
    cpu: 16
    memory: 16Gi
  options:
    no-depends: true
  dependencies:
    runtime:
      - cuda-toolkit-${{vars.cuda-version}}
      - libgomp
      - nvidia-nccl-cuda-${{vars.cuda-version}}
      - openmp-17-dev
      - py${{vars.py-version}}-numpy
      - py${{vars.py-version}}-pyyaml
      - py${{vars.py-version}}-typing-extensions
      - python-${{vars.py-version}}

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version
  - from: ${{package.name}}
    match: '.*cuda-(\d+)\.\d+$'
    replace: '$1'
    to: cuda-major-version
  - from: ${{package.name}}
    match: '^py(\d+\.\d+)-.*'
    replace: '$1'
    to: py-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - gcc-12-default
      - ninja
      - nvidia-cuda-cccl-${{vars.cuda-version}}
      - nvidia-cuda-profiler-api-${{vars.cuda-version}}
      - nvidia-cudnn-8-cuda-12-dev
      # cuda
      - nvidia-driver
      - py${{vars.py-version}}-installer
      - py${{vars.py-version}}-numpy
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-pytorch-cuda-12.3
      - py${{vars.py-version}}-setuptools
      - py${{vars.py-version}}-wheel
      - python-${{vars.py-version}}
      - python-${{vars.py-version}}-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pytorch/audio
      tag: v${{package.version}}
      expected-commit: 3edcf69e78a3c9a3077a11159861422440ec7d4a

  - runs: |
      export PATH="$PATH:/usr/local/cuda-12.4/bin"

      export USE_CUDA=1
      export FORCE_CUDA=1
      export USE_CUDNN=1
      export TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0+PTX 8.0 8.6 8.7 8.9 9.0"
      export TORCH_NVCC_FLAGS="-Xfatbin -compress-all"

      export CFLAGS="$CFLAGS -Wno-error=nonnull -Wno-nonnull"
      export CXXFLAGS="$CXXFLAGS -Wno-error=nonnull -Wno-nonnull"

      export CUDA_VERSION="12.4"
      export CUDAToolkit_ROOT="/usr/local/cuda-12.4"

      export BUILD_VERSION="${{package.version}}+cu124"

      /usr/share/pytorch/.venv/bin/pip install -r requirements.txt

      /usr/share/pytorch/.venv/bin/python setup.py bdist_wheel
      /usr/share/pytorch/.venv/bin/pip install dist/*.whl

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/torchaudio
      mv /usr/share/pytorch/.venv ${{targets.destdir}}/usr/share/torchaudio/

      # edit the venv paths
      sed -i "s|/usr/share/pytorch|/usr/share/torchaudio|g" ${{targets.destdir}}/usr/share/torchaudio/.venv/bin/*

      # allow site-packages
      sed -i "s|include-system-site-packages = false|include-system-site-packages = true|g" ${{targets.destdir}}/usr/share/torchaudio/.venv/pyvenv.cfg

  - uses: strip

subpackages:
  - name: py3.12-wheels-torchaudio-cuda-12.4
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/share/wheels
          cp dist/*.whl ${{targets.contextdir}}/usr/share/wheels

update:
  enabled: true
  github:
    identifier: pytorch/audio
    strip-prefix: v
    tag-filter: v2.3.

test:
  environment:
    contents:
      packages:
        - build-base
        - bash
        - libgomp
        - openmp-17-dev
        - py3.12-pytorch-cuda-12.4
  pipeline:
    - runs: |
        export PATH=/usr/share/torchaudio/.venv/bin:$PATH
        if ! python -c "import torchaudio" > output.out 2>&1; then
            echo "Failed to import torchaudio"
            cat output.out
            exit 1
        else
            echo "torchaudio imported successfully"
            exit 0
        fi
