package:
  name: python-3.8
  version: 3.8.18
  epoch: 3
  description: "the Python programming language"
  copyright:
    - license: PSF-2.0
  dependencies:
    runtime:
    provides:
      - python3=${{package.full-version}}
      - python-3=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.python.org/ftp/python/${{package.version}}/Python-${{package.version}}.tar.xz
      expected-sha256: 3ffb71cd349a326ba7b2fadc7e7df86ba577dd9c4917e52a8401adbda7405e3f

  - name: Force use of system libraries
    runs: |
      rm -rf Modules/expat \
        Modules/_ctypes/darwin* \
        Modules/_ctypes/libffi*

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip \
         --with-lto

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: altinstall DESTDIR="${{targets.destdir}}"

  - runs: |
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyc' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyo' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name 'libpython*.a' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'test' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'tests' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'idle_test' -exec rm -rf '{}' +

  - name: Install python symlink
    runs: |
      ln -s python3.8 "${{targets.destdir}}"/usr/bin/python

  - uses: strip

subpackages:
  - name: "python-3.8-doc"
    description: "python3.8 documentation"
    pipeline:
      - uses: split/manpages

  - name: "python-3.8-dev"
    description: "python3.8 development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/include/python3.8
          mv "${{targets.subpkgdir}}"/usr/include/python3.8/pyconfig.h "${{targets.destdir}}"/usr/include/python3.8/
    dependencies:
      runtime:
        - python-3.8

update:
  enabled: true
  github:
    identifier: python/cpython
    strip-prefix: v
    tag-filter: v3.8
    use-tag: true

test:
  environment:
    contents:
      packages:
        - busybox
        - wolfi-base
  pipeline:
    - runs: |
        python --version
