#nolint:valid-pipeline-git-checkout-tag
package:
  name: pythoncapi-compat
  version: "0_git20250915"
  epoch: 0
  description: "The pythoncapi-compat project can be used to write a C extension supporting a wide range of Python versions with a single code base."
  copyright:
    - license: 0BSD

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-sphinx-bin

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python/pythoncapi-compat.git
      expected-commit: 90c06a4cae557bdbfa4f231a781d2b5c1a8f6d1c
      branch: main

  - runs: |
      install -Dm 0644 pythoncapi_compat.h ${{targets.destdir}}/usr/include/pythoncapi-compat/pythoncapi_compat.h
      cd docs
      make man
      install -Dm0644 build/man/pythoncapi_compat.1 ${{targets.destdir}}/usr/share/man/man1/pythoncapi_compat.1

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    description: "${{package.name}} manpages"
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  git: {}
  schedule:
    period: weekly
    reason: No releases, everything is commit based.
