package:
  name: qemu
  version: "8.2.2"
  epoch: 0
  description: "fast processor emulator"
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bison
      - build-base
      - busybox
      - flex
      - git
      - glib-dev
      - glib-static
      - ncurses-dev
      - ncurses-static
      - ninja-build
      - perl
      - py3-packaging
      - py3-pip
      - py3-sphinx
      - python3
      - samurai
      - zlib-dev
      - zlib-static

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/qemu/qemu
      expected-commit: 11aa0b1ff115b86160c4d37e7c37e6a6b13b77ea
      tag: v${{package.version}}

  - uses: autoconf/configure
    with:
      opts: |
        --enable-linux-user \
        --disable-system \
        --static \
        --disable-glusterfs \
        --disable-debug-info \
        --disable-bsd-user \
        --disable-werror \
        --disable-xen \
        --disable-brlapi \
        --disable-bpf \
        --disable-cap-ng \
        --disable-capstone \
        --disable-curl \
        --disable-curses \
        --disable-docs \
        --disable-gcrypt \
        --disable-gnutls \
        --disable-gtk \
        --disable-guest-agent \
        --disable-guest-agent-msi \
        --disable-libnfs \
        --disable-mpath \
        --disable-nettle \
        --disable-numa \
        --disable-sdl \
        --disable-spice \
        --disable-tools

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: true
  github:
    identifier: qemu/qemu
    use-tag: true
