package:
  name: quic-go-fips
  version: 0.55.0
  epoch: 0
  description: A production-ready QUIC implementation in pure Go
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/quic-go/quic-go.git
      expected-commit: 7c1ce0efe280e4d82acad43b8cd8284596361103
      tag: v${{package.version}}

  - runs: |
      install -dm0755 "${{targets.destdir}}/usr/share/quic-go"
      git rev-parse HEAD | tee "${{targets.destdir}}/usr/share/quic-go/commit.txt"

subpackages:
  - name: quic-go-server-fips
    description: Server binary for quic-go
    pipeline:
      - uses: go/build
        with:
          packages: ./interop/server/main.go
          output: server
          ldflags: -X github.com/quic-go/quic-go/qlog.quicGoVersion=$(git describe --always --long --dirty)
          go-package: go-fips
    test:
      pipeline:
        - uses: test/go-fips-check
        - runs: |
            mkdir -p /logs

  - name: quic-go-client-fips
    description: Client binary for quic-go
    pipeline:
      - uses: go/build
        with:
          packages: ./interop/client/main.go
          output: client
          ldflags: -X github.com/quic-go/quic-go/qlog.quicGoVersion=$(git describe --always --long --dirty)
          go-package: go-fips
    test:
      pipeline:
        - uses: test/go-fips-check
        - runs: mkdir -p /logs

  - name: quic-go-compat-fips
    description: Compatibility subpackage for upstream image
    pipeline:
      - runs: |
          mkdir -p /quic-go
          ln -s /usr/bin/server /quic-go/server
          ln -s /usr/share/quic-go/commit.txt /quic-go/commit.txt
          ln -s /usr/bin/client /quic-go/client
    test:
      pipeline:
        - uses: test/tw/symlink-check

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - runs: |
        stat /usr/share/quic-go/commit.txt | grep 0644
