package:
  name: quic-network-simulator
  version: 0_git20251021
  epoch: 0
  description: ns3-based network simulator for QUIC testing
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - coreutils
      - ethtool
      - hostname
      - hostname
      - iperf
      - iproute2
      - iputils
      - net-tools
      - quic-go
      - quic-go-client
      - quic-go-server
      - tcpdump
      - wget

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/quic-interop/quic-network-simulator.git
      branch: master
      expected-commit: 777f2518f0a5e606e910db46d84eb222a194df73

  - runs: |
      install -Dpm0755 -t ${{targets.destdir}}/usr/bin ./endpoint/run_endpoint.sh
      install -Dpm0755 -t ${{targets.destdir}}/usr/bin ./endpoint/setup.sh

subpackages:
  - name: quic-network-simulator-compat
    description: Compatibility subpackage for wait-for-it
    dependencies:
      runtime:
        - quic-network-simulator
    pipeline:
      - runs: |
          install -dpm0755 ${{targets.subpkgdir}}
          ln -s ./usr/bin/setup.sh ${{targets.subpkgdir}}/setup.sh
          ln -s ./usr/bin/setup.sh ${{targets.subpkgdir}}/run_endpoint.sh
    test:
      pipeline:
        - uses: test/tw/symlink-check

update:
  enabled: true
  git:
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - quic-network-simulator-compat
  pipeline:
    - runs: |
        run_endpoint.sh
        exit 1
