package:
  name: rabbitmq-default-user-credential-updater-fips
  version: "1.0.9"
  epoch: 2 # CVE-2025-61729
  description: Updates RabbitMQ default user password
  copyright:
    - license: MPL-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rabbitmq/default-user-credential-updater
      tag: v${{package.version}}
      expected-commit: d44e1e04d9d5d09b190719475487947405729600

  - uses: go/build
    with:
      go-package: go-fips
      packages: .
      output: default-user-credential-updater

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        default-user-credential-updater -h  2>&1 | grep "Usage of default-user-credential-updater:"
        default-user-credential-updater version
        default-user-credential-updater --help

update:
  enabled: true
  github:
    identifier: rabbitmq/default-user-credential-updater
    strip-prefix: v
