package:
  name: rancher-agent-2.9
  version: 2.9.1
  epoch: 0
  description: Complete container management platform - agent
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher-agent=${{package.full-version}}
    runtime:
      - kubectl
      - tini
      - rancher-kontainer-driver-metadata-${{vars.major-minor-version}}
      - rancher-system-charts-${{vars.major-minor-version}}
      - rancher-partner-charts
      - rancher-charts-${{vars.major-minor-version}}
      - rancher-loglevel
      - rancher-rke2-charts
      - rancher-helm3-charts
      - util-linux-misc # unshare
      - mount
      - umount
      - busybox # nsenter
      - util-linux-dev
      - jq
      - gzip
      - gawk
      - bash
      - sysstat
      - acl-dev
      - vim
      - iproute2
      - net-tools
      - openssh-client
      - busybox
      - posix-libc-utils
      - curl
      - openssl

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/rancher
      tag: v${{package.version}}
      expected-commit: b9ce27a38a459f8d35d483867d3caf968a7eb998

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 k8s.io/kubernetes@v1.30.3 k8s.io/apiserver@v0.30.3 github.com/opencontainers/runc@v1.1.14

  - uses: go/build
    with:
      packages: ./cmd/agent
      output: agent
      ldflags: |
        -X main.VERSION=${{package.version}}
      tags: k8s

  - runs: |
      mkdir -p ${{targets.contextdir}}/usr/bin
      install -Dm755 package/run.sh ${{targets.contextdir}}/usr/bin/
      install -Dm755 package/kubectl-shell.sh ${{targets.contextdir}}/usr/bin/
      install -Dm755 package/shell-setup.sh ${{targets.contextdir}}/usr/bin/

test:
  pipeline:
    - runs: |
        agent | grep "Rancher agent version ${{package.version}}"

update:
  enabled: true
  github:
    identifier: rancher/rancher
    strip-prefix: v
    use-tag: true
    tag-filter: v2.9.
