package:
  name: rancher-charts-2.9
  version: 0_git_git20240913
  epoch: 0
  description: Complete container management platform - charts
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher-charts=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - perl-utils

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/charts
      branch: release-v2.9
      expected-commit: 4a19238a0920463b9582c8593526d322ac78dc13
      depth: -1

  - runs: |
      shasum256=$(echo -n "https://git.rancher.io/charts" |shasum -a 256 | awk '{ print $1 }')
      mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256
      cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256

  - runs: |
      git checkout master
      mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/library
      cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/library

test:
  environment:
    contents:
      packages:
        - perl-utils
  pipeline:
    - runs: |
        shasum256=$(echo -n "https://git.rancher.io/charts" |shasum -a 256 | awk '{ print $1 }')
        # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256/`
        test -f /var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256/README.md
        # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/library/`
        test -f /var/lib/rancher-data/local-catalogs/library/README.md

update:
  enabled: true
  git: {}
  schedule:
    period: hourly
    reason: Commit at head of branch moves frequently
