#nolint:valid-pipeline-git-checkout-tag
package:
  name: raspberry-pi-utils
  version: "0.0.0_git20250421"
  epoch: 0
  description: A collection of scripts and simple applications for Raspberry Pi.
  copyright:
    - license: BSD-3-Clause
  target-architecture:
    - aarch64

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/raspberrypi/utils
      branch: master
      expected-commit: f92b9735ba3141103c73cd0bf9781644caa91e42

subpackages:
  # https://www.raspberrypi.com/documentation/computers/os.html#vcgencmd
  - name: vcgencmd
    pipeline:
      - working-directory: vcgencmd
        pipeline:
          - uses: cmake/configure
          - uses: cmake/build
          - uses: cmake/install
    test:
      pipeline:
        - runs: |
            # Fake a vcio device because vcgencmd opens it before doing anything else, including printing the help
            touch /dev/vcio
            vcgencmd | grep "Usage:"

update:
  enabled: true
  git: {}
  schedule:
    period: weekly
    reason: This project doesn't do releases and everything is commit based
