package:
  name: redis-7.4
  version: "7.4.7"
  epoch: 2
  description: Advanced key-value store
  copyright:
    # IMPORTANT: redis v7.4+ introduced a licensing change, which provides two
    # choices. We are selecting SSPL instead of RSAL, as that restricts our use-case.
    - license: SSPL-1.0
  dependencies:
    provides:
      - redis=${{package.full-version}}
    runtime:
      - merged-usrsbin
      - posix-libc-utils-bin # `getent` is required on startup in ha mode for ip introspection cluster formation
      - wolfi-baselayout

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - jemalloc
      - linux-headers
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4d1a341aaf0b96f9d2c43418efac732e31dc28ad
      repository: https://github.com/redis/redis.git
      tag: ${{package.version}}

  - uses: patch
    with:
      patches: 0000-Disable-protected-mode.patch CVE-2025-27151.patch

  - runs: |
      export CFLAGS="$CFLAGS -DUSE_MALLOC_USABLE_SIZE"
        make \
        BUILD_TLS=yes \
        all -j$(nproc)
      make install PREFIX=/usr INSTALL_BIN="${{targets.destdir}}/usr/bin"

  - uses: strip

subpackages:
  - name: redis-cli-${{vars.major-minor-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/redis-cli "${{targets.subpkgdir}}"/usr/bin/redis-cli
    description: redis-cli is the command line interface utility to talk with Redis.
    dependencies:
      provides:
        - redis-cli=${{package.full-version}}
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
    test:
      pipeline:
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: redis-cli
            real-pkg-name: ${{subpkg.name}}

  - name: redis-benchmark-${{vars.major-minor-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/redis-benchmark "${{targets.subpkgdir}}"/usr/bin/redis-benchmark
    description: redis-benchmark utility that simulates running commands done by N clients while at the same time sending M total queries.
    dependencies:
      provides:
        - redis-benchmark=${{package.full-version}}
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
    test:
      pipeline:
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: redis-benchmark
            real-pkg-name: ${{subpkg.name}}

  - name: redis-${{vars.major-minor-version}}-iamguarded-compat
    dependencies:
      provides:
        - redis-iamguarded-compat=${{package.full-version}}
      runtime:
        - bash
        - busybox # Required by startup scripts
        - coreutils
        - libxcrypt
        - merged-usrsbin
        - openssl
        - redis
        - redis-cli
        - wait-for-port
        - wolfi-baselayout
    pipeline:
      - uses: iamguarded/build-compat
        with:
          package: redis
          version: ${{vars.major-minor-version}}
      - runs: |
          # The startup scripts expect these directories to be in place.
          # If not, redis will fail to launch.
          mkdir -p /iamguarded/redis/data
          mkdir -p /opt/iamguarded/redis/etc.default
          mkdir -p /opt/iamguarded/redis/etc

          # Moves in the default redis configuration. Note the iamguarded scripts
          # create a copy of this later and make some modifications.
          cp redis.conf /opt/iamguarded/redis/etc/redis-default.conf

          ln -s /opt/iamguarded/scripts/redis/entrypoint.sh ${{targets.contextdir}}/entrypoint.sh
          ln -s /opt/iamguarded/scripts/redis/run.sh ${{targets.contextdir}}/run.sh
      - uses: iamguarded/finalize-compat
        with:
          package: redis
          version: ${{vars.major-minor-version}}
    test:
      pipeline:
        - uses: iamguarded/test-compat
          with:
            package: redis
            version: ${{vars.major-minor-version}}
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: redis-iamguarded-compat
            real-pkg-name: ${{subpkg.name}}

  - name: redis-sentinel-${{vars.major-minor-version}}-iamguarded-compat
    dependencies:
      provides:
        - redis-sentinel-iamguarded-compat=${{package.full-version}}
      runtime:
        - bash
        - busybox # Required by startup scripts
        - coreutils
        - libxcrypt
        - merged-usrsbin
        - openssl
        - redis
        - redis-cli
        - wait-for-port
        - wolfi-baselayout
    pipeline:
      - uses: iamguarded/build-compat
        with:
          package: redis-sentinel
          version: ${{vars.major-minor-version}}
      - runs: |
          mkdir -p /opt/iamguarded/redis-sentinel/etc
          cp redis.conf /opt/iamguarded/redis-sentinel/etc/redis-default.conf
      - uses: iamguarded/finalize-compat
        with:
          package: redis-sentinel
          version: ${{vars.major-minor-version}}
    test:
      pipeline:
        - uses: iamguarded/test-compat
          with:
            package: redis-sentinel
            version: ${{vars.major-minor-version}}
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: redis-sentinel-iamguarded-compat
            real-pkg-name: ${{subpkg.name}}

  - name: redis-cluster-${{vars.major-minor-version}}-iamguarded-compat
    dependencies:
      provides:
        - redis-cluster-iamguarded-compat=${{package.full-version}}
      runtime:
        - bash
        - busybox # Required by startup scripts
        - coreutils
        - libxcrypt
        - merged-usrsbin
        - openssl
        - redis
        - redis-cli
        - wait-for-port
        - wolfi-baselayout
    pipeline:
      - uses: iamguarded/build-compat
        with:
          package: redis-cluster
          version: ${{vars.major-minor-version}}
      - runs: |
          mkdir -p /opt/iamguarded/redis/etc
          mkdir -p /opt/iamguarded/redis/etc.default
          cp redis.conf /opt/iamguarded/redis/etc/redis-default.conf
      - uses: iamguarded/finalize-compat
        with:
          package: redis-cluster
          version: ${{vars.major-minor-version}}
    test:
      pipeline:
        - uses: iamguarded/test-compat
          with:
            package: redis-cluster
            version: ${{vars.major-minor-version}}
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: redis-cluster-iamguarded-compat
            real-pkg-name: ${{subpkg.name}}

update:
  enabled: true
  github:
    identifier: redis/redis
    tag-filter-prefix: "7.4."

test:
  environment:
    contents:
      packages:
        - redis-cli
  pipeline:
    - runs: |
        cat <<EOF >> /tmp/redis.conf
        dbfilename dump.rdb
        pidfile /tmp/redis_6379.pid
        dir /tmp/
        EOF

        redis-server /tmp/redis.conf > /dev/null 2>&1 &
        sleep 2 # wait for redis to start
        redis-cli SET bike:1 "Process 134" || exit 1
        redis-cli GET bike:1 | grep 'Process 134' || exit 1
        redis-cli exists bike:1 | grep 1 || exit 1
        redis-cli exists bike:2 | grep 0 || exit 1
    - runs: |
        redis-server --version | grep "jemalloc" || exit 1
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: redis
        real-pkg-name: ${{package.name}}
