package:
  name: request-4334
  version: 0
  epoch: 4
  description: Custom Certificate Chain for Danske Certs
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - bash
      - bash-binsh
      - ca-certificates

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates
      - ca-certificates-bundle
      - openssl

pipeline:
  - runs: |
      install -Dm755 bash-init.sh ${{targets.contextdir}}/etc/bash.bashrc
      install -Dm755 bash-init.sh ${{targets.contextdir}}/etc/profile.d/apk-mirror.sh

      mkdir -p "${{targets.destdir}}"/usr/local/share/ca-certificates/
      cp ./usr/local/share/ca-certificates/danske-custom-certs.crt "${{targets.destdir}}"/usr/local/share/ca-certificates/danske-custom-certs.crt
      update-ca-certificates

test:
  environment:
    contents:
      packages:
        - bash
        - openssl
        - busybox
        - ca-certificates-bundle
        - ca-certificates
  pipeline:
    - runs: |
        #!/bin/bash
        openssl version

update:
  enabled: false
  manual: true
  exclude-reason: |
    Static Certificate Content for Danske Bank (intended for POV)
