package:
  name: request-4334
  version: 0
  epoch: 6
  description: Custom Certificate Chain for Danske Certs
  copyright:
    - license: PROPRIETARY
  options:
    no-depends: true
    no-provides: true
  dependencies:
    runtime:
      - bash
      - ca-certificates

environment:
  contents:
    packages:
      - bash
      - bash-builtins
      - busybox
      - ca-certificates
      - ca-certificates-bundle
      - gawk
      - openssl

pipeline:
  - runs: |
      install -Dm755 ./bin/sh ${{targets.contextdir}}/bin/sh
      install -Dm755 bash-init.sh ${{targets.contextdir}}/etc/bash.bashrc
      install -Dm755 bash-init.sh ${{targets.contextdir}}/etc/profile.d/apk-mirror.sh

      mkdir -p "${{targets.destdir}}"/usr/local/share/ca-certificates/
      cp ./usr/local/share/ca-certificates/danske-custom-certs.crt "${{targets.destdir}}"/usr/local/share/ca-certificates/danske-custom-certs.crt
      awk 'BEGIN { c = 0; }
          /-----BEGIN CERTIFICATE-----/ {
              c++;
              filename = sprintf("${{targets.destdir}}/usr/local/share/ca-certificates/danske-cert%d.crt", c);
              print > filename;
              next;
          }
          { print > filename }' "${{targets.destdir}}"/usr/local/share/ca-certificates/danske-custom-certs.crt
      rm "${{targets.destdir}}"/usr/local/share/ca-certificates/danske-custom-certs.crt
      update-ca-certificates

test:
  environment:
    contents:
      packages:
        - bash
        - openssl
        - busybox
        - ca-certificates-bundle
        - ca-certificates
  pipeline:
    - runs: |
        #!/bin/bash
        openssl version

update:
  enabled: false
  manual: true
  exclude-reason: |
    Static Certificate Content for Danske Bank (intended for POV)
