package:
  name: sigstore-policy-controller
  version: 0.8.4
  epoch: 0
  description: Enforce policy on a Kubernetes cluster based on verifiable supply-chain metadata
  copyright:
    - license: Apache-2.0
  dependencies: 
    runtime:
      - ko
      - kubectl
      - kind

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-fips

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/policy-controller
      tag: v${{package.version}}
      expected-commit: 8596f22c6b18dc5784ded99dd3896d585b2deb29
  - uses: go/build

update:
  enabled: true
  github:
    identifier: sigstore/policy-controller
    strip-prefix: v
