package:
  name: slang
  version: 2.3.3
  epoch: 2
  description: S-Lang is a powerful interpreted language
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - libpng-dev
      - ncurses-dev
      - oniguruma-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.jedsoft.org/git/slang.git
      tag: v${{package.version}}
      expected-commit: a0f675ffdd5ac07789ee65900b4f88a9ba60e67c

  - uses: autoconf/configure
    with:
      opts: |
        --with-zlib=/usr/lib \
        --with-zinc=/usr/include \

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: "${{package.name}} headers"
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

  - name: ${{package.name}}-doc
    description: "${{package.name}} manpages"
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
