package:
  name: spring-boot
  version: 3.5.0
  epoch: 0
  description:
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:

data:
  - name: openjdk-versions
    items:
      17: "openjdk-17"
      21: "openjdk-21"

environment:
  contents:
    packages:
      - bash
      - busybox
      - gradle
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    LANG: en_US.UTF-8

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/spring-projects/spring-boot
      tag: v${{package.version}}-M1
      expected-commit: 094693d0cb3414da207e304937cb1374a136452e

subpackages:
  - range: openjdk-versions
    name: ${{package.name}}-${{range.value}}
    dependencies:
      runtime:
        - ${{range.value}}-default-jvm
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/home/nonroot/.m2/repository/org/springframework/boot/
          mkdir -p ~/.m2/repository/org/springframework/boot/
          ./gradlew publishToMavenLocal
          cp -rp ~/.m2/repository/org/springframework/boot/ ${{targets.destdir}}/home/nonroot/.m2/repository/org/springframework/boot/

test:
  environment:
    contents:
      packages:
        - bash
        - busybox
  pipeline:
    - runs: |
        JARFILE="$HOME/.m2/repository/org/springframework/boot/spring-boot/${{package.version}}/spring-boot-${{package.version}}.jar"
        SNAPSHOT_JARFILE="$HOME/.m2/repository/org/springframework/boot/spring-boot/${{package.version}}-SNAPSHOT/spring-boot-${{package.version}}-SNAPSHOT.jar"
        if [ -f "$JARFILE" ] || [ -f "$SNAPSHOT_JARFILE" ]; then
          exit 0
        else
          exit 1
        fi

update:
  enabled: true
  github:
    identifier: spring-projects/spring-boot
    strip-prefix: v
    strip-suffix: -M1
    use-tag: true
