package:
  name: stakater-reloader-0.0.119
  version: 0.0.119
  epoch: 5
  description: A Kubernetes controller to watch changes in ConfigMap and Secrets and do rolling upgrades on Pods
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - stakater-reloader=0.0.119

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stakater/Reloader
      tag: v${{package.version}}
      expected-commit: 9c85ce404b2a30ca8fb2844d8152a34ad157daa6

  - runs: |
      # GHSA-vvpx-j8f3-3w6h,
      # fix CVE-2023-39325 ,CVE-2023-3978 and CVE-2023-44487
      go mod edit -replace golang.org/x/net=golang.org/x/net@v0.17.0
      go mod tidy
      mkdir -p ${{targets.destdir}}/usr/bin
      go build -o ${{targets.destdir}}/usr/bin/manager .

  - uses: strip

subpackages:
  - name: stakater-reloader-compat-0.0.119
    description: compatibility symlinks package for stakater-reloader helm charts
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p ${{targets.subpkgdir}}
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager

update:
  enabled: false
