#nolint:valid-pipeline-git-checkout-tag
package:
  name: systemd-ephemeral
  version: "0.0.2"
  epoch: 0
  description: systemd mount units for volatile /home, /etc and /var
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - systemd

environment:
  contents:
    packages:
      - busybox

pipeline:
  - runs: |
      mkdir -p ${{targets.contextdir}}/usr/lib/systemd/system/
      mkdir -p ${{targets.contextdir}}/usr/lib/systemd/system/sysinit.target.wants/
      mkdir -p ${{targets.contextdir}}/usr/lib/tmpfiles.d/
      install -Dm644 overlay-dirs.conf ${{targets.contextdir}}/usr/lib/tmpfiles.d/
      install -Dm644 etc.mount ${{targets.contextdir}}/usr/lib/systemd/system/
      install -Dm644 var.mount ${{targets.contextdir}}/usr/lib/systemd/system/
      install -Dm644 home.mount ${{targets.contextdir}}/usr/lib/systemd/system/
      ln -s ../etc.mount ${{targets.contextdir}}/usr/lib/systemd/system/sysinit.target.wants/etc.mount
      ln -s ../var.mount ${{targets.contextdir}}/usr/lib/systemd/system/sysinit.target.wants/var.mount
      ln -s ../home.mount ${{targets.contextdir}}/usr/lib/systemd/system/sysinit.target.wants/home.mount

update:
  enabled: false
  exclude-reason: |
    This is the upstream for this package
