package:
  name: systemd-units-squid
  version: 1
  epoch: 0
  description: systemd units for nginx
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - squid

environment:
  contents:
    packages:
      - busybox

pipeline:
  - runs: |
      mkdir -p ${{targets.contextdir}}/usr/lib/systemd/system/
      mkdir -p ${{targets.contextdir}}/usr/lib/sysusers.d/
      install -Dm644 squid.service ${{targets.contextdir}}/usr/lib/systemd/system/
      install -Dm644 squid.sysusers ${{targets.contextdir}}/usr/lib/sysusers.d/squid.conf

test:
  environment:
    contents:
      packages:
        - systemd
  pipeline:
    - runs: |
        systemd-sysusers
        [ -z "$(systemd-analyze verify squid.service 2>&1)" ]
        systemd-analyze --no-pager --offline=true security squid.service

update:
  enabled: false
  exclude-reason: "This package is for VMs product only"
