package:
  name: task-fips
  version: "3.46.4"
  epoch: 0
  description: A task runner / simpler Make alternative written in Go
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/go-task/task
      tag: v${{package.version}}
      expected-commit: 179bde1f37561b0d5e96e99688de735ce9eef05c

  - uses: go/build
    with:
      packages: ./cmd/task
      modroot: .
      go-package: go-fips
      output: task

update:
  enabled: true
  github:
    identifier: go-task/task
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - uses: test/tw/help-check
      with:
        bins: task
    - uses: test/tw/ver-check
      with:
        bins: task
    - name: demo taskfile
      runs: |
        cat <<EOF > Taskfile.yml
        version: '3'
        tasks:
          hello:
            cmds:
              - echo "Hello, world!"
        EOF
        task hello
        task --list-all
