package:
  name: tomcat-9-fips
  version: "9.0.104"
  epoch: 1
  description: Apache Tomcat Web Server
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - tomcat-fips=${{package.full-version}}

data:
  - name: openjdk-versions
    items:
      21: "openjdk-21"
      17: "openjdk-17"
      11: "openjdk-11"

environment:
  contents:
    packages:
      - ant
      - build-base
      - busybox
      - ca-certificates-bundle
      # Only 17 is used during the build process
      - openjdk-17

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/tomcat
      tag: ${{package.version}}
      expected-commit: f8cfae0a0d1c8dc592099a1430cd08e352430823

  - uses: patch
    with:
      patches: Enable-FIPS.patch

  - runs: |
      cat <<EOF > build.properties
      skip.installer=true
      base.path=$PWD
      compile.debug=false
      EOF

subpackages:
  - range: openjdk-versions
    name: tomcat-9-${{range.value}}-fips
    dependencies:
      runtime:
        - bcfips-policy-140-3-j${{range.key}}
        - ${{range.value}}-default-jvm
        - tomcat-native
      provides:
        - tomcat-9-${{range.value}}-fips-policy-140-3=${{package.full-version}}
    pipeline:
      - runs: |
          # Only OpenJDK 8 and 17 are supported at buildtime
          # However, we're able to run Tomcat with OpenJDK 11-21
          if [[ "${{range.key}}" == "8" ]]; then
            export JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"
          else
            export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
          fi

          ant -Dskip.build.java.version=true

          mkdir -p ${{targets.contextdir}}/usr/share/tomcat
          cp LICENSE ${{targets.contextdir}}/usr/share/tomcat/

          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/bin
          cp output/build/bin/* ${{targets.contextdir}}/usr/share/tomcat/bin

          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/conf
          cp output/build/conf/* ${{targets.contextdir}}/usr/share/tomcat/conf

          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/lib
          cp output/build/lib/* ${{targets.contextdir}}/usr/share/tomcat/lib

          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/logs
          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/temp
          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/webapps

          # This includes the manager and host-manager apps.
          # The apps are not directly usable without copying into the webapps directory.
          # See https://github.com/docker-library/tomcat/pull/181 for more context.
          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/webapps.dist
          rm -rf output/build/webapps/examples
          cp -r output/build/webapps/* ${{targets.contextdir}}/usr/share/tomcat/webapps.dist/

test:
  pipeline:
    - uses: java-fips/algorithms
      with:
        java-version: 17

update:
  enabled: true
  ignore-regex-patterns:
    - '-M\d+$'
  github:
    identifier: apache/tomcat
    use-tag: true
    tag-filter: 9.
