package:
  name: vault-csi-provider-fips
  version: "1.6.0"
  epoch: 0
  description: CSI (Container Storage Interface) plugin for HashiCorp Vault
  copyright:
    - license: BUSL-1.1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/vault-csi-provider
      tag: v${{package.version}}
      expected-commit: 3cf958390e79733be1a4627677c3c20c0c18356a

  - uses: go/build
    with:
      packages: .
      modroot: .
      go-package: go-fips
      output: vault-csi-provider
      ldflags: |
        -X 'github.com/hashicorp/vault-csi-provider/internal/version.BuildVersion=${{package.version}}'
        -X 'github.com/hashicorp/vault-csi-provider/internal/version.GoVersion=$(go version)'
        -X 'github.com/hashicorp/vault-csi-provider/internal/version.BuildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")'

update:
  enabled: true
  github:
    identifier: hashicorp/vault-csi-provider
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
    environment:
      KUBERNETES_SERVICE_HOST: "127.0.0.1"
      KUBERNETES_SERVICE_PORT: 32764
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        vault-csi-provider --version
        vault-csi-provider --help
    - uses: test/kwok/cluster
    - uses: test/daemon-check-output
      with:
        start: /usr/bin/vault-csi-provider
        setup: |
          mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
          echo "default" > /var/run/secrets/kubernetes.io/serviceaccount/namespace
          kubectl create serviceaccount default
          kubectl create token default > /var/run/secrets/kubernetes.io/serviceaccount/token
        timeout: 30
        expected_output: |
          Creating new gRPC server
          Opening unix socket
          Starting gRPC server
          Starting health handler
        post: |
          curl localhost:8080/health/ready -v 2>&1 | grep "200 OK"
