#!/bin/sh

set -e

error() {
	echo "ERROR: $@" 1>&2
	exit 1
}

info() {
	echo "INFO: $@"
}

usage() {
	echo "
$0 [OPTIONS]

Options:
 -a|--arch ARCH		System architecture, x86_64 or aarch64; defaults to local system architecture per 'uname -m'
 -d|--disk DISK_IMG	Path to disk image, will be generated if unspecified
 -e|--ephemeral		Ephemeral mode; boot qemu with kernel and initrd directly; DISK_IMG will be ignored
 -h|--help		This help screen
 -i|--initrd		Path to initrd image, will be generated if unspecified
 -k|--kernel		Path to kernel image, will be generated if unspecified
 -m|--mem		Amount of memory in MB to give to virtual machine, default is 2000
 --mission		Path to a shell script, to copy into the initrd and run instead of init
 -q|--qemu-opts		Additional options to append and pass to qemu
 -s|--smp		Number of CPUs to pass to qemu, default is the number on the local system, per 'nproc'
 -v|--verbose		Verbose mode
"
}

# You will need to add more memory if you want to do things like adding apk's in this VM
dir=$(dirname $0)/

# Handle command line options
while [ ! -z "$1" ]; do
        case "$1" in
		-a|--arch)
			arch="$2"
			shift 2
		;;
		-d|--disk)
			if [ -z "$2" ]; then
				shift
			else
				diskimg="$2"
				shift 2
			fi
		;;
		-e|--ephemeral)
			ephemeral=1
			shift
		;;
		-h|--help)
			usage
			exit 0
		;;
		-i|--initrd)
			initrd="$2"
			shift 2
		;;
		-k|--kernel)
			kernel="$2"
			shift 2
		;;
                -m|--mem)
			mem="$2"
			shift 2
		;;
		--mission)
			mission="$2"
			shift 2
		;;
		-q|--qemu-opts)
			qemu_opts="$2"
			shift 2
		;;
		-s|--smp)
			smp="$2"
			shift 2
		;;
		-v|--verbose)
			set -x
			export verbose=1
			shift
		;;
		*)
			usage
			exit 1
		;;
	esac
done
[ -z "$arch" ] && arch=$(uname -m)
[ -z "$initrd" ] && initrd=$(dirname "$0")/initrd.$arch.cpio.gz
[ -z "$diskimg" ] && diskimg=$(dirname "$0")/disk.$arch.img
[ -z "$kernel" ] && kernel=$(ls $(dirname "$0")/vmlinuz-$arch* 2>/dev/null | sort | tail -n1)
[ -z "$mem" ] && mem=2000
[ -z "$smp" ] && smp=$(nproc)
[ -z "$ephemeral" ] && ephemeral=0

# Fetch a kernel, if needed
[ -e "$kernel" ] || kernel=$($dir/.fetch-linux-kernel --arch $arch)
info "kernel = $kernel"

# Build a new initrd if one doesn't exist, or we need to copy an executable into it
# Mission is an optional shell script to run on vm boot in initrd
if [ ! -e "$initrd" ] || [ -f "$mission" ]; then
	if [ -x "$mission" ]; then
		mission_tmp=$(mktemp $dir/mission-XXXXXXXX)
		cat $mission > $mission_tmp
		m=$(basename $mission_tmp)
		info "mission = $mission"
	fi
	# We need to build an initrd
	info "Building an initrd..."
	docker run --rm -it \
		-e verbose="$verbose" \
		--mount type=bind,source="$dir",destination="/srv" \
		cgr.dev/chainguard/wolfi-base:latest \
		/srv/.mkinitrd $(id -u):$(id -g) $arch $m
	info "initrd = $initrd"
	rm -f $mission_tmp
fi

# Setup disk image, if necessary
if [ "$ephemeral" = "0" ]; then
	info "Using a disk image..."
	if [ ! -e "$diskimg" ]; then
		# We need to build a bootable disk image
		# Need privileged to losetup and mount loopback devices
		docker run --privileged --rm -it \
			-e HTTP_AUTH="basic:apk.cgr.dev:user:$(chainctl auth token --audience apk.cgr.dev)" -e verbose="$verbose" \
			--mount type=bind,source="$dir",destination="/srv" \
			cgr.dev/chainguard/wolfi-base:latest \
			/srv/.mkdiskimg $(id -u):$(id -g) /srv/$(basename $kernel) /srv/$(basename $initrd)

	fi
	info "disk = $diskimg"
	qemu_opts="$qemu_opts -drive format=raw,if=virtio,file=$diskimg"
	# Need to add bios if we're booting from disk
	case "$arch" in
		x86_64)
			qemu_opts="$qemu_opts -bios /usr/share/qemu/OVMF.fd"
		;;
		aarch64)
			qemu_opts="$qemu_opts -bios /usr/share/qemu-efi-aarch64/QEMU_EFI.fd"
		;;
	esac
else
	# Running in kernel/initrd ephemeral mode
	info "Using ephemeral mode..."
	qemu_opts="$qemu_opts -kernel $kernel -initrd $initrd"
fi


# Run the VM in qemu-kvm
# Use "poweroff" to shutdown from within the VM, or "killall qemu-system-x86_64" from outside the VM
case "$arch" in
	x86_64)
		qemu="qemu-system-x86_64"
		if [ -w /dev/kvm ] && [ "$arch" = "$(uname -m)" ]; then
			# Run x86_64/amd64 with acceleration:
			qemu_opts="$qemu_opts -cpu host -enable-kvm"
		else
			# Run x86_64/amd64 without acceleration:
			qemu_opts="$qemu_opts -cpu SandyBridge"
		fi
		append="console=ttyS0 quiet"
	;;
	aarch64)
		qemu="qemu-system-aarch64"
		[ "$smp" -gt 8 ] && smp=8
		if [ -w /dev/kvm ] && [ "$arch" = "$(uname -m)" ]; then
			# Run on Linux aarch64 with /dev/kvm acceleration:
			qemu_opts="$qemu_opts -cpu host -accel kvm -machine virt"
		# elif somehow test if running on a Mac
			# Run MacoOS aarch64 with hvf acceleration:
			#qemu_opts="$qemu_opts -cpu host -accel hvf -machine virt"
		else
			# Run x86_64/amd64 without acceleration:
			qemu_opts="$qemu_opts -cpu cortex-a72 -machine virt"
		fi
		append="quiet"
	;;
esac


qemu_opts="$qemu_opts -m $mem -smp $smp -nographic -netdev user,id=id1,hostfwd=tcp::2222-:22 -device virtio-net-pci,netdev=id1"
case "$qemu_opts" in
	*-kernel*)
		exec $qemu $qemu_opts -append "$append"
	;;
	*)
		exec $qemu $qemu_opts
	;;
esac
