package:
  name: yq-fips
  version: "4.45.2"
  epoch: 0
  description: "yq is a portable command-line YAML, JSON, XML, CSV and properties processor"
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mikefarah/yq
      tag: v${{package.version}}
      expected-commit: c59fa8de59f1f5a16fdbfd1e2a6e97a1b42a64b9

  - uses: go/build
    with:
      packages: .
      output: yq
      go-package: go-fips

  - uses: strip

test:
  pipeline:
    - runs: |
        yq --version | grep "version v${{package.version}}"
        yq --help
    - uses: test/go-fips-check

update:
  enabled: true
  github:
    identifier: mikefarah/yq
    strip-prefix: v
