archs:
  - amd64
  - arm64
contents:
  build_repositories:
    - https://apk.cgr.dev/chainguard-private
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - https://packages.cgr.dev/extras
  packages:
    - apk-tools
    - bash-binsh
    - busybox
    - chainguard-baselayout
    - coreutils
    - dbus
    - google-compute-engine-oslogin
    - google-guest-agent
    - google-guest-config
    - iproute2
    - kmod
    - kmod-libs
    - linux-gcp-generic-boot-installed
    - mount
    - openssh-pam-config
    - openssh-server
    - openssh-service
    - openssh-sftp-server
    - polkit
    - shadow
    - sudo-rs
    - systemd-boot
    - systemd-boot-installed
    - systemd-default-network
    - systemd-init
    - systemd-logind-service
    - systemd-repart-rootfs
    - udev
    - umount
    - util-linux-misc
    - xfsprogs
