#!/bin/sh
# shellcheck disable=SC2162,SC3043
Usage() {
    cat <<EOF
Usage: ${0##*/} user [fingerprint]

write ssh keys to stdout for user.
fingerprint is the fingerprint of the key or certificate.
EOF
}

stderr() { echo "$@" 1>&2; }
fail() { stderr "FATAL:" "$@"; exit 1; }

ec2md_setup() {
    [ -n "$EC2MD_TOK" ] && [ -n "$EC2MD_URL" ] && return 0
    local tok="" ttl=120
    local tokurls="http://169.254.169.254:80"
    tokurls="$tokurls http://[fd00:ec2::254]:80"
    for tokurl in $tokurls; do
        tok=$(curl --fail --max-time 5 --silent \
                -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: $ttl" \
                "${tokurl}/latest/api/token") || continue
        [ -n "$tok" ] && url="$tokurl" && break
    done
    if [ -z "$url" ]; then
        stderr "could not get a token on ec2 from $tokurls"
        return 1
    fi
    EC2MD_TOK="$tok"
    EC2MD_URL="$url"
}

ec2md_fetch() {
    ec2md_setup || return 1
    local path="$1" rc=0
    local url="$EC2MD_URL/$path" tok="$EC2MD_TOK"
    curl --silent --fail \
        -H "X-aws-ec2-metadata-token: $tok" "$url" && return 0
    rc=$?
    stderr "ec2md_fetch failed [$rc] on '$url'"
    return 1
}

ec2dump_keys() {
    local out="" num="" tok="" ver="2024-04-11"
    # index shows newline separated items '0=name\n1=name\n'
    # get the index and then loop over items.
    out=$(ec2md_fetch "$ver/meta-data/public-keys") || {
        stderr "failed to list ec2 public-keys"
        return 1
    }
    for tok in ${out}; do
        num=${tok%%=*}
        ec2md_fetch "$ver/meta-data/public-keys/$num/openssh-key" || {
            stderr "failed to retrieve public key '$num' for $tok"
            return 1
        }
    done
    return 0
}

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    Usage
    exit 0
elif [ $# -lt 1 -o $# -gt 2 ]; then
    stderr "$0 received $# args ($*), expected 1 or 2"
    exit 1
fi

user="$1"
fp=$2


cloud="$(systemd-detect-virt)"
stderr "Fetching keys on $cloud"
case $cloud in
    google)
        url="http://metadata.google.internal/computeMetadata/v1/instance/attributes/ssh-keys"
        out=$(curl --fail -H "Metadata-Flavor: Google" "$url") ||
            fail "failed retrieving keys on $cloud"
        printf "%s" "$out" | cut -d':' -f2-
        ;;
    microsoft)
        url="http://169.254.169.254/metadata/instance/compute/publicKeys?api-version=2021-02-01"
        out=$(curl --fail -H "Metadata: true" "$url") ||
            fail "failed retrieving keys on $cloud"
        printf "%s" "$out" | cut -d':' -f2 | cut -d'"' -f2
        ;;
    amazon)
        # Should check the passed in $2 arg for the key fingerprint.
        # If it is found in ec2dump_keys we can choose not to execute
        # eic binary at all. Because eic connect binary will return
        # error when no keys are found, which then makes sshd not
        # trust the already printed ec2dump_keys. sshd really needs to
        # gain support for multiple authorized_keys commands.
        ec2dump_keys
        if [ -x /opt/aws/bin/eic_run_authorized_keys ]; then
            /opt/aws/bin/eic_run_authorized_keys "$@" || :
        fi
        ;;
    *) fail "unsupported cloud \"$cloud\"";;
esac
