#!/bin/sh
# shellcheck disable=SC2162,SC3043
CR="
"

# the PATH here will not include /bin or /sbin
# until we're usr merged, we have programs in /bin we need (mktemp)
PATH=$PATH:/bin:/sbin

read_info() {
    local idd="/sys/class/dmi/id" fails=""

    # this is redirected to silence errors
    {
    read PRODUCT_NAME < "$idd/product_name" ||
        fails="$fails $idd/product_name"
    read PRODUCT_SERIAL < "$idd/product_serial" ||
        fails="$fails $idd/product_serial"
    read CHASSIS_ASSET < "$idd/chassis_asset_tag" ||
        fails="$fails $idd/chassis_asset_tag"
    } >/dev/null 2>&1
    [ -z "$fails" ] && return 0
    stderr "failed reading info from ${fails# }"
    return 1
}

get_cloud() {
    local GCE="Google Compute Engine"
    local azure="7783-7084-3265-9085-8269-3286-77"
    [ "$PRODUCT_NAME" = "$GCE" ] && { echo "GCE"; return 0; }
    [ "$CHASSIS_ASSET" = "$azure" ] && { echo "Azure"; return 0; }
    case "$PRODUCT_SERIAL" in
        [Ee][Cc]2*) echo "EC2"; return 0;;
        chainguard-*) echo "Chainguard"; return 0;;
    esac
    return 0
}

stderr() { echo "$@" 1>&2; }
fail() { stderr "FATAL:" "$@"; exit 1; }

ec2md_setup() {
    [ -n "$EC2MD_TOK" ] && [ -n "$EC2MD_URL" ] && return 0
    local tok="" ttl=120
    local tokurls="http://169.254.169.254:80"
    tokurls="$tokurls http://[fd00:ec2::254]:80"
    for tokurl in $tokurls; do
        tok=$(curl --fail --max-time 5 --silent \
                -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: $ttl" \
                "${tokurl}/latest/api/token") || continue
        [ -n "$tok" ] && url="$tokurl" && break
    done
    if [ -z "$url" ]; then
        stderr "could not get a token on ec2 from $tokurls"
        return 1
    fi
    EC2MD_TOK="$tok"
    EC2MD_URL="$url"
}

ec2md_fetch() {
    ec2md_setup || return 1
    local path="$1" rc=0
    local url="$EC2MD_URL/$path" tok="$EC2MD_TOK"
    curl --silent --fail \
        -H "X-aws-ec2-metadata-token: $tok" "$url" && return 0
    rc=$?
    stderr "ec2md_fetch failed [$rc] on '$url'"
    return 1
}

ec2dump_keys() {
    local out="" num="" tok="" ver="2024-04-11"
    # index shows newline separated items '0=name\n1=name\n'
    # get the index and then loop over items.
    out=$(ec2md_fetch "$ver/meta-data/public-keys") || {
        stderr "failed to list ec2 public-keys"
        return 1
    }
    for tok in ${out}; do
        num=${tok%%=*}
        ec2md_fetch "$ver/meta-data/public-keys/$num/openssh-key" || {
            stderr "failed to retrieve public key '$num' for $tok"
            return 1
        }
    done
    return 0
}

get_cmdline_keys() {
    local cmdline
    [ -r /proc/cmdline ] || return 0
    read cmdline < /proc/cmdline || {
        stderr "failed reading /proc/cmdline"
        return 1
    }
    local keys="" out="" tok=""
    for tok in $cmdline; do
        case "$tok" in
            sshkey=*)
                out=$(echo "${tok#*=}" | base64 -d) || {
                    stderr "failed decoding base64 content in $tok"
                    return 1
                }
                keys="$keys${out%"${CR}"}$CR"
        esac
    done
    printf "%s" "$keys"
}

get_oemstring_keys() {
    if ! command -v dmidecode >/dev/null 2>&1; then
        stderr "dmidecode is not available, cannot read chainguard keys"
        return 0
    fi
    local out="" n=1
    while out=$(dmidecode "--oem-string=$n" 2>/dev/null) && [ -n "$out" ]; do
        n=$((n+1))
        case "$out" in
            chainguard.dev/v1/ssh-pubkey=*)
                echo "${out#*=}"
                return 0
                ;;
        esac
    done
}

chainguard_dump_keys() {
    local cmdline="" oemstrings=""
    cmdline=$(get_cmdline_keys) || return
    oemstrings=$(get_oemstring_keys) || return
    printf "%s" "${cmdline}${oemstrings}"
}

Usage() {
    cat <<EOF
Usage: ${0#*/} [outfile]

    pull keys from cloud platform and write to outfile.
    outfile defaults to /root/.ssh/authorized_keys
EOF
}

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    Usage
    exit 0
fi

if [ -n "$CLOUD_PLATFORM" ]; then
    cloud="$CLOUD_PLATFORM"
else
    read_info || fail "reading platform failed (sudo?)"
    cloud=$(get_cloud)
    if [ -z "$cloud" ]; then
        echo "unknown platform"
        echo "product=\"$PRODUCT_NAME\" serial=\"$PRODUCT_SERIAL\"" \
            "asset=\"$CHASSIS_ASSET\""
        exit 0
    fi
fi

akeys="$1"
if [ -z "$akeys" ]; then
    # systemd may not have HOME set and that is sometimes required
    # for expanding ~.  So do it ourselves.
    p=$(echo ~/.ssh)
    if [ "$p" = "~/.ssh" ]; then
        id=$(id -u)
        name=$(id -un)
        if [ "$id" = "0" ]; then
            p="/root/.ssh"
            echo "HOME was not set. Using /root as home for id 0"
        elif [ -d "/home/$name" ]; then
            echo "HOME was not set. Using /home/$name for user '$name'"
            p="/home/$name/.ssh"
        fi
    fi
    akeys="$p/authorized_keys"
fi

keyd="."
if [ "$akeys" != "-" ]; then
    keyd=$(dirname "$akeys") || fail "failed getting dirname for '$akeys'"
fi

umask 077 || fail "failed setting umask"

tmpf=$(mktemp) || fail "failed to create tmpfile"
trap "rm -f '$tmpf'" EXIT

if [ ! -d "$keyd" ]; then
    mkdir "$keyd" || fail "failed to create directory '$keyd'"
fi


stderr "Fetching keys on $cloud"
case "$cloud" in
    GCE)
        url="http://metadata.google.internal/computeMetadata/v1/instance/attributes/ssh-keys"
        out=$(curl --fail -H "Metadata-Flavor: Google" "$url") ||
            fail "failed retrieving keys on $cloud"
        printf "%s" "$out" | cut -d':' -f2- > "$tmpf"
        ;;
    Azure)
        local url="http://169.254.169.254/metadata/instance/compute/publicKeys?api-version=2021-02-01"
        out=$(curl --fail -H "Metadata: true" "$url") ||
            fail "failed retrieving keys on $cloud"
        printf "%s" "$out" | cut -d':' -f2 | cut -d'"' -f2 > "$tmpf"
        ;;
    EC2)
        ec2dump_keys > "$tmpf"
        ;;
    Chainguard)
        chainguard_dump_keys > "$tmpf" ||
            fail "failed reading chainguard keys"
        ;;
    *) fail "unsupported cloud \"$cloud\"";;
esac

if [ "$akeys" != "-" ]; then
    exec > "$akeys" || fail "failed writing to $akeys"
fi

num=0
while read line; do
    printf "%s\n" "$line"
    num=$((num+1))
done < "$tmpf"
stderr "Wrote $num keys from $cloud to $akeys"
