name: Create boot-installed package

inputs:
  version-flavor:
    description: "The version-flavor of the modules dir"
    required: true

  extra-args:
    description: "Arguments to append to the commandline"
    required: false

pipeline:
  - runs: |
      mkdir -p ${{targets.subpkgdir}}/boot/efi/chainguard/${{inputs.version-flavor}}/
      if [ "${{build.arch}}" = 'aarch64' ]; then
        # Apparently on aarch64 the kernel cannot be compressed, so we forcibly decompress it here.
        gunzip --stdout ${{targets.destdir}}/boot/vmlinuz > ${{targets.subpkgdir}}/boot/efi/chainguard/${{inputs.version-flavor}}/linux
      fi
      if [ "${{build.arch}}" = 'x86_64' ]; then
        cp ${{targets.destdir}}/boot/vmlinuz ${{targets.subpkgdir}}/boot/efi/chainguard/${{inputs.version-flavor}}/linux
      fi
      mkdir -p ${{targets.subpkgdir}}/boot/efi/loader/entries/
      cat > ${{targets.subpkgdir}}/boot/efi/loader/entries/chainguard-${{inputs.version-flavor}}.conf <<EOF
        # Boot Loader Specification type#1 entry
        title      Chainguard
        version    ${{inputs.version-flavor}}
        sort-key   chainguard
        # The root argument must match the form documented (only) here:
        # https://github.com/torvalds/linux/blob/3022e9d0/block/early-lookup.c#L217
        options    root=PARTLABEL=Chainguard console=ttyS0 rw ${{inputs.extra-args}}
        linux      /chainguard/${{inputs.version-flavor}}/linux
      EOF
      # In addition to noting the root partition above, configure /etc/fstab as well.
      mkdir -p ${{targets.subpkgdir}}/etc
      echo "/dev/gpt-auto-root / auto defaults,x-systemd.growfs 0 1" > "${{targets.subpkgdir}}/etc/fstab"
