name: Build the traditional kernel image format

needs:
  packages:
    - bison
    - build-base
    - busybox
    - ca-certificates-bundle
    - coreutils
    - diffutils
    - elfutils
    - elfutils-dev
    - findutils
    - flex
    - gawk
    - gnutar
    - openssl
    - openssl-dev
    - pahole
    - pahole-dev
    - perl
    - python3
    - wolfi-base
    - gmp
    - gmp-dev
    - mpc
    - mpc-dev
    - mpfr
    - mpfr-dev
    - zstd

inputs:
  version-flavor:
    description: "The version-flavor of the modules dir"
    required: true
  make-targets:
    description: "Make targets. Default: arch specific kernel image"
    required: false

pipeline:
  - runs: |
      TARGET=""
      if [ "${{build.arch}}" = 'aarch64' ]; then
        TARGET="Image.gz"
      fi
      if [ "${{build.arch}}" = 'x86_64' ]; then
        TARGET="bzImage"
      fi
      [ -n "${{inputs.make-targets}}" ] && TARGET="${{inputs.make-targets}}"
      make -j $(nproc) $TARGET LOCALVERSION=""
      if [ -z "${{inputs.make-targets}}" ]; then
          mkdir -p ${{targets.destdir}}/boot
          install -T -m644 .config ${{targets.destdir}}/boot/config-${{inputs.version-flavor}}
          install -T -m644 $(find . -type f \( -name bzImage -or -name Image.gz \) -print -quit) ${{targets.destdir}}/boot/vmlinuz-${{inputs.version-flavor}}
          ln -sf vmlinuz-${{inputs.version-flavor}} ${{targets.destdir}}/boot/vmlinuz
      fi
