name: Build initramfs with dracut

needs:
  packages:
    - busybox
    - dracut-ng

inputs:
  version-flavor:
    description: "The version-flavor of the modules dir"
    required: true
  kmoddir:
    description: "modules directory"
    required: true
  output:
    description: |
      Where to write initramfs.
      Default matches the kernel location for boot-installed pipeline.
      bootc wants initramfs in
        /usr/lib/modules/${{inputs.version-flavor}}/initramfs.img
    required: false
    default: ${{targets.contextdir}}/boot/efi/chainguard/${{inputs.version-flavor}}/initrd

pipeline:
  - runs: |
      kver=${{inputs.version-flavor}}
      modd=${{inputs.kmoddir}}
      outf=${{inputs.output}}

      set -o pipefail

      td=$(mktemp -d "/tmp/dracut.XXXXXX")
      mkdir "$td/tmp" "$td/out.d"
      TMPDIR="$td/tmp" dracut \
          --verbose --no-hostonly --reproducible --zstd \
          --no-early-microcode \
          --omit=busybox \
          --kver="$kver" --kmoddir="$modd" \
          "$td/out.d/initrd.img" 2>&1 |
          tee "$td/build.log" ||
          { echo "FATAL: dracut failed $?" 2>&1; exit 1; }

      if grep -q -e "FAILED:" -e "ERROR:" "$td/build.log"; then
          echo "FATAL: dracut did not exit failure, but contained ERROR or FAIL in output"
          exit 1
      fi

      outd=$(dirname "$outf")
      mkdir -p "$outd"
      mv "$td/out.d/initrd.img" "$outf"
