inputs:
  moniker:
    required: true
    description: Version moniker (mainline, stable, longterm)

needs:
  packages:
    - busybox

pipeline:
  # We have update.ignore_regex_patterns and update.version_transform stanzas
  # in linux-*.yaml files to ensure that robots select an appropriate version
  # which matches the kernel version moniker, but these do not apply to humans
  # updating the package. We want to make sure that the version we've updated to
  # is appropriate for whatever release moniker the package tracks.
  - name: Check for forbidden package versions
    runs: |
      if [ "${{inputs.moniker}}" = "mainline" ]; then
        case "${{package.version}}" in
          *".0")
            ;;
          *"rc"*)
            ;;
          *)
            echo "ERROR: Version appears to not be X.Y.0 or X.Y_rcZ version, does not appear to be mainline version."
            exit 1
            ;;
        esac
      elif [ "${{inputs.moniker}}" = "longterm" ]; then
        case "${{package.version}}" in
          # Update this with
          # curl -fsSL https://www.kernel.org/releases.json | jq -r '.releases[] | select(.moniker == "longterm") | .version' | sed -E 's/^([0-9]+\.[0-9]+)\.[0-9]+/\1.*/' | paste -sd'|' -
          # Hardcoded so that 1. build is reproducible, 2. it's easier to keep building old kernel versions forever, 3. we don't have to worry about another network call failing
          6.12.*|6.6.*|6.1.*|5.15.*|5.10.*|5.4.*)
            ;;
          *)
            echo "ERROR: Unknown linux LTS version."
            exit 1
            ;;
        esac
      elif [ "${{inputs.moniker}}" = "stable" ]; then
        case "${{package.version}}" in
          *"_rc"*)
            echo "ERROR: Version has _rc. This is not a stable kernel version."
            exit 1
            ;;
          *".0")
            echo "ERROR: Version has trailing zero. This is not a stable kernel version."
            exit 1
            ;;
          [0-9]*.[0-9]*.[0-9]*)
            ;;
          [0-9]*.[0-9]*)
            echo "ERROR: Version is missing patch version. This is not a stable kernel version."
            exit 1
            ;;
        esac
      else
        echo "ERROR: Unknown kernel version moniker. Don't know if this is a valid version."
        exit 1
      fi
      echo "${{package.version}} is a permitted ${{inputs.moniker}} version"
