---
apiVersion: v1
data:
  api-key: c2stMTIzNDU2Nzg5MGFiY2RlZg==
  password: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
  username: YWRtaW4=
kind: Secret
metadata:
  name: mysecret
  namespace: default
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: mysecret
    uid: ""
type: Opaque
