#!/bin/sh

# This must run within a docker container in order to run mknod and create nodes inside of the cpio tarball

set -e
set -x

[ -z "$1" ] && echo "ERROR: please supply your UID:GID as the first argument" 1>&2 && exit 1

owner="$1"
mission="$2"
dir="/tmp"

# Make an initramfs
apk update
apk add apko

# Start with wolfi-base, add systemd for init and mount for some boot processes
cat <<EOF >"$dir"/base.yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - mount
    - systemd
    - wolfi-base
EOF

# Generate a base wolfi tarball
apko build-minirootfs $dir/base.yaml $dir/base.tar.gz
mkdir -p $dir/initramfs/rootfs

# Extract that tarball so that we can add some configuration
tar -C $dir/initramfs/rootfs -xf $dir/base.tar.gz || true

# Symlink systemd to /init to actually boot the system
ln -sf /usr/lib/systemd/systemd $dir/initramfs/rootfs/init

# Symlink a timezone to avoid boot prompt for timezone
ln -sf /usr/share/zoneinfo/UTC $dir/initramfs/rootfs/etc/localtime

# Let's make our on login shell or executable runner
if [ -f "/srv/$mission" ] && [ -x "/srv/$mission" ]; then
	cp -af /srv/$mission $dir/initramfs/rootfs/root/
	cat <<EOF >$dir/initramfs/rootfs/root/$mission.sh
#!/bin/sh
/root/$mission
poweroff >/dev/null 2>&1
EOF
	chmod 700 $dir/initramfs/rootfs/root/$mission.sh
	# Boot straight to a wrapper script that executes our "mission"
	sed -i "s|^ExecStart=.*agetty.*|ExecStart=-/bin/sh -l /root/$mission.sh|" $dir/initramfs/rootfs/usr/lib/systemd/system/serial-getty@.service
else
	# Boot straight to busybox shell as root (like a container!)
	sed -i "s|^ExecStart=.*agetty.*|ExecStart=-/bin/sh -l|" $dir/initramfs/rootfs/usr/lib/systemd/system/serial-getty@.service
fi

# Disable systemd login; boot straight to busybox shell as root (like a container!)
mkdir -p $dir/initramfs/rootfs/etc/systemd/system/
ln -sf /dev/null $dir/initramfs/rootfs/etc/systemd/system/systemd-logind.service
sed -i 's|^ExecStart=.*|ExecStart=/bin/true|' $dir/initramfs/rootfs/usr/lib/systemd/system/systemd-vconsole-setup.service

# Set the hostname to "wolfi" for a little lightweight branding
echo "wolfi" > $dir/initramfs/rootfs/etc/hostname
sed -i -e "s/\slocalhost\s/ localhost wolfi /" $dir/initramfs/rootfs/etc/hosts

# Setup dhcp networking
cat > $dir/initramfs/rootfs/etc/systemd/network/20-wired.network <<- EOF
[Match]
Name=en*
[Network]
DHCP=yes
EOF

# Archive and compress this directory structure into a cpio file for initramfs
( cd $dir/initramfs/rootfs && find . >../files )
( cd $dir/initramfs/rootfs && cpio --format=newc -o ) <$dir/initramfs/files | gzip --to-stdout >/srv/initramfs.$(uname -m).cpio.gz

# Chown this file back to the user who ran the docker command that built this file
# Otherwise, the user is going to end up with a root-owned file in their directory
chown "$owner" /srv/initramfs.$(uname -m).cpio.gz
