#!/bin/bash
# shellcheck disable=SC2015
INSTALLER_OPTS=${INSTALLER_OPTS:-"debug"}
tball=${1:-/tmp/tball.tar.gz}

vr() { echo "$@" 1>&2; "$@"; }
fail() { echo "$@" 1>&2; exit 1; }

cleanup() {
    echo "cleanup"
    if [ -n "${SCRATCH_LO}" ]; then
        vr losetup --detach="$SCRATCH_LO"
        SCRATCH_LO=""
    fi
    if [ -n "${SCRATCH_FILE}" ]; then
        vr rm -f "$SCRATCH_FILE"
        SCRATCH_FILE=""
    fi
    if [ -n "${DISK_LO}" ]; then
        vr losetup --detach="$DISK_LO"
        DISK_LO=""
    fi
    if [ -n "${DISK_FILE}" ]; then
        echo "keeping disk file $DISK_FILE"
        #vr rm -f "$DISK_FILE"
        DISK_FILE=""
    fi
}

DISK_FILE=""
DISK_LO=""
SCRATCH_FILE=""
SCRATCH_LO=""
trap cleanup EXIT

disk="disk.img"
rm -f "$disk" || fail "failed remove disk"
vr truncate --size=20G "$disk" && DISK_FILE="$disk" &&
    lodev=$(vr losetup --find --show "$disk") &&
    DISK_LO="$lodev" ||
    fail "failed setting up $disk"

scratch="scratch.img"
vr truncate --size=20G "$scratch" && SCRATCH_FILE="$scratch" &&
    lodev=$(vr losetup --find --show "$scratch") &&
    SCRATCH_LO="$lodev" ||
    fail "failed setting up $scratch"

rm -Rf out.d && mkdir out.d || fail "failed out.d setup"
vr env INSTALLER_LIBDIR="$PWD/scripts" \
    ./scripts/installer guest-install --input-tar="$tball" \
    --scratch="$SCRATCH_LO" \
    --disk="$DISK_LO" \
    --output=./out.d
