name: Retrieves an archive from either the local maven repository or the one in GAR

# Note: for local development (optional), this expects a local maven repository to be mounted at /var/cache/melange/.m2/repository
# and a local gcloud configuration to be mounted at /var/cache/melange/.config/gcloud which can be done by leveraging the `melange-cache` directory.
# A helper make target is added to `Makefile` to make this easier: make init-gcp-auth.
# In post-submit automation, this should just use the metadata server authentication that elastic build already has access to.
needs:
  packages:
    - bash
    - google-cloud-sdk

inputs:
  group-id:
    description: "The group ID of the artifact to retrieve"
    required: true
  artifact-id:
    description: "The artifact ID of the artifact to retrieve"
    required: true
  version:
    description: "The version of the artifact to retrieve"
    required: true
  packaging:
    description: "The packaging of the artifact to retrieve (tar.gz, zip, jar, pom, etc.)"
    default: "tar.gz"
  file-suffix:
    description: "The suffix of the file to retrieve (file names are typically <artifact-id>-<version>.<packaging>)"
    default: ""
  gar-project:
    description: "The URL of the GAR repository"
    default: "ecosystems-squad"
  gar-location:
    description: "The location of the artifact in the GAR repository"
    default: "us-central1"
  gar-repository:
    description: "The repository of the artifact in the GAR repository"
    default: "ecosystems-maven-repo"

pipeline:
  - name: Get the artifact
    runs: |
      GROUP_PATH=$(echo ${{inputs.group-id}} | tr '.' '/')

      # Local artifact path
      FILE_NAME="${{inputs.artifact-id}}-${{inputs.version}}${{inputs.file-suffix}}.${{inputs.packaging}}"
      MAVEN_REPO_PATH="$GROUP_PATH/${{inputs.artifact-id}}/${{inputs.version}}/$FILE_NAME"

      # This will only be used if a local maven repo was copied into the melange cache
      LOCAL_ARTIFACT_PATH="/var/cache/melange/.m2/repository/$MAVEN_REPO_PATH"

      # Check if artifact exists locally
      if [ -f "$LOCAL_ARTIFACT_PATH" ]; then
          echo "Artifact found locally: $LOCAL_ARTIFACT_PATH"
          cp $LOCAL_ARTIFACT_PATH .
      else
          echo "Artifact not found locally. Attempting to download from GAR..."
          if [ -d "/var/cache/melange/.config/gcloud" ]; then
            mkdir -p ~/.config/gcloud
            cp -r /var/cache/melange/.config/gcloud/* ~/.config/gcloud/
          fi
          gcloud artifacts files download \
            --project=${{inputs.gar-project}} \
            --location=${{inputs.gar-location}} \
            --repository=${{inputs.gar-repository}} \
            --destination=. \
            --local-filename=$FILE_NAME \
            $MAVEN_REPO_PATH
      fi
