package:
  name: cloudbeat-9.3
  version: "9.3.0"
  epoch: 0 # GHSA-37cx-329c-33x3
  description: Cloudbeat is a cloud-native security and compliance monitoring tool for real-time threat detection and policy enforcement across cloud environments.
  copyright:
    - license: Elastic-2.0
  dependencies:
    provides:
      - cloudbeat=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/elastic/cloudbeat
      tag: v${{package.version}}
      expected-commit: 490275fbc86169fbb5c015add8aedac0665f0223

  - uses: go/bump
    with:
      deps: |-
        github.com/containerd/containerd@v1.7.29
        github.com/sigstore/rekor@v1.5.0
        github.com/sigstore/sigstore@v1.10.4
        github.com/go-git/go-git/v5@v5.16.5

  - uses: go/build
    with:
      packages: .
      output: cloudbeat
      ldflags: -X 'github.com/elastic/cloudbeat/build.Version=${{package.version}}' -X 'github.com/elastic/cloudbeat/build.CommitSHA=$(git rev-parse HEAD)'

  - uses: strip

  - name: copy cloudbeat.yml
    runs: |
      mkdir -p ${{targets.destdir}}/usr/share/cloudbeat
      cp cloudbeat.yml ${{targets.destdir}}/usr/share/cloudbeat/cloudbeat.yml

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: elastic/cloudbeat
    tag-filter-prefix: v9.3.
    use-tag: true

test:
  environment:
    accounts:
      users:
        - username: elasticsearch
          uid: 1000
          gid: 0
      run-as: 0
    contents:
      packages:
        - bash
        - curl
        - elasticsearch-8
        - jq
        - kibana-8
        - sudo
        - wait-for-it
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
      ES_JAVA_HOME: /usr/lib/jvm/default-jvm
  pipeline:
    - name: Test cloudbeat setup
      runs: |
        chown -R elasticsearch:root /usr/share/elasticsearch
        sudo -E -u elasticsearch /usr/share/elasticsearch/bin/elasticsearch -d \
          -Ediscovery.type=single-node \
          -Expack.security.enabled=false \
          -p /tmp/elasticsearch.pid > /dev/null 2>&1 &
        wait-for-it localhost:9200 --timeout=60
        # Confirm Elasticsearch status before continuing
        es_status=$(curl -s -X GET "http://localhost:9200/_cluster/health?pretty" | jq -r '.status')
        echo "Elasticsearch status: $es_status"
        timer_start=$(date +%s)
        while [ $es_status != "green" ]
        do
          timer_now=$(date +%s)
          es_status=$(curl -s -X GET "http://localhost:9200/_cluster/health?pretty" | jq -r '.status')
          echo "Elasticsearch status: $es_status"
          if [ $(( timer_now - timer_start )) -gt 60 ]
          then
            echo "Timed out waiting for Elasticsearch!"
            exit 1
          fi
          sleep 2
        done
        # Run Kibana
        echo -e "elasticsearch.hosts: [\"http://localhost:9200\"]" > kibana.yml
        (
          /usr/share/kibana/bin/kibana --config kibana.yml --allow-root 2>&1 > tee kibana.log 2>&1 &
        ) &
        wait-for-it localhost:5601 --timeout=60

        export KUBERNETES_MASTER="https://127.0.0.1:32764"
        export NODE_NAME="node-000000"
        export KUBECONFIG="/root/.kube/config"
        curl -o cloudbeat.yml https://raw.githubusercontent.com/elastic/cloudbeat/refs/heads/main/cloudbeat.yml
        sleep 1

        cloudbeat > /dev/null 2>&1 &
        sleep 60
        grep -E '"name":"cloudbeat"|\"version\":\"${{package.version}}\"' logs/cloudbeat-*
