package:
  name: nvidia-libcusparse-12.0
  version: 12.0.1.140
  epoch: 2
  description: CUDA cuSPARSE
  copyright:
    - license: PROPRIETARY
  options:
    no-depends: true
  dependencies:
    provides:
      - nvidia-libcusparse=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcusparse/linux-sbsa/libcusparse-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "f0df2c3d36b4529d84f8d447c7640a988f4c52db965b4582abfc282c90173937"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcusparse/linux-x86_64/libcusparse-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "e6042e6e8c9f075e6f23a172473a384858dd8d0a1e97950763f96eec329e168b"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    test:
      pipeline:
        - uses: test/pkgconf

test:
  pipeline:
    - name: Verify installation and license
      runs: |
        test -d /usr/local/cuda-${{vars.cuda-version}}
        test -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
        test -d /usr/local/cuda-${{vars.cuda-version}}/lib64
    - uses: test/tw/ldd-check

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false
