package:
  name: nvidia-cuda-cupti-12.9
  version: "12.9.79"
  epoch: 3
  description: CUPTI
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-cuda-cupti=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cupti/linux-sbsa/cuda_cupti-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "84f8657375c23a425b2d107c3cde1ce75777bff9798b744b78e146fdc02d2de0"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cupti/linux-x86_64/cuda_cupti-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "f779a24e8f0177b4ce45cbf118cb470139fb5107858df96689d0a0aa01f0fba1"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    test:
      pipeline:
        - uses: test/tw/devpackage

update:
  enabled: false

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-cuda-cupti
        real-pkg-name: ${{package.name}}
