package:
  name: nvidia-cuda-gdb-11.8
  version: 11.8.86
  epoch: 1
  description: CUDA GDB
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-cuda-gdb=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_gdb/linux-sbsa/cuda_gdb-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "acca29e2e8d341d058bb4cad76ec8c565fe15f39205aba72f5e92d360e49a360"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_gdb/linux-x86_64/cuda_gdb-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "15252a58df4c2b09dfd3c4bf91c3aebdb2bbb84a61573d92690076ee5066bdff"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv share ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

subpackages:
  - name: ${{package.name}}-extras
    description: ${{package.name}} extras
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/local/cuda-${{vars.cuda-version}}/
          mv extras ${{targets.contextdir}}/usr/local/cuda-${{vars.cuda-version}}/

update:
  enabled: false

test:
  pipeline:
    - runs: |
        /usr/local/cuda-${{vars.cuda-version}}/bin/cuda-gdb --version
