package:
  name: nvidia-cuda-cuobjdump-11.8
  version: 11.8.86
  epoch: 3
  description: CUDA's objdump
  copyright:
    - license: LicenseRef-NVIDIA-CUDA-cuobjdump
      license-path: LICENSE
  dependencies:
    provides:
      - nvidia-cuda-cuobjdump=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cuobjdump/linux-sbsa/cuda_cuobjdump-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "a630e95396437d0a8643d0184e95ac10a7c85488eff23955c94d1270dd45af2e"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cuobjdump/linux-x86_64/cuda_cuobjdump-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "28218273db8ffeb3ae4b31bfb4e4d90f0ae3373454c7970703c063dfd0377ba7"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      cp LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

update:
  enabled: false

test:
  pipeline:
    - runs: |-
        /usr/local/cuda-${{vars.cuda-version}}/bin/cuobjdump --version
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-cuda-cuobjdump
        real-pkg-name: ${{package.name}}
