package:
  name: nvidia-cuda-nvdisasm-11.5
  version: 11.5.119
  epoch: 3 # go/extras-rsc/nvidia-cuda-nvdisasm-11.5
  description: CUDA nvdisasm
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-cuda-nvdisasm=${{package.full-version}}
  resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/linux-sbsa/cuda_nvdisasm-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "698ccf414b9a7d823dc8d9818df72cac0a10d618ab143b221bbf321ada96ef08"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/linux-x86_64/cuda_nvdisasm-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "7b5055db4fbc270a49d69dae6320331d16b3d50f828a9b155e7bf2abe138f273"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

update:
  enabled: false

test:
  pipeline:
    - runs: |
        /usr/local/cuda-${{vars.cuda-version}}/bin/nvdisasm --version
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-cuda-nvdisasm
        real-pkg-name: ${{package.name}}
