package:
  name: nvidia-cuda-nvprune-12.6
  version: 12.6.77
  epoch: 2
  description: CUDA nvprune
  copyright:
    - license: LicenseRef-NVIDIA-CUDA-nvprune
      license-path: LICENSE
  dependencies:
    provides:
      - nvidia-cuda-nvprune=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/linux-sbsa/cuda_nvprune-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "94e0fb67ac1329b22f1e459aad5bdf0188a65c9f03d8635601fc88180d089199"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/linux-x86_64/cuda_nvprune-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "c633bf85f0263ff01fd2c34bd8341e65363faef775b3127dfdac48d74e6d2b8b"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      cp LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

update:
  enabled: false

test:
  pipeline:
    - runs: |
        /usr/local/cuda-${{vars.cuda-version}}/bin/nvprune --version
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-cuda-nvprune
        real-pkg-name: ${{package.name}}
