package:
  name: nvidia-cuda-nvdisasm-12.8
  version: "12.8.90"
  epoch: 3
  description: CUDA nvdisasm
  copyright:
    - license: LicenseRef-NVIDIA-CUDA-nvdisasm
      license-path: LICENSE
  dependencies:
    provides:
      - nvidia-cuda-nvdisasm=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/linux-sbsa/cuda_nvdisasm-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "250ae30e878b0c4c1553e7c7f28c2c763902c807b5f493ebc16e6e10c71213f2"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/linux-x86_64/cuda_nvdisasm-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "8ac63f4079c47707ec958af3a97ceeb18194e16827a2766058f5872f6c3412ae"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      cp LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

update:
  enabled: false

test:
  pipeline:
    - runs: |
        /usr/local/cuda-${{vars.cuda-version}}/bin/nvdisasm --version
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-cuda-nvdisasm
        real-pkg-name: ${{package.name}}
