package:
  name: nvidia-cuda-cupti-13.1
  version: "13.1.115"
  epoch: 0
  description: CUPTI
  copyright:
    - license: PROPRIETARY
  dependencies:
    provides:
      - nvidia-cuda-cupti=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cupti/linux-sbsa/cuda_cupti-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "4d81812c493880b8cff8cb38ac858f5b3769ebec3a94f65148f1936e8282913c"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cupti/linux-x86_64/cuda_cupti-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "c712f0181a63484d843897e39ced6bb32167e79c96181a3ca3fd33626b6a6b11"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
      mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    test:
      pipeline:
        - uses: test/tw/devpackage

update:
  enabled: false

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-cuda-cupti
        real-pkg-name: ${{package.name}}
