package:
  name: nvidia-cuda-profiler-api-12.5
  version: 12.5.39
  epoch: 5
  description: CUDA Profiler API
  copyright:
    - license: LicenseRef-NVIDIA-CUDA-profiler-api
      license-path: LICENSE
  dependencies:
    provides:
      - nvidia-cuda-profiler-api=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/linux-sbsa/cuda_profiler_api-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "09417ae94cbfe41203b825906083a7658e3ba7b4380fb6de7e896fc741d3046c"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/linux-x86_64/cuda_profiler_api-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "4dfefe155e042d1e00a7a8d847a2d886ca5f39a7019dd14ae72b69aaf6e94986"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      cp LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

test:
  pipeline:
    - name: Verify license exists
      runs: |
        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE ]; then
          echo "License file not found!"
          exit 1
        fi
    - name: Verify header files exist
      runs: |
        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/include/cudaProfiler.h ]; then
          echo "cudaProfiler.h header file not found!"
          exit 1
        fi
        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/include/cuda_profiler_api.h ]; then
          echo "cuda_profiler_api.h header file not found!"
          exit 1
        fi
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-cuda-profiler-api
        real-pkg-name: ${{package.name}}

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false
