package:
  name: nvidia-libcusparse-12.1
  version: 12.1.0.106
  epoch: 6 # go/extras-rsc/nvidia-libcusparse-12.1
  description: CUDA cuSPARSE
  copyright:
    - license: LicenseRef-NVIDIA-CUDA-libcusparse
      license-path: LICENSE
  options:
    no-depends: true
  dependencies:
    provides:
      - nvidia-libcusparse=${{package.full-version}}
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}
      - nvidia-libnvjitlink-${{vars.cuda-version}}
  resources:
    cpu: "2"
    memory: 5Gi

environment:
  contents:
    packages:
      - busybox

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcusparse/linux-sbsa/libcusparse-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "1cede312d23dd19225cac1124363835127a08d9641f7e2a330056b7c35190703"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/libcusparse/linux-x86_64/libcusparse-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "ae1f604d6aa753b156e3072519a29938b74b37b727c7bd78fab73add78f83907"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-12.1/
      mv include ${{targets.destdir}}/usr/local/cuda-12.1/
      mv lib ${{targets.destdir}}/usr/local/cuda-12.1/lib64
      cp LICENSE ${{targets.destdir}}/usr/local/cuda-12.1/${{package.name}}.LICENSE

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/pkgconfig/
      mv pkg-config/* ${{targets.destdir}}/usr/share/pkgconfig/
      sed -i 's|targets/.*-linux/||g' ${{targets.destdir}}/usr/share/pkgconfig/*

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - nvidia-libcusparse-12.1
    test:
      pipeline:
        - uses: test/pkgconf

test:
  pipeline:
    - name: Verify installation and license
      runs: |
        test -d /usr/local/cuda-${{vars.cuda-version}}
        test -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
        test -d /usr/local/cuda-${{vars.cuda-version}}/lib64
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: nvidia-libcusparse
        real-pkg-name: ${{package.name}}

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false

var-transforms:
  - from: ${{package.name}}
    match: .*-(\d+\.\d+).*
    replace: $1
    to: cuda-version
