package:
  name: nvidia-cuda-nvcc-12.4
  version: 12.4.131
  epoch: 14
  description: CUDA NVCC
  copyright:
    - license: LicenseRef-NVIDIA-CUDA-nvcc
      license-path: LICENSE
  dependencies:
    # We need to replace math-vector.h from glibc-dev
    # as we need to guard vector types on arm64
    replaces:
      - glibc-dev
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox
      - glibc-dev

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

vars:
  gcc-latest-major-version: 13

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-sbsa/cuda_nvcc-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "83f130dab0325e12b90fdf1279c0cbbd88acf638ef0a7e0cad72d50855a4f44a"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/linux-x86_64/cuda_nvcc-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "7ffba1ada0e4b8c17e451ac7a60d386aa2642ecd08d71202a0b100c98bd74681"
          timeout: 30

  # Without this patch nvcc will not work with glibc 2.41 an newer, as their
  # recently added C23 math functions conflict with CUDA header definitions.
  # glibc 2.42 introduced the same problem with yet another math function.
  - uses: patch
    with:
      patches: math_functions_glibc_2.41.patch math_functions_glibc_2.42.patch

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv include ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
      cp LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv nvvm ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/

  - if: ${{build.arch}} == "aarch64"
    runs: |
      install -Dm755 /usr/include/bits/math-vector.h ${{targets.contextdir}}/usr/include/bits/math-vector.h

      # Fixes: https://github.com/chainguard-dev/internal-dev/issues/21940
      #
      # Packages FTBFS because NVCC disables Neon on ARM64, but math-vector.h will
      # include the arm_neon header anyway. A fix for this has been submitted to upstream
      # glibc at:
      #
      #  https://sourceware.org/pipermail/libc-alpha/2023-September/151770.html
      #
      # Unfortunately, the patch wasn't accepted as is, because the glibc maintainers
      # consider this to be a problem with the C parser. It's messy, but for now this
      # is the best we can do.
      #
      # This "sed" basically implements the solution discussed at:
      #
      #  https://github.com/NixOS/nixpkgs/pull/264599#issuecomment-1790820506
      sed -i \
        -e 's@^#if __GNUC_PREREQ(9, 0)$@#if __GNUC_PREREQ(9, 0) \&\& !defined(__CUDACC__)@' \
        -e 's@^#elif __glibc_clang_prereq(8, 0)$@#elif __glibc_clang_prereq(8, 0) \&\& !defined(__CUDACC__)@' \
        -e 's@^#if __GNUC_PREREQ(10, 0) || __glibc_clang_prereq(11, 0)$@#if (__GNUC_PREREQ(10, 0) || __glibc_clang_prereq(11, 0)) \&\& !defined(__CUDACC__)@' \
        ${{targets.contextdir}}/usr/include/bits/math-vector.h

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
      # We must ship the math-vector.h header with the main package as C compilers need
      # glibc headers, and we do not depend on the NVCC dev package everywhere
      - if: ${{build.arch}} == "aarch64"
        runs: |
          mkdir -p ${{targets.destdir}}/usr/include
          mv ${{targets.contextdir}}/usr/include/bits ${{targets.destdir}}/usr/include/
    dependencies:
      runtime:
        - ${{package.name}}=${{package.full-version}}
    test:
      pipeline:
        - uses: test/tw/devpackage

  - name: nvcc-${{vars.cuda-version}}-gcc
    description: metapackage for the latest gcc version supported by ${{package.name}}
    dependencies:
      runtime:
        - ${{package.name}}=${{package.full-version}}
        - gcc-${{vars.gcc-latest-major-version}}
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}-dev=${{package.full-version}}
            - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
      pipeline:
        - runs: |
            nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
            tmpdir="$(mktemp -d)"
            trap "rm -rf $tmpdir" EXIT
            cat > "$tmpdir/gcc-version.cu" << EOF
            #include <iostream>

            int main() {
              std::cout << __GNUC__ << "\n";
            }
            EOF
            gxx_bin="g++-${{vars.gcc-latest-major-version}}"
            # Verify that the latest default gcc is available and works
            "$nvcc" -ccbin "$gxx_bin" \
              "$tmpdir/gcc-version.cu" -o "$tmpdir/gcc-version"
            [ "$("$tmpdir/gcc-version")" = "${{vars.gcc-latest-major-version}}" ]
            # Attempt to verify that we build w/ the system gcc by default
            # (which may fail if unsupported, that's OK)
            rm -rf "$tmpdir"
            test -x $(command -v g++)
            tmpdir="$(mktemp -d)"
            trap "rm -rf $tmpdir" EXIT
            "$nvcc" -allow-unsupported-compiler \
              "$tmpdir/gcc-version.cu" -o "$tmpdir/gcc-version" || exit 0
            [ "$("$tmpdir/gcc-version")" = "$(g++ -dumpversion)" ]

  - name: nvcc-${{vars.cuda-version}}-gcc-default
    description: metapackage for the latest gcc version supported by ${{package.name}} as the system default
    dependencies:
      runtime:
        - gcc-${{vars.gcc-latest-major-version}}-default
        - nvcc-${{vars.cuda-version}}-gcc=${{package.full-version}}
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}-dev=${{package.full-version}}
            - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
      pipeline:
        - runs: |
            nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
            tmpdir="$(mktemp -d)"
            trap "rm -rf $tmpdir" EXIT
            cat > "$tmpdir/gcc-version.cu" << EOF
            #include <iostream>

            int main() {
              std::cout << __GNUC__ << "\n";
            }
            EOF
            "$nvcc" "$tmpdir/gcc-version.cu" -o "$tmpdir/gcc-version"
            [ "$("$tmpdir/gcc-version")" = "${{vars.gcc-latest-major-version}}" ]

  - name: nvcc-${{vars.cuda-version}}-gcc-wrapper
    description: ${{package.name}} configured to use latest compatible gcc
    dependencies:
      runtime:
        - ${{package.name}}=${{package.full-version}}
        - nvcc-${{vars.cuda-version}}-gcc=${{package.full-version}}
    pipeline:
      - runs: |
          cuda_home="/usr/local/cuda-${{vars.cuda-version}}"
          mkdir -p "${{targets.contextdir}}$cuda_home/bin"
          for cmd in gcc g++; do
            wrapper="${{targets.contextdir}}$cuda_home/bin/$cmd"
            cat > "$wrapper" << 'EOF'
          #!/bin/sh
          gcc_bin="/usr/local/bin/${0##*/}-${{vars.gcc-latest-major-version}}"
          exec ${gcc_bin} "$@"
          EOF
            chmod +x "$wrapper"
          done
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}-dev=${{package.full-version}}
            - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
      pipeline:
        - runs: |
            cuda_home="/usr/local/cuda-${{vars.cuda-version}}"
            export PATH="$cuda_home/bin:$PATH"
            nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
            tmpdir="$(mktemp -d)"
            trap "rm -rf $tmpdir" EXIT
            cd "$tmpdir"
            cat > "$tmpdir/gcc-version.cu" << EOF
            #include <iostream>

            int main() {
              std::cout << __GNUC__ << "\n";
            }
            EOF
            "$nvcc" "$tmpdir/gcc-version.cu" -o "$tmpdir/gcc-version"
            [ "$("$tmpdir/gcc-version")" = "${{vars.gcc-latest-major-version}}" ]

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-dev=${{package.full-version}}
        # Used to check compat with latest GCC version
        - gcc
        # See comment block in nvcc-${{vars.cuda-version}}-gcc
        - gcc-${{vars.gcc-latest-major-version}}
        - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
  pipeline:
    - uses: test/tw/ldd-check
    - name: Test .c files can be compiled
      runs: |
        gcc_bin="gcc-${{vars.gcc-latest-major-version}}"
        nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
        nvcc_cmd="$nvcc -ccbin $gcc_bin"
        tmpdir="$(mktemp -d)"
        trap "rm -rf $tmpdir" EXIT
        cat <<EOF > "$tmpdir/test-c.c"
        #include <math.h>
        int main() {
          return 0;
        }
        EOF
        $nvcc_cmd -o "$tmpdir/test-c" "$tmpdir/test-c.c"
        "$tmpdir/test-c"
    - name: Test .cu files can be compiled
      runs: |
        gcc_bin="gcc-${{vars.gcc-latest-major-version}}"
        nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
        nvcc_cmd="$nvcc -ccbin $gcc_bin"
        tmpdir="$(mktemp -d)"
        trap "rm -rf $tmpdir" EXIT
        cat <<EOF > "$tmpdir/test-cu.cu"
        #include <math.h>
        int main() {
          return 0;
        }
        EOF
        $nvcc_cmd -o "$tmpdir/test-cu" "$tmpdir/test-cu.cu"
        "$tmpdir/test-cu"
    - name: Test our gcc latest version configuration
      runs: |
        next_gcc_ver="$((${{vars.gcc-latest-major-version}} + 1))"
        # There's currently no gcc-$ver command for the latest gcc
        if [ "$(gcc -dumpversion)" = "$next_gcc_ver" ]; then
          next_gcc_bin="gcc"
        elif apk add "gcc-${next_gcc_ver}"; then
          next_gcc_bin="gcc-${next_gcc_ver}"
        else
          # looks like no newer gcc is available
          exit 0
        fi
        tmpdir="$(mktemp -d)"
        trap "rm -rf $tmpdir" EXIT
        cat <<EOF > "$tmpdir/test-cu.cu"
        #include <math.h>
        int main() {
          return 0;
        }
        EOF
        nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
        nvcc_cmd="$nvcc -ccbin $next_gcc_bin -o /dev/null $tmpdir/test-cu.cu"
        log_file="$tmpdir/log"
        if ! $nvcc_cmd > "$log_file" 2>&1 && \
          grep "unsupported GNU version!" "$log_file"; then
          exit 0
        fi
        echo "ERROR: config says the latest supported gcc is ${{vars.gcc-latest-major-version}}" 1>&2
        echo "ERROR: expected using gcc-${next_gcc_ver} to fail with an unsupported compiler error" 1>&2
        cat "$log_file"
        exit 1
