package:
  name: nvidia-cuda-compat-12.5
  version: 555.42.06
  epoch: 3
  description: CUDA ${{vars.cuda-version}} forward compatibility libraries
  copyright:
    - license: LicenseRef-NVIDIA-CUDA-compat
      license-path: LICENSE
  dependencies:
    runtime:
      - nvidia-cuda-ld-config-${{vars.cuda-version}}

environment:
  contents:
    packages:
      - busybox
      - crane

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version
  - from: ${{package.name}}
    match: '.*-(\d+)\.(\d+).*'
    replace: '$1-$2'
    to: cuda-version-deb

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          # SBSA = ARM Server Base System Architecture (now called SystemReady)
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/nvidia_driver/linux-sbsa/nvidia_driver-linux-sbsa-${{package.version}}-archive.tar.xz"
          expected-sha256: "a764c03c9be66fb35144ec23aafa7cf73f9d392fced38db982c32ac53f997a7d"
          timeout: 30
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/nvidia_driver/linux-x86_64/nvidia_driver-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "944a7b3c30265f440fe8d2d2579fca82a2bd01431d4ad3ab43f9a03725a0c447"
          timeout: 30

  - working-directory: lib
    runs: |
      set -oue pipefail

      # Directory containing compat libs
      compatdir="usr/local/cuda-${{vars.cuda-version}}/compat"

      # Use CUDA runtime image for the latest version of Ubuntu
      # And use Docker instead of NGC as images appear to be published here first
      cuda_tag=$(crane ls --platform linux/${{build.goarch}} --omit-digest-tags nvidia/cuda | \
                 grep "^${{vars.cuda-version}}.*runtime-ubuntu" | \
                 sort | tail -n1)

      # Extract compat library basenames from given tag. Filter out path, soversion, and dupes
      compat_libs=$(crane export --platform linux/${{build.goarch}} nvidia/cuda:$cuda_tag - | \
                    tar tf - $compatdir | sed "s|^$compatdir/||; s|^$compatdir$||" | \
                    sed "s/\.so.*//" | sort -u)

      # Install compat libraries
      mkdir -p ${{targets.contextdir}}/$compatdir
      for lib in $compat_libs; do
        # pkcs11 depends on libcrypto 1.1 which we do not provide or support
        if [ "${lib}" = "libnvidia-pkcs11" ]; then
          continue
        fi
        mv ${lib}.so.* ${{targets.contextdir}}/$compatdir/
      done

      # Link libraries
      for so in ${{targets.contextdir}}/$compatdir/*.so.*.*; do
        ldconfig -l "$so"
      done

update:
  exclude-reason: "TODO: implement automation to track updates upstream"
  enabled: false

test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        # Sanity check, we should at least have libcuda
        compatdir="/usr/local/cuda-${{vars.cuda-version}}/compat"
        stat "$compatdir/libcuda.so.${{package.version}}"
        echo "$compatdir" > /etc/ld.so.conf.d/${{context.name}}.conf
        ldconfig -v -N | grep "libcuda.so.1 -> libcuda.so.${{package.version}}"
