package:
  name: nvidia-cuda-memcheck-11.8
  version: 11.8.86
  epoch: 2
  description: CUDA Memcheck
  target-architecture:
    - x86_64
  copyright:
    - license: LicenseRef-NVIDIA-CUDA-memcheck
      license-path: LICENSE

var-transforms:
  - from: ${{package.name}}
    match: '.*-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

environment:
  contents:
    packages:
      - busybox

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: "https://developer.download.nvidia.com/compute/cuda/redist/cuda_memcheck/linux-x86_64/cuda_memcheck-linux-x86_64-${{package.version}}-archive.tar.xz"
          expected-sha256: "539ce6b3cf03593f72f7830217145c87f94246b1c8c056fde2da82234aba2a3e"
          timeout: 30

  # Setup version symlinks
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      mv bin ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/
      cp LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE

update:
  # No release-monitoring support for the multi-arch "enterprise" driver, only
  # for x86-only consumer release train.
  enabled: false
