package:
  name: packer
  version: "1.15.0"
  epoch: 2 # GHSA-q9hv-hpm4-hj6x
  copyright:
    - license: BUSL-1.1
  dependencies:
    provides:
      # REMOVE_POST_USRMERGE - https://github.com/orgs/wolfi-dev/discussions/40270
      - ${{package.name}}-compat=${{package.full-version}}
    runtime:
      - merged-bin
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/packer
      tag: v${{package.version}}
      expected-commit: 87a51e9ad8bc906dc391ac9b7345b8dec7d0e9bc

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/crypto@v0.45.0
      modroot: packer_test/common/plugin_tester

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.28.0
        github.com/go-git/go-git/v5@v5.16.5
        github.com/cloudflare/circl@v1.6.3

  - uses: go/build
    with:
      packages: .
      output: packer
      ldflags: -X github.com/packer/version.GitCommit=$(git rev-parse HEAD)

update:
  enabled: true
  github:
    identifier: hashicorp/packer
    strip-prefix: v

test:
  pipeline:
    - name: verison check
      runs: |
        packer version
    - name: installing, validating and formatting
      runs: |
        cat << 'EOF' > docker-wolfi.pkr.hcl
        packer {
          required_plugins {
            docker = {
              version = ">= 1.0.8"
              source = "github.com/hashicorp/docker"
            }
          }
        }

        source "docker" "wolfi" {
          image  = "cgr.dev/chainguard/wolfi-base:latest"
          commit = true
        }

        build {
          name    = "test-packer"
          sources = [
            "source.docker.wolfi"
          ]
        }
        EOF
        packer init .
        packer validate .
        packer fmt .
        # not invoking packer build given we don't have docker available in test environment.
    - uses: test/virtualpackage
      with:
        virtual-pkg-name: ${{package.name}}-compat
        real-pkg-name: ${{package.name}}
