package:
  name: sox-ng
  version: "14.7.0.5"
  epoch: 0
  description: sox_ng is another Swiss Army Knife of sound processing utilities
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - libtool
      - opus-dev
      - pkgconf-dev

# even though the version they released this time is X.Y.Z.W, their versioning scheme is still X.Y.Z when --version is called
var-transforms:
  - from: ${{package.version}}
    match: '^(\d+\.\d+\.\d+).*$'
    replace: '$1'
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://codeberg.org/sox_ng/sox_ng.git
      tag: sox_ng-${{package.version}}
      expected-commit: ea03e31761333a99cb47ddc0c8941c8d44dcfd50

  - uses: autoconf/configure
    with:
      opts: |
        --enable-replace \
        --with-distro="Wolfi" \
        --with-ffmpeg

  - uses: autoconf/make
    with:
      opts: all README

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - "-rc"
    - '\+git\d{8}'
  git:
    strip-prefix: sox_ng-

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: ${{package.name}} manpages
    test:
      pipeline:
        - uses: test/docs

  - name: ${{package.name}}-static
    description: ${{package.name}} static libraries
    pipeline:
      - uses: split/static
    test:
      pipeline:
        - uses: test/emptypackage

test:
  environment:
    contents:
      packages:
        - ffmpeg
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: sox_ng sox play_ng play rec rec_ng
    - uses: test/tw/ver-check
      with:
        bins: sox_ng sox play_ng play
        version: ${{vars.mangled-package-version}}
    - runs: |
        # `play` and `rec` are omited here since this would require functional ALSA inside the runner
        # Which can be an issue due to multiple runners (QEMU/Docker/Bubblewrap) having different support
        # around these low-level aspects of testing
        ffmpeg -f lavfi -i "sine=f=1000:d=2" original.wav

        sox -v 0.9 original.wav faded_out.wav fade t 0 5
        soxi ./faded_out.wav > out.txt
        grep -F -e "44100" out.txt
        grep -F -e "16-bit" out.txt
        grep -F -e "706k" out.txt
