package:
  name: vgpu-util
  version: "25.01.21"
  epoch: 10 # CVE-2025-61732
  description: NVIDIA vGPU util for gpu-driver-container
  copyright:
    - license: PROPRIETARY
  resources:
    cpu: "2"
    memory: 1Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - make
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NVIDIA/gpu-driver-container
      tag: ${{package.version}}
      expected-commit: fe65aa7c08d1295134607be5cb46c63988da380a

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      cd vgpu/src || exit
      go build -o vgpu-util
      mv vgpu-util ${{targets.destdir}}/usr/bin

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    # https://github.com/NVIDIA/gpu-driver-container/blob/747637e2427c05534306a505b25bb6d7291abd56/ubuntu22.04/Dockerfile#L76
    description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/vgpu-util ${{targets.subpkgdir}}/usr/local/bin
    test:
      pipeline:
        - runs: |
            readlink -v /usr/local/bin/vgpu-util

update:
  enabled: true
  github:
    identifier: NVIDIA/gpu-driver-container
    use-tag: true

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
  pipeline:
    - runs: |
        # It should return NUM_OF_VGPU_DEVICES=0
        vgpu-util count | grep 0
