// Code generated by jsonenums -type=ID; DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
)

var (
	_IDNameToValue = map[string]ID{
		"UnidentifiedMetric": UnidentifiedMetric,
		"SSHDStartTime":      SSHDStartTime,
	}

	_IDValueToName = map[ID]string{
		UnidentifiedMetric: "UnidentifiedMetric",
		SSHDStartTime:      "SSHDStartTime",
	}
)

func init() {
	var v ID
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_IDNameToValue = map[string]ID{
			interface{}(UnidentifiedMetric).(fmt.Stringer).String(): UnidentifiedMetric,
			interface{}(SSHDStartTime).(fmt.Stringer).String():      SSHDStartTime,
		}
	}
}

// MarshalJSON is generated so ID satisfies json.Marshaler.
func (r ID) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _IDValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid ID: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so ID satisfies json.Unmarshaler.
func (r *ID) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ID should be a string, got %s", data)
	}
	v, ok := _IDNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid ID %q", s)
	}
	*r = v
	return nil
}
