// Code generated by "stringer -type=ID"; DO NOT EDIT.

package metrics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnidentifiedMetric-0]
	_ = x[SSHDStartTime-1]
}

const _ID_name = "UnidentifiedMetricSSHDStartTime"

var _ID_index = [...]uint8{0, 18, 31}

func (i ID) String() string {
	if i < 0 || i >= ID(len(_ID_index)-1) {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[i]:_ID_index[i+1]]
}
