#!/bin/sh
# shellcheck disable=SC2162,SC3043
fail() { for m in "$@"; do echo "FATAL:" "$m"; done 1>&2; exit 1; }

PATH=$PATH:/bin:/sbin
dev="/dev/disk/by-id/google-home"

if [ ! -b "$dev" ] ; then
  fail "'home' disk ($dev) not found"
fi

if grep ' /home ' /proc/mounts ; then
  echo "/home already mounted"
  exit 0
fi

if mount "$dev" /home -t xfs; then
  echo "mounted $dev to /home as xfs"
  exit 0;
fi
rc=$?

size=4M
zeros="bb9f8df61474d25e71fa00722318cd387396ca1736605e1248821cc0de3d3af8"
found=$(dd if="$dev" bs="$size" count=1 2>/dev/null | sha256sum)
found=${found%% *}
if [ "$found" != "$zeros" ]; then
  fail "Error $rc with 'mount $dev /home -t xfs'" \
    "It contained non-zero data in the first $size bytes" \
    "so it will not be re-formatted.  To force reformat run:" \
    "  sudo dd if=/dev/zero of=$dev bs=$size count=1"
fi

echo "$dev looked empty (had $size of zeros). Formatting it with xfs."
mkfs.xfs -Lhome "$dev" ||
  fail "Error $rc creating xfs filesystem on $dev with:" \
    " mkfs.xfs -Lhome $dev"

mount "$dev" /home -t xfs ||
  fail "Error $? mounting $dev after mkfs.xfs"

echo "mounted $dev to /home as xfs after formatting"
