#!/bin/sh
# shellcheck disable=SC2162,SC3043

PATH=$PATH:/bin:/sbin

if [ ! -b /dev/disk/by-id/google-home ] ; then
  echo "'home' disk not found"
  exit 1
fi

if grep ' /home ' /proc/mounts ; then
  echo "/home already mounted"
  exit 0
fi

mount /dev/disk/by-id/google-home /home -t xfs
