#!/usr/bin/env bash
# shellcheck disable=SC2015,SC2039,SC2166,SC3043

source "$(dirname -- "${BASH_SOURCE[0]}")/lib.sh"

VERBOSITY=0
TEMP_D=""
TOP_D=$(cd "${0%/*}/.." && pwd)
WAIT_SSH_TIMEOUT=${WAIT_SSH_TIMEOUT:-5m}
WAIT_CONSOLE_TIMEOUT=${WAIT_CONSOLE_TIMEOUT:-5m}
WAIT_TEST_TIMEOUT=${WAIT_TEST_TIMEOUT:-10m}
# shellcheck disable=SC2034
METD="/tmp/chainguard-vmtest-metrics"
METRIC_TAGS="helper-script:test-wolfi-vm${METRIC_TAGS:+,${METRIC_TAGS}}"

Usage() {
    cat <<EOF
Usage: ${0##*/} [ options ] cloud out-dir

   cloud is one of 'aws', 'azure', 'gcp', 'qemu'

   options:
      -h|--help               show this help text
      -v|--verbose            increase verbosity
         --test-arch ARCH     install deps needed for testing ARCH
                              [x86_64, aarch64, ALL] - default ALL
         --wolfi-vm DIR       where is the wolfi-vm top level dir
                              [required] used for finding output and other things.
EOF
}

bad_Usage() { Usage 1>&2; [ $# -eq 0 ] || stderr "$@"; return 1; }
cleanup() {
    [ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
}

source "$TOP_D/helpers/test-wolfi-vm-aws"
source "$TOP_D/helpers/test-wolfi-vm-azure"
source "$TOP_D/helpers/test-wolfi-vm-gcp"
source "$TOP_D/helpers/test-wolfi-vm-qemu"

main() {
    local short_opts="hv"
    local long_opts="help,test-arch:,wolfi-vm:,verbose"
    local getopt_out=""
    getopt_out=$(getopt --name "${0##*/}" \
        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { bad_Usage; return; }

    local cur="" next="" testarches="" arch="" outd="" cloud="" wolfivmd=""

    while [ $# -ne 0 ]; do
        { cur="$1"; next="$2"; }
        case "$cur" in
            -h|--help) Usage ; exit 0;;
               --wolfi-vm) wolfivmd=$next; shift;;
               --test-arch) testarches=$next; shift;;
            -v|--verbose) VERBOSITY=$((VERBOSITY+1));;
            --) shift; break;;
        esac
        shift;
    done

    [ $# -ge 2 ] || { bad_Usage "got $# args [$*], expected min. 2"; return 1; }
    cloud="$1"
    outd="$2"
    shift 2

    # shellcheck disable=SC2034  # (used by log() in lib.sh)
    LOG="$outd/test-wolfi-vm.log"

    [ -n "$wolfivmd" ] || { bad_Usage "--wolfi-vm is required"; return 1; }
    [ -d "$wolfivmd" ] || { stderr "--wolfi-vm '$wolfivmd' is not a dir"; return 1; }

    METRIC_TAGS="cloud:$cloud,wolfi-vm-commit:$(cd "$wolfivmd" && git rev-parse HEAD),vms-test-commit:$(git rev-parse HEAD),$METRIC_TAGS"
    if [ "$testarches" = "" -o "$testarches" = "ALL" ]; then
        testarches="x86_64 aarch64"
    fi

    for arch in $testarches; do
        case "$arch" in
            x86_64|aarch64) continue;;
            *) fail "unknown arch $arch";;
        esac
    done

    [ -d "$outd" ] || mkdir -p "$outd" ||
        fail "could not create $outd"

    #shellcheck disable=SC2086
    case "$cloud" in
        aws)  test_aws "$wolfivmd" "$outd" "$@";;
        qemu) test_qemu_arches  "$wolfivmd" "$outd" $testarches;;
        azure) test_azure "$wolfivmd" "$outd" "$@";;
        gcp)   test_gcp "$wolfivmd" "$outd" "$@";;
        *)
           echo "Testing for cloud=$cloud with wolfi-vm dir at $wolfivmd"
           echo "Does not do anything just yet"
           ;;
    esac
}

case "$1" in
    _testqemu)
        shift
        test_qemu "$@"
        exit;;
esac
main "$@"
# vi: ts=4 expandtab
