#!/usr/bin/env bash
# shellcheck disable=SC2015
# To be sourced by test-wolfi-vm

bad_qemu_usage() { qemu_usage 1>&2; [ $# -eq 0 ] || stderr "$@"; return 1; }

qemu_usage() {
    cat <<EOF
Usage: ${0##*/} [ options ] qemu out-dir

    qemu options:
      (none)

    environment variables:
      QEMU_VMS              space-separated list of VM images to test

EOF
}

test_qemu() {
    local wolfivmd="$1" outd="$2" arch="" rund="" key="" vmname
    local runner="${TOP_D}/runner/qemu"
    shift 2
    if [ -z "$LOG" ]; then
        LOG="$outd/test-wolfi-vm.log"
    fi
    # archvms are arch/vmname.
    # expects that wolfivmd/output/<arch>/<vmname> contains the build output
    local arch_vms=( )
    arch_vms=( "$@" )

    TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") || return

    rund="$TEMP_D/run"
    mkdir "$rund" || return
    trap cleanup EXIT

    known_hosts="$rund/known_hosts"
    key="$rund/id_rsa"
    rq ssh-keygen -t rsa -N '' -f "$key" ||
        { stderr "failed creating ssh key"; return 1; }

    local vmoutd="" vmname="" vfails="" fails="" testconfig="" vmconfigs="" user="" num_vmconfigs=""
    local archvm=""
    for archvm in "${arch_vms[@]}"; do
        arch="${archvm%%/*}"
        vmname="${archvm#*/}"
        vmoutd="$wolfivmd/output/$arch/$vmname"
        testconfig="$wolfivmd/configs/$vmname/test.yaml"
        if ! strContains " ${QEMU_VMS:-${vmname}} " " $vmname "; then
            continue
        fi
        vfails=""
        [ -f "$testconfig" ] || {
            vfails="$arch/$vmname/missing-test-config"
            log "finished $arch-$vmname FAIL - $vfails"
            fails="${fails+$fails }$vfails"
            continue
        }
        yqassert "1" -re 'explode(.) | .version' "$testconfig" || {
            vfails="$arch/$vmname/version-mismatch"
            log "finished $arch-$vmname FAIL - $vfails"
            fails="${fails+$fails }$vfails"
            continue
        }
        yqassert "qemu" -re 'explode(.) | .cloud' "$testconfig" || {
            vfails="$arch/$vmname/cloud-mismatch"
            log "finished $arch-$vmname FAIL - $vfails"
            fails="${fails+$fails }$vfails"
            continue
        }
        # convert to json because bash mangles yaml
        vmconfigs=$(yq -o json -re "explode(.) | .vmconfigs.$arch" "$testconfig") || {
            vfails="$arch/$vmname/read-vmconfigs"
            log "finished $arch-$vmname FAIL - $vfails"
            fails="${fails+$fails }$vfails"
            continue
        }
        user=$(yq -re "explode(.) | .data.vmuser" "$testconfig") || { log "using default user 'linky'"; user="linky"; }
        num_vmconfigs=$(echo "$vmconfigs" | jq 'length') || {
            vfails="$arch/$vmname/malformed-vmconfigs"
            log "finished $arch-$vmname FAIL - $vfails"
            fails="${fails+$fails }$vfails"
            continue
        }

        log "starting $vmname with arch $arch"

        local i="" fwcode="" fwcode_relative="" fwvars="" fwvars_relative="" vmconfig_name="" named_tests="" test_groups="" vm_testd="" voutd="" runnerpid="" group="" tname="" vm_testd="" vmd="" launcher="" runnerpid=""
        for i in $(seq 0 $((num_vmconfigs-1))); do

            fwcode_relative=$(echo "$vmconfigs" | jq -re ".[$i].fwcode") || {
                vfails="$vfails $arch/$vmname/no-fwcode-defined"
                continue
            }
            fwcode=$(dirname "$testconfig")/"$fwcode_relative"
            [ -f "$fwcode" ] || {
                vfails="$vfails $arch/$vmname/missing-fwcode-file"
                continue
            }
            fwvars_relative=$(echo "$vmconfigs" | jq -re ".[$i].fwvars") || {
                vfails="$vfails $arch/$vmname/no-fwvars-defined"
                continue
            }
            fwvars="$vmoutd/$fwvars_relative"
            [ -f "$fwvars" ] || {
                vfails="$vfails $arch/$vmname/missing-fwvars-file"
                continue
            }
            vmconfig_name=$(echo "$vmconfigs" | jq -re ".[$i].name" 2>/dev/null) || vmconfig_name=$(basename "$fwcode")
            named_tests=$(echo "$vmconfigs" | jq -re ".[$i].tests[].name | select (. != null)" 2>/dev/null) || named_tests=""
            test_groups=$(echo "$vmconfigs" | jq -re ".[$i].tests[].group | select (. != null)" 2>/dev/null) || test_groups=""
            for group in $test_groups; do
                for tname in "$TOP_D/pkg/test/$group/"*; do
                    named_tests="$named_tests $group/$(basename "$tname")"
                done
            done
            if [ -z "$named_tests" ]; then
                vfails="$vfails $arch/$vmname/$vmconfig_name/no-tests-defined"
                continue
            fi

            vm_testd="$TEMP_D/$arch/$vmname/$vmconfig_name"
            rq mkdir -p "$vm_testd" || {
                stderr "failed creating vm test dir $vm_testd"
                return 1
            }
            vmd="$rund/$arch/$vmname/$vmconfig_name"
            rq mkdir -p "$vmd" || {
                stderr "failed creating vmdir $vmd"
                return 1
            }
            voutd="$outd/$arch/$vmname/$vmconfig_name"
            rq mkdir -p "$voutd" || {
                stderr "failed creating vm out dir $voutd"
                return 1
            }

            vr "$runner" create --fwcode="$fwcode" --fwvars="$fwvars" \
                "$vmd" "$vmoutd/disk.raw" || {
                    stderr "failed $runner create";
                    vfails="$arch/$vmname/$vmconfig_name/create"
                    continue
            }

            if launcher=$(echo "$vmconfigs" | jq -re ".[$i].launch"); then
                local test_config_dir=""
                test_config_dir=$(dirname "$testconfig") || {
                    stderr "failed to get dir of $testconfig"
                    continue
                }
                launcher="$test_config_dir/$launcher"
            else
                log "launch option is unspecified for $vmconfig_name, using default runner"
                launcher=("$runner" "start")
            fi
            # Start VM
            set -- env RUNNER="$runner" "${launcher[@]}" "--arch=$arch" --public-key="$key.pub" "$vmd"
            log "starting $*"
            "$@" > "$voutd/vm-start.log" 2>&1 &
            runnerpid=$!

            vr "$runner" --timeout="${WAIT_SSH_TIMEOUT}" wait-for-ssh "$vmd" \
                >> "$known_hosts" || {
                stderr "failed runner wait-for-ssh $arch-$vmname-$vmconfig_name"
                vfails="$vfails $arch/$vmname/$vmconfig_name/wait-for-ssh"
                if [ ! -f "$vmd/ttyS0.log" ]; then
                    stderr "[$arch-$vmname-$vmconfig_name] FATAL wait-for-ssh timeout." \
                        "console log missing."
                else
                    sed -e 's,^,> ,' "$vmd/ttyS0.log" 2>&1
                    stderr "[$arch-$vmname-$vmconfig_name] FATAL wait-for-ssh timeout." \
                        "console log above"
                    cp "$vmd/ttyS0.log" "$voutd/console.log" ||
                        stderr "[$arch-$vmname-$vmconfig_name] WARN copying ttyS0.log to outd"
                fi
                kill "$runnerpid"
                continue
            }

            # Run tests
            for tid in $named_tests; do
                case "$tid" in
                    *"/"*)
                        tname="${tid##*/}"
                        tgroup="${tid%%/*}"
                        tname_pretty="$tgroup-$tname"
                        tfile="$TOP_D/test/$arch/$tgroup/$tname"
                        ;;
                    *)
                        tname="$tid"
                        tgroup=""
                        tname_pretty="$tname"
                        location=$(dirname "$testconfig")"/"$(echo "$vmconfigs" | jq -re ".[$i].tests[] | select(.name==\"$tname\").location") || {
                            vfails="$vfails $arch/$vmname/$vmconfig_name/missing-test-location-$tname"
                            continue
                        }
                        goarch=$(goarch "$arch") || {
                            vfails="$vfails $arch/$vmname/$vmconfig_name/invalid-test-arch-$tname"
                            continue
                        }
                        tfile="$vm_testd/$tname"
                        rq env GOOS="linux" GOARCH="$goarch" go test -C "$location" -c -o "$tfile" -tags vmtest || {
                            vfails="$vfails $arch/$vmname/$vmconfig_name/compile-test-$tname"
                            continue
                        }
                        ;;
                esac

                test_emits_metrics "$tfile"
                local emits_metrics=$? metric_args=()
                if [ $emits_metrics -eq 0 ]; then
                    metric_args=("-metric-tags" "arch:$arch,$METRIC_TAGS" )
                fi
                test_user=$(echo "$vmconfigs" | jq -re ".[$i].vmuser" 2>/dev/null) || test_user="$user"
                vrl "$voutd/test-$tname_pretty" "$runner" run-remote --sudo --user "$test_user" \
                    --private-key="$key" --file="$tfile" "$vmd" --known-hosts="$known_hosts" \
                       -- -test.v -test.timeout "$WAIT_TEST_TIMEOUT" "${metric_args[@]}" ||
                       vfails="$vfails $arch/$vmname/test-$tname_pretty"
                if [ $emits_metrics -eq 0 ]; then
                    rqc "$voutd/$tname_pretty-artifacts.json" "$runner" ssh --user "$test_user" --private-key="$key" --known-hosts="$known_hosts" "$vmd" \
                        "if [ -f '$METD/$tname' ]; then cat '$METD/$tname'; fi" ||
                        vfails="$vfails $arch/$vmname/$tname_pretty-artifacts"
                fi
            done

            kill "$runnerpid"
            wait "$runnerpid"

            if [ ! -f "$vmd/ttyS0.log" ]; then
                vfails="$vfails $arch/$vmname/$vmconfig_name/console-log"
                stderr "$vmd/ttyS0.log did not exist"
            elif ! cp "$vmd/ttyS0.log" "$voutd/console.log"; then
                vfails="$vfails $arch/$vmname/$vmconfig_name/console-log"
                stderr "failed copy of $vmd/ttyS0.log"
            fi

            vfails=${vfails# }
            if [ -z "$vfails" ]; then
                log "finished $arch/$vmname/$vmconfig_name PASS"
            else
                log "finished $arch/$vmname/$vmconfig_name FAIL - $vfails"
            fi
        done
        fails="${fails:+$fails }$vfails"
    done
    if [ -z "$fails" ]; then
        log "PASS - no failures"
        return 0
    fi
    log "FAIL - $fails"
    return 1
}

test_qemu_arches() {
    local wolfivmd="$1" outd="$2"
    shift 2
    local arch="" d="" things=""
    things=( )
    for arch in "$@"; do
        for d in "${wolfivmd}/output/$arch"/*; do
            # shellcheck disable=SC2295
            things+=( "$arch/${d##*/$arch/}" )
        done
        :
    done
    if [ "${#things[@]}" = "0" ]; then
        fail "Did not find anything to test in $wolfivmd (arches=$*)"
    fi

    local tmpd="" mkfile="" tab="	" procs=""
    local p=${VM_CONCURRENT_TEST_MAX} jobsnum=""
    if [ -z "$p" ]; then
        procs=$(nproc) || {
            stderr "nproc failed. using 2 for number of procs"
            procs=2
        }
        p=${procs}
    fi
    # p=0 means call make with --jobs= (no limit)
    jobsnum="$p"
    [ "$p" = "0" ] && p="" && jobsnum="unlimited"
    stderr "Testing ${#things[@]} vms in $jobsnum jobs"
    tmpd=$(mktemp -d "${TMPDIR:-/tmp}"/test-qemu.XXXXXX) ||
        fail "failed mktemp -d"
    # shellcheck disable=SC2064
    trap "rm -Rf '$tmpd'" EXIT

    mkfile="$tmpd/test-qemu.mk"
    cat > "$mkfile" <<EOF
SHELL := /bin/bash
.SHELLFLAGS = -o pipefail -ec
.PHONY: ${things[*]}
${things[*]}: %:
${tab}@mkdir -p "$outd/\$*"
${tab}"$0" _testqemu "$wolfivmd" "$outd" "\$*" 2>&1 | tee "$outd/\$*/test-output.log"
EOF

    set -o pipefail
    vr make "--jobs=$p" "--file=$mkfile" "${things[@]}" 2>&1 | tee "$outd/test-output.log"
}
