#!/bin/sh

set -ex

name="sccache-cg-config"
if [ -f "/usr/lib/${name}/gcc-wrapper" ]; then
    echo "ERROR: Already initialized" 2>&1
    exit 1
fi
if [ ! -f "/usr/local/bin/gcc-wrapper" ]; then
    echo "ERROR: /usr/local/bin/gcc-wrapper not found" 2>&1
    exit 1
fi

mkdir -p "/usr/lib/${name}"
mv /usr/local/bin/gcc-wrapper "/usr/lib/${name}"

cat > "/usr/local/bin/gcc-wrapper"<<EOF
#!/bin/sh

set -e

sccache=""
# Don't run sccache under sccache
test -n "\${SCCACHE_START_SERVER}" || sccache="sccache"
exec \${sccache} /usr/lib/${name}/\${0##*/} "\$@"
EOF
chmod +x "/usr/local/bin/gcc-wrapper"

for cmd in /usr/local/bin/*; do
    test -e "${cmd}" || continue
    test -h "${cmd}" || continue
    [ "$(readlink "${cmd}")" = "gcc-wrapper" ] || continue
    ln -s gcc-wrapper "/usr/lib/${name}/${cmd##*/}"
done

for cmd in /usr/local/cuda-*/bin/nvcc; do
    test -e "${cmd}" || continue
    mv "${cmd}" "${cmd}.sccache"
    cat > "${cmd}"<<EOF
#!/bin/sh

set -e

sccache=""
# Don't run sccache under sccache
test -n "\${SCCACHE_START_SERVER}" || sccache="sccache"
exec \${sccache} "\${0}.sccache" "\$@"
EOF
    chmod +x "${cmd}"
done
