archs:
  - amd64
  - arm64
contents:
  build_repositories:
    - https://apk.cgr.dev/chainguard-private
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - https://packages.cgr.dev/extras
  packages:
    - apk-tools
    - azure-configs
    # cni-plugins conflicts because of bridge but I'm hoping I can get
    # away with not having iproute2 for now.
    - azure-vnet-cni
    - bash
    - bash-binsh
    - chainguard-baselayout
    - cloud-init # (Optional) dep for walinuxagent
    # I'm not 100% sure which plugins Azure actually uses
    - cni-plugins-loopback
    - cni-plugins-portmap
    - containerd
    - containerd-service
    - coreutils
    - dbus
    - iproute2
    - kmod
    - kmod-libs
    - kubernetes
    - linux-azure-generic-boot-installed
    - mount
    - net-tools
    - openssh-pam-config # Login with locked account
    - openssh-server
    - openssh-service
    - openssh-sftp-server
    - polkit
    # AKS sets sysctls and busybox does not seem sufficient
    - procps
    - runc
    - shadow
    - sudo-rs
    - systemd-boot
    - systemd-boot-installed
    - systemd-default-network
    - systemd-init
    - systemd-logind-service
    - systemd-repart-rootfs
    - udev
    - umount
    - util-linux-misc
    - walinuxagent # Azure cloud agent
    - wolfi-keys
    - xfsprogs
