accounts:
  groups:
  run-as: "0"
  users:
annotations: {}
archs:
  - amd64
  - arm64
cmd: ""
contents:
  build_repositories:
    - https://apk.cgr.dev/chainguard-private
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - https://packages.cgr.dev/extras
  packages:
    - chainguard-baselayout
    - cloud-ssh-keys-fetcher
    - dbus
    - google-compute-engine-oslogin
    - google-guest-agent
    - google-guest-agent-manager
    - google-guest-config
    - google-osconfig-agent
    - iproute2
    - kmod
    - kmod-libs
    - libselinux
    - libsemanage
    - libsepol
    - linux-boot-configuration
    - linux-boot-installed
    - mount
    - openssh-server
    - openssh-service
    - policycoreutils
    - sudo-rs
    - systemd-boot
    - systemd-boot-installed
    - systemd-default-network
    - systemd-init
    - systemd-logind-service
    - systemd-repart-rootfs
    - udev
    - umount
    - unusrmerge
    - util-linux-misc
    - xfsprogs
entrypoint:
  command: /usr/lib/systemd/systemd
  services: {}
  shell-fragment: ""
  type: ""
environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
include: ""
paths:
stop-signal: ""
vcs-url: ""
volumes:
work-dir: /
