name: Prepare a target Chart

needs:
  packages:
    - bash
    - ripgrep
    - sed

inputs:
  chart-path:
    description: |
      The path to the chart to prepare for packaging

pipeline:
  - name: Fetch tools
    uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      branch: tools
      expected-commit: 443c923ccefdbe7d7b0aab1f18351aa6a97e9e25
      destination: ./iamguarded-tools

  - name: Prepare
    runs: |
      ./iamguarded-tools/hack/prepare.sh ${{inputs.chart-path}}
