metadata_dir = "/tmp/garage-fjall/meta"
data_dir = "/tmp/garage-fjall/data"
db_engine = "fjall"
replication_factor = 1
rpc_bind_addr = "[::]:3921"
rpc_public_addr = "127.0.0.1:3921"
rpc_secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3920"

[admin]
api_bind_addr = "[::]:3923"
