name: Runs tests for ciphers, digests, ssl & tls providers for java fips

# Pull in the specific java version and fips policy
needs:
  packages:
    - bash
    - openjdk-${{inputs.java-version}}
    - bcfips-policy-${{inputs.fips-compliance-version}}-j${{inputs.java-version}}

inputs:
  java-version:
    description: "The java version to use for the test"
    default: "11"
  fips-compliance-version:
    descriptoin: "The version of the fips compliance to test"
    default: "140-2"
  

pipeline:
  - name: Test openjdk algorithm
    runs: |
      cd $(mktemp -d)
      cp /usr/lib/bcfips-policy-${{inputs.fips-compliance-version}}/* .

      _java_home="/usr/lib/jvm/java-${{inputs.java-version}}-openjdk"
      JAVA_HOME="$_java_home" ./test.sh