// Code generated by "enumer -json -output id_generated.go -type=ID"; DO NOT EDIT.

package files

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _IDName = "UnidentifiedFileDmesgJournalCtlB0SystemdAnalyzeSystemdCriticalChainProc1MountinfoNestedQemuConsole"

var _IDIndex = [...]uint8{0, 16, 21, 33, 47, 67, 81, 98}

const _IDLowerName = "unidentifiedfiledmesgjournalctlb0systemdanalyzesystemdcriticalchainproc1mountinfonestedqemuconsole"

func (i ID) String() string {
	if i < 0 || i >= ID(len(_IDIndex)-1) {
		return fmt.Sprintf("ID(%d)", i)
	}
	return _IDName[_IDIndex[i]:_IDIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IDNoOp() {
	var x [1]struct{}
	_ = x[UnidentifiedFile-(0)]
	_ = x[Dmesg-(1)]
	_ = x[JournalCtlB0-(2)]
	_ = x[SystemdAnalyze-(3)]
	_ = x[SystemdCriticalChain-(4)]
	_ = x[Proc1Mountinfo-(5)]
	_ = x[NestedQemuConsole-(6)]
}

var _IDValues = []ID{UnidentifiedFile, Dmesg, JournalCtlB0, SystemdAnalyze, SystemdCriticalChain, Proc1Mountinfo, NestedQemuConsole}

var _IDNameToValueMap = map[string]ID{
	_IDName[0:16]:       UnidentifiedFile,
	_IDLowerName[0:16]:  UnidentifiedFile,
	_IDName[16:21]:      Dmesg,
	_IDLowerName[16:21]: Dmesg,
	_IDName[21:33]:      JournalCtlB0,
	_IDLowerName[21:33]: JournalCtlB0,
	_IDName[33:47]:      SystemdAnalyze,
	_IDLowerName[33:47]: SystemdAnalyze,
	_IDName[47:67]:      SystemdCriticalChain,
	_IDLowerName[47:67]: SystemdCriticalChain,
	_IDName[67:81]:      Proc1Mountinfo,
	_IDLowerName[67:81]: Proc1Mountinfo,
	_IDName[81:98]:      NestedQemuConsole,
	_IDLowerName[81:98]: NestedQemuConsole,
}

var _IDNames = []string{
	_IDName[0:16],
	_IDName[16:21],
	_IDName[21:33],
	_IDName[33:47],
	_IDName[47:67],
	_IDName[67:81],
	_IDName[81:98],
}

// IDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IDString(s string) (ID, error) {
	if val, ok := _IDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ID values", s)
}

// IDValues returns all values of the enum
func IDValues() []ID {
	return _IDValues
}

// IDStrings returns a slice of all String values of the enum
func IDStrings() []string {
	strs := make([]string, len(_IDNames))
	copy(strs, _IDNames)
	return strs
}

// IsAID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ID) IsAID() bool {
	for _, v := range _IDValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ID
func (i ID) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ID
func (i *ID) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ID should be a string, got %s", data)
	}

	var err error
	*i, err = IDString(s)
	return err
}
