version: 1
cloud: qemu
data:
  vmuser: linky
vmconfigs:
  x86_64:
    - fwcode: ../../builder/ovmf-x86_64.fd
      fwvars: uefi-data.fd
      name: "q35"
      tests:
        - group: core
        - group: secureboot
    - fwcode: ../../builder/ovmf-x86_64.fd
      fwvars: uefi-data.empty.fd
      name: "q35-setupmode"
      tests:
        - group: core
        - group: secureboot
  aarch64:
    - fwcode: ../../builder/ovmf-aarch64.fd
      fwvars: uefi-data.fd
      name: "virt"
      tests:
        - group: core
        - group: secureboot
    - fwcode: ../../builder/ovmf-aarch64.fd
      fwvars: uefi-data.empty.fd
      name: "virt-setupmode"
      tests:
        - group: core
        - group: secureboot
