#!/bin/sh
# shellcheck disable=SC2015,SC2166
Usage() {
    idurl="https://github.com/chainguard-images/images-private/.github/workflows/release.yaml@refs/heads/main"
    cat <<EOF
Usage: ${0##*/} attestaion [manifest]

Extract the manifest from an attestation file.
Attestation file is as obtained by:
	cosign verify-attestation \
		--type=https://apko.dev/image-configuration \
		--certificate-oidc-issuer=https://token.actions.githubusercontent.com \
		\"--certificate-identity=$idurl\" \
        cgr.dev/chainguard-private/curl

manifest is a apko build json.
EOF
}
fail() { echo "$@" 1>&2; exit 1; }

[ $# -eq 0 ] && { Usage 1>&2; exit 1; }
[ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit 0; }

infile="$1"
outfile=${2:-"-"}

if [ -f "$infile" -a "$infile" != "-" ]; then
    exec <"$infile" || fail "failed reading $infile"
elif [ "$infile" = "-" ]; then
    :
else
    echo "input file '$infile': not a file"
    exit 1
fi

payload=$(jq -r .payload) && [ -n "$payload" ] || fail "failed extracting payload from $infile"
decoded=$(printf "%s" "$payload" | base64 -d) && [ -n "$decoded" ] ||
    fail "failed base64 decoding payload in $infile"
predicate=$(printf "%s" "$decoded" | jq .predicate) && [ -n "$predicate" ] ||
    fail "failed extracting predicate from decoded payload in $infile"

if [ "$outfile" != "-" ]; then
    exec > "$outfile" || fail "failed writing to outfile '$outfile'"
fi

printf "%s" "$predicate"
