#!/bin/python3
import yaml, argparse
from pathlib import Path
import boto3, time

ROOT_DIR="awspub"
IMAGE_NAME="aws-docker-dev"
#PRODUCT_ID = "prod-twxvqqhdmpwe2"  # your AMI product ID

CHAINGUARD_ACCOUNTS = [
    "607334848609",
    "891377301584",
    "832127465091",
    "979992218380",
    "235494789672",
    "452336408843",
    "394393753540",
    ]

ALLOWED_ACCOUNTS = [
    # Chainguard Accounts
    "607334848609",
    #"394393753540",
    #"891377301584",
    #"832127465091",
    #"979992218380",
    #"235494789672",
    #"297512042063",
    #"782858285006",
    #"452336408843",
    #"235494789672"
    ]

def get_product_code(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    try:
        images = data["awspub"]["images"]
        for image_id, image_data in images.items():
            marketplace = image_data.get("marketplace")
            if not marketplace:
                raise KeyError(f"No 'marketplace' section found for image {image_id}")
            entity_id = marketplace.get("entity_id")
            if not entity_id:
                raise KeyError(f"No 'entity_id' found under 'marketplace' for image {image_id}")
            print(f"Entity ID for image {image_id}: {entity_id}")
            return entity_id
    except KeyError as e:
        raise RuntimeError(f"Error: {e}")

def get_path_for_image(image_name):
    extension = ".yaml"
    root = Path("awspub", "aarch64")
    target_name = f"{image_name}{extension}"

    for file_path in root.rglob(target_name):
        if file_path.is_file():
            return file_path.resolve()

    raise FileNotFoundError(f"YAML file not found for: {image_name}")

def update_marketplace_listing(product_id, wait=True):
    mp = boto3.client("marketplace-catalog", region_name="us-east-1")
    change = {
        "ChangeType": "UpdateTargeting",
        "Entity": {"Type": "AmiProduct@1.0", "Identifier": product_id},
        "DetailsDocument": {
            "PositiveTargeting": {"BuyerAccounts": ALLOWED_ACCOUNTS}
        },
    }

    resp = mp.start_change_set(
        Catalog="AWSMarketplace",
        ChangeSet=[change],
        ChangeSetName="update-allowlist"
    )

    change_set_id = resp["ChangeSetId"]

    # Optionally poll until done
    while wait:
        d = mp.describe_change_set(Catalog="AWSMarketplace", ChangeSetId=change_set_id)
        status = d["Status"]
        if status in ("SUCCEEDED", "FAILED", "CANCELLED"):
            print(status, d.get("FailureCode"), d.get("FailureDescription"))
            break
        time.sleep(10)

path = get_path_for_image(IMAGE_NAME)
product_id = get_product_code(path)
product_id = "prod-twxvqqhdmpwe2"
print(product_id)
update_marketplace_listing(product_id)



"""
def parse_args():
    parser = argparse.ArgumentParser(
        description="Process AMI image and customer details."
    )

    parser.add_argument(
        "--image-name",
        required=True,
        help="Name of the image (e.g., ubuntu-24.04-chainguard)."
    )

    parser.add_argument(
        "--customer-name",
        required=True,
        help="Name of the customer (e.g., AcmeCorp)."
    )

    parser.add_argument(
        "--account",
        required=True,
        help="12-digit AWS account ID associated with the customer."
    )

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    print(f"Image Name: {args.image_name}")
    print(f"Customer Name: {args.customer_name}")
    print(f"Account: {args.account}")
"""
