#!/usr/bin/env bash
# shellcheck disable=SC2015,SC2166,SC3043
#
# Docs:
# - https://learn.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic
# - https://learn.microsoft.com/en-us/azure/virtual-machines/linux/disks-upload-vhd-to-managed-disk-cli
TEMP_D=""
VERBOSITY=1
DEF_RESOURCE_GROUP="chainguard-vms"

Usage() {
    cat <<EOF
Usage: ${0##*/} [--name=name] image

  Publish raw disk image 'image'.

    options:

      -v | --verbose        be more verbose
           --name    NAME   register image under provided name.
                            default is to use the basename of 'image' with
                            extensions removed.
           --arch    ARCH   register image as architecture ARCH
      --resource-group GRP  use resource-group for publishing. [$DEF_RESOURCE_GROUP]


  Publish raw disk image 'image' to azure using 'az' and 'azcopy' cli.
  If image ends in .vhd it is assumed to be in the right format
  (subformat=fixed,force_size).  Raw disk images will be converted
  using 'qemu-img convert'.

EOF
}

cleanup() {
    [ -n "$TEMP_D" ] || return 0
    rm -Rf "$TEMP_D"
}

stderr() { echo "$@" 1>&2; }

assert_cmds() {
    local p="" missing=""
    for p in "$@"; do
        command -v "$p" >/dev/null 2>&1 || missing="${missing} $p"
    done
    [ -z "$missing" ] && return 0
    stderr "missing commands ${missing# }"
    return 1
}

create_vhd() {
    assert_cmds qemu-img || return
    local file="$1" out="$2"
    stderr "creating vhd $out from $file"
    vr convert-to-vhd qemu-img convert -f raw -o subformat=fixed,force_size -O vpc "$file" "$out" ||
        { stderr "failed conversion of $file to vpc in $out"; return 1; }
}

vr() {
    local name="$1" rc="" sstart="$SECONDS"
    shift
    stderr "execute[$name]:" "$@"
    "$@"
    rc=$?
    stderr "finished[$name] rc=$rc in $((SECONDS-$sstart))s"
    return "$rc"
}

main() {
    local short_opts="hv"
    local long_opts="help,arch:,name:,resource-group:,verbose"
    local getopt_out=""
    getopt_out=$(getopt --name "${0##*/}" \
        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { Usage 1>&2; return 1; }

    local name="" out="" arch="" file="" name="" defname=""
    local resource_group="${DEF_RESOURCE_GROUP}"
    while [ $# -ne 0 ]; do
        { cur="$1"; next="$2"; }
        case "$cur" in
            -h|--help) Usage ; exit 0;;
               --arch) arch="$next"; shift;;
               --name) name=$2; shift;;
               --resource-group) resource_group=$2; shift;;
            -v|--verbose) VERBOSITY=$((VERBOSITY+1));;
            --) shift; break;;
        esac
        shift;
    done

    if [ $# -ne 1 ]; then
        Usage 1>&2
        stderr "Got $# args, expected 1"
        return 1
    fi

    assert_cmds az azcopy jq wc || return

    file="$1"
    defname=$(basename "$file")
    defname=${defname%.vhd}

    if [ ! -f "$file" ]; then
        stderr "$file: not a file"
        return 1
    fi

    local archin="" azarch=""
    if [ -z "$archin" ]; then
        arch=$(uname -m)
    fi

    case "$arch" in
        aarch64|arm64) azarch="arm64";;
        x86_64|amd64|x64) azarch="x64";;
        *) stderr "unknown arch $arch"; return 1;;
    esac

    if [ -z "$archin" ]; then
        stderr "arbitrarily decided that $file is arch '$azarch' [use --arch=$azarch]"
    fi

    TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
        { stderr "failed to create tempdir"; return 1; }
    trap cleanup EXIT

    local vhd=""
    case "$file" in
        *.vhd)
            vhd="$file"
            stderr "Assuming $file is a suitably prepared vhd image"
            ;;
        *)
            vhd="${TEMP_D}/$defname.vhd"
            create_vhd "$file" "$vhd" ||
                { stderr "failed creating a vhd image from $file"; return 1; }
           ;;
    esac

    if [ -z "$name" ]; then
        name=$defname
    fi

    local infojs="" disk_size="" sparse_size=""
    infojs=$(qemu-img info --format=vpc --output=json "$vhd")
    sparse_size=$(echo "$infojs" | jq -r '.children[0].info."actual-size"')
        [ -n "$disk_size" ] && [ -n "$sparse_size" ] ||
    disk_size=$(wc -c < "$vhd") || {
        stderr "failed to get size of $vhd with 'wc -c'"
        return 1
    }

    #local gib=$((1024*1024*1024))
    #if [ "$((((disk_size-512)/gib)*gib))" != "$disk_size" ]; then
    #    stderr "disk size (${disk_size} bytes - 512) of vhd $vhd from $file is not even GiB"
    #    exit 1
    #fi
    #out=$(wc -c <"$vhd")
    #echo "out: $out $((out/1024/1024)) MiB"
    #echo "sps: $sparse_size $((sparse_size/1024/1024)) MiB"
    #echo "dis: $disk_size $((disk_size/1024/1024)) MiB"
    stderr "uploading $vhd ($((disk_size/1024/1024))MiB" \
        "sparse=$((sparse_size/1024/1024))MiB) to azure"

    # Create disk
    vr "create disk" az disk create \
        --resource-group="${resource_group}" \
        --name="$name" \
        --os-type=Linux \
        --upload-type=Upload \
        --upload-size-bytes="$disk_size" \
        --sku=standard_lrs \
        --hyper-v-generation=V2 \
        --architecture="$azarch" || {
            stderr "publishing $file failed"
            return 1
        }

    # Enable Write access on disk 86400 (1 day) pulled from docs
    local out="" duration=$((60*60*24)) aurl=""
    out=$(vr enable-disk-write az disk grant-access \
        --resource-group="$resource_group" --name="$name" \
        --access-level=Write --duration-in-seconds="$duration") || {
        stderr "granting access to $name failed"
        return 1
    }

    # Copy image to disk
    # aurl is is a long url like # https://...blob.storage.azure.net/...?sv=...&sig=...
    aurl=$(printf "%s" "$out" | jq -r .accessSAS) && [ -n "$aurl" ] || {
        stderr "failed parsing jq output of az disk grant-access"
        stderr "$out"
        return 1
    }
    stderr "uploading $vhd ($((disk_size/1024/1024))MiB " \
        "sparse=$((sparse_size/1024/1024))MiB) to azure"
    vr "copy-image-to-disk" \
        azcopy copy "$vhd" "$aurl" --blob-type=PageBlob || {
        stderr "Failed copying image to disk"
        return 1
    }

    vr "revoke-access" az disk revoke-access \
        --name="$name" --resource-group="$resource_group" || {
        stderr "failed revoking access to $name"
        return 1
    }

    return 0
}

if [ "$1" = "create-vhd" ]; then
    shift
    TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
        { stderr "failed to create tempdir"; exit 1; }
    create_vhd "$@"
    exit
fi

main "$@"
