#!/usr/bin/python3
import json
import sys

cfgin = sys.argv[1]
output = sys.argv[2]

pkgs = []
if len(sys.argv) > 3:
    pkgs = sys.argv[3:]

with open(cfgin, "rb") as fp:
    cfg = json.loads(fp.read())

cfg['contents']['packages'].extend(pkgs)
cfg['contents']['packages'].sort()

with open(output, "w") as fpw:
    fpw.write(
        json.dumps(cfg, indent=1, sort_keys=True, separators=(',', ': ')))
