#!/usr/bin/env python3

import argparse
import base64
import json
import os
import sys


def main():
    parser = argparse.ArgumentParser(
        description="Extract compliance reports from a test run artifacts JSON file",
    )
    parser.add_argument(
        "artifacts_file",
        help="Path to the test run artifacts JSON file",
    )
    parser.add_argument(
        "--output-dir",
        help="Directory to save output files to",
        required=False,
    )
    parser.add_argument(
        "--output-prefix",
        help="Prefix to use for naming output files",
        required=False,
    )
    args = parser.parse_args()

    if args.output_dir:
        os.makedirs(args.output_dir, exist_ok=True)

    with open(args.artifacts_file, "r") as f:
        data = json.load(f)

    for func_name in data.get("Functions", {}):
        for file_obj in data["Functions"][func_name].get("files", []):
            if file_obj["ID"] != "ComplianceHTMLReport":
                continue

            profile = file_obj["Data"]["scap_profile"]
            content = file_obj["Content"]
            if content is None:
                print(
                    f"Artifacts file '{args.artifacts_file}' does not have any content for profile '{profile}'! " +
                    f"Most likely the compliance/reports test failed. Please check 'test-reports.stderr'.",
                    file=sys.stderr
                )
                sys.exit(1)

            report = base64.b64decode(content)

            # Remove prefix (e.g. "xccdf_org.ssgproject.content_profile_cis_server_l1")
            profile = profile.replace("xccdf_org.ssgproject.content_profile_", "")

            report_file = f"{profile}.html"
            if args.output_prefix:
                report_file = args.output_prefix + report_file
            if args.output_dir:
                report_file = os.path.join(args.output_dir, report_file)

            with open(report_file, "wb") as f:
                f.write(report)

            print(f"Extracted: {report_file}")


if __name__ == "__main__":
    main()
