#!/usr/bin/env bash

set -euxo pipefail

GCP_PROJECT=${GCP_PROJECT:-wolfi-vm}
IMAGE_FAMILY=${IMAGE_FAMILY:-chainguard-generic-amd64}
ZONE=${ZONE:-us-central1-a}
NAME=${NAME:-$USER-test}

if [[ ! -z $(gcloud compute instances describe ${NAME} --zone=${ZONE} --project=${GCP_PROJECT}) ]]; then
    echo "Deleting existing instance ${NAME}"
    time gcloud compute instances delete ${NAME} --zone=${ZONE} --project=${GCP_PROJECT}
fi

time gcloud compute instances create ${NAME} \
    --project=${GCP_PROJECT} \
    --zone=${ZONE} \
    --image-family=${IMAGE_FAMILY} \
    --image-project=${GCP_PROJECT} \
    --machine-type=n1-standard-2 \
    --metadata "enable-oslogin=TRUE,ssh-keys=jason_chainguard_dev:$(cat ${HOME}/.ssh/id_ed25519.pub)"

IP=$(gcloud compute instances describe ${NAME} --zone=${ZONE} --project=${GCP_PROJECT} --format=json | jq -r '.networkInterfaces[0].accessConfigs[0].natIP')

# TODO(jason): Remove previous entries from ~/.ssh/known_hosts

ssh root@${IP}
