#!/bin/sh
# shellcheck disable=SC2015,SC2166,SC3043
TEMP_D=""
VERBOSITY=0

Usage() {
    cat <<EOF
Usage: ${0##*/} [options] thing output

  Get 'thing' from a wolfi or chainguard repo.

  Currently supported 'thing' is:
     ovmf
     kernel

  options:

    -v | --verbose        be more verbose
    -a | --arch   ARCH    provide arch (default 'uname -m')

  Environment:

     HTTP_AUTH - can provide auth for curl
EOF
}

cleanup() {
    [ -n "$TEMP_D" ] || return 0
    rm -Rf "$TEMP_D"
}

stderr() { echo "$@" 1>&2; }
fail() { [ $# -eq 0 ] || stderr "$@"; exit 1; }

main() {
    local short_opts="a:hv"
    local long_opts="arch:,help,name:,verbose"
    local getopt_out=""
    getopt_out=$(getopt --name "${0##*/}" \
        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { Usage 1>&2; return 1; }

    local cur="" next="" thing="" out="" arch=""
    while [ $# -ne 0 ]; do
        { cur="$1"; next="$2"; }
        case "$cur" in
            -h|--help) Usage ; exit 0;;
            -a|--arch) arch=$next; shift;;
            -v|--verbose) VERBOSITY=$((VERBOSITY+1));;
            --) shift; break;;
        esac
        shift;
    done

    if [ -z "$arch" ]; then
        arch=$(uname -m) || fail "uname -m failed"
        # Darwin says 'arm64' for 'uname -m'
        [ "$arch" = "arm64" ] && arch="aarch64"
    fi

    if [ $# -ne 2 ]; then
        Usage 1>&2
        stderr "Got $# args, expected 2"
        return 1
    fi

    case "$arch" in
        x86_64|aarch64) :;;
        *) fail "bad arch $arch";;
    esac

    thing="$1"
    outfile="$2"

    if ! command -v fetch-pkg >/dev/null 2>&1; then
        PATH="${0%/*}:$PATH"
        command -v fetch-pkg >/dev/null 2>&1 || fail "no fetch-pkg in path"
    fi

    case "$thing" in
        kernel)
            package="chainguard-private/linux"
            pkgarch="$arch"
            ;;
        ovmf)
            case "$arch" in
                x86_64|aarch64)
                    package="wolfi/qemu-system-$arch"
                    ;;
                *) fail "unknown arch $arch"
            esac
            ;;
    esac

    local fullver="" out="" extract_file=""
    out=$(fetch-pkg --list "$package") || fail "failed list versions of $package"
    # fullver is like 6.13-r1
    fullver=$(echo "$out" | tail -n 1)

    case "$thing" in
        kernel) extract_file="boot/vmlinuz-$arch-$fullver";;
        ovmf) extract_file="usr/share/qemu/edk2-$arch-code.fd";;
    esac

    TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
        { stderr "failed to create tempdir"; return 1; }
    trap cleanup EXIT

    local apk="${TEMP_D}/${package#*/}-$fullver.apk"
    local tmpf="$outfile.$$"

    fetch-pkg "--arch=$arch" "--output=$apk" "$package" ||
        fail "failed to download $package at $fullver"

    tmpf="$outfile.$$"
    tar -xzOf "$apk" "$extract_file" > "$tmpf" 2>/dev/null || {
        rm -f "$tmpf"
        tar tvf "$apk" | sed 's,^,> ,' 2>&1
        fail "failed extracting '$extract_file' from $package. see tar tvf above."
    }

    if [ ! -s "$tmpf" ]; then
        rm -f "$tmpf"
        fail "$package seemed to have no file $extract_file"
    fi

    mv "$tmpf" "$outfile" || fail "failed renaming $tmpf to $outfile"
    echo "pulled $thing from $package=$fullver $extract_file to $outfile"

    return 0
}

main "$@"
