#!/bin/sh -ex
# shellcheck disable=SC2015,SC2039,SC2166,SC3043

_grep() {
    set +x
    local m="$1"; shift;
    for f in "$@"; do
        while read line ; do
            case "$line" in
                *$m*) echo "$f: $line"; continue;;
            esac
        done < "$f"
    done
}

write_kernel_conf() {
    local rootd="$1" rootflag="" out="" ver="" opts="" fname="" kernel=""

    # basically find a single chainguard/*/linux file and write
    # an entry in boot/efi/loader/entries for it.
    out=$(cd "$rootd/boot/efi" && set +f && set -- chainguard/*/linux
        [ $# -eq 0 ] && { echo "no kernel found" 1>&2; exit 1; };
        echo "$# - $*" 1>&2
        for f in "$@"; do [ -f "$f" ] && echo "$f" && exit 0; done
        echo "didn't find kernel" 1>&2
        exit 1) || return 1
    kernel="/$out"
    # grab the version from chainguard/6.1.2/linux
    ver=${out#chainguard/}
    ver=${ver%/linux}
    rootflag="root=PARTLABEL=Chainguard"

    local console="ttyS0" debugtty="ttyS1"
    case "$ARCH" in
        x86_64) :;;
        aarch64)
            console="ttyAMA0";
            debugtty="ttyS0";;
    esac

    opts="$rootflag systemd.debug-shell=$debugtty console=$console"

    local rwflag="" ofname="boot/efi/loader/entries/chainguard-$ver.conf"
    if [ ! -f "$rootd/$ofname" ]; then
        echo "expected config file in $ofname was not found." 1>&2
        return 1
    else
        local line=""
        line=$(_grep "options * rw" "$rootd/$ofname")
        if [ -n "$line" ]; then
            rwflag="rw"
        fi
    fi

    fname="boot/efi/loader/entries/chainguard-$ver-debug.conf"

    cat > "$rootd/$fname" <<EOF || return 1
title      Chainguard-debug
version    $ver
sort-key   0chainguard
options    $opts${rwflag:+ $rwflag}
linux      $kernel
EOF

    ( set +x;
      echo "=== /$fname =="
      sed 's,^,| ,' "$rootd/$fname"
      echo "=== cmdlines ===" ;
      cd "$rootd/boot/efi/loader/entries" && _grep options *.conf )
}

setup_debug() {
    local rootd="$1"

    write_kernel_conf "$rootd" ||
        { echo "failed writing kernel conf"; return 1; }
}


DEBUG=${DEBUG:-false}
case "$DEBUG" in
    true|false) :;;
    *) echo "bad value DEBUG='$DEBUG'"; exit 1;;
esac

[ -z "$ARCH" ] && {
    ARCH=$(uname -m);
    echo "WARNING: $ARCH was not set in $0. Using 'uname -m' ($ARCH)"
}
case "$ARCH" in
    x86_64|aarch64) :;;
    *) echo "bad value ARCH='$ARCH'"; exit 1;;
esac

tarball=/dev/vda
disk=/dev/vdb

GPT_UUID=11111111-1111-1111-11111111111111111
PT_UUID_EFI=22222222-2222-2222-2222-222222222222
PT_UUID_ROOT=33333333-3333-3333-3333-333333333333
FS_UUID_ROOT=44444444-4444-4444-4444-444444444444
FS_UUID_EFI=55555555 # 32 bit int

# https://uapi-group.org/specifications/specs/discoverable_partitions_specification
EFI_TYPE="c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
ROOT_X86_64="4f68bce3-e8cd-4db1-96e7-fbcaf984b709"
ROOT_AARCH64="b921b045-1df0-41c3-af44-4c6f280d3fae"

case "$ARCH" in
    x86_64) ROOT_TYPE="${ROOT_X86_64}";;
    aarch64) ROOT_TYPE="${ROOT_AARCH64}";;
esac

[ -e "$tarball" ]
[ -b "$disk" ]

# Create a GPT parition table on our disk where the
# EFI System Partition (ESP) is 100M to hold the kernel,
# systemd-boot, and a handful of configuration files.
# The root partition will be the remainder of the disk.
sfdisk $disk <<EOF
label: gpt
label-id: $GPT_UUID
unit: sectors
sector-size: 512

disk.raw1 : start=  2048, size= 2048000, type=$EFI_TYPE, uuid=$PT_UUID_EFI, name="ESP"
disk.raw2 : start=2050048, size=, type=$ROOT_TYPE, uuid=$PT_UUID_ROOT, name="Chainguard", attrs="GUID:59"
EOF

uefi_partition="${disk}1"
root_partition="${disk}2"

# Format our EFP System Partition with FAT32 (required)
mkfs.fat -i "$FS_UUID_EFI" -F 32 $uefi_partition
# Format our root partition with xfs
mkfs.xfs -s size=512 -m "uuid=$FS_UUID_ROOT" -f $root_partition

# Mount our root partition, and our EFI System Partition
root_dir=$(mktemp -d /tmp/root.XXXXXX)
mount $root_partition $root_dir
mkdir -p $root_dir/boot/efi
mount $uefi_partition $root_dir/boot/efi

# Extract our initrd to our root partition, to be used as our root filesystem
tar -xpf "$tarball" --numeric-owner -C $root_dir
if [ "$DEBUG" = "true" ]; then
    setup_debug "$root_dir" || exit
fi

umount $root_dir/boot/efi
umount $root_dir/

echo Done.
