#!/bin/sh -ex

write_kernel_conf() {
    local rootd="$1" rootflag="" out="" ver="" opts="" fname="" kernel=""
    ( cd "$rootd/boot/efi" && find . -type f )

    # basically find a single chainguard/*/linux file and write
    # an entry in boot/efi/loader/entries for it.
    out=$(cd "$rootd/boot/efi" && set +f && set -- chainguard/*/linux
        [ $# -eq 0 ] && { echo "no kernel found" 1>&2; exit 1; };
        echo "$# - $*" 1>&2
        for f in "$@"; do [ -f "$f" ] && echo "$f" && exit 0; done
        echo "didn't find kernel" 1>&2
        exit 1) || return 1
    kernel="/$out"
    # grab the version from chainguard/6.1.2/linux
    ver=${out#chainguard/}
    ver=${ver%/linux}
    rootflag="root=PARTUUID=33333333-3333-3333-3333-333333333333"
    opts="$rootflag systemd.debug-shell=ttyS1 console=ttyS0"
    fname="boot/efi/loader/entries/chainguard-$ver-debug.conf"

    cat > "$rootd/$fname" <<EOF || return 1
title      Chainguard-debug
version    $ver
sort-key   0chainguard
options    $opts
linux      $kernel
EOF

    _grep() {
        local m="$1"; shift;
        for f in "$@"; do
            while read line ; do
                case "$line" in
                    *$m*) echo "$f: $line";;
                esac
            done < "$f"
        done
    }
    ( set +x;
      echo "=== /$fname =="
      sed 's,^,| ,' "$rootd/$fname"
      echo "=== cmdlines ===" ;
      cd "$rootd/boot/efi/loader/entries" && _grep options *.conf )
}

setup_debug() {
    local rootd="$1"

    write_kernel_conf "$rootd" ||
        { echo "failed writing kernel conf"; return 1; }
}


DEBUG=${DEBUG:-false}
case "$DEBUG" in
    true|false) :;;
    *) echo "bad value DEBUG='$DEBUG'"; exit 1;;
esac

tarball=/dev/vda
disk=/dev/vdb
rm -f /output/result

GPT_UUID=11111111-1111-1111-11111111111111111
PT_UUID_EFI=22222222-2222-2222-2222-222222222222
PT_UUID_ROOT=33333333-3333-3333-3333-333333333333
FS_UUID_ROOT=44444444-4444-4444-4444-444444444444
FS_UUID_EFI=55555555 # 32 bit int

[ -e "$tarball" ]
[ -b "$disk" ]

# Create a GPT parition table on our disk where the
# EFI System Partition (ESP) is 100M to hold the kernel,
# systemd-boot, and a handful of configuration files.
# The root partition will be the remainder of the disk.
sfdisk $disk <<EOF
label: gpt
label-id: $GPT_UUID
unit: sectors
sector-size: 512

disk.raw1 : start=  2048, size= 204800, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=$PT_UUID_EFI
disk.raw2 : start=206848, size=3985408, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=$PT_UUID_ROOT
EOF

uefi_partition="${disk}1"
root_partition="${disk}2"

# Format our EFP System Partition with FAT32 (required)
mkfs.fat -i "$FS_UUID_EFI" -F 32 $uefi_partition
# Format our root partition with xfs
mkfs.xfs -s size=512 -m "uuid=$FS_UUID_ROOT" -f $root_partition

# Mount our root partition, and our EFI System Partition
root_dir=$(mktemp -d /tmp/root.XXXXXX)
mount $root_partition $root_dir
mkdir -p $root_dir/boot/efi
mount $uefi_partition $root_dir/boot/efi

# Extract our initrd to our root partition, to be used as our root filesystem
tar -xpf "$tarball" --numeric-owner -C $root_dir
if [ "$DEBUG" = "true" ]; then
    setup_debug "$root_dir" || exit
fi

umount $root_dir/boot/efi
umount $root_dir/

echo 0 > /output/result
echo Done.
