#!/bin/sh
Usage() {
    cat <<EOF
Usage: ${0##*/} output [arch]

   create ovmf.fd for arch in some way (copy or download or something)
EOF
}

[ $# -gt 0 ] || { Usage 1>&2; exit 1; }
[ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit; }

out=$1
arch=${2:-$(uname -m)}

# old path was to for user to copy to ~/Downloads/OVMF-arch.fd
for cand in /usr/share/ovmf/OVMF.fd ~/Downloads/OVMF-$arch.fd ; do
    [ -f "$cand" ] || continue
    cp -v "$cand" "$out" || fail "failed to cp $cand $out"
    exit 0
done

echo "could not find a ovmf.fd for $arch"
echo "=== Please find yourself a OVMF.fd for $arch and put it in $out ==="
exit 1
