#!/usr/bin/env bash
# shellcheck disable=SC2015,SC2039,SC2166,SC3043

Usage(){
    cat <<EOF
Usage: ${0##*/} arch [accel]

   Print -machine and -cpu flags for qemu-system-ARCH.

   options:
     -H | --host-arch   arch (per uname -m)
     -o | --os          OS (Linux or Darwin) like 'uname -s'

   If accel is provided, it can be one of:

     on:           force use of acceleration
     off:          disable acceleration
     auto:         use best acceleration available or none
     hvf,tcg,kvm:  use this acceleration
EOF
}

stderr() { echo "$@" 1>&2; }
fail() { stderr "$@"; exit 1; }

main() {
    local short_opts="hH:o:"
    local long_opts="help,host-arch:,os:,"
    local getopt_out=""
    getopt_out=$(getopt --name "${0##*/}" \
        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { bad_Usage; return; }

    local cur="" next=""
    local host="" arch="" hostos="" accel=""
    while [ $# -ne 0 ]; do
        { cur="$1"; next="$2"; }
        case "$cur" in
            -h|--help) Usage ; exit 0;;
               --host-arch) host="$next"; shift;;
               --hostos) hostos="$next"; shift;;
            --) shift; break;;
        esac
        shift;
    done

    [ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit 0; }

    if [ $# -gt 2 -o $# -lt 1 ]; then
        Usage 1>&2
        echo "Got $# args ($*), expected 1, 2 or 3" 1>&2
        exit 1
    fi

    arch="$1"
    accel="$2"

    case "$arch" in
        aarch64|x86_64) :;;
        *) fail "unexpected arch $arch";;
    esac

    [ -n "$hostarch" ] || hostarch=$(uname -m)
    case "$hostarch" in
        aarch64|x86_64) :;;
        *) fail "unsupported host arch $hostarch";;
    esac

    [ -n "$hostos" ] || hostos=$(uname -s)
    case "$hostos" in
        [Ll]inux) hostos="linux";;
        [Dd]arwin) hostos="darwin";;
        *) fail "unknown hostos $hostos";;
    esac

    [ -c /dev/kvm ] && [ -w /dev/kvm ] && support_kvm=true || support_kvm=false

    out=$(sysctl kern.hv_support 2>/dev/null) && [ "$out" = "1" ] &&
        support_hvf=true || support_hvf="false"

    accelval=""
    case "$accel" in
        on)
            [ "$hostos" = "darwin" ] && accelval="hvf"
            [ "$hostos" = "linux" ] && accelval="kvm"
            ;;
        off) accelval="";;
        tcg) accelval=tcg;;
        hvf) [ "$hostos" = "darwin" ] ||
                fail "accel '$accel' only supported on darwin";;
        kvm) [ "$hostos" = "linux" ] ||
                fail "accel 'kvm' only supported on linux";;
    esac

    case "$arch" in
        aarch64) machine=virt;;
        x86_64) machine=q35;;
    esac

    if [ "$hostarch" = "$arch" ]; then
        cpuval="max"
    else
        case "$arch" in
            aarch64) cpuval="cortex-a53";;
            x86_64) cpuval="max";;
        esac
    fi

    if [ "$debug" = "true" ]; then
        stderr "hostarch=$hostarch"
        stderr "hostos=$hostos"
        stderr "accel=$accel"
        stderr "accelval=$accelval"
        stderr "cpuval=$cpuval"
        stderr "machine=$machine"
        stderr "support_kvm=$supports_kvm"
        stderr "support_hvf=$supports_hvf"
    fi

    if [ "$hostarch" = "$arch" ]; then
        if [ "$hostos" = "darwin" ]; then
            if [ "$accelval" = "" ]; then
                [ "$support_hvf" = "true" ] && accelval="hvf"
            fi
            echo "-machine $machine${accelval:+,accel=$accelval} -cpu $cpuval"
            return 0
        elif [ "$hostos" = "linux" ]; then
            if [ "$accelval" = "" ]; then
                [ "$support_kvm" = "true" ] && accelval="kvm"
            fi
            echo "-machine $machine${accelval:+,accel=$accelval} -cpu $cpuval"
            return 0
        fi
    else
        echo "-machine $machine${accelval:+,accel=$accelval} -cpu $cpuval"
        return 0
    fi
    fail "unexpected error"
}

main "$@"

