// Code generated by "enumer -json -output metrics_id_generated.go -type=ID"; DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _IDName = "UnidentifiedMetricSSHDStartTime"

var _IDIndex = [...]uint8{0, 18, 31}

const _IDLowerName = "unidentifiedmetricsshdstarttime"

func (i ID) String() string {
	if i < 0 || i >= ID(len(_IDIndex)-1) {
		return fmt.Sprintf("ID(%d)", i)
	}
	return _IDName[_IDIndex[i]:_IDIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IDNoOp() {
	var x [1]struct{}
	_ = x[UnidentifiedMetric-(0)]
	_ = x[SSHDStartTime-(1)]
}

var _IDValues = []ID{UnidentifiedMetric, SSHDStartTime}

var _IDNameToValueMap = map[string]ID{
	_IDName[0:18]:       UnidentifiedMetric,
	_IDLowerName[0:18]:  UnidentifiedMetric,
	_IDName[18:31]:      SSHDStartTime,
	_IDLowerName[18:31]: SSHDStartTime,
}

var _IDNames = []string{
	_IDName[0:18],
	_IDName[18:31],
}

// IDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IDString(s string) (ID, error) {
	if val, ok := _IDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ID values", s)
}

// IDValues returns all values of the enum
func IDValues() []ID {
	return _IDValues
}

// IDStrings returns a slice of all String values of the enum
func IDStrings() []string {
	strs := make([]string, len(_IDNames))
	copy(strs, _IDNames)
	return strs
}

// IsAID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ID) IsAID() bool {
	for _, v := range _IDValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ID
func (i ID) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ID
func (i *ID) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ID should be a string, got %s", data)
	}

	var err error
	*i, err = IDString(s)
	return err
}
