name: Validate an iamguarded chart

needs:
  packages:
    - bash
    - helm
    - ripgrep
    - yq

inputs:
  chart-name:
    description: |
      The name of the chart to validate
  ignored-files:
    description: |
      Allows the space-separated string of file paths to contain bitnami references
    default: ""

pipeline:
  - name: Fetch tools
    pipeline:
      - uses: auth/github
        with:
          repo: chainguard-dev/iamguarded-tools
      - uses: git-checkout
        with:
          repository: https://github.com/chainguard-dev/iamguarded-tools
          branch: main
          destination: ./.iamguarded-tools

  - name: Validate
    runs: |
      # pass full path to chart
      ./.iamguarded-tools/chart/validate.sh /${{inputs.chart-name}} "${{inputs.ignored-files}}"
