name: traefik
metadata:
    release_monitor:
        id: 89172
        name: traefik
    endoflife:
        name: traefik
streams:
    - stream: "3.6"
      versions:
        - version: 3.6.2
          sources:
            - type: endoflife.date
              published_at: 2025-11-19T00:27:02Z
            - type: git
              tag: v3.6.2
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.6.2
              published_at: 2025-11-18T16:06:09Z
            - type: github_release
              tag: v3.6.2
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.6.2
              published_at: 2025-11-18T16:25:16Z
            - type: release_monitor
              tag: 3.6.2
        - version: 3.6.1
          sources:
            - type: endoflife.date
              published_at: 2025-11-14T00:26:42Z
            - type: git
              tag: v3.6.1
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.6.1
              published_at: 2025-11-13T13:20:04Z
            - type: github_release
              tag: v3.6.1
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.6.1
              published_at: 2025-11-13T14:28:54Z
            - type: release_monitor
              tag: 3.6.1
        - version: 3.6.0
          sources:
            - type: endoflife.date
              published_at: 2025-11-08T21:48:25Z
            - type: git
              tag: v3.6.0
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.6.0
              published_at: 2025-11-07T15:16:04Z
            - type: github_release
              tag: v3.6.0
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.6.0
              published_at: 2025-11-07T15:34:35Z
            - type: release_monitor
              tag: 3.6.0
    - stream: "3.5"
      versions:
        - version: 3.5.6
          sources:
            - type: endoflife.date
              published_at: 2025-11-08T00:27:05Z
            - type: git
              tag: v3.5.6
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.6
              published_at: 2025-11-07T13:40:05Z
            - type: github_release
              tag: v3.5.6
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.6
              published_at: 2025-11-07T13:59:02Z
            - type: release_monitor
              tag: 3.5.6
        - version: 3.5.5
          sources:
            - type: git
              tag: v3.5.5
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.5
              published_at: 2025-11-07T13:06:00Z
            - type: release_monitor
              tag: 3.5.5
        - version: 3.5.4
          sources:
            - type: endoflife.date
              published_at: 2025-10-29T00:28:34Z
            - type: git
              tag: v3.5.4
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.4
              published_at: 2025-10-28T10:44:04Z
            - type: github_release
              tag: v3.5.4
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.4
              published_at: 2025-10-28T11:09:25Z
            - type: release_monitor
              tag: 3.5.4
        - version: 3.5.3
          sources:
            - type: endoflife.date
              published_at: 2025-09-27T00:26:51Z
            - type: git
              tag: v3.5.3
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.3
              published_at: 2025-09-26T08:46:03Z
            - type: github_release
              tag: v3.5.3
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.3
              published_at: 2025-09-26T09:31:01Z
            - type: release_monitor
              tag: 3.5.3
        - version: 3.5.2
          sources:
            - type: endoflife.date
              published_at: 2025-09-10T00:26:48Z
            - type: git
              tag: v3.5.2
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.2
              published_at: 2025-09-09T10:12:04Z
            - type: github_release
              tag: v3.5.2
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.5.2
              published_at: 2025-09-09T10:28:12Z
            - type: release_monitor
              tag: 3.5.2
    - stream: "3.4"
      versions:
        - version: 3.4.5
          sources:
            - type: endoflife.date
              published_at: 2025-07-24T00:50:27Z
            - type: git
              tag: v3.4.5
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.5
              published_at: 2025-07-23T09:16:04Z
            - type: github_release
              tag: v3.4.5
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.5
              published_at: 2025-07-23T09:35:46Z
            - type: release_monitor
              tag: 3.4.5
        - version: 3.4.4
          sources:
            - type: endoflife.date
              published_at: 2025-07-12T00:58:27Z
            - type: git
              tag: v3.4.4
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.4
              published_at: 2025-07-11T08:26:04Z
            - type: github_release
              tag: v3.4.4
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.4
              published_at: 2025-07-11T08:41:34Z
            - type: release_monitor
              tag: 3.4.4
        - version: 3.4.3
          sources:
            - type: endoflife.date
              published_at: 2025-06-27T00:48:07Z
            - type: git
              tag: v3.4.3
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.3
              published_at: 2025-06-26T13:18:04Z
            - type: github_release
              tag: v3.4.3
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.3
              published_at: 2025-06-26T13:34:31Z
            - type: release_monitor
              tag: 3.4.3
        - version: 3.4.2
          sources:
            - type: git
              tag: v3.4.2
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.2
              published_at: 2025-06-26T10:30:04Z
            - type: github_release
              tag: v3.4.2
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.2
              published_at: 2025-06-26T10:45:04Z
            - type: release_monitor
              tag: 3.4.2
        - version: 3.4.1
          sources:
            - type: endoflife.date
              published_at: 2025-05-28T12:15:17Z
            - type: git
              tag: v3.4.1
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.1
              published_at: 2025-05-27T12:32:04Z
            - type: github_release
              tag: v3.4.1
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.4.1
              published_at: 2025-05-27T12:53:58Z
            - type: release_monitor
              tag: 3.4.1
    - stream: "3.3"
      versions:
        - version: 3.3.7
          sources:
            - type: endoflife.date
              published_at: 2025-05-06T12:54:05Z
            - type: git
              tag: v3.3.7
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.7
              published_at: 2025-05-05T08:38:04Z
            - type: github_release
              tag: v3.3.7
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.7
              published_at: 2025-05-05T08:53:40Z
            - type: release_monitor
              tag: 3.3.7
        - version: 3.3.6
          sources:
            - type: endoflife.date
              published_at: 2025-04-20T19:52:44Z
            - type: git
              tag: v3.3.6
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.6
              published_at: 2025-04-18T09:10:04Z
            - type: github_release
              tag: v3.3.6
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.6
              published_at: 2025-04-18T09:28:22Z
            - type: release_monitor
              tag: 3.3.6
        - version: 3.3.5
          sources:
            - type: endoflife.date
              published_at: 2025-04-01T12:25:50Z
            - type: git
              tag: v3.3.5
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.5
              published_at: 2025-03-31T08:38:04Z
            - type: github_release
              tag: v3.3.5
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.5
              published_at: 2025-03-31T08:55:12Z
            - type: release_monitor
              tag: 3.3.5
        - version: 3.3.4
          sources:
            - type: endoflife.date
              published_at: 2025-02-26T12:49:56Z
            - type: git
              tag: v3.3.4
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.4
              published_at: 2025-02-25T10:04:04Z
            - type: github_release
              tag: v3.3.4
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.4
              published_at: 2025-02-25T10:18:58Z
            - type: release_monitor
              tag: 3.3.4
        - version: 3.3.3
          sources:
            - type: endoflife.date
              published_at: 2025-02-03T12:28:09Z
            - type: git
              tag: v3.3.3
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.3
              published_at: 2025-01-31T14:46:04Z
            - type: github_release
              tag: v3.3.3
              tag_uri: https://github.com/traefik/traefik/releases/tag/v3.3.3
              published_at: 2025-01-31T15:03:54Z
            - type: release_monitor
              tag: 3.3.3
    - stream: "2.11"
      versions:
        - version: 2.11.31
          sources:
            - type: endoflife.date
              published_at: 2025-11-14T00:26:42Z
            - type: git
              tag: v2.11.31
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.31
              published_at: 2025-11-13T09:42:16Z
            - type: github_release
              tag: v2.11.31
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.31
              published_at: 2025-11-13T10:01:56Z
            - type: release_monitor
              tag: 2.11.31
        - version: 2.11.30
          sources:
            - type: endoflife.date
              published_at: 2025-10-29T00:28:34Z
            - type: git
              tag: v2.11.30
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.30
              published_at: 2025-10-28T08:44:04Z
            - type: github_release
              tag: v2.11.30
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.30
              published_at: 2025-10-28T09:03:27Z
            - type: release_monitor
              tag: 2.11.30
        - version: 2.11.29
          sources:
            - type: endoflife.date
              published_at: 2025-08-27T11:39:42Z
            - type: git
              tag: v2.11.29
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.29
              published_at: 2025-08-26T12:50:08Z
            - type: github_release
              tag: v2.11.29
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.29
              published_at: 2025-08-26T13:14:55Z
            - type: release_monitor
              tag: 2.11.29
        - version: 2.11.28
          sources:
            - type: endoflife.date
              published_at: 2025-07-24T00:50:27Z
            - type: git
              tag: v2.11.28
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.28
              published_at: 2025-07-23T08:34:04Z
            - type: github_release
              tag: v2.11.28
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.28
              published_at: 2025-07-23T08:56:11Z
            - type: release_monitor
              tag: 2.11.28
        - version: 2.11.27
          sources:
            - type: endoflife.date
              published_at: 2025-07-12T00:58:27Z
            - type: git
              tag: v2.11.27
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.27
              published_at: 2025-07-11T07:30:05Z
            - type: github_release
              tag: v2.11.27
              tag_uri: https://github.com/traefik/traefik/releases/tag/v2.11.27
              published_at: 2025-07-11T07:45:38Z
            - type: release_monitor
              tag: 2.11.27
