issuer: https://accounts.google.com

# version-stream-creator@nghia-chainguard-ng.iam.gserviceaccount.com (dev environment)
subject: "100880354428695703313"

permissions:
  checks: read
  contents: write
  pull_requests: write
