issuer: https://accounts.google.com

# kleung:  ebuild-py5wka7s7g5no2hg8tpoqi9@kleung-chainguard.iam.gserviceaccount.com
# staging: ebuild-ccncbvvdeww3kz6m62n5a6x@staging-enforce-cd1e.iam.gserviceaccount.com
# prod:    
# "([kleung]|[staging]|[prod])"
subject_pattern: "(108286754379380263406|113371820205225739092)"

permissions:
  contents: read
  checks: write
