issuer: https://accounts.google.com

# There's the GH PR handler, and a cron job, so we need two accounts here.
# staging-images: bot-label-sla@staging-images-183e.iam.gserviceaccount.com (107980260030120050243)
# staging-images: cron-sla-label@staging-images-183e.iam.gserviceaccount.com (111643071869316414848)
subject_pattern: "(107980260030120050243|111643071869316414848)"

permissions:
  contents: read
  pull_requests: write # to add labels
