issuer: https://accounts.google.com

# staging-images: lifecycle-eol-deleter@staging-images-183e.iam.gserviceaccount.com
# prod-images: lifecycle-eol-deleter@prod-images-c6e5.iam.gserviceaccount.com
subject_pattern: "(103984212424345573635|117399883874485279199)"

permissions:
  contents: write
  pull_requests: write
