issuer: https://accounts.google.com

# staging-enforce: update-bot-stereo@staging-enforce-cd1e.iam.gserviceaccount.com (106114918196365401610)
subject_pattern: "106114918196365401610"

permissions:
  contents: write
  pull_requests: write
  workflows: write
  issues: write
