# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "Scan VM Disks"
description: "Scan VM Disks with Grype."

inputs:
  vm_group:
    required: true
    default: ""
    description: "Which group of images"
  arch:
    required: true
    default: ""
    description: "Which acrchitecture we will build the vm"

runs:
  using: composite

  steps:
      # Add a block like this in a separate PR *before* landing tests in a new module.
      - name: Install grype
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: scan disks
        shell: bash
        run: |
          echo "scanning ${{ env.VM_ARCH }} disks-${{ env.VM_GROUP}}"
          # Scan for CVEs, fail early
          for disk in output/"${{ env.VM_ARCH }}"/*; do
            outbase="${disk}/$(basename $disk)-${{ env.VM_ARCH }}-${{ env.VM_GROUP}}-${{ env.BUILD_TIMESTAMP }}"
            grype sbom:${disk}/syft.sbom.json > "$outbase-grype.output" || true
            mv ${disk}/syft.sbom.json "$outbase-syft.sbom.json"
          done
        env:
          VM_ARCH: ${{ inputs.arch }}
          VM_GROUP: ${{ inputs.vm_group }}
          TMPDIR: ${{ runner.temp }}

      - name: upload SBOM artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sbom-${{ env.VM_GROUP }}-${{ env.VM_ARCH }}-${{ env.BUILD_TIMESTAMP }}
          path: output/${{ env.VM_ARCH }}/*/*-${{ env.VM_ARCH }}-${{ env.VM_GROUP }}-${{ env.BUILD_TIMESTAMP }}-syft.sbom.json
        env:
          VM_ARCH: ${{ inputs.arch }}
          VM_GROUP: ${{ inputs.vm_group }}
          TMPDIR: ${{ runner.temp }}

      - name: upload grype scan output artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: grype-${{ env.VM_GROUP }}-${{ env.VM_ARCH }}-${{ env.BUILD_TIMESTAMP }}
          path: output/${{ env.VM_ARCH }}/*/*-${{ env.VM_ARCH }}-${{ env.VM_GROUP }}-${{ env.BUILD_TIMESTAMP }}-grype.output
        env:
          VM_ARCH: ${{ inputs.arch }}
          VM_GROUP: ${{ inputs.vm_group }}
          TMPDIR: ${{ runner.temp }}
