#!/bin/sh
set -e

ami=$1
[ -n "$1" ] || { echo must specify ami; exit 1; }

# One can also use yaml config
eksctl create cluster \
       --tags "Environment=wolfi-vm-test" \
       --with-oidc \
       --version 1.32 \
       --node-type t3.large \
       --node-ami "$ami" \
       --node-ami-family AmazonLinux2023 \
       --vpc-nat-mode Disable

echo To delete use: eksctl delete cluster NAME
