#!/usr/bin/env bash

set -euxo pipefail

image="${1:-}"

arch=${arch:-}
SSHKEY=${SSHKEY:-id_ed25519.pub}
GCP_PROJECT=${GCP_PROJECT:-wolfi-vm}
IMAGE_FAMILY=${IMAGE_FAMILY:-chainguard-generic-amd64}
IMAGE=${image}
ZONE=${ZONE:-us-central1-a}
NAME=${NAME:-$USER-test}

if [ -n "$IMAGE" ]; then
    IMAGE_FAMILY=""
    archstr="$IMAGE"
else
    archstr="$IMAGE_FAMILY"
fi

if [ -z "$arch" ]; then
    case "$archstr" in
        *arm64*) arch=aarch64;;
        *amd64*) arch=x86_64;;
    esac
fi

case "$arch" in
    aarch64)
        mtype="t2a-standard-1"
        ;;
    x86_64)
        mtype="n1-standard-2"
        ;;
    *) echo "bad arch $arch"; exit 1;;
esac

pubkey=$(cat "$HOME/.ssh/$SSHKEY") ||
    { echo "Error reading $HOME/.ssh/$SSHKEY" 1>&2; exit 1; }
exinst=$(gcloud compute instances describe "${NAME}" --zone="${ZONE}" --project="${GCP_PROJECT}") ||
    { echo "Error running gcloud compute to check for existing instance" 1>&2; exit 1; }
if [ -n "$exinst" ]; then
    echo "Deleting existing instance ${NAME}"
    time gcloud compute instances delete "${NAME}" --zone="${ZONE}" --project="${GCP_PROJECT}"
fi

time gcloud compute instances create "${NAME}" \
    --project="${GCP_PROJECT}" \
    --zone="${ZONE}" \
    ${IMAGE:+--image="${IMAGE}"} \
    ${IMAGE_FAMILY:+--image-family="${IMAGE_FAMILY}"} \
    --image-project="${GCP_PROJECT}" \
    --machine-type="$mtype" \
    --metadata "enable-oslogin=TRUE,serial-port-enable=true,ssh-keys=$USER:$pubkey"

out=$(gcloud compute instances describe "${NAME}" --zone="${ZONE}" --project="${GCP_PROJECT}" --format=json) ||
    { stderr "Error running gcloud compute instances describe $NAME"; return 1; }
[ -n "$out" ] ||
    { stderr "gcloud compute describe $NAME showed no output"; return 1; }

IP=$(echo "$out" | jq -r '.networkInterfaces[0].accessConfigs[0].natIP')

# TODO(jason): Remove previous entries from ~/.ssh/known_hosts

ssh "root@${IP}"
