#!/bin/sh
Usage() {
    cat <<EOF
Usage: ${0##*/} disk-output build-config-path

Example:

    ${0##*/} output/x86_64/qemu-base-slim/disk-debug.raw \
       configs/qemu-base-slim/build.yaml x86_64
EOF
}

fail() {
    echo "FATAL:" "[${0##*/}]" "$@" 1>&2
    exit 1
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    Usage
    exit 0
fi

[ $# -eq 3 ] || {
    Usage 1>&2
    fail "Got $# args, expected 3"
}

output="$1"
buildcfg="$2"
targetarch="$3"
opts="targetarch=$targetarch"

[ -f "$buildcfg" ] || fail "build config '$buildcfg' is not a file"

case "$output" in
    *-debug.*) opts="$opts,debug";;
esac

# would like to parse config in some way to find this.
# for now, have to rely on name
case "$buildcfg" in
    *immutable*) opts="$opts,immutable";;
esac

case "$buildcfg" in
    *rpi*) opts="$opts,rpi";;
esac

case "$buildcfg" in
    *hardened*) opts="$opts,cis";;
esac

echo "$opts"
