#!/bin/bash
# shellcheck disable=SC2015,SC2039,SC2166,SC3043

SECTOR_SIZE=512
NEW_UUID=54444444-4444-4444-4444-444444444444
PT_NAME="Chainguard"
LODEV=""

stderr() { echo "$@" 1>&2; }
fail() { local r=$?;  [ $r -eq 0 ] && r=1; failrc "$r" "$@"; }
failrc() { local r="$1"; shift; [ $# -eq 0 ] || stderr "$@"; exit "$r"; }

Usage() {
    cat <<EOF
Usage: ${0##*/} [ options ] disk.raw

   whack the filesystem uuid in disk.raw to be different.

   You cannot mount an xfs filesystem with a UUID if you have the same
   UUID already mounted.  This presents a problem for mounting an
   image you just built on a workstation, where workstation has it's
   rootfs with the same UUID you just built.

   options:

           --name     NAME    default: "$PT_NAME"
      -U | --uuid     UUID    default: "$NEW_UUID"
EOF
}

bad_Usage() { Usage 1>&2; [ $# -eq 0 ] || stderr "$@"; return 1; }
cleanup() {
    if [ -n "$LODEV" ]; then
        losetup --detach="$LODEV"
    fi
}

main() {
    local short_opts="hU:v"
    local long_opts="help,name:,uuid:,verbose"
    local getopt_out=""
    getopt_out=$(getopt --name "${0##*/}" \
        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { bad_Usage; return; }

    local cur="" next="" disk="" uuid="$NEW_UUID" name="$PT_NAME"

    while [ $# -ne 0 ]; do
        { cur="$1"; next="$2"; }
        case "$cur" in
            -h|--help) Usage ; exit 0;;
            -U|--uuid) uuid=$next; shift;;
               --name) name=$next; shift;;
            --) shift; break;;
        esac
        shift;
    done

    [ $# -eq 1 ] || { bad_Usage "must provide arguments"; return; }
    disk="$1"
    shift

    [ -f "$disk" ] || [ -b "$disk" ] ||
        { stderr "$disk: not a file or block device"; return 1; }

    local p="" missing=""
    for p in xfs_admin losetup partx blkid awk sed dd; do
        command -v "$p" >/dev/null 2>&1 ||
            missing="$missing,$p"
    done
    missing=${missing#,}
    [ -z "$missing" ] || fail "missing some dependencies: $missing"

    trap cleanup EXIT

    local soffset="" offset="" out="" out2="" ptnum=""
    out=$(partx --bytes "$disk") ||
        fail "failed[$?]: partx --bytes '$disk'"
    # NR  START     END SECTORS       SIZE NAME       UUID
    # 1    8192 2097151 2088960 1069547520 ESP        22222222-2222-2222-2222-222222222222
    # 2 2097152 4192255 2095104 1072693248 Chainguard 33333333-3333-3333-3333-333333333333
    out2=$(echo "$out" | awk '$6 == pn { printf("%s/%s\n", $1, $2); }' pn="$name") ||
        fail "awk failed"
    [ -n "$out2" ] || fail "did not find $name" "$out"
    soffset=${out2#*/}
    offset=$((soffset*SECTOR_SIZE))
    ptnum=${out2%/*}
    stderr "found $name in partition $ptnum at offset $offset ($soffset sectors)"

    local fpath="$disk"
    if [ "$offset" != "0" ]; then
        fpath=$(losetup --find --offset="$offset" --show "$disk") ||
            fail "failed setting up loop dev for $disk @ $offset"
        LODEV="$fpath"
    fi

    xfs_admin -U "$uuid" "$fpath" || fail "failed xfs_admin -U $uuid $fpath"

    out=$(blkid --offset="$offset" --probe "$disk") ||
        fail "failed running blkid"

    if ! echo "$out" | grep -q "$uuid"; then
        stderr "blkid --offset=$offset --probe $disk: did not find uuid '$uuid'"
        stderr "output: $out"
        return 1
    fi

    stderr "looks good"
}

main "$@"
# vi: ts=4 expandtab
