name: Remove omit symbol from files

needs:
  packages:
    - busybox

inputs:
  files:
    description: "The files to operate on. Space separated."
    required: false
    default: "Makefile"

pipeline:
  - runs: |
      fail() { echo "$@" 1>&2; exit 1; }

      td=$(mktemp -d) || fail "failed mktemp"
      cat > "$td/seds" <<"EOF"
      s/-ldflags[[:space:]]*"[^"]*-s[^"]*"/-ldflags "-w"/g
      EOF

      set --
      while read line; do
          [ -n "$line" ] || continue
          set -- "$@" "-e" "$line"
      done <"$td/seds"

      trap "rm -Rf '$td'" EXIT

      for f in ${{inputs.files}}; do
          [ -f "$f" ] || fail "$f: not a file"
          bk="$td/${f##*/}"
          cp "$f" "$bk" || fail "failed backup of $f"

          # Use sed to remove -s flag only after -ldflags
          sed -i "$@" -- "$f" || fail "failed sed-editing $f"

          if diff -u "$bk" "$f" > "$td/diff"; then
              fail "editing '$f' did not make a change with sed $*"
          fi

          echo "updated $f as follows"
          sed 's,^,>,' "$td/diff"
      done
