# This is an unguarded package for a customer that is expected to have CVEs. Leave pinned to 20220623.
#nolint:valid-pipeline-git-checkout-tag
package:
  name: abseil-cpp-20220623
  version: "20220623"
  epoch: 1 # go/enterprise-rsc/abseil-cpp-20220623
  description: Abseil Common Libraries (C++)
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - abseil-cpp=${{package.full-version}}
  resources:
    cpu: "3"
    memory: 10Gi

environment:
  contents:
    packages:
      - autoconf
      - automake
      - busybox
      - ca-certificates-bundle
      - cmake
      - gcc-12
      - gtest-dev
      - samurai
  environment:
    # https://github.com/wolfi-dev/os/issues/34075
    CMAKE_CXX_FLAGS: -fdelete-null-pointer-checks
    CXX: "c++-12"

var-transforms:
  - from: ${{package.version}}
    match: ^\d{2}(\d{4}).*$
    replace: ${1}.0.0
    to: soversion

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/abseil/abseil-cpp
      branch: lts_2022_06_23
      expected-commit: 053d842fa6c55ee103057b3c325b1923fd5d67d2

  - runs: |
      cmake -B build -G Ninja \
      -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS" \
      -DCMAKE_CXX_STANDARD=17 \
      -DCMAKE_BUILD_TYPE=MinSizeRel \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_LIBDIR=lib \
      -DBUILD_SHARED_LIBS=ON \
      -DABSL_BUILD_TESTING=OFF \
      -DABSL_BUILD_TEST_HELPERS=ON \
      -DABSL_USE_EXTERNAL_GOOGLETEST=ON \
      -DABSL_PROPAGATE_CXX_STD=ON \
      -DABSL_FIND_GOOGLETEST=ON

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: libabsl${{vars.soversion}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/*.so.* ${{targets.contextdir}}/usr/lib/
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    description: ${{package.name}} dev
    dependencies:
      provides:
        - abseil-cpp-dev=${{package.full-version}}
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check
          with:
            packages: ${{subpkg.name}}

update:
  enabled: false
  # LTS support policy: https://abseil.io/about/releases#long-term-support-lts-branches
  # Latest release for the 2022-06 LTS branch: https://github.com/abseil/abseil-cpp/releases/tag/20220623.2
  exclude-reason: "Despite the LTS support policy, the branch is practically no longer maintained"
  github:
    identifier: abseil/abseil-cpp

test:
  pipeline:
    - uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
