package:
  name: apparmor
  version: "4.1.6"
  epoch: 0
  description: "Mandatory Access Control (MAC) using Linux Security Module (LSM)"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - merged-lib
      - merged-usrsbin
      - wolfi-baselayout

vars:
  python-version: 3.13
  ruby-version: 3.4

environment:
  contents:
    packages:
      - autoconf-archive
      - bash
      - bison
      - build-base
      - busybox
      - coreutils
      - flex
      - gettext
      - libtool
      - linux-headers
      - linux-pam-dev
      - perl-dev
      - py${{vars.python-version}}-setuptools
      - python-${{vars.python-version}}
      - python-${{vars.python-version}}-dev
      - ruby-${{vars.ruby-version}}-dev
      - sed # busybox sed doesn't work
      - swig

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/apparmor/apparmor.git
      tag: v${{package.version}}
      expected-commit: c0e9c22be14fd20c8512f3c92286f53c9b97f94b

subpackages:
  - name: libapparmor
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - py${{vars.python-version}}-legacy-cgi
        - wolfi-baselayout
    pipeline:
      - working-directory: libraries/libapparmor
        pipeline:
          - runs: |
              autoreconf -vfi
          - uses: autoconf/configure
            with:
              opts: |
                --prefix=/usr \
                --sbindir=/usr/bin \
                --with-perl \
                --with-python \
                --with-ruby
          - uses: autoconf/make
          - uses: autoconf/make-install
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: apparmor-utils
    dependencies:
      runtime:
        - apparmor-parser
        - bash
        - merged-lib
        - merged-usrsbin
        - py${{vars.python-version}}-libapparmor
        - py${{vars.python-version}}-notify2
        - py${{vars.python-version}}-psutil
        - py${{vars.python-version}}-pygobject
        - py${{vars.python-version}}-tkinter
        - python-${{vars.python-version}} # give /usr/bin/python3 -> python${{vars.python-version}}
        - wolfi-baselayout
    pipeline:
      - working-directory: utils
        pipeline:
          - uses: autoconf/make
          - uses: autoconf/make-install
          - name: "Fixup usr merge"
            runs: |
              mkdir -p ${{targets.subpkgdir}}/usr/bin
              mv ${{targets.subpkgdir}}/usr/sbin/* ${{targets.subpkgdir}}/usr/bin/
              rmdir ${{targets.subpkgdir}}/usr/sbin/
    test:
      pipeline:
        - runs: |
            aa-easyprof --help
            aa-audit --help
            aa-autodep --help
            aa-cleanprof --help
            aa-complain --help
            aa-decode --help
            aa-disable --help
            aa-enforce --help
            aa-genprof --help
            aa-logprof --help
            aa-mergeprof --help
            aa-notify --help
            aa-remove-unknown --help
            aa-unconfined --help

  - name: apparmor-pam
    pipeline:
      - working-directory: changehat/pam_apparmor
        pipeline:
          - uses: autoconf/make
          - uses: autoconf/make-install
          - name: "Fixup usr merge"
            runs: |
              mkdir -p ${{targets.subpkgdir}}/usr/lib
              mv ${{targets.subpkgdir}}/lib/* ${{targets.subpkgdir}}/usr/lib/
              rmdir ${{targets.subpkgdir}}/lib/
    test:
      pipeline:
        - uses: test/tw/ldd-check
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout

  - name: apparmor-binutils
    pipeline:
      - working-directory: binutils
        pipeline:
          - uses: autoconf/make
          - uses: autoconf/make-install
          - name: "Fixup usr merge"
            runs: |
              mkdir -p ${{targets.subpkgdir}}/usr/bin
              mv ${{targets.subpkgdir}}/usr/sbin/* ${{targets.subpkgdir}}/usr/bin/
              rmdir ${{targets.subpkgdir}}/usr/sbin/
    test:
      pipeline:
        - runs: |
            aa-enabled --help || [ $? == 1 ]
            aa-exec --help
            aa-features-abi --help
            aa-load --help
            aa-status --help
            apparmor_status --help
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout

  - name: libapparmor-dev
    pipeline:
      - uses: split/dev
        with:
          package: libapparmor
    test:
      pipeline:
        - uses: test/tw/ldd-check
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout

  - name: libapparmor-doc
    pipeline:
      - uses: split/manpages
        with:
          package: libapparmor
    test:
      pipeline:
        - uses: test/docs
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout

  - name: py${{vars.python-version}}-libapparmor
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/
          mv ${{targets.subpkgdir}}/../libapparmor/usr/lib/python* ${{targets.subpkgdir}}/usr/lib/
    test:
      pipeline:
        - uses: python/import
          with:
            imports: import LibAppArmor
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout

  - name: ruby-libapparmor
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/
          mv ${{targets.subpkgdir}}/../libapparmor/usr/lib/ruby ${{targets.subpkgdir}}/usr/lib/
    test:
      pipeline:
        - uses: test/tw/ldd-check
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout

  - name: perl-libapparmor
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.subpkgdir}}/../libapparmor/usr/lib/perl* ${{targets.subpkgdir}}/usr/lib/
    test:
      pipeline:
        - uses: test/tw/ldd-check
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout

  - name: apparmor-binutils-doc
    pipeline:
      - uses: split/manpages
        with:
          package: apparmor-binutils
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout
    test:
      pipeline:
        - uses: test/tw/docs

  - name: apparmor-parser
    pipeline:
      - working-directory: parser
        pipeline:
          - uses: autoconf/make
          - uses: autoconf/make-install
          - name: "Fixup usr merge"
            runs: |
              mkdir -p ${{targets.subpkgdir}}/usr/bin
              mkdir -p ${{targets.subpkgdir}}/usr/lib
              mv ${{targets.subpkgdir}}/sbin/* ${{targets.subpkgdir}}/usr/bin/
              rmdir ${{targets.subpkgdir}}/sbin/
              mv ${{targets.subpkgdir}}/lib/* ${{targets.subpkgdir}}/usr/lib/
              rmdir ${{targets.subpkgdir}}/lib/
    test:
      pipeline:
        - runs: |
            # Needs kernel support
            apparmor_parser || [ $? == 1 ]
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout

  - name: apparmor-parser-dev
    pipeline:
      - uses: split/dev
        with:
          package: apparmor-parser
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout
    test:
      pipeline:
        - uses: test/emptypackage

  - name: apparmor-parser-doc
    pipeline:
      - uses: split/manpages
        with:
          package: apparmor-parser
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout
    test:
      pipeline:
        - uses: test/tw/docs

  - name: apparmor-utils-doc
    pipeline:
      - uses: split/manpages
        with:
          package: apparmor-parser
    dependencies:
      runtime:
        - merged-lib
        - merged-usrsbin
        - wolfi-baselayout
    test:
      pipeline:
        - uses: test/emptypackage

update:
  enabled: true
  git:
    strip-prefix: v
  ignore-regex-patterns:
    - git-conversion # Bad tag

# Based on package contents inspection, it was found that this origin package is empty apart from its own SBOM and this test was added to confirm it is empty and will fail if the package is no longer empty (contains more than an SBOM)
test:
  pipeline:
    - uses: test/emptypackage
