package:
  name: cass-operator-fips
  version: "1.28.0"
  epoch: 4 # CVE-2025-68119
  description: Manages Cassandra cluster as standalone product or as part of the k8ssandra-operator
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      # for fips config & fips-provider
      - openssl-config-fipshardened
      # either melange SCA should provide these
      # or we should make go-fips shared link on these
      - so:libcrypto.so.3
      - so:libssl.so.3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8ssandra/cass-operator.git
      tag: v${{package.version}}
      expected-commit: e5928d0a833766fefa5c9fb82f9de42a2df77413

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd
      output: ${{package.name}}-manager
      go-package: go-fips

subpackages:
  - name: cass-operator-compat-fips
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    dependencies:
      runtime:
        - cass-operator-fips
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          # For backwards compatibility, create a symlink to as-is location
          ln -sf /usr/bin/${{package.name}}-manager ${{targets.subpkgdir}}/usr/bin/manager
          # The helm chart expects the cass-operator binaries to be in / instead of /usr/bin
          ln -sf /usr/bin/${{package.name}}-manager ${{targets.subpkgdir}}/manager
    test:
      pipeline:
        - runs: |-
            set -euo pipefail
            manager --help

update:
  enabled: true
  github:
    identifier: k8ssandra/cass-operator
    strip-prefix: v
    tag-filter: v

test:
  environment:
    contents:
      packages:
        - cass-operator-compat-fips
        - cmd:mkcert
        - curl
        - wait-for-it
        - git
    environment:
      KUBERNETES_SERVICE_HOST: "127.0.0.1"
      KUBERNETES_SERVICE_PORT: "8080"
      WATCH_NAMESPACE: "default"
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |-
        set -euo pipefail
        manager --help
    - uses: test/kwok/cluster
    - name: Apply CRDs
      runs: kubectl apply --server-side=true -k github.com/k8ssandra/cass-operator/config/crd?ref=v${{package.version}}
    - name: Launch operator with dummy kubeconfig
      uses: test/daemon-check-output
      with:
        setup: |-
          set -euo pipefail
          kubectl config view --minify --raw > /tmp/kubeconfig.yaml
          mkcert example.com myapp.dev localhost 127.0.0.1 ::1
          mkdir -p /tmp/k8s-webhook-server/serving-certs
          mv example.com+4-key.pem /tmp/k8s-webhook-server/serving-certs/tls.key
          mv example.com+4.pem /tmp/k8s-webhook-server/serving-certs/tls.crt
          mkdir -p /configs
          touch /configs/image_config.yaml
          mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
          echo "default" > /var/run/secrets/kubernetes.io/serviceaccount/namespace
        start: manager --kubeconfig=/tmp/kubeconfig.yaml --metrics-bind-address=:8080 --metrics-secure=false
        timeout: 60
        expected_output: |
          Starting webhook server
          Starting Controller
          Updated current TLS certificate
          Starting certificate poll+watcher
        post: |-
          set -euo pipefail
          wait-for-it -t 3 --strict localhost:8081 -- echo "Health probe is up"
          echo "Verifying health endpoint"
          curl -sf http://127.0.0.1:8081/healthz
          echo "Health endpoint is serving as expected"
          echo "Verifying metrics endpoint"
          wait-for-it -t 3 --strict localhost:8080 -- echo "Metrics endpoint is up"
          curl -sf http://127.0.0.1:8080/metrics | grep -F "controller_runtime_"
          echo "Metrics endpoint is serving as expected"
