package:
  name: cg
  version: "0.2.209"
  epoch: 0 # GHSA-59jp-pj84-45mr
  description: Chainguard's internal tool for working with packages, images, and vulnerabilities
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/mono

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/mono
      expected-commit: fcec3312ed9d05efc96d53e071e75ae10a456731
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: |
        -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}}
        -X sigs.k8s.io/release-utils/version.gitCommit=$(git rev-parse HEAD)
        -X sigs.k8s.io/release-utils/version.buildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
      output: cg
      packages: .
      modroot: ./cg

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/mono
    strip-prefix: v

test:
  pipeline:
    - runs: |
        cg version
