package:
  name: chainguard-workstation-configs
  version: "0.0.1"
  epoch: 3
  description: Configuration files for the Chainguard Workstation
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - linux-pam
      - systemd

environment:
  contents:
    packages:
      - bash
      - busybox
      - curl
      - systemd

pipeline:
  - name: "Chainguard workstation config"
    runs: |
      # DISABLED for now
      #mkdir -p ${{targets.destdir}}/etc/profile.d/
      # Install 01-setup-chainctl.sh
      #cp 01-setup-chainctl.sh ${{targets.destdir}}/etc/profile.d/

      mkdir -p ${{targets.destdir}}/etc/systemd/logind.conf.d/
      cp logind.conf ${{targets.destdir}}/etc/systemd/logind.conf.d/workstation.conf

      # Chainguard Workstation boot service
      mkdir -p ${{targets.destdir}}/usr/lib/systemd/system
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm644 chainguard-workstation-boot.service ${{targets.destdir}}/usr/lib/systemd/system
      install -Dm755 chainguard-workstation-boot.sh ${{targets.destdir}}/usr/bin

test:
  pipeline:
    - runs: |
        #ls /etc/profile.d/01-setup-chainctl.sh
        systemd-analyze verify /usr/lib/systemd/system/chainguard-workstation-boot.service

update:
  enabled: false
  exclude-reason: No upstream
