package:
  name: chart-argo-argo-rollouts
  version: "2.40.6"
  epoch: 0
  description: A Helm chart for Argo Rollouts
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/argoproj/argo-helm
      tag: argo-rollouts-${{package.version}}
      expected-commit: e353ad43221b199169a9e8f0d72fd8ca90b80e0c

  - uses: charts/package
    with:
      chart-path: charts/argo-rollouts
      images: |
        argo-rollouts:
          values:
            controller:
              image:
                registry: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        kubectl-argo-rollouts:
          values:
            dashboard:
              image:
                registry: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
      test: |
        cases:
          - name: default
            images: [argo-rollouts]
          - name: with-dashboard
            images: [argo-rollouts, kubectl-argo-rollouts]
            values:
              dashboard:
                enabled: true

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: argoproj/argo-helm
    strip-prefix: argo-rollouts-
    use-tag: true
    tag-filter-prefix: argo-rollouts-
