package:
  name: chart-kubernetes-sigs-aws-fsx-csi-driver
  version: "1.15.0"
  epoch: 0
  description: A Helm chart for AWS FSx for Lustre CSI Driver
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/aws-fsx-csi-driver
      tag: helm-chart-aws-fsx-csi-driver-${{package.version}}
      expected-commit: 7446ae31747f668a93d9a14a71311b49fd301a3c

  - uses: charts/package
    with:
      chart-path: charts/aws-fsx-csi-driver
      images: |
        aws-fsx-csi-driver:
          values:
            image:
              repository: ${registry_repo}
              tag: ${pseudo_tag}
        csi-provisioner:
          values:
            sidecars:
              provisioner:
                image:
                  repository: ${registry_repo}
                  tag: ${pseudo_tag}
        csi-resizer:
          values:
            sidecars:
              resizer:
                image:
                  repository: ${registry_repo}
                  tag: ${pseudo_tag}
        livenessprobe:
          values:
            sidecars:
              livenessProbe:
                image:
                  repository: ${registry_repo}
                  tag: ${pseudo_tag}
        csi-node-driver-registrar:
          values:
            sidecars:
              nodeDriverRegistrar:
                image:
                  repository: ${registry_repo}
                  tag: ${pseudo_tag}
      test: |
        values:
          imagePullSecrets:
            - my-pull-secret
        cases:
          - name: default
            images: [aws-fsx-csi-driver, csi-provisioner, csi-resizer, livenessprobe, csi-node-driver-registrar]

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/aws-fsx-csi-driver
    strip-prefix: helm-chart-aws-fsx-csi-driver-
    use-tag: true
    tag-filter-prefix: helm-chart-aws-fsx-csi-driver-
