package:
  name: chart-prometheus-prometheus
  version: "28.6.1"
  epoch: 0
  description: Prometheus is a monitoring system and time series database.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-prometheus-alertmanager
      - chart-prometheus-kube-state-metrics
      - chart-prometheus-prometheus-node-exporter
      - chart-prometheus-prometheus-pushgateway

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/helm-charts
      tag: prometheus-${{package.version}}
      expected-commit: 39dff3ca9ca95b5e8eae564bdc2daeabfd277bae

  - uses: charts/package
    with:
      chart-path: charts/prometheus
      images: |
        prometheus:
          values:
            server:
              image:
                repository: ${registry_repo}
                tag: ${tag}
                digest: ${digest}
        prometheus-config-reloader:
          values:
            configmapReload:
              prometheus:
                image:
                  repository: ${registry_repo}
                  tag: ${tag}
                  digest: ${digest}
      test: |
        cases:
          - name: default
            images: [prometheus, prometheus-config-reloader]

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: prometheus-community/helm-charts
    strip-prefix: prometheus-
    use-tag: true
    tag-filter-prefix: prometheus-
