package:
  name: chart-argo-argo-workflows
  version: "0.47.4"
  epoch: 0
  description: A Helm chart for Argo Workflows
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/argoproj/argo-helm
      tag: argo-workflows-${{package.version}}
      expected-commit: f270b2d01fb2871c6d23eee90c435c15dbb8a6c2

  - uses: charts/package
    with:
      chart-path: charts/argo-workflows
      images: |
        workflow-controller:
          values:
            controller:
              image:
                registry: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        argoexec:
          values:
            executor:
              image:
                registry: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        argocli:
          values:
            server:
              image:
                registry: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
      test: |
        cases:
          - name: default
            images: [workflow-controller, argoexec, argocli]

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: argoproj/argo-helm
    strip-prefix: argo-workflows-
    use-tag: true
    tag-filter-prefix: argo-workflows-
