package:
  name: chart-opentelemetry-opentelemetry-collector
  version: "0.145.0"
  epoch: 0
  description: OpenTelemetry Collector Helm chart for Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-helm-charts
      tag: opentelemetry-collector-${{package.version}}
      expected-commit: 8ba8e06485a1ce9fb137b8cfd29f2d8093c8f0ea

  - uses: charts/package
    with:
      chart-path: charts/opentelemetry-collector
      images: |
        opentelemetry-collector:
          values:
            image:
              repository: ${registry_repo}
              tag: ${tag}
              digest: ${digest}
      test: |
        cases:
          - name: deployment
            images: [opentelemetry-collector]
            values:
              mode: deployment
          - name: daemonset
            images: [opentelemetry-collector]
            values:
              mode: daemonset
          - name: statefulset
            images: [opentelemetry-collector]
            values:
              mode: statefulset

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-helm-charts
    strip-prefix: opentelemetry-collector-
    use-tag: true
    tag-filter-prefix: opentelemetry-collector-
