package:
  name: chart-iamguarded-cloudnative-pg
  version: "1.0.11"
  epoch: 1
  description: cloudnative-pg iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: cloudnative-pg/${{package.version}}
      expected-commit: 98bb1e0bee60e843f71a3925a1b11d8f076a8715

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/cloudnative-pg

  - uses: charts/package
    with:
      chart-path: iamguarded/cloudnative-pg

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: cloudnative-pg/
    use-tag: true
    tag-filter-prefix: cloudnative-pg/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /cloudnative-pg
