package:
  name: chart-apache-couchdb
  version: "4.6.3"
  epoch: 0
  description: A database featuring seamless multi-master sync, that scales from big data to mobile, with an intuitive HTTP/JSON API and designed for reliability.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/couchdb-helm
      tag: couchdb-${{package.version}}
      expected-commit: d73290409d1c03fd7f9a8da9608db1e5259791e7

  - uses: charts/package
    with:
      chart-path: couchdb
      images: |
        couchdb:
          values:
            image:
              repository: ${registry_repo}
              tag: ${pseudo_tag}
        busybox:
          values:
            initImage:
              repository: ${registry_repo}
              tag: ${pseudo_tag}
        couchdb-search:
          values:
            searchImage:
              repository: ${registry_repo}
              tag: ${pseudo_tag}
        curl:
          values:
            autoSetup:
              image:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
        placement-manager:
          values:
            placementConfig:
              image:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
      test: |
        values:
          couchdbConfig:
            couchdb:
              uuid: decafbaddecafbaddecafbaddecafbad
        cases:
          - name: default
            images: [couchdb, busybox]
          - name: with-search
            images: [couchdb, busybox, couchdb-search]
            values:
              enableSearch: true
          - name: with-autosetup
            images: [couchdb, busybox, curl]
            values:
              autoSetup:
                enabled: true
          - name: with-placement-manager
            images: [couchdb, busybox, placement-manager]
            values:
              placementConfig:
                enabled: true

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: apache/couchdb-helm
    strip-prefix: couchdb-
    use-tag: true
    tag-filter-prefix: couchdb-
