package:
  name: chart-iamguarded-seaweedfs
  version: "6.0.4"
  epoch: 0
  description: seaweedfs iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common
      - chart-iamguarded-mariadb
      - chart-iamguarded-postgresql

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: seaweedfs/${{package.version}}
      expected-commit: 422ab34c39259f9852a8506f4b70c0d4aa62cff9

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/seaweedfs

  - uses: charts/package
    with:
      chart-path: iamguarded/seaweedfs

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: seaweedfs/
    use-tag: true
    tag-filter-prefix: seaweedfs/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /seaweedfs
