package:
  name: chart-iamguarded-grafana-alloy
  version: "1.0.7"
  epoch: 1
  description: grafana-alloy iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: grafana-alloy/${{package.version}}
      expected-commit: 7185daca622f7b0d80bb24dcb27fcaafc47498fb

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: patch
    with:
      patches: values.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/grafana-alloy

  - uses: charts/package
    with:
      chart-path: iamguarded/grafana-alloy

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: grafana-alloy/
    use-tag: true
    tag-filter-prefix: grafana-alloy/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /grafana-alloy
