package:
  name: chart-kedacore-keda
  version: "2.19.0"
  epoch: 0
  description: Event-based autoscaler for workloads on Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kedacore/charts
      tag: v${{package.version}}
      expected-commit: 86f514c2e28d70c8a0bf5ec1ad3cbec80b24ebf2

  - uses: charts/package
    with:
      chart-path: keda
      images: |
        keda:
          values:
            image:
              keda:
                registry: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        keda-metrics-apiserver:
          values:
            image:
              metricsApiServer:
                registry: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        keda-admission-webhooks:
          values:
            image:
              webhooks:
                registry: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
      test: |
        values:
          imagePullSecrets:
            - name: my-pull-secret
        cases:
          - name: default
            images: [keda, keda-metrics-apiserver, keda-admission-webhooks]

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: kedacore/charts
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
