package:
  name: chart-sigstore-tsa
  version: "2.0.3"
  epoch: 0
  description: Timestamp Authority issuing RFC3161 signed timestamps.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/helm-charts
      tag: tsa-${{package.version}}
      expected-commit: c6cb3e1b5497cd8b21f808c869c16c59329d97d2

  - uses: charts/package
    with:
      chart-path: charts/tsa
      images: |
        timestamp-server:
          values:
            server:
              image:
                registry: ${registry}
                repository: ${repo}
                version: ${pseudo_tag}
      test: |
        cases:
          - name: default
            images: [timestamp-server]

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: sigstore/helm-charts
    strip-prefix: tsa-
    use-tag: true
    tag-filter-prefix: tsa-
