package:
  name: chart-coredns-coredns
  version: "1.45.2"
  epoch: 0
  description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS Services
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/coredns/helm
      tag: coredns-${{package.version}}
      expected-commit: 64409d1fd2a63e56a639a1f164e59827cf5560bd

  - uses: charts/package
    with:
      chart-path: charts/coredns
      images: |
        coredns:
          values:
            image:
              repository: ${registry_repo}
              tag: ${pseudo_tag}
        cluster-proportional-autoscaler:
          values:
            autoscaler:
              image:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
      test: |
        cases:
          - name: default
            images: [coredns]
          - name: with-autoscaler
            images: [coredns, cluster-proportional-autoscaler]
            values:
              autoscaler:
                enabled: true

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: coredns/helm
    strip-prefix: coredns-
    use-tag: true
    tag-filter-prefix: coredns-
