package:
  name: chart-kubernetes-sigs-aws-load-balancer-controller
  version: "3.0.0"
  epoch: 0
  description: AWS Load Balancer Controller Helm chart for Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/aws-load-balancer-controller
      tag: v${{package.version}}
      expected-commit: eada2dbae991bf5936ae437052bbdf06295a0ea4

  - uses: charts/package
    with:
      chart-path: helm/aws-load-balancer-controller
      images: |
        aws-load-balancer-controller:
          values:
            image:
              repository: ${registry_repo}
              tag: ${pseudo_tag}
      test: |
        cases:
          - name: default
            images: [aws-load-balancer-controller]
            values:
              clusterName: test-cluster

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/aws-load-balancer-controller
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
