package:
  name: chart-iamguarded-grafana-loki
  version: "6.0.8"
  epoch: 1
  description: grafana-loki iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common
      - chart-iamguarded-grafana-alloy
      - chart-iamguarded-memcached

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: grafana-loki/${{package.version}}
      expected-commit: 98c8390a5d0407d018aa310afb39ab14b666fa06

  - uses: patch
    with:
      patches: iamguarded.patch

  # Required so we can specify our own images used in the chart
  - uses: patch
    with:
      patches: values.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/grafana-loki

  - uses: charts/package
    with:
      chart-path: iamguarded/grafana-loki

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: grafana-loki/
    use-tag: true
    tag-filter-prefix: grafana-loki/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /grafana-loki
