package:
  name: chart-hashicorp-consul
  version: "1.9.3"
  epoch: 0
  description: Official HashiCorp Consul Chart
  copyright:
    - license: MPL-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/consul-k8s
      tag: v${{package.version}}
      expected-commit: 7ffed3cda5431ef6117c8acb5ad1b4082b2b778c

  - uses: charts/package
    with:
      chart-path: charts/consul
      images: |
        consul:
          values:
            global:
              image: ${ref}
        consul-k8s-control-plane:
          values:
            global:
              imageK8S: ${ref}
        consul-dataplane:
          values:
            global:
              imageConsulDataplane: ${ref}
        consul-telemetry-collector:
          values:
            telemetryCollector:
              image: ${ref}
      test: |
        # Hardcoded images in the bundled prometheus addon template
        # (prometheus.yaml) are not configurable via values
        ignore:
          - jimmidyson/configmap-reload:v0.4.0
          - index.docker.io/jimmidyson/configmap-reload:v0.4.0
          - quay.io/prometheus/prometheus:v2.24.0
        cases:
          - name: default
            images: [consul, consul-k8s-control-plane, consul-dataplane]
          - name: with-gateways
            images: [consul, consul-k8s-control-plane, consul-dataplane]
            values:
              meshGateway:
                enabled: true
          - name: with-telemetry-collector
            images: [consul, consul-k8s-control-plane, consul-dataplane, consul-telemetry-collector]
            values:
              telemetryCollector:
                enabled: true
          - name: with-dns-proxy
            images: [consul, consul-k8s-control-plane, consul-dataplane]
            values:
              dns:
                proxy:
                  enabled: true
          - name: with-prometheus
            images: [consul, consul-k8s-control-plane, consul-dataplane]
            values:
              prometheus:
                enabled: true

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: hashicorp/consul-k8s
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
    tag-filter-contains: .
