package:
  name: chart-aws-observability-amazon-cloudwatch-observability
  version: "4.10.0"
  epoch: 0
  description: A Helm chart for Amazon CloudWatch Observability
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws-observability/helm-charts
      tag: amazon-cloudwatch-observability-${{package.version}}
      expected-commit: bbc75011d30d2e73db484f7f54ebab9058370a35

  - uses: charts/package
    with:
      chart-path: charts/amazon-cloudwatch-observability
      images: |
        cloudwatch-agent-operator:
          values:
            manager:
              image:
                repositoryDomainMap:
                  public: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        cloudwatch-agent:
          values:
            agent:
              image:
                repositoryDomainMap:
                  public: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        fluent-bit:
          values:
            containerLogs:
              fluentBit:
                image:
                  repositoryDomainMap:
                    public: ${registry}
                  repository: ${repo}
                  tag: ${pseudo_tag}
                  tagWindows: ${pseudo_tag}
        dcgm-exporter:
          values:
            dcgmExporter:
              image:
                repositoryDomainMap:
                  public: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        neuron-monitor:
          values:
            neuronMonitor:
              image:
                repositoryDomainMap:
                  public: ${registry}
                repository: ${repo}
                tag: ${pseudo_tag}
        target-allocator:
          values:
            agent:
              prometheus:
                targetAllocator:
                  image:
                    repositoryDomainMap:
                      public: ${registry}
                    repository: ${repo}
                    tag: ${pseudo_tag}
        auto-instrumentation-java:
          values:
            manager:
              autoInstrumentationImage:
                java:
                  repositoryDomain: ${registry}
                  repository: ${repo}
                  tag: ${pseudo_tag}
        auto-instrumentation-python:
          values:
            manager:
              autoInstrumentationImage:
                python:
                  repositoryDomain: ${registry}
                  repository: ${repo}
                  tag: ${pseudo_tag}
        auto-instrumentation-dotnet:
          values:
            manager:
              autoInstrumentationImage:
                dotnet:
                  repositoryDomain: ${registry}
                  repository: ${repo}
                  tag: ${pseudo_tag}
        auto-instrumentation-nodejs:
          values:
            manager:
              autoInstrumentationImage:
                nodejs:
                  repositoryDomain: ${registry}
                  repository: ${repo}
                  tag: ${pseudo_tag}
      test: |
        values:
          clusterName: test-cluster
          region: us-east-1
        cases:
          - name: default
            images:
              - cloudwatch-agent-operator
              - cloudwatch-agent
              - fluent-bit
              - dcgm-exporter
              - neuron-monitor
              - target-allocator
              - auto-instrumentation-java
              - auto-instrumentation-python
              - auto-instrumentation-dotnet
              - auto-instrumentation-nodejs

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: aws-observability/helm-charts
    strip-prefix: amazon-cloudwatch-observability-
    use-tag: true
    tag-filter-prefix: amazon-cloudwatch-observability-
