package:
  name: chart-mattermost-operator
  version: "1.0.4"
  epoch: 0
  description: A Helm chart for Mattermost Operator
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mattermost/mattermost-helm
      tag: mattermost-operator-${{package.version}}
      expected-commit: 21740a17e8377c3091f0bdf6ff534cbe5c9e31e1

  - uses: charts/package
    with:
      chart-path: charts/mattermost-operator
      images: |
        mattermost-operator:
          values:
            mattermostOperator:
              image:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
      test: |
        cases:
          - name: default
            images: [mattermost-operator]

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: mattermost/mattermost-helm
    strip-prefix: mattermost-operator-
    use-tag: true
    tag-filter-prefix: mattermost-operator-
