package:
  name: chart-flannel-io-flannel
  version: "0.28.1"
  epoch: 0
  description: Install Flannel Network Plugin.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flannel-io/flannel
      tag: v${{package.version}}
      expected-commit: 5b6fc3ae0bf7ce3abbffef72c1bd3e60cda58556

  - uses: charts/package
    with:
      chart-path: chart/kube-flannel
      chart-version: v${{package.version}}
      images: |
        flannel:
          values:
            flannel:
              image:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
        flannel-cni-plugin:
          values:
            flannel:
              image_cni:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
        kube-network-policies:
          values:
            netpol:
              image:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
      test: |
        cases:
          - name: default
            images: [flannel, flannel-cni-plugin]
          - name: with-netpol
            images: [flannel, flannel-cni-plugin, kube-network-policies]
            values:
              netpol:
                enabled: true

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: flannel-io/flannel
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
