package:
  name: chart-dandydeveloper-redis-ha
  version: "4.35.10"
  epoch: 0
  description: Highly available Kubernetes implementation of Redis
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/DandyDeveloper/charts
      tag: redis-ha-${{package.version}}
      expected-commit: f4aadb7523966fd3852589627c18db937415a439

  - uses: charts/package
    with:
      chart-path: charts/redis-ha
      images: |
        redis:
          values:
            image:
              repository: ${registry_repo}
              tag: ${pseudo_tag}
        haproxy:
          values:
            haproxy:
              image:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
        configmap-test:
          values:
            configmapTest:
              image:
                repository: ${registry_repo}
                tag: ${pseudo_tag}
        sysctl:
          values:
            sysctlImage:
              registry: ${registry}
              repository: ${repo}
              tag: ${pseudo_tag}
        exporter:
          values:
            exporter:
              image: ${registry_repo}
              tag: ${pseudo_tag}
      test: |
        values:
          imagePullSecrets:
            - name: pull-secret
        cases:
          - name: default
            images: [redis, configmap-test]
          - name: with-haproxy
            images: [redis, haproxy, configmap-test]
            values:
              haproxy:
                enabled: true
          - name: with-sysctl
            images: [redis, configmap-test, sysctl]
            values:
              sysctlImage:
                enabled: true
          - name: with-exporter
            images: [redis, configmap-test, exporter]
            values:
              exporter:
                enabled: true

test:
  pipeline:
    - uses: test/chart-standards

update:
  enabled: true
  github:
    identifier: DandyDeveloper/charts
    strip-prefix: redis-ha-
    use-tag: true
    tag-filter-prefix: redis-ha-
