package:
  name: chart-iamguarded-valkey
  version: "4.0.2"
  epoch: 0
  description: valkey iamguarded chart
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - chart-iamguarded-common

pipeline:
  - uses: auth/github
    with:
      repo: chainguard-dev/iamguarded-charts

  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/iamguarded-charts
      tag: valkey/${{package.version}}
      expected-commit: 134bd399b5c144171f03c23e839a2bf62487fe47

  - uses: patch
    with:
      patches: iamguarded.patch

  - uses: iamguarded/prepare
    with:
      chart-path: iamguarded/valkey

  - uses: charts/package
    with:
      chart-path: iamguarded/valkey

update:
  enabled: true
  github:
    identifier: chainguard-dev/iamguarded-charts
    strip-prefix: valkey/
    use-tag: true
    tag-filter-prefix: valkey/

test:
  pipeline:
    - uses: auth/github
      with:
        repo: chainguard-dev/iamguarded-charts
    - uses: iamguarded/validate
      with:
        chart-name: /valkey
