package:
  name: cloud-init
  version: "26.1"
  epoch: 0
  description: Cloud instance initialization
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - blkid
      - cmd:sudo
      - dhclient
      - e2fsprogs
      - glibc-locale-en
      - logger
      - lsblk
      - netcat-openbsd
      - openssh-pam-config # Optional - Enables login for locked accounts
      - py${{vars.python-version}}-configobj
      - py${{vars.python-version}}-jinja2
      - py${{vars.python-version}}-jsonpatch
      - py${{vars.python-version}}-jsonschema
      - py${{vars.python-version}}-netifaces
      - py${{vars.python-version}}-oauthlib
      - py${{vars.python-version}}-passlib
      - py${{vars.python-version}}-pyserial
      - py${{vars.python-version}}-pyyaml
      - py${{vars.python-version}}-requests
      - py${{vars.python-version}}-ssh-import-id-bin
      - sgdisk
      - shadow
      - systemd

vars:
  python-version: "3.13"

environment:
  contents:
    packages:
      - bash-completion
      - build-base
      - busybox
      - meson
      - py${{vars.python-version}}-configobj
      - py${{vars.python-version}}-jinja2
      - py${{vars.python-version}}-jsonpatch
      - py${{vars.python-version}}-jsonschema
      - py${{vars.python-version}}-passlib
      - py${{vars.python-version}}-pyserial
      - py${{vars.python-version}}-pytest
      - py${{vars.python-version}}-pytest-mock
      - py${{vars.python-version}}-pyyaml
      - py${{vars.python-version}}-requests
      - py${{vars.python-version}}-responses
      - python-${{vars.python-version}}
      - systemd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/canonical/cloud-init.git
      expected-commit: 8bf3567532b07e2cc15aa4c76c36ebed65ccfaec
      tag: ${{package.version}}

  - uses: patch
    with:
      patches: |
        chainguard-cloud-init.patch
        probe-cdrom.patch
        probe-cdrom-config.patch
        is_container-with-sshd-pid-1.patch

  - uses: meson/configure
    with:
      opts: |
        -Dlibexecdir=lib

  - uses: meson/compile

  - runs: |
      meson test --no-rebuild --print-errorlogs -C output

  - uses: meson/install

  - name: Install System Files
    runs: |
      install -vDm 644 ./systemd/disable-sshd-keygen-if-cloud-init-active.conf -t ${{targets.destdir}}/usr/lib/systemd/system/sshd-keygen@.service.d/

      # systemd-networkd-wait-online is timing out in ~2sec which is shorter than the default should be
      # It seems to also think it needs more interfaces configured that it really does
      # We'll consider ourselves online as long as any given interface is.
      mkdir -p ${{targets.destdir}}/usr/lib/systemd/system/systemd-networkd-online-wait.service.d/
      echo "[Service]\nExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any\n" >>  "${{targets.destdir}}/usr/lib/systemd/system/systemd-networkd-online-wait.service.d/10-any.conf"

  - name: Update shbangs for python version
    runs: |
      set +x
      for p in usr/bin/cloud-init usr/bin/cloud-id ; do
        fp="${{targets.destdir}}/$p"
        read orig < "$fp" ||
          { echo "FATAL: error reading shbang from $p"; exit 1; }
        case "$orig" in
          *python3) :;;
          *) echo "FATAL: $p unexpected shbang '$orig'"; exit 1;;
        esac

        # change python3 -> python3.X, and drop /usr/bin/env
        sed -i -e '1s,python3,python${{vars.python-version}},' \
          -e 's,/usr/bin/env ,/usr/bin/,' "$fp" ||
          { echo "FATAL: failed to update shbang in $p"; exit 1; }
        read new < "$fp" ||
          { echo "FATAL: error reading shbang after update in $p"; exit 1; }

        if [ "$orig" = "$new" ]; then
          echo "FATAL: update of shbang in $p failed (orig=new=$new)"; exit 1;
        fi

        echo "updated shbang in $p: '$orig' -> '$new'"
      done

subpackages:
  - name: "${{package.name}}-doc"
    description: "cloud-init documentation"
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/tw/docs

update:
  enabled: true
  github:
    identifier: canonical/cloud-init

test:
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: cloud-init
    - uses: test/tw/help-check
      with:
        bins: cloud-init
