package:
  name: dante
  version: 1.4.4
  epoch: 0
  description: Dante SOCKS server and client
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex

pipeline:
  - uses: fetch
    with:
      uri: https://www.inet.no/dante/files/dante-${{package.version}}.tar.gz
      expected-sha512: bf6b82fcad63d0920b77cebe360612a639c8532fbda6dc84f1bc88e89671e358f4819bf9759b1ba3bb7fbe703eec7e59d9cef620b6e65f177686d5b00e5f221a

  # ifdev.patch and gaierrval.patch are general bug fixes
  # glibc-interposition.patch converts K&R function definitions to ANSI C for glibc compatibility
  - uses: patch
    with:
      patches: ifdev.patch gaierrval.patch glibc-interposition.patch

  - runs: |
      CFLAGS="$CFLAGS -Wno-implicit-function-declaration -D_GNU_SOURCE" \
      ac_cv_func_sched_setscheduler=no ./configure --prefix=/usr --sbindir=/usr/bin

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      install -Dvm644 example/sockd.conf -t "${{targets.destdir}}"/etc/

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/devpackage

  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      environment:
        contents:
          packages:
            - glibc-iconv
      pipeline:
        - uses: test/docs

  - name: ${{package.name}}-server
    description: Dante SOCKS server
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/etc
          mkdir -p "${{targets.contextdir}}"/usr/bin
          mv "${{targets.destdir}}"/etc/sockd.conf "${{targets.contextdir}}"/etc/
          mv "${{targets.destdir}}"/usr/bin/sockd "${{targets.contextdir}}"/usr/bin/
    test:
      pipeline:
        - runs: |
            sockd -v

update:
  enabled: true
  release-monitor:
    identifier: 411

test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        socksify echo "test"
