#nolint:valid-spdx-license
package:
  name: databricks-cli-fips
  version: "0.287.0"
  epoch: 0 # CVE-2025-47907
  description: Databricks CLI for interacting with Databricks services
  copyright:
    - license: Databricks

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/databricks/cli
      tag: v${{package.version}}
      expected-commit: a001ca55ba0582484ceff8055f57c4a6c2ef0433

  - uses: go/build
    with:
      packages: .
      ldflags: |
        -X github.com/databricks/cli/internal/build.buildProjectName=databricks
        -X github.com/databricks/cli/internal/build.buildVersion=${{package.version}}
        -X github.com/databricks/cli/internal/build.buildBranch=$(git rev-parse --abbrev-ref HEAD)
        -X "github.com/databricks/cli/internal/build.buildTimestamp=$(date -u -d "@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%s)"
      output: databricks
      go-package: go-fips

update:
  enabled: true
  # Github backend cannot be used as the databricks org has our CI on their IP block list :(
  git:
    strip-prefix: v
  ignore-regex-patterns:
    - snapshot # Invalid tag

subpackages:
  - name: ${{package.name}}-compat
    description: Compatibility package for databricks CLI
    dependencies:
      runtime:
        - ${{package.name}}
        - terraform-fips
        - terraform-provider-databricks-fips
        - terraform-provider-databricks-fips-cli-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/app/bin
          ln -s /usr/bin/databricks ${{targets.contextdir}}/app/databricks
          ln -s /usr/bin/terraform ${{targets.contextdir}}/app/bin/terraform

          mkdir -p ${{targets.contextdir}}/app/config
          cp docker/config.tfrc ${{targets.contextdir}}/app/config/
    test:
      environment:
        environment:
          DATABRICKS_TF_CLI_CONFIG_FILE: /app/config/config.tfrc
          DATABRICKS_TF_EXEC_PATH: /app/bin/terraform
      pipeline:
        - runs: |
            export PATH="/app:$PATH"
            which databricks | grep /app/databricks
            /app/databricks --version
            /app/databricks --help
            /app/bin/terraform init

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |-
        databricks --version
        databricks --help
