package:
  name: docbook-xsl
  version: 1.79.2
  epoch: 0
  description: Stylesheets for converting DocBook XML into HTML, man pages and other presentations
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/docbook/xslt10-stylesheets/releases/download/release/${{package.version}}/docbook-xsl-${{package.version}}.tar.bz2
      expected-sha256: 316524ea444e53208a2fb90eeb676af755da96e1417835ba5f5eb719c81fa371

  - runs: |
      install_root="${{targets.destdir}}/usr/share/xml/docbook/xsl-ns-stylesheets"
      mkdir -p "${install_root}"

      dirs="common fo html manpages highlighting images epub htmlhelp javahelp website xhtml xhtml5 params lib extensions profiling assembly eclipse epub3 roundtrip slides template webhelp xhtml-1_1"

      for dir in $dirs; do
        if [ -d "$dir" ]; then
          echo "Installing $dir/..."
          cp -a "$dir" "${install_root}/"
        fi
      done

      files="VERSION.xsl catalog.xml COPYING README AUTHORS VERSION"

      for file in $files; do
        if [ -f "$file" ]; then
          echo "Installing $file..."
          cp -v "$file" "${install_root}/"
        fi
      done

test:
  pipeline:
    - uses: test/tw/contains-files
      with:
        files: |
          /usr/share/xml/docbook/xsl-ns-stylesheets/VERSION.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/manpages/docbook.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/html/docbook.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/fo/docbook.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/common/common.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/manpages/param.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/manpages/html-synop.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/html/param.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/lib/lib.xsl
          /usr/share/xml/docbook/xsl-ns-stylesheets/html/titlepage.templates.xsl

subpackages:
  - name: docbook-xsl-doc
    description: Documentation for DocBook XSL stylesheets
    pipeline:
      - runs: |
          docdir="${{targets.subpkgdir}}/usr/share/doc/docbook-xsl"
          mkdir -p "${docdir}"

          for f in README* NEWS* REL* CHANGELOG*; do
            [ -e "$f" ] && cp -a "$f" "${docdir}/"
          done
    test:
      pipeline:
        - uses: test/tw/docs

update:
  enabled: true
  github:
    identifier: docbook/xslt10-stylesheets
    use-tag: true
    tag-filter: 'release/'
    strip-prefix: 'release/'
