package:
  name: dockerize-fips
  version: "0.9.9"
  epoch: 1 # CVE-2025-61731
  description: Utility to simplify running applications in docker containers
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jwilder/dockerize
      tag: v${{package.version}}
      expected-commit: ffdb7e40867b108a2661e955562bae021e6f71e1

  - uses: go/build
    with:
      packages: .
      output: dockerize
      go-package: go-fips

update:
  enabled: true
  github:
    identifier: jwilder/dockerize
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    - runs: |
        dockerize --version
        dockerize --help
    - uses: test/go-fips-check
