package:
  name: flux-kustomize-controller-fips
  version: "1.8.0"
  epoch: 2 # GHSA-q9hv-hpm4-hj6x
  description: The GitOps Toolkit Kustomize reconciler
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - git
      - gnupg-fips
      - gnupg-fips-gpgconf
      - gnupg-fips-utils
      - gnupg-fips-wks-client
      - gpg-fips
      - gpg-fips-agent
      - gpg-fips-wks-server
      - gpgsm-fips
      - gpgv-fips
      - openssh-client
      - openssl-config-fipshardened
      - tzdata

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 40b3758089386f35aef0330b917ec8d388dadefb
      repository: https://github.com/fluxcd/kustomize-controller
      tag: v${{package.version}}

  - runs: |
      sed -i 's/go 1\.[0-9]\+\(\.[0-9]\+\)\?/go 1.25/' go.mod
      sed -i '/toolchain /d' go.mod

  - uses: go/bump
    with:
      deps: |-
        filippo.io/edwards25519@v1.1.1
        github.com/cloudflare/circl@v1.6.3

  - uses: go/build
    with:
      ldflags: -X main.Version=${{package.version}}
      output: kustomize-controller
      packages: .
      go-package: go-fips

  - uses: strip

update:
  ignore-regex-patterns:
    - api/
  enabled: true
  github:
    identifier: fluxcd/kustomize-controller
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/go-fips-check
    - uses: test/kwok/cluster
    - name: Verify kustomize-controller installation
      uses: test/daemon-check-output
      with:
        setup: |
          set -euo pipefail
          kubectl apply -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml
          kubectl wait --for=condition=Ready nodes --all
        start: kustomize-controller --health-addr :9441 --metrics-addr :8081
        expected_output: |
          Starting Controller
          Kustomization
          Starting workers
        timeout: 30
        post: |-
          set -euo pipefail
          curl -sf localhost:8081/metrics | grep -F rest_client_requests_total
