package:
  name: flux-notification-controller-fips
  version: "1.8.0"
  epoch: 0 # CVE-2025-61732
  description: The GitOps Toolkit event forwarded and notification dispatcher
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "4"
    memory: 10Gi

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-fips

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6c9097335fa657f238dfcc97c231a88428d00ac2
      repository: https://github.com/fluxcd/notification-controller
      tag: v${{package.version}}

  - runs: |
      sed -i 's/go 1\.[0-9]\+\(\.[0-9]\+\)\?/go 1.25/' go.mod
      sed -i '/toolchain /d' go.mod
      go mod tidy

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      CGO_ENABLED=1 go build \
        -ldflags="-X main.Version=${{package.version}}" \
        -trimpath -a -o "${{targets.destdir}}"/usr/bin/notification-controller .

  - uses: strip

update:
  enabled: true
  github:
    identifier: fluxcd/notification-controller
    strip-prefix: v
    tag-filter: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/go-fips-check
    - uses: test/kwok/cluster
    - name: Launch controller with kwok cluster
      uses: test/daemon-check-output
      with:
        setup: |
          kubectl apply -f https://github.com/fluxcd/notification-controller/releases/download/v${{package.version}}/notification-controller.crds.yaml
          kubectl wait --for=condition=Ready nodes --all
        start: notification-controller --health-addr :9441 --metrics-addr :8081
        timeout: 30
        expected_output: |
          Starting Controller
          Starting workers
        post: |
          curl --silent --fail localhost:8081/metrics
          curl --silent --fail localhost:9441/healthz
