package:
  name: foxx-cli
  version: "2.1.1"
  epoch: 4
  description: "CLI for managing Foxx services"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - nodejs

pipeline:
  - uses: npm/install
    with:
      package: ${{package.name}}
      prefix: ${{targets.contextdir}}/usr
      version: ${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: arangodb/foxx-cli
    use-tag: true
    tag-filter: v
    strip-prefix: v

test:
  pipeline:
    - name: Check help
      runs: |
        foxx --help
        foxx install --help
    - name: Initialize an example Foxx service
      runs: |
        foxx init -e
    - uses: test/tw/ldd-check
