package:
  name: fulcio-fips
  version: "1.8.5"
  epoch: 7
  description: Sigstore OIDC PKI
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 11Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/fulcio
      tag: v${{package.version}}
      expected-commit: eaae2f2be56df9dea5f9b439ec81bedae4c0978d

  - uses: go/bump
    with:
      deps: |-
        github.com/sigstore/sigstore@v1.10.4
        filippo.io/edwards25519@v1.1.1
        go.opentelemetry.io/otel/sdk@v1.40.0

  - uses: go/build
    with:
      packages: ./
      modroot: .
      output: fulcio
      go-package: go-fips

update:
  enabled: true
  github:
    identifier: sigstore/fulcio
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/go-fips-check
    - uses: test/tw/ver-check
      with:
        bins: fulcio
    - name: Run fulcio server
      runs: |-
        set -euo pipefail
        fulcio serve --ca=ephemeralca > out.log 2>&1 &
        echo "Sleep 2 seconds and try to retrieve root certificate"
        sleep 2
        # Verify server responds with root certificate (fails test if HTTP error or timeout)
        curl -sf localhost:8080/api/v1/rootCert

environment:
  contents:
    packages:
      - go-fips-1.25
