package:
  name: grype-db
  version: "0.51.0"
  epoch: 0 # GHSA-j5w8-q4qc-rx2x
  description: Application to create a Grype vulnerability database from upstream vulnerability data sources.
  copyright:
    - license: Apache-2.0

vars:
  python-version: 3.13

environment:
  contents:
    packages:
      - busybox
      - py${{vars.python-version}}-hatchling
      - py${{vars.python-version}}-pip
      - py${{vars.python-version}}-uv-dynamic-versioning
      - python-${{vars.python-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/grype-db
      tag: v${{package.version}}
      expected-commit: 013670be3fbdc9eea9e85f19c549aa48f8320e55

  - uses: go/build
    with:
      ldflags: -X main.version=${{package.version}}
      output: grype-db
      packages: ./cmd/grype-db

subpackages:
  - name: ${{package.name}}-manager
    description: Python manager component for Grype vulnerability database
    dependencies:
      runtime:
        - tzdata
        - git
        - libmagic
        - py${{vars.python-version}}-boto3
        - py${{vars.python-version}}-click
        - py${{vars.python-version}}-colorlog
        - py${{vars.python-version}}-dataclass-wizard
        - py${{vars.python-version}}-iso8601
        - py${{vars.python-version}}-mergedeep
        - py${{vars.python-version}}-magic
        - py${{vars.python-version}}-pyyaml
        - py${{vars.python-version}}-pyyaml-include
        - py${{vars.python-version}}-requests
        - py${{vars.python-version}}-semver
        - py${{vars.python-version}}-tabulate
        - py${{vars.python-version}}-yardstick
        - py${{vars.python-version}}-zstandard
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{vars.python-version}}
      - uses: strip
    test:
      pipeline:
        - runs: |
            grype-db-manager --help
            grype-db-manager --version

update:
  enabled: true
  git:
    strip-prefix: v

test:
  # grype-db pull needs a local copy of vunnel. Just choose one of the
  # supported python versions. They get tested more thoroughly in the
  # vunnel package tests.
  environment:
    contents:
      packages:
        - py3.12-vunnel-bin
  pipeline:
    - runs: |
        set -euxo pipefail
        cat <<EOF >> .grype-db.yaml
        provider:
          vunnel:
            executor: local
            generate-configs: true
        EOF
        cat .grype-db.yaml
        grype-db --version
        grype-db --help
        grype-db pull -g -p wolfi
