package:
  name: grype-fips
  version: "0.106.0"
  epoch: 1 # go/enterprise-rsc/grype-fips
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "12"
    memory: 11Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/grype
      tag: v${{package.version}}
      expected-commit: 823d98b8e9939d9f1a7e713463ff4c9b47fa051a

  - uses: go/build
    with:
      go-package: go-fips
      ldflags: -X main.version=${{package.version}}
      output: grype
      packages: ./cmd/grype

update:
  enabled: true
  github:
    identifier: anchore/grype
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        grype --version
        grype --help
        grype cgr.dev/chainguard/wolfi-base | grep -E "(No vulnerabilities found|VULNERABILITY)"
        grype db list
