package:
  name: ipcalc
  version: 0.51
  epoch: 0
  description: Ipv6 capable continuation of the subnet calculator
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - perl-cgi

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kjokjo/ipcalc
      expected-commit: 4ae72efb0424ba7d6cab0ee94ec9be5004083def
      tag: ${{package.version}}

  - runs: |
      install -Dpm0644 -t "${{targets.destdir}}/usr/share/man/man1/" "./${{package.name}}.1"
      install -Dpm0755 -t "${{targets.destdir}}/usr/bin/" "./${{package.name}}" "./${{package.name}}.cgi"

update:
  enabled: true
  git: {}

subpackages:
  - name: ${{package.name}}-doc
    description: Documentation for ${{package.name}}
    pipeline:
      - uses: split/alldocs
      - runs: install -Dpm0644 -t "${{targets.subpkgdir}}/usr/share/licenses/${{package.name}}/" license
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/tw/help-check
      with:
        bins: ipcalc
    - uses: test/tw/ver-check
      with:
        bins: ipcalc
    - runs: ipcalc.cgi | grep -F -e "<title>IP Calculator / IP Subnetting</title>"
    - runs: |
        OUTPUT="$(mktemp)"
        ipcalc 192.168.0.1/24 | tee "${OUTPUT}"
        grep -F -e "Netmask:   255.255.255.0" "${OUTPUT}"
        grep -F -e "HostMin:   192.168.0.1" "${OUTPUT}"
        grep -F -e "HostMax:   192.168.0.254" "${OUTPUT}"
