package:
  name: jaeger-operator-fips
  version: "1.65.0"
  epoch: 14 # GHSA-9h8m-3fm2-qjrq
  description: Jaeger Operator for Kubernetes to simplify the deployment and management of the Jaeger tracing platform.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "6"
    memory: 9Gi

environment:
  contents:
    packages:
      - openssl-config-fipshardened

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jaegertracing/jaeger-operator
      tag: v${{package.version}}
      expected-commit: 77c2ee4de53d07267002d6088e75eb7a34e5000d

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.27.0
        golang.org/x/net@v0.38.0
        go.opentelemetry.io/otel/sdk@v1.40.0

  - uses: go/build
    with:
      go-package: go-fips
      packages: .
      output: jaeger-operator

update:
  enabled: true
  github:
    identifier: jaegertracing/jaeger-operator
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
        - openssl
  pipeline:
    - uses: test/go-fips-check
    - uses: test/tw/help-check
      with:
        bins: jaeger-operator
    # AUTOGENERATED
    - uses: test/kwok/cluster
    - name: Launch operator with kwok cluster
      uses: test/daemon-check-output
      with:
        setup: |
          set -euo pipefail
          mkdir -p /tmp/k8s-webhook-server/serving-certs
          openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
            -keyout /tmp/k8s-webhook-server/serving-certs/tls.key \
            -out /tmp/k8s-webhook-server/serving-certs/tls.crt \
            -subj "/CN=jaeger-operator-webhook-service.default.svc" \
            -addext "subjectAltName=DNS:jaeger-operator-webhook-service.default.svc"
          kubectl apply -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v${{package.version}}/config/crd/bases/jaegertracing.io_jaegers.yaml
          sleep 1
        start: jaeger-operator start --metrics-port "8080" --health-probe-bind-address ":8081"
        timeout: 30
        expected_output: |
          Starting Controller
          Starting workers
          Serving webhook server
        post: |-
          set -euo pipefail
          curl -sf http://127.0.0.1:8080/metrics
          curl -sf http://127.0.0.1:8081/healthz
