# Adpated from:
package:
  name: jujutsu
  version: "0.38.0"
  epoch: 0 # go/enterprise-rsc/jujutsu
  description: Git-compatible distributed version control system
  copyright:
    - license: APACHE-2.0
  resources:
    cpu: "12"
    memory: 14Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jj-vcs/jj
      tag: v${{package.version}}
      expected-commit: 2508982cde5c7e4db0933e0b6469f9e778e71e28

  - uses: rust/cargobump

  - uses: cargo/build
    with:
      output: jj

subpackages:
  - name: jujutsu-docs
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/usr/share/man
          target/release/jj util install-man-pages ${{targets.destdir}}/usr/share/man
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: jj
    - uses: test/tw/ver-check
      with:
        bins: jj

update:
  enabled: true
  github:
    identifier: jj-vcs/jj
    use-tag: true
    strip-prefix: v
