package:
  name: knative-net-istio
  version: "1.21.0"
  epoch: 2 # CVE-2025-68121
  description: Knative net-istio defines a KIngress controller for Istio.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "2"
    memory: 8Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/knative-extensions/net-istio.git
      tag: knative-v${{package.version}}
      expected-commit: 3b01e1531d5089216e62a8224978bf01a679e0a2

data:
  - name: packages
    items:
      # controller: TO BE ADDED:
      webhook:

subpackages:
  - name: knative-net-istio-${{range.key}}
    range: packages
    description: Knative net-istio ${{range.key}} component.
    dependencies:
      runtime:
        - ca-certificates-bundle
    pipeline:
      - name: Build knative-net-istio-${{range.key}}
        uses: go/build
        with:
          packages: ./cmd/${{range.key}}
          output: ${{range.key}}
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - name: Check knative-net-istio-${{range.key}} runs
          runs: |
            ${{range.key}} --help

  - name: "knative-net-istio-${{range.key}}-compat"
    range: packages
    description: "compatibility symlinks package for knative-net-istio-${{range.key}}"
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /ko-app/
          mkdir -p ${{targets.contextdir}}/ko-app
          ln -sf /usr/bin/${{range.key}} ${{targets.contextdir}}/ko-app/${{range.key}}
    test:
      pipeline:
        - name: Test compat directory
          runs: |
            test "$(readlink -fv /ko-app/${{range.key}})" = "/usr/bin/${{range.key}}"

update:
  enabled: true
  github:
    identifier: knative-extensions/net-istio
    strip-prefix: knative-v

# Functional tests for webhook component
test:
  environment:
    environment:
      KUBERNETES_SERVICE_HOST: "127.0.0.1"
      KUBERNETES_SERVICE_PORT: "32764"
      SYSTEM_NAMESPACE: "knative-serving"
    contents:
      packages:
        - ${{package.name}}-webhook
        - ${{package.name}}-webhook-compat
        - istioctl
  pipeline:
    - uses: test/kwok/cluster
    - name: Test entrypoiny and logs
      uses: test/daemon-check-output
      with:
        setup: |
          kubectl apply -f https://github.com/knative/serving/releases/latest/download/serving-crds.yaml
          kubectl apply -f https://github.com/knative/serving/releases/latest/download/serving-core.yaml
          istioctl install -y
          kubectl apply -f "https://github.com/knative/net-istio/releases/download/knative-v${{package.version}}/net-istio.yaml"
        start: |
          webhook -kubeconfig ~/.kube/config
        timeout: 10
        # Omit 'ERROR':
        # * webhook throws: the object has been modified; please apply your changes to the latest version and try again
        # similar to https://github.com/chainguard-dev/enterprise-packages/blob/bd1af8f77530611d167efdb4d1d346517d6dea27/knative-serving-1.17.yaml#L105
        error_strings: |
          FATAL
          FAIL
          Traceback.*most.recent.call
          Exception in thread
          panic
          command not found
        expected_output: |
          Registering 1 clients
          Registering 2 informer factories
          Registering 3 informers
          Registering 3 controllers
          Running with Standard leader election
          Starting configmap watcher
          Starting informers
          Informers have been synced, unblocking admission webhooks
          Starting controllers
          Starting controller and workers
          Started workers
          will run in leader-elected mode with id
          Webhook is valid
          Updating webhook
          Reconcile succeeded
