package:
  name: kubernetes-ingress-defaultbackend-fips
  version: "1.38.1"
  epoch: 1 # go/enterprise-rsc/kubernetes-ingress-defaultbackend-fips
  description: 'A simple web server that respond 404 common used in kubernetes ingress, serve pages 404 at root and 200 at /healthz'
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "2"
    memory: 7Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/ingress-gce
      tag: v${{package.version}}
      expected-commit: d9bbdee23ccd3b9522a58357c5c2ae98ba9d6971

  - uses: go/build
    with:
      packages: ./cmd/404-server
      output: defaultbackend
      ldflags: -w
      vendor: true
      go-package: go-fips

update:
  enabled: true
  github:
    identifier: kubernetes/ingress-gce
    use-tag: true
    strip-prefix: v
  ignore-regex-patterns:
    - "1000.1.0" # Bad version

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        defaultbackend --help
