package:
  name: linkerd2-fips
  version: "26.2.1"
  epoch: 1 # CVE-2026-27141
  description: "meta linkerd package"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - yarn

vars:
  go-package: go-fips

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b5621f5c07d8ae36cb7393923dda871e90ece588
      repository: https://github.com/linkerd/linkerd2/
      tag: edge-${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.51.0

subpackages:
  - name: ${{package.name}}-web
    dependencies:
      runtime:
        - openssl-config-fipshardened
    pipeline:
      - runs: |
          ./bin/web setup install --frozen-lockfile
          ./bin/web build
          go build -mod=readonly -o web/web -ldflags "-w" ./web
          mkdir -p ${{targets.contextdir}}/app
          mkdir -p ${{targets.contextdir}}/templates
          cp -r ./web/app/dist ${{targets.contextdir}}/app
          cp -r ./web/templates ${{targets.contextdir}}/
          cp ./web/web ${{targets.contextdir}}/
    test:
      pipeline:
        - uses: test/go-fips-check
        - name: version and help message
          runs: |
            /web -version
            /web -help
            /web > web.log 2>&1 && cat web.log | grep 'starting admin server'

  - name: ${{package.name}}-cli
    dependencies:
      runtime:
        - openssl-config-fipshardened
    pipeline:
      - uses: go/build
        with:
          go-package: ${{vars.go-package}}
          packages: ./cli
          tags: prod
          output: linkerd
          ldflags: -X github.com/linkerd/linkerd2/pkg/version.Version=edge-${{package.version}}
    test:
      pipeline:
        - name: linkerd version check
          runs: linkerd version --client | grep ${{package.version}}

  - name: ${{package.name}}-proxy-identity
    dependencies:
      runtime:
        - openssl-config-fipshardened
    pipeline:
      - uses: go/build
        with:
          go-package: ${{vars.go-package}}
          packages: ./proxy-identity
          output: linkerd2-proxy-identity
          install-dir: lib/linkerd
    test:
      pipeline:
        - uses: test/go-fips-check
        - name: check presence of required files
          runs: |
            # executable doesn't have help or version flag.
            stat /usr/lib/linkerd/linkerd2-proxy-identity

  - name: ${{package.name}}-controller
    dependencies:
      runtime:
        - openssl-config-fipshardened
    pipeline:
      - uses: go/build
        with:
          go-package: ${{vars.go-package}}
          packages: ./controller/cmd/main.go
          tags: prod
          output: controller
    test:
      pipeline:
        - uses: test/go-fips-check
        - name: check presence of required files
          runs: |
            # executable doesn't have help or version flag.
            stat /usr/bin/controller

  - name: ${{package.name}}-controller-compat
    description: "upstream image have executable placed at /"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf /usr/bin/controller ${{targets.contextdir}}/controller
    # test added by a robot (compat)
    test:
      pipeline:
        - runs: |
            readlink -v /controller

  - name: ${{package.name}}-metrics-api
    dependencies:
      runtime:
        - ca-certificates-bundle
        - openssl-config-fipshardened
    pipeline:
      - uses: go/build
        with:
          go-package: ${{vars.go-package}}
          packages: ./viz/metrics-api/cmd/main.go
          tags: prod
          output: metrics-api
    test:
      pipeline:
        - uses: test/go-fips-check
        - name: version and help message
          runs: |
            /usr/bin/metrics-api -version
            /usr/bin/metrics-api -help

  - name: ${{package.name}}-metrics-api-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}
          ln -sf /usr/bin/metrics-api ${{targets.contextdir}}/metrics-api
    # test added by a robot (compat)
    test:
      pipeline:
        - runs: |
            readlink -v /metrics-api

  - name: ${{package.name}}-tap
    dependencies:
      runtime:
        - openssl-config-fipshardened
    pipeline:
      - uses: go/build
        with:
          go-package: ${{vars.go-package}}
          packages: ./viz/tap/cmd/main.go
          tags: prod
          output: tap
    test:
      pipeline:
        - uses: test/go-fips-check
        - runs: |
            # executable doesn't have help or version flags
            # it only take two args https://github.com/linkerd/linkerd2/blob/main/viz/tap/cmd/main.go (to be run inside kubernetes)
            stat /usr/bin/tap
            /usr/bin/tap api 2>&1 | grep "starting admin server"

  - name: ${{package.name}}-tap-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}
          ln -sf /usr/bin/tap ${{targets.contextdir}}/tap
    # test added by a robot (compat)
    test:
      pipeline:
        - runs: |
            readlink -v /tap

update:
  enabled: true
  github:
    identifier: linkerd/linkerd2
    tag-filter: edge-
    strip-prefix: edge-

# Based on package contents inspection, it was found that this origin package is empty apart from its own SBOM and this test was added to confirm it is empty and will fail if the package is no longer empty (contains more than an SBOM)
test:
  pipeline:
    - uses: test/emptypackage
