package:
  name: linux-qemu-6.18
  version: "6.18.15"
  epoch: 0
  description: "the QEMU generic linux kernel 6.18 LTS"
  copyright:
    - license: GPL-2.0
  resources:
    cpu: 16
    memory: 24Gi
  dependencies:
    # If installing linux:version-flavor with no preference,
    # make this default.
    provider-priority: 10
    runtime:
      - ${{package.name}}-modules=${{package.full-version}}
      # Ensure we get Chainguard branding in our VMs.
      - chainguard-baselayout

vars:
  # DO NOT BUMP
  # Pinned to certified build.
  jitterentropy-package: linux-jitterentropy-6.18
  jitterentropy-version: 6.18.0-r0

environment:
  environment:
    KBUILD_BUILD_USER: noreply
    KBUILD_BUILD_HOST: chainguard.dev
    KBUILD_BUILD_VERSION: Chainguard
  contents:
    packages:
      - bootc-dracut

var-transforms:
  - from: ${{package.name}}
    match: 'linux-(.*)'
    replace: '$1'
    to: flavor
  - from: ${{package.name}}
    match: 'linux-(.*)-[0-9.]+'
    replace: '$1-generic'
    to: config-flavor
  - from: ${{package.name}}
    match: 'linux-(.*)'
    replace: '${{package.full-version}}-$1'
    to: version-flavor
  # Turn "6.18.0" into "6.18", but keep "6.18.51" as "6.18.51"
  - from: ${{package.version}}
    match: '^(\d+[.]\d+)(?:[.]0|([.][1-9]\d*))$'
    replace: '$1$2'
    to: mangled-package-version
  - from: ${{package.version}}
    match: '^(\d+\.\d+)\.\d+$'
    replace: '$1'
    to: mangled-kernel-major-version

pipeline:
  - uses: kernel/version-check
    with:
      moniker: longterm

  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{vars.mangled-package-version}}
      expected-commit: df0dc1b06fb6b6461f9838694bf84079eca7562a

  - uses: patch
    with:
      patches: |
        patches/${{vars.mangled-kernel-major-version}}/0001-random-use-jitterentropy.patch
        patches/${{vars.mangled-kernel-major-version}}/0001-module-Make-use-of-platform-keyring-for-module-signa.patch
        patches/${{vars.mangled-kernel-major-version}}/0001-ignore-new-warnings.patch

  - uses: kernel/config
    with:
      base: ${{vars.mangled-kernel-major-version}}
      flavor: ${{vars.config-flavor}}
      make-targets: hardening.config
      version-flavor: ${{vars.version-flavor}}

  - uses: kernel/reusable-jitterentropy
    with:
      package: ${{vars.jitterentropy-package}}
      version: ${{vars.jitterentropy-version}}
      kernel-version: ${{vars.mangled-kernel-major-version}}

  - uses: kernel/build
    with:
      version-flavor: ${{vars.version-flavor}}

subpackages:
  - name: "${{package.name}}-boot-installed"
    description: "Linux kernel (installed for EFI)"
    dependencies:
      runtime:
        # Ensure we get Chainguard branding in our VMs.
        - ${{package.name}}-modules=${{package.full-version}}
        - chainguard-baselayout
        - systemd-boot-installed
      provides:
        - ${{package.name}}-boot-configuration=${{package.full-version}}
    pipeline:
      - uses: kernel/boot-installed
        with:
          version-flavor: ${{vars.version-flavor}}
          aarch64_console: ttyS0

  - name: "${{package.name}}-fips-boot-installed"
    description: "FIPS Linux kernel (installed for EFI)"
    dependencies:
      runtime:
        # Ensure we get Chainguard branding in our VMs.
        - ${{package.name}}-modules=${{package.full-version}}
        - chainguard-baselayout
        - systemd-boot-installed
      provides:
        - ${{package.name}}-boot-configuration=${{package.full-version}}
    pipeline:
      - uses: kernel/boot-installed
        with:
          version-flavor: ${{vars.version-flavor}}
          aarch64_console: ttyS0
          extra-args: fips=1

  - name: "${{package.name}}-modules"
    description: "Linux kernel modules"
    pipeline:
      - uses: kernel/modules
        with:
          version-flavor: ${{vars.version-flavor}}
    dependencies:
      runtime:
        - merged-lib
        - wolfi-baselayout

  - name: "${{package.name}}-bootc-boot-installed"
    description: "Linux kernel (installed for EFI)"
    dependencies:
      runtime:
        # Ensure we get Chainguard branding in our VMs.
        - ${{package.name}}-modules=${{package.full-version}}
        - chainguard-baselayout
        - systemd-boot-installed
      provides:
        - ${{package.name}}-boot-configuration=${{package.full-version}}
    pipeline:
      - uses: kernel/boot-installed
        with:
          version-flavor: ${{vars.version-flavor}}
      - uses: kernel/dracut
        with:
          version-flavor: ${{vars.version-flavor}}
          kmoddir: ${{targets.destdir}}-modules/usr/lib/modules/${{vars.version-flavor}}
          output: ${{targets.subpkgdir}}/usr/lib/modules/${{vars.version-flavor}}/initramfs.img
      - runs: |
          kmodd=usr/lib/modules/${{vars.version-flavor}}
          mkdir -p "${{targets.subpkgdir}}/$kmodd"
          mv ${{targets.subpkgdir}}/boot/chainguard/${{vars.version-flavor}}/linux \
             "${{targets.subpkgdir}}/$kmodd/vmlinuz"
          rm -Rf ${{targets.subpkgdir}}/boot

  - name: ${{package.name}}-headers
    description: Linux kernel headers
    pipeline:
      - uses: kernel/headers
        with:
          version-flavor: ${{vars.version-flavor}}

test:
  pipeline:
    - uses: kernel/test/kconfig/systemd
    - uses: kernel/test/config-snippet
      with:
        snippet: jitterentropy-6.18
        # CRYPTO_MANAGER_DISABLE_TESTS will just not be present instead
        # of being present with =n
        # CRYPTO_USER_API is =y (instead of =m) because it needs to be builtin for melange
        # test for that separately
        x86_64_exclude: CRYPTO_MANAGER_DISABLE_TESTS CRYPTO_USER_API
        aarch64_exclude: CRYPTO_MANAGER_DISABLE_TESTS CRYPTO_USER_API
    - uses: kernel/test/kconfig
      with:
        config-options: CRYPTO_USER_API
    - uses: kernel/test/config-snippet
      with:
        snippet: ${{vars.config-flavor}}
        # Depends on CONFIG_X86
        aarch64_exclude: VIRTIO_PCI_ADMIN_LEGACY
    - name: Test Basic Boot
      uses: kernel/test/console_grep
      with:
        string: "Unable to mount root fs"
    - name: Test for XFS
      uses: kernel/test/console_grep
      with:
        string: "xfs"
    - name: Test for NVME
      uses: kernel/test/console_grep
      with:
        string: "nvme nvme0: pci function"
    - name: Test for ip6tables
      uses: kernel/test/console_grep
      with:
        string: "Segment Routing with IPv6"
    - uses: kernel/test/random_quality
      with:
        args: fips=1
    - name: Test for reusable jent
      uses: kernel/test/console_grep
      with:
        string: "jitterentropy built from ${{vars.jitterentropy-version}}"
    - uses: kernel/test/modprobe
      with:
        modprobe: zram

update:
  enabled: true
  github:
    identifier: gregkh/linux
    use-tag: true
    strip-prefix: v
    tag-filter: v6.18
  version-transform:
    # mainline release tag x.y to kernel version x.y.0
    - match: ^(\d+[.]\d+)$
      replace: $1.0
