package:
  name: longhorn-spdk
  version: "24.09"
  epoch: 0
  description: "Storage Performance Development Kit(SPDK) by Longhorn"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - mount
      - python3

environment:
  contents:
    packages:
      - autoconf
      - automake
      - avahi-dev
      - bash
      - build-base
      - busybox
      - coreutils
      - file
      - fuse3-dev
      - libaio-dev
      - libtool
      - liburing-dev
      - meson
      - ninja
      - numactl-dev
      - openssl-dev
      - patchelf
      - posix-libc-utils # getconf
      - py3-grpcio-tools
      - py3-jinja2
      - py3-pandas
      - py3-paramiko
      - py3-pexpect
      - py3-pip
      - py3-pyelftools
      - py3-pyparsing
      - py3-tabulate
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/longhorn/spdk
      expected-commit: 19524ad45373e35d5fdc06f4e081444d87ceed80
      tag: v${{package.version}}
      recurse-submodules: true # (All submodules have BSD-3-Clause license)

  - runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --disable-examples \
        --disable-tests \
        --without-dpdk \
        --disable-unit-tests \
        --with-ublk

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-examples
    description: "Examples for ${{package.name}}"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/dpdk
          mv ${{targets.destdir}}/usr/share/dpdk/examples ${{targets.subpkgdir}}/usr/share/dpdk
    test:
      pipeline:
        - runs: |
            # Validate that the examples dir is non-empty
            [ "$(ls -A /usr/share/dpdk/examples)" ]

  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: ${{package.name}}-libs
    description: "libraries for ${{package.name}}"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/lib*.so.* ${{targets.subpkgdir}}/usr/lib
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: ${{package.name}}-binaries
    description: longhorn spdk subpackage containing only binaries
    pipeline:
      - runs: |
          # Upstream longhorn-instance-manager image only needs longhorn's spdk binaries
          # https://github.com/longhorn/longhorn-instance-manager/blob/master/package/Dockerfile#L130
          mkdir -p "${{targets.contextdir}}/usr/bin"
          # Copy all for spdk_* binaries
          cp -r ${{targets.destdir}}/usr/bin/spdk_* "${{targets.contextdir}}/usr/bin"
    test:
      pipeline:
        - runs: |
            test -f /usr/bin/spdk_cli
            test -f /usr/bin/spdk_dd
            test -f /usr/bin/spdk_lspci
            test -f /usr/bin/spdk_nvme_discover
            test -f /usr/bin/spdk_nvme_identify
            test -f /usr/bin/spdk_nvme_perf
            test -f /usr/bin/spdk_rpc
            test -f /usr/bin/spdk_tgt
            test -f /usr/bin/spdk_top
            test -f /usr/bin/spdk_trace
            test -f /usr/bin/spdk_trace_record

  - name: ${{package.name}}-compat
    description: "Compatibility package for upstream ${{package.name}} binaries"
    dependencies:
      runtime:
        - ${{package.name}}-binaries
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          # Symlink all spdk_* binaries
          ln -sf /usr/bin/spdk_cli "${{targets.subpkgdir}}"/usr/local/bin/spdk_cli
          ln -sf /usr/bin/spdk_dd "${{targets.subpkgdir}}"/usr/local/bin/spdk_dd
          ln -sf /usr/bin/spdk_lspci "${{targets.subpkgdir}}"/usr/local/bin/spdk_lspci
          ln -sf /usr/bin/spdk_nvme_discover "${{targets.subpkgdir}}"/usr/local/bin/spdk_nvme_discover
          ln -sf /usr/bin/spdk_nvme_identify "${{targets.subpkgdir}}"/usr/local/bin/spdk_nvme_identify
          ln -sf /usr/bin/spdk_nvme_perf "${{targets.subpkgdir}}"/usr/local/bin/spdk_nvme_perf
          ln -sf /usr/bin/spdk_rpc "${{targets.subpkgdir}}"/usr/local/bin/spdk_rpc
          ln -sf /usr/bin/spdk_tgt "${{targets.subpkgdir}}"/usr/local/bin/spdk_tgt
          ln -sf /usr/bin/spdk_top "${{targets.subpkgdir}}"/usr/local/bin/spdk_top
          ln -sf /usr/bin/spdk_trace "${{targets.subpkgdir}}"/usr/local/bin/spdk_trace
          ln -sf /usr/bin/spdk_trace_record "${{targets.subpkgdir}}"/usr/local/bin/spdk_trace_record
    test:
      pipeline:
        - uses: test/tw/symlink-check
          with:
            allow-absolute: true

update:
  enabled: true
  ignore-regex-patterns:
    - .*\+.*
    - .*-dev
    - .*-rc\d+
    - -pre
    - "-\\d+$"
    - ^\d+\.\d+\.\d+ # Ignore vX.Y.Z and longer (three-number versions)
    - ^[^0-9].* # Ignore anything not v<num>.* (e.g., vfoo)
    - ^\d+$ # Ignore v<number> with no dot
  github:
    identifier: longhorn/spdk
    use-tag: true
    strip-prefix: v

capabilities:
  add:
    - CAP_SYS_ADMIN # for creating mount target

test:
  environment:
    environment:
      SPDK_HUGEPAGE_DIR: /home/build/huge
    accounts:
      run-as: 0
    contents:
      packages:
        - openssl
        - mount
        - sudo
        - go-spdk-helper
  pipeline:
    - name: "Validate discovery binary"
      runs: |
        TMPLOG=$(mktemp)
        # nvme_discovery
        spdk_nvme_discover --transport "trtype:TCP adrfam:IPv4 traddr:192.168.100.8 trsvcid:4420" 2>&1 | tee "$TMPLOG" | grep -q "Cannot get hugepage information"
    - name: "Set up DPDK"
      runs: |
        # Set up for DPDK
        mkdir -p "${SPDK_HUGEPAGE_DIR}"
        mount -t hugetlbfs -o pagesize=2M none "${SPDK_HUGEPAGE_DIR}"
        mkdir -p /var/run/dpdk
    - name: "Functional tests for spdk_* binaries"
      uses: test/daemon-check-output
      with:
        setup: mktemp /tmp/spdk_dd_out.XXXXXX
        start: spdk_dd --if /dev/zero --of /tmp/spdk_dd_out.XXXXXX --count 64 --bs 4096 --no-huge --disable-cpumask-locks --mem-size 512 > /tmp/spdk.log 2>&1
        expected_output: |
          Starting SPDK
          started
          Total cores available: 1
        post: |
          [ "$(stat -c%s /tmp/spdk_dd_out.XXXXXX)" -eq $((64 * 4096)) ] || exit 1
          # Binary will give non-zero exit code since DPDK set up needs more deps, but this matches upstream longhorn SPDK configuration
          spdk_lspci 2>&1 | tee /tmp/spdk_lspci.log | grep -q "hugepage information"
