package:
  name: mcp-grafana-fips
  version: "0.11.2"
  epoch: 1
  description: MCP server for grafana
  dependencies:
    runtime:
      - ca-certificates
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/mcp-grafana
      tag: v${{package.version}}
      expected-commit: ca870bf3e585d0dcb305612ece1741f401f1e1a3

  - uses: go/build
    with:
      packages: ./cmd/mcp-grafana/main.go
      output: mcp-grafana
      go-package: go-fips

subpackages:
  - name: ${{package.name}}-compat
    description: compat package for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/app
          ln -sf /usr/bin/mcp-grafana ${{targets.contextdir}}/app/mcp-grafana
    test:
      pipeline:
        - runs: stat /app/mcp-grafana

update:
  enabled: true
  git:
    tag-filter-prefix: v
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - name: basic test
      runs: |
        mcp-grafana --help
      uses: test/daemon-check-output
      with:
        start: /usr/bin/mcp-grafana -log-level=debug --disable-proxied
        timeout: 30
        expected_output: |
          Starting Grafana MCP server
          Using Grafana configuration
          Creating Grafana client

environment:
  contents:
    packages:
      - go-fips-1.25
