package:
  name: nvshmem4py-cuda-13
  version: 0.1.2.36443669
  epoch: 0
  description: Source code to build the Python language bindings for NVSHMEM
  copyright:
    - license: BSD-3-Clause

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+)'
    replace: "$1"
    to: cuda-major-version

environment:
  contents:
    packages:
      - busybox

pipeline:
  - runs: |
      mkdir -p "${{context.name}}"

  - uses: fetch
    with:
      uri: "https://developer.download.nvidia.com/compute/nvshmem/redist/nvshmem_python/source/nvshmem_python-source-${{package.version}}_cuda${{vars.cuda-major-version}}-archive.tar.xz"
      expected-sha256: "2abf8e17c32e74b4b7ab804f779334bb90af2bc692208ee74ce0a21c7afad110"
      directory: "${{context.name}}"

  - runs: |
      mkdir -p "${{targets.contextdir}}/usr/src/"
      cp -a "${{context.name}}" "${{targets.contextdir}}/usr/src/"

update:
  enabled: false
  exclude-reason: "Requires an NVIDIA-specific release monitor"

test:
  pipeline:
    - uses: test/tw/contains-files
      with:
        dir: "/usr/src/nvshmem4py-cuda-${{vars.cuda-major-version}}/examples/"
        name: "*.py"
