package:
  name: onnx
  version: "1.18.0"
  epoch: 0
  description: Open Neural Network Exchange
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - protobuf-dev
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/onnx/onnx.git
      expected-commit: e709452ef2bbc1d113faf678c24e6d3467696e83
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      output-dir: output
      opts: |
        -DONNX_USE_LITE_PROTO=OFF \
        -DONNX_USE_PROTOBUF_SHARED_LIBS=ON \
        -DPython3_EXECUTABLE=/usr/bin/python3 \
        -DBUILD_SHARED_LIBS=ON

  - working-directory: output
    runs: ninja gen_onnx_proto

  - uses: cmake/build

  - uses: cmake/install

  - runs: install -Dpm0644 -t "${{targets.destdir}}/usr/include/onnx/" "./output/onnx/"*.proto

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: Onnxruntime development includes
    pipeline:
      - uses: split/dev

  - name: ${{package.name}}-static
    description: Onnxruntime static libraries
    pipeline:
      - uses: split/static

update:
  enabled: true
  github:
    identifier: onnx/onnx
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - build-base
        - onnx-dev
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        TEST_PROG_MAIN="onnxtest.cpp"
        tee "${TEST_PROG_MAIN}" <<'EOF'
        #include <iostream>
        #include "onnx/common/version.h"

        int main() {
          std::cout << ONNX_NAMESPACE::LAST_RELEASE_VERSION;
        }
        EOF
        c++ "${TEST_PROG_MAIN}" -o onnxtest
        ./onnxtest | grep -F -e "${{package.version}}"
