package:
  name: opentofu-fips-1.11
  version: "1.11.4"
  epoch: 0 # CVE-2025-61729
  copyright:
    - license: MPL-2.0
  dependencies:
    provides:
      - opentofu-fips=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2a9b7ac61409f7f22bde65c192c5814eb4b75cdf
      repository: https://github.com/opentofu/opentofu
      tag: v${{package.version}}

  - uses: go/build
    with:
      go-package: go-fips
      ldflags: -X 'github.com/opentofu/opentofu/version.dev=no'
      modroot: .
      output: tofu
      packages: ./cmd/tofu

update:
  enabled: true
  ignore-regex-patterns:
    - "rc"
    - "beta"
  github:
    identifier: opentofu/opentofu
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v1.11

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        tofu --version
        tofu --help
    - name: tofu Initialization
      runs: |
        echo "provider \"local\" {}" > example.tf
        tofu init -input=false || exit 1
    - name: tofu Plan Creation
      runs: |
        tofu plan -input=false -out=tfplan || exit 1
    - name: tofu Apply Execution
      runs: |
        tofu apply -input=false tfplan || exit 1
