package:
  name: openmpi-cuda-13.0
  version: "5.0.9"
  epoch: 1 # go/enterprise-rsc/openmpi-cuda-13.0
  description: Message passing library for high-performance computing
  copyright:
    - license: BSD-3-Clause-Open-MPI AND mpich2
  dependencies:
    replaces:
      - openmpi
    provides:
      - openmpi=${{package.version}}
    runtime:
      - hwloc-cuda-${{vars.cuda-version}}
      - numactl
      - openpmix
      - prrte
      - so:libfabric.so.1
      - so:libucm.so.0
      - so:libucp.so.0
      - so:libucs.so.0
      - so:libuct.so.0
  options:
    no-depends: true
  resources:
    cpu: "8"
    memory: 11Gi

var-transforms:
  - from: ${{package.name}}
    match: .*cuda-(\d+\.\d+)
    replace: $1
    to: cuda-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - flex
      - flex-dev
      - gfortran
      - hwloc-cuda-${{vars.cuda-version}}-dev
      - libevent-dev
      - libfabric-dev
      - libgomp
      - libtool
      - libxml2-16
      - libxml2-dev
      - nvidia-cuda-cudart-${{vars.cuda-version}}
      - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
      - nvidia-cuda-nvcc-${{vars.cuda-version}}
      - nvidia-cuda-nvcc-${{vars.cuda-version}}-dev
      - openpmix-dev
      - perl
      - posix-libc-utils
      - prrte-dev
      - py3-recommonmark
      - py3-sphinx-bin
      - py3-sphinx-rtd-theme
      - ucx-dev
      - zlib-dev
  environment:
    CUDA_HOME: /usr/local/cuda-${{vars.cuda-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-mpi/ompi
      tag: v${{package.version}}
      expected-commit: b79100b3fbbf45b3c6ed82a6b67b6346f8cfdc41
      recurse-submodules: true

  - runs: |
      perl autogen.pl
      chmod +x configure
      # workaround for https://github.com/open-mpi/ompi/issues/12257
      # see https://gitlab.archlinux.org/archlinux/packaging/packages/openmpi/-/blob/main/PKGBUILD#L51-54
      sed -i 's|WRAPPER__FCFLAGS|WRAPPER_FCFLAGS|g' configure
      sed -i 's|WRAPPER_EXTRA_FCFLAGS|WRAPPER_FCFLAGS|g' configure
      sed -i 's|"-I/usr/include",||' opal/tools/wrappers/opal_wrapper.c

  - uses: autoconf/configure
    with:
      opts: |
        --with-prefix=/usr \
        --with-libevent=external \
        --with-hwloc=external \
        --with-pmix=external \
        --with-prrte=external \
        --with-cuda=/usr/local/cuda-${{vars.cuda-version}}

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    options:
      no-depends: true
    dependencies:
      runtime:
        - ${{package.name}}==${{package.full-version}}
        - hwloc-cuda-${{vars.cuda-version}}-dev
    description: openmpi dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check
          with:
            packages: ${{context.name}}

  - name: ${{package.name}}-doc
    description: openmpi documenation
    pipeline:
      - uses: split/alldocs
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/share/openmpi
          cp -r examples ${{targets.contextdir}}/usr/share/openmpi
    test:
      pipeline:
        - uses: test/docs

test:
  environment:
    contents:
      packages:
        - build-base
        - gfortran
        - hwloc-cuda-${{vars.cuda-version}}
        - libcuda-stub-cuda-${{vars.cuda-version}}-dev
        - openjdk-17-default-jdk
        - openpmix-dev
        - ${{package.name}}
        - ${{package.name}}-dev
        - ${{package.name}}-doc
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: mpiexec mpirun ompi_info oshrun
    - uses: test/tw/help-check
      with:
        bins: mpiCC mpic++ mpicc mpicxx mpiexec mpirun ompi_info oshrun
    - runs: |
        cp -r /usr/share/openmpi/examples .
        cd examples
        mpifort --showme
        make

update:
  enabled: true
  github:
    identifier: open-mpi/ompi
    strip-prefix: v
    use-tag: true
