# Using go-fips-md5
# Upstream using md5 hashes for pod annotations
# Ref: https://github.com/percona/percona-server-mongodb-operator/blob/6dedac1d6a679fc2e1eb3aab38236d00968448bb/pkg/controller/perconaservermongodb/psmdb_controller.go#L1395-L1404
package:
  name: percona-server-mongodb-operator-fips
  version: "1.21.2"
  epoch: 3 # CVE-2025-68121
  description: Kubernetes Operator which deploys and manages Percona Server for MongoDB on Kubernetes clusters.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash-binsh
      - coreutils

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).(\d+).(\d+).*
    replace: "release-${1}-${2}-${3}"
    to: flag-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/percona/percona-server-mongodb-operator.git
      tag: v${{package.version}}
      expected-commit: db303972e57470cfb9415ecc48a382bf2cc32037

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/crypto@v0.45.0
        github.com/cert-manager/cert-manager@v1.18.5

  - uses: go/build
    with:
      packages: ./cmd/manager/main.go
      output: percona-server-mongodb-operator
      ldflags: -X main.GitCommit=$(git rev-parse HEAD) -X main.GitBranch=${{vars.flag-version}}
      go-package: go-fips-md5

subpackages:
  - name: percona-server-mongodb-operator-healthcheck-fips
    description: mongodb-healthcheck binary for percona-server-mongodb-operator
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/mongodb-healthcheck/main.go
          output: mongodb-healthcheck
          ldflags: -X main.GitCommit=$(git rev-parse HEAD) -X main.GitBranch=${{vars.flag-version}}
          go-package: go-fips-md5
    test:
      pipeline:
        - uses: test/go-fips-check
          with:
            package-match: percona-server-mongodb-operator-healthcheck-fips

update:
  enabled: true
  github:
    identifier: percona/percona-server-mongodb-operator
    strip-prefix: v

test:
  environment:
    environment:
      OPERATOR_NAME: percona-server-mongodb-operator
      WATCH_NAMESPACE: "*"
      LOG_STRUCTURED: "false"
      LOG_LEVEL: INFO
      RESYNC_PERIOD: 5s
      DISABLE_TELEMETRY: "false"
      VERSION: ${{package.version}}
    contents:
      packages:
        - percona-server-mongodb-operator-healthcheck-fips
  pipeline:
    - name: "Check FIPS"
      uses: test/go-fips-check
    - name: "Basic"
      runs: |
        percona-server-mongodb-operator --help
        mongodb-healthcheck --help
    - name: "Setup KWOK cluster"
      uses: test/kwok/cluster
    - name: "Install PSMDB CRD that the operator watches"
      runs: |
        kubectl apply --server-side -f https://raw.githubusercontent.com/percona/percona-server-mongodb-operator/v${{package.version}}/deploy/bundle.yaml
        kubectl wait --for=condition=Established crd --all --timeout=60s
    - name: "Verify operator"
      uses: test/daemon-check-output
      with:
        start: |
          ./psmdb-setup.sh
        timeout: 60
        expected_output: |
          Starting metrics server
          Serving metrics server
          starting server
          Starting EventSource
          Starting Controller
          Starting workers
