package:
  name: postgrest
  # https://docs.postgrest.org/en/latest/ says "Starting from v14.0, only
  # even-numbered MAJOR versions will be released, reserving odd-numbered
  # MAJOR versions for development".  Be careful to only update this to
  # even-numbered major versions.
  version: "14.3"
  epoch: 1
  description: "Serve a RESTful API from any PostgreSQL database"
  copyright:
    - license: "MIT"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cabal-install
      - libffi-dev
      - postgresql-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/PostgREST/postgrest"
      destination: "${{package.name}}"
      tag: "v${{package.version}}"
      expected-commit: "545f45d9de9399439f650d9ae91784d37c40587c"

  # Override upstream to allow building with GHC 9.14.
  - working-directory: "${{package.name}}"
    runs: |
      cat >cabal.project.local <<EOF
      allow-newer: *:Cabal, *:base, *:containers, *:ghc, *:ghc-bignum, *:template-haskell, *:text, *:time
      package postgrest
        ghc-options: -Wno-error=incomplete-record-selectors
      EOF

  # When updating to a new version, uncomment this and follow its instructions:
  # - working-directory: "${{package.name}}"
  #   uses: haskell/record-dependencies
  #
  - uses: haskell/fetch-dependencies

  - working-directory: "${{package.name}}"
    runs: cabal install -j"$(nproc)" --installdir="${{targets.destdir}}/usr/bin" --install-method=copy exe:postgrest

  - working-directory: "${{package.name}}"
    uses: haskell/install-cabal-freeze

  - uses: strip

update:
  enabled: true
  manual: true
  exclude-reason: "Requires manual updates using haskell/record-dependencies"
  github:
    identifier: PostgREST/postgrest
    strip-prefix: "v"
    tag-filter-prefix: "v"

# It's difficult to get the upstream test suite working, because it relies
# on a complex Nix setup.  We can at least run some smoke tests.
test:
  pipeline:
    - uses: test/tw/help-check
      with:
        bins: postgrest
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: postgrest
