package:
  name: prometheus-operator-fips
  version: "0.89.0"
  epoch: 2
  description: Prometheus Operator creates/configures/manages Prometheus clusters atop Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - merged-bin
      - wolfi-baselayout

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

vars:
  PKG: "github.com/prometheus/common"

environment:
  contents:
    packages:
      - go-fips-1.25
      - go-fips-md5
      - wget
      - xz

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-operator/prometheus-operator.git
      tag: v${{package.version}}
      expected-commit: e13fb157486c9957c11a88fca97bf1a758a915c8

  - uses: go/build
    with:
      go-package: go-fips
      packages: ./cmd/operator
      output: operator
      ldflags: |
        -X ${{vars.PKG}}/version.Revision=$(git rev-parse --short HEAD)
        -X ${{vars.PKG}}/version.BuildDate=$(date -d@${SOURCE_DATE_EPOCH} -u +'%Y-%m-%dT%H:%M:%SZ')
        -X ${{vars.PKG}}/version.Branch=$(git branch --show-current)
        -X ${{vars.PKG}}/version.Version=v${{package.version}}

  - runs: |
      # test uses the -race flag which is incompatible with -buildmode=pie
      unset GOFLAGS
      make test-unit

subpackages:
  - name: prometheus-config-reloader-fips
    description: Prometheus Operator creates/configures/manages Prometheus clusters atop Kubernetes
    dependencies:
      # REMOVE_POST_USRMERGE - https://github.com/orgs/wolfi-dev/discussions/40270
      provides:
        - prometheus-config-reloader-oci-entrypoint-compat-fips=${{package.full-version}}
      runtime:
        - merged-bin
        - wolfi-baselayout
    pipeline:
      - uses: go/build
        with:
          go-package: go-fips
          packages: ./cmd/prometheus-config-reloader
          output: prometheus-config-reloader
          ldflags: |
            -X ${{vars.PKG}}/version.Revision=$(git rev-parse --short HEAD)
            -X ${{vars.PKG}}/version.BuildDate=$(date -d@${SOURCE_DATE_EPOCH} -u +'%Y-%m-%dT%H:%M:%SZ')
            -X ${{vars.PKG}}/version.Branch=$(git branch --show-current)
            -X ${{vars.PKG}}/version.Version=v${{package.version}}
    test:
      pipeline:
        - uses: test/go-fips-check
          with:
            package-match: prometheus-config-reloader-fips
        - uses: test/tw/ver-check
          with:
            bins: prometheus-config-reloader
        - uses: test/tw/help-check
          with:
            bins: prometheus-config-reloader

  - name: prometheus-admission-webhook-fips
    description: Prometheus Operator creates/configures/manages Prometheus clusters atop Kubernetes
    pipeline:
      - uses: go/build
        with:
          go-package: go-fips
          packages: ./cmd/admission-webhook
          output: admission-webhook
          ldflags: |
            -X ${{vars.PKG}}/version.Revision=$(git rev-parse --short HEAD)
            -X ${{vars.PKG}}/version.BuildDate=$(date -d@${SOURCE_DATE_EPOCH} -u +'%Y-%m-%dT%H:%M:%SZ')
            -X ${{vars.PKG}}/version.Branch=$(git branch --show-current)
            -X ${{vars.PKG}}/version.Version=v${{package.version}}
    test:
      pipeline:
        - uses: test/go-fips-check
          with:
            package-match: prometheus-admission-webhook-fips
        - uses: test/tw/ver-check
          with:
            bins: admission-webhook
        - uses: test/tw/help-check
          with:
            bins: admission-webhook
    dependencies:
      runtime:
        - merged-bin
        - wolfi-baselayout

  - name: ${{package.name}}-iamguarded-compat
    description: "compat package for iamguarded"
    pipeline:
      - runs: |
          mkdir -p /opt/iamguarded/prometheus-operator/bin/
          ln -sf /usr/bin/operator /opt/iamguarded/prometheus-operator/bin/operator
      - uses: iamguarded/build-compat
        with:
          package: prometheus-operator
          version: ${{vars.major-version}}
      - uses: iamguarded/finalize-compat
        with:
          package: prometheus-operator
          version: ${{vars.major-version}}
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - runs: |
            set -euo pipefail
            stat /opt/iamguarded/prometheus-operator/bin/operator
            /opt/iamguarded/prometheus-operator/bin/operator --version
        - uses: iamguarded/test-compat
          with:
            package: prometheus-operator
            version: ${{vars.major-version}}

test:
  environment:
    contents:
      packages:
        - curl
        - git
        - prometheus-config-reloader-fips
        - prometheus-admission-webhook-fips
    environment:
      KUBERNETES_SERVICE_HOST: "127.0.0.1"
      KUBERNETES_SERVICE_PORT: "32764"
  pipeline:
    - uses: test/go-fips-check
    - uses: test/tw/ver-check
      with:
        bins: operator
    - uses: test/tw/help-check
      with:
        bins: operator
    - uses: test/kwok/cluster
      with:
        serviceaccount: true
    - name: Launch operator with kwok cluster
      uses: test/daemon-check-output
      with:
        setup: |
          set -euo pipefail
          kubectl apply -f https://github.com/prometheus-operator/prometheus-operator/releases/download/v${{package.version}}/stripped-down-crds.yaml
          # Wait for CRDs to be established before starting operator
          kubectl wait --for=condition=Established crd --all --timeout=60s
          kubectl create clusterrolebinding prometheus-operator-dev --clusterrole=cluster-admin --serviceaccount=default:default
        start: operator --web.listen-address ":8080"
        timeout: 30
        expected_output: |
          Starting Prometheus Operator
          connection established
          successfully synced all caches
        post: |
          set -euo pipefail
          curl -sf localhost:8080/healthz
          curl -sf localhost:8080/metrics

update:
  enabled: true
  github:
    identifier: prometheus-operator/prometheus-operator
    strip-prefix: v
