package:
  name: prometheus-node-exporter-fips
  version: "1.10.2"
  epoch: 4 # CVE-2025-61729
  description: Prometheus Exporter for machine metrics
  copyright:
    - license: Apache-2.0

vars:
  PKG: "github.com/prometheus/common"

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/node_exporter
      tag: v${{package.version}}
      expected-commit: 654f19dee6a0c41de78a8d6d870e8c742cdb43b9

  - uses: go/bump
    with:
      deps: |-
        github.com/opencontainers/selinux@v1.13.0
        golang.org/x/crypto@v0.45.0

  - uses: go/build
    with:
      go-package: go-fips
      packages: .
      output: node_exporter
      ldflags: |
        -X ${{vars.PKG}}/version.Revision=$(git rev-parse --short HEAD)
        -X ${{vars.PKG}}/version.BuildDate=$(date -d@${SOURCE_DATE_EPOCH} -u +'%Y-%m-%dT%H:%M:%SZ')
        -X ${{vars.PKG}}/version.Branch=$(git branch --show-current)
        -X ${{vars.PKG}}/version.Version=v${{package.version}}

subpackages:
  - name: ${{package.name}}-iamguarded-compat
    description: "iamguarded compat package for ${{package.name}}"
    pipeline:
      - uses: iamguarded/build-compat
        with:
          package: prometheus-node-exporter
          version: ${{vars.major-version}}
      - runs: |
          mkdir -p /opt/iamguarded/node-exporter/bin
          ln -sf /usr/bin/node_exporter /opt/iamguarded/node-exporter/bin/node_exporter
      - uses: iamguarded/finalize-compat
        with:
          package: prometheus-node-exporter
          version: ${{vars.major-version}}
    test:
      pipeline:
        - runs: stat /opt/iamguarded/node-exporter/bin/node_exporter
        - uses: iamguarded/test-compat
          with:
            package: prometheus-node-exporter
            version: ${{vars.major-version}}

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        node_exporter --version
        node_exporter --help

update:
  enabled: true
  git:
    strip-prefix: v
