package:
  name: prometheus-stackdriver-exporter
  version: "0.18.0"
  epoch: 15 # CVE-2025-61731
  description: Google Stackdriver Prometheus exporter
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/stackdriver_exporter
      tag: v${{package.version}}
      expected-commit: 3b1a6e9ebb85a176b8ab48639f8e0a2a4a2f7bcf

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.27.0
        golang.org/x/net@v0.38.0
        golang.org/x/crypto@v0.45.0

  - uses: go/build
    with:
      packages: .
      output: stackdriver_exporter
      ldflags: |
        -X github.com/prometheus/common/version.Version=${{package.version}}
        -X github.com/prometheus/common/version.Revision=${{package.epoch}}
        -X github.com/prometheus/common/version.Branch=v${{package.version}}
        -X github.com/prometheus/common/version.BuildUser=chainguard
        -X github.com/prometheus/common/version.BuildDate=$(date -u -d "@$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")

update:
  enabled: true
  github:
    identifier: prometheus-community/stackdriver_exporter
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - name: version check
      runs: |
        stackdriver_exporter --version 2>&1 | grep "chainguard"
        stackdriver_exporter --version 2>&1 | grep "$(date -u -d "@$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")"
        stackdriver_exporter --version 2>&1 | grep "branch: v${{package.version}}"
        stackdriver_exporter --version 2>&1 | grep "revision: ${{package.epoch}}"
        stackdriver_exporter --version 2>&1 | grep "version ${{package.version}}"
        stackdriver_exporter --help 2>&1 | grep "Show context-sensitive help"
