package:
  name: py3-yardstick
  version: "0.16.1"
  epoch: 0
  description: A tool for verifying database construction semantics
  copyright:
    - license: Apache-2.0

vars:
  pypi-package: yardstick
  import: yardstick

data:
  - name: py-versions
    # yardstick requires >= 3.11 to run
    items:
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-build-base
      - py3-supported-hatchling
      - py3-supported-uv-dynamic-versioning

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/yardstick
      tag: v${{package.version}}
      expected-commit: 56dbe57f31cacdba9787e514cb2f4732a9df5a98

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      runtime:
        - py${{range.key}}-click
        - py${{range.key}}-dataclass-wizard
        - py${{range.key}}-dataclasses-json
        - py${{range.key}}-gitpython
        - py${{range.key}}-importlib-metadata
        - py${{range.key}}-mergedeep
        - py${{range.key}}-omitempty
        - py${{range.key}}-prompt-toolkit
        - py${{range.key}}-pygments
        - py${{range.key}}-pyyaml
        - py${{range.key}}-requests
        - py${{range.key}}-tabulate
        - py${{range.key}}-xxhash
        - py${{range.key}}-zstandard
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      environment:
        contents:
          packages:
            - git
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}
    pipeline:
      - uses: split/bin
    test:
      pipeline:
        - runs: |
            set -euxo pipefail
            yardstick --help
            yardstick version

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  git:
    strip-prefix: v
