# this wont work for py3.13, we stick to py3.12 for now with flexibity to support later
package:
  name: py3-torch-tensorrt-cuda-12.9
  version: "2.10.0"
  epoch: 0
  description: Datasets, Transforms and Models specific to Computer Vision
  copyright:
    - license: BSD-3-Clause
  target-architecture:
    - x86_64
  resources:
    cpu: 16
    memory: 16Gi
  options:
    no-depends: true

vars:
  cudnn-version: 9
  gcc-version: 14
  pypi-package: torch-tensorrt
  import: torch_tensorrt

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version
  - from: ${{package.name}}
    match: '.*cuda-(\d+)\.\d+$'
    replace: '$1'
    to: cuda-major-version
  - from: ${{package.name}}
    match: '.*cuda-(\d+)\.(\d+)$'
    replace: 'cu$1$2'
    to: cuda-pyvariant

data:
  - name: py-versions
    items:
      3.12: "312"

environment:
  contents:
    packages:
      - bash
      - bazel-6
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-15
      - cmake
      - coreutils
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - gcc-${{vars.gcc-version}}-default
      - git
      - libffi-dev
      - libgomp
      - libjpeg-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libpng-utils
      - libtorch-cuda-${{vars.cuda-version}}-dev
      - ninja
      - nvidia-cuda-cccl-${{vars.cuda-version}}
      - nvidia-cuda-profiler-api-${{vars.cuda-version}}
      - nvidia-driver
      - nvidia-nccl-cuda-${{vars.cuda-version}}-dev
      - patchelf
      - posix-libc-utils
      - py3-supported-build-base-dev
      - py3-supported-numpy-2.2
      - tensorrt-cuda-${{vars.cuda-major-version}}
      - tensorrt-cuda-${{vars.cuda-major-version}}-dev
  environment:
    BUILD_VERSION: ${{package.version}}+${{vars.cuda-pyvariant}}
    CUDA_HOME: /usr/local/cuda-${{vars.cuda-version}}
    CMAKE_CUDA_ARCHITECTURES: all
    FORCE_CUDA: 1
    USE_CUDA: 1
    USE_CUDNN: 1
    VERBOSE: 1
    TORCH_CUDA_ARCH_LIST: "7.0 7.5 8.0 8.6 9.0 10.0 12.0+PTX"
    TORCH_NVCC_FLAGS: -Xfatbin -compress-all

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pytorch/TensorRT
      tag: v${{package.version}}
      expected-commit: 1a1c2e20dce4392c1c2a63d3587e86c9ca637c03

subpackages:
  # TODO: enable this when we have a working Open source NVIDIA TensorRT python module https://github.com/NVIDIA/TensorRT
  # - range: py-versions
  #   name: py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
  #   description: python${{range.key}} version of ${{vars.pypi-package}}
  #   dependencies:
  #     runtime:
  #       - cuda-toolkit-${{vars.cuda-version}}
  #       # For some reason this isn't detected
  #       - libgomp
  #       - libjpeg-turbo
  #       - libpng
  #       - nvidia-cudnn-${{vars.cudnn-version}}-cuda-${{vars.cuda-major-version}}
  #       - nvidia-nccl-cuda-${{vars.cuda-version}}
  #       - tensorrt-cuda-${{vars.cuda-major-version}}
  #       - openmp-17
  #       - py${{range.key}}-numpy-1.26
  #       - py${{range.key}}-pillow
  #       - py${{range.key}}-pyyaml
  #       - py${{range.key}}-torch-cuda-${{vars.cuda-version}}
  #       - py${{range.key}}-typing-extensions
  #       - py${{range.key}}-packaging
  #   pipeline:
  #     - name: Python Build
  #       runs: |
  #         export CUDA_HOME=/usr/local/cuda-${{vars.cuda-version}}
  #         export PATH="$CUDA_HOME/bin:$PATH"
  #         export CMAKE_CUDA_COMPILER=$CUDA_HOME/bin/nvcc
  #         export CUDACXX=$CUDA_HOME/bin/nvcc
  #         python${{range.key}} setup.py bdist_wheel --py-only
  #         python${{range.key}} -m pip install --verbose \
  #           --no-index --no-build-isolation --no-deps \
  #           --force-reinstall --no-compile --prefix=/usr "--root=${{targets.contextdir}}" dist/*.whl
  #         sitepkgd=$(python${{range.key}} -c 'import site; print(site.getsitepackages()[0])')
  #         python${{range.key}} -m compileall --invalidation-mode=unchecked-hash -r100 ${{targets.contextdir}}/$sitepkgd
  # Disabling it because we need NVIDIA tensorrt python module too
  # test:
  #   pipeline:
  #     - uses: python/import
  #       with:
  #         python: python${{range.key}}
  #         import: "torch_tensorrt"
  # - name: py3-supported-${{vars.pypi-package}}
  #   description: meta package providing ${{vars.pypi-package}} for supported python versions.
  #   dependencies:
  #     runtime:
  #       - py3.12-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
  - name: libtorch-tensorrt-cuda-${{vars.cuda-version}}
    description: Shared C++ torch-tensorrt extensions for python${{range.key}}
    dependencies:
      runtime:
        - libnvinfer-cuda-${{vars.cuda-major-version}}
        - libnvinfer-bin-cuda-${{vars.cuda-major-version}}
        - libnvinfer-plugin-cuda-${{vars.cuda-major-version}}
        - libnvinfer-cuda-${{vars.cuda-major-version}}
        - nvidia-cuda-cudart-${{vars.cuda-version}}
        - libtorch-cuda-${{vars.cuda-version}}
    options:
      no-depends: true
    pipeline:
      - name: Build torch-tensorrt
        runs: |
          # These env are re-declared here because in environment.environment, the variable substitution didn't work
          export CUDA_HOME=/usr/local/cuda-${{vars.cuda-version}}
          export PATH="$PATH:$CUDA_HOME/bin"

          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCUDA_TOOLKIT_ROOT_DIR=${CUDA_HOME} \
            -DTensorRT_ROOT=/usr/local/tensorrt \
            -DUSE_SYSTEM_NVTX=1 \
            -DCMAKE_CUDA_ARCHITECTURES=${CMAKE_CUDA_ARCHITECTURES}

          make -j$(nproc)
          make install DESTDIR="${{targets.contextdir}}"
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: libtorch-tensorrt-cuda-${{vars.cuda-version}}-dev
    description: Development headers for libtorch-tensorrt
    dependencies:
      runtime:
        - libtorch-tensorrt-cuda-${{vars.cuda-version}}
    pipeline:
      - uses: split/dev
        with:
          package: libtorch-tensorrt-cuda-${{vars.cuda-version}}
    test:
      pipeline:
        - uses: test/tw/ldd-check

update:
  enabled: true
  git:
    strip-prefix: v
    tag-filter-prefix: v

# Based on package contents inspection, it was found that this origin package is empty apart from its own SBOM and this test was added to confirm it is empty and will fail if the package is no longer empty (contains more than an SBOM)
test:
  pipeline:
    - uses: test/emptypackage
