package:
  name: py3-dogtag-pki
  version: "11.9.0"
  epoch: 0
  description: Python3 bindings for Dogtag PKI library
  copyright:
    - license: GPL-2.0-only

vars:
  pypi-package: dogtag-pki

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dogtagpki/pki.git
      tag: v${{package.version}}
      expected-commit: 6d405e8e8de0579dbefcebd8fbf8cee82d947763

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-cryptography
        - py${{range.key}}-ldap
        - py${{range.key}}-requests
        - py${{range.key}}-six
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: pki
        - uses: python/import
          with:
            python: python${{range.key}}
            import: pki.util
        - runs: |
            python${{range.key}} <<'EOF' | grep -F -e "/usr/share/pki"
            import pki
            print(pki.PACKAGE_VERSION)
            EOF

update:
  enabled: true
  github:
    identifier: dogtagpki/pki
    strip-prefix: v
    strip-suffix: -.*
    use-tag: true

test:
  pipeline:
    - uses: test/emptypackage
