package:
  name: py3-fastapi
  version: "0.129.2"
  epoch: 0
  description: A modern, fast (high-performance), web framework for building APIs with Python based on standard Python type hints
  copyright:
    - license: MIT

vars:
  pypi-package: fastapi
  import: fastapi

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

environment:
  contents:
    packages:
      - busybox
      - py3-supported-python

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fastapi/fastapi
      tag: ${{package.version}}
      expected-commit: 1e78a36b7310003f0ff634627d8a7bc53c6ccdee

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      runtime:
        - py${{range.key}}-annotated-doc
        - py${{range.key}}-pydantic
        - py${{range.key}}-starlette~0.50
        - py${{range.key}}-typing-extensions
    pipeline:
      - uses: py/chainguard-lib-install
        with:
          python: ${{range.key}}
      - runs: |
          # This package provides a /usr/bin/fastapi command, but it is
          # not usable without fastapi-cli, which isn't yet in wolfi.
          rm -rf ${{targets.contextdir}}/usr/bin
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: fastapi/fastapi
