package:
  name: py3-hatch-build-scripts
  version: "1.0.0"
  epoch: 2 # go/enterprise-rsc/py3-hatch-build-scripts
  description: A plugin for Hatch that runs build scripts and saves their artifacts.
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0
  resources:
    cpu: "1"
    memory: 2Gi

vars:
  pypi-package: hatch-build-scripts
  import: hatch_build_scripts

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-hatchling

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rmorshea/hatch-build-scripts
      tag: v${{package.version}}
      expected-commit: b45b87c333ac8e8338203d9dc3cc1212314434ea

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: rmorshea/hatch-build-scripts
    strip-prefix: v
