package:
  name: py3-flashinfer-python-cuda-13.0
  version: "0.6.4"
  epoch: 0
  description: Kernel Library for LLM Serving
  copyright:
    - license: Apache-2.0

vars:
  pypi-package: flashinfer
  import: flashinfer

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: "$1"
    to: cuda-version

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - py3-supported-build-base
      - py3-supported-torch-cuda-${{vars.cuda-version}}
  environment:
    CUDA_HOME: /usr/local/cuda-${{vars.cuda-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flashinfer-ai/flashinfer
      tag: v${{package.version}}
      expected-commit: f1e6fdcb8f65104047697f022b5d055ef022d763

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      runtime:
        - py${{range.key}}-cuda-python-cuda-${{vars.cuda-version}}
        - py${{range.key}}-einops
        - py${{range.key}}-ninja
        - py${{range.key}}-numpy-2.2
        - py${{range.key}}-nvidia-cudnn-frontend-cuda-${{vars.cuda-version}}
        - py${{range.key}}-nvidia-nvshmem-cuda-${{vars.cuda-version}}
        - py${{range.key}}-pynvml
        - py${{range.key}}-apache-tvm-ffi
        - py${{range.key}}-nvidia-cutlass-dsl-cuda-${{vars.cuda-version}}
        - py${{range.key}}-requests
        - py${{range.key}}-click
        - py${{range.key}}-tabulate
        - py${{range.key}}-tqdm
        - py${{range.key}}-torch-cuda-${{vars.cuda-version}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - name: "Install torch-c-dlpack-ext"
        runs: |
          # Fixes this runtime error:
          # /usr/lib/python3.10/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:106: UserWarning: Failed to JIT torch
          # c dlpack extension, EnvTensorAllocator will not be enabled. You may try AOT-module via `pip install torch-c-dlpack-ext`
          # Manual attempts to get it to compile using JIT were unsuccessful.
          pip${{range.key}} install --prefix=/usr --root=${{targets.contextdir}} --root-user-action ignore torch-c-dlpack-ext
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: test/tw/ldd-check
          with:
            # torch_c_dlpack_ext links against libtorch_python.so from torch package
            extra-library-paths: /usr/lib/python${{range.key}}/site-packages/torch/lib
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3-${{vars.pypi-package}}-bin-cuda-${{vars.cuda-version}}
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    pipeline:
      - uses: split/bin
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: flashinfer

  - name: py3-supported-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.11-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.12-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
        - py3.13-${{vars.pypi-package}}-cuda-${{vars.cuda-version}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: flashinfer-ai/flashinfer
    strip-prefix: v
