package:
  name: py3-hypothesis
  version: "6.150.2"
  epoch: 0
  description: The property-based testing library for Python
  copyright:
    - license: MPL-2.0

vars:
  pypi-package: hypothesis

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/HypothesisWorks/hypothesis.git
      tag: hypothesis-python-${{package.version}}
      expected-commit: a3d5bffcdc660527ff0ac5c977c0268748ad50c0

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-attrs
        - py${{range.key}}-exceptiongroup
        - py${{range.key}}-sortedcontainers
    pipeline:
      - working-directory: hypothesis-python
        uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}
        - runs: |
            python${{range.key}} <<'EOF' | tee output.txt
            from hypothesis import given, strategies as st

            @given(st.integers())
            def test_is_integer(n):
                print(f"called with {n}")
                assert isinstance(n, int)

            test_is_integer()
            EOF
            sed -n '1p' ./output.txt | grep -E -e "called with.*[[:digit:]]*"
            sed -n '2p' ./output.txt | grep -E -e "called with.*[[:digit:]]*"
            sed -n '3p' ./output.txt | grep -E -e "called with.*[[:digit:]]*"

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
        - py3-${{vars.pypi-package}}-bin
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}
        - py${{range.key}}-click
        - py${{range.key}}-libcst
        - py${{range.key}}-pyyaml
    pipeline:
      - uses: split/bin
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: hypothesis
        - uses: test/tw/ver-check
          with:
            bins: hypothesis

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage
        - uses: python/import
          with:
            python: python3.10
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.11
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.pypi-package}}
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.pypi-package}}

update:
  enabled: true
  git:
    strip-prefix: hypothesis-python-

test:
  pipeline:
    - uses: test/emptypackage
