package:
  name: py3-cuda-python-cuda-12.9
  version: "12.9.0"
  epoch: 0
  description: Low-level Python Bindings for CUDA
  copyright:
    - license: PROPRIETARY

var-transforms:
  - from: ${{package.name}}
    match: '.*cuda-(\d+\.\d+).*'
    replace: '$1'
    to: cuda-version

data:
  - name: py-versions
    items:
      3.10:
      3.11:
      3.12:
      3.13:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - nvidia-cuda-profiler-api-${{vars.cuda-version}}
      - py3-supported-build-base-dev
      - py3-supported-cython
      - py3-supported-pyclibrary
      - py3-supported-versioneer
  environment:
    CUDA_HOME: /usr/local/cuda-${{vars.cuda-version}}
    LIBRARY_PATH: /usr/local/cuda-${{vars.cuda-version}}/lib64

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NVIDIA/cuda-python
      tag: v${{package.version}}
      expected-commit: 34ef8252bf88f791d0339b3ee84eed2fff80a73e

subpackages:
  - range: py-versions
    name: py${{range.key}}-cuda-python-cuda-${{vars.cuda-version}}
    description: python${{range.key}} version of cuda-python
    dependencies:
      runtime:
        - py${{range.key}}-cuda-bindings-cuda-${{vars.cuda-version}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
        working-directory: cuda_python
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: cuda
        - uses: test/tw/ldd-check

  - name: py3-supported-cuda-python-cuda-${{vars.cuda-version}}
    description: meta package providing cuda-python for supported python versions.
    dependencies:
      runtime:
        - py3.10-cuda-python-cuda-${{vars.cuda-version}}
        - py3.11-cuda-python-cuda-${{vars.cuda-version}}
        - py3.12-cuda-python-cuda-${{vars.cuda-version}}
        - py3.13-cuda-python-cuda-${{vars.cuda-version}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: cuda
        - uses: python/import
          with:
            python: python3.11
            import: cuda
        - uses: python/import
          with:
            python: python3.12
            import: cuda
        - uses: python/import
          with:
            python: python3.13
            import: cuda

  - range: py-versions
    name: py${{range.key}}-cuda-bindings-cuda-${{vars.cuda-version}}
    description: python${{range.key}} version of cuda.bindings
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
        working-directory: cuda_bindings
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: cuda.bindings
        - uses: test/tw/ldd-check

  - name: py3-supported-cuda-bindings-cuda-${{vars.cuda-version}}
    description: meta package providing cuda.bindings for supported python versions.
    dependencies:
      runtime:
        - py3.10-cuda-bindings-cuda-${{vars.cuda-version}}
        - py3.11-cuda-bindings-cuda-${{vars.cuda-version}}
        - py3.12-cuda-bindings-cuda-${{vars.cuda-version}}
        - py3.13-cuda-bindings-cuda-${{vars.cuda-version}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: cuda.bindings
        - uses: python/import
          with:
            python: python3.11
            import: cuda.bindings
        - uses: python/import
          with:
            python: python3.12
            import: cuda.bindings
        - uses: python/import
          with:
            python: python3.13
            import: cuda.bindings

test:
  pipeline:
    - uses: test/emptypackage

update:
  enabled: true
  github:
    identifier: NVIDIA/cuda-python
    tag-filter-prefix: v12.9.
    strip-prefix: v
