package:
  name: py3-sepolgen
  version: "3.10"
  epoch: 0 # go/enterprise-rsc/py3-sepolgen
  description: "SELinux sepolicy python modules and apps"
  copyright:
    - license: GPL-2.0-only
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - busybox
      - coreutils
      - gcc
      - gettext
      - glibc-dev
      - libselinux-dev
      - libsemanage-dev
      - libsepol-dev
      - pkgconf-dev
      - py3-supported-pip
      - py3-supported-python-dev
  environment:
    SBINDIR: /usr/bin

vars:
  pypi-package: sepolgen

data:
  - name: py-versions
    items:
      3.13: "313"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SELinuxProject/selinux.git
      tag: ${{package.version}}
      expected-commit: ca10fc4204ed60540d41d2499127c18ad0643f9e

  - runs: |
      # Depends on GUI, dbus, glade and not yet unpackaged deps
      sed '1s|sepolicy||' -i python/Makefile

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - libselinux-python
    pipeline:
      - uses: autoconf/make-install
        working-directory: python
        with:
          opts: PYTHON=python${{range.key}}
      - runs: |
          sed '1s|python3 |python${{range.key}} |' -i ${{targets.contextdir}}/usr/bin/*
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: import ${{vars.pypi-package}}
        - uses: test/tw/ldd-check
        - uses: test/tw/help-check
          with:
            bins: audit2allow audit2why chcat semanage sepolgen-ifgen

  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
        with:
          package: py3.13-${{vars.pypi-package}}
      - runs: |
          rm -rf ${{targets.outdir}}/py3*-${{vars.pypi-package}}/usr/share/man
    test:
      pipeline:
        - uses: test/docs

  - name: ${{package.name}}-locales
    description: ${{package.name}} locale files
    pipeline:
      - uses: split/locales
        with:
          package: py3.13-${{vars.pypi-package}}
      - runs: |
          rm -rf ${{targets.outdir}}/py3*-${{vars.pypi-package}}/usr/share/locale

update:
  enabled: true
  github:
    identifier: SELinuxProject/selinux
    use-tag: true
    tag-filter: policycoreutils-
    strip-prefix: policycoreutils-

test:
  pipeline:
    - uses: test/emptypackage
