package:
  name: py3-xformers-cuda-12.9
  version: 0.0.31
  epoch: 1
  description: Toolbox to Accelerate Research on Transformers
  copyright:
    - license: BSD-3-Clause
  target-architecture:
    - x86_64
  # arm64 is not officially supported, https://github.com/facebookresearch/xformers/issues/1071
  # https://github.com/facebookresearch/xformers/issues/1142
  resources:
    cpu: 128
    memory: 256Gi

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "313"

vars:
  # Let's use gcc-12, since we also use it to build torch.
  gcc-version: 12
  pypi-package: xformers
  cuda-version: "12.9"
  cuda-major-version: "12"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cuda-toolkit-${{vars.cuda-version}}-dev
      - gcc-${{vars.gcc-version}}
      - nvidia-cuda-cccl-${{vars.cuda-version}}
      - py3-supported-build-base
      - py3-supported-build-base-dev
      - py3-supported-torch-cuda-${{vars.cuda-version}}
      - py3-supported-torch-cuda-${{vars.cuda-version}}-dev
      - samurai
  environment:
    # Should match corresponding py3.x-torch-x.x-cuda-x.x package
    TORCH_CUDA_ARCH_LIST: "7.0 7.2 7.5 8.0 8.6 8.7 8.9 9.0 9.0a"
    CUDA_HOME: /usr/local/cuda-${{vars.cuda-version}}
    NVCC_APPEND_FLAGS: -ccbin gcc-${{vars.gcc-version}} --compiler-options -fdelete-null-pointer-checks
    NVCC_FLAGS: -Xfatbin -compress-all
    MAX_JOBS: 16

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/facebookresearch/xformers
      tag: v${{package.version}}
      expected-commit: eb0946a363464da96ea40afd1a7f72a907c25497
      recurse-submodules: true

subpackages:
  - range: py-versions
    name: py${{range.key}}-xformers-cuda-${{vars.cuda-version}}
    description: python${{range.key}} version of xformers with CUDA ${{vars.cuda-version}} support
    dependencies:
      runtime:
        - py${{range.key}}-torch-cuda-${{vars.cuda-version}}
    options:
      no-depends: true
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
    test:
      environment:
        contents:
          packages:
            - python-${{range.key}}
      pipeline:
        - uses: test/tw/pip-check
          with:
            python: python${{range.key}}
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}
        - uses: test/tw/ldd-check

update:
  enabled: false # https://github.com/chainguard-dev/internal-dev/issues/8369
  github:
    identifier: facebookresearch/xformers
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/byproductpackage
