#nolint:valid-pipeline-git-checkout-tag
package:
  name: pythoncapi-compat
  version: "0_git20260212"
  epoch: 0
  description: "The pythoncapi-compat project can be used to write a C extension supporting a wide range of Python versions with a single code base."
  copyright:
    - license: 0BSD

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-sphinx-bin

vars:
  header: usr/include/pythoncapi-compat/pythoncapi_compat.h

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python/pythoncapi-compat.git
      expected-commit: f6121eb60f9fe9ff227fc78f9b39d3bd2a81f434
      branch: main

  - runs: |
      install -Dm 0644 pythoncapi_compat.h ${{targets.destdir}}/${{vars.header}}
      cd docs
      make man
      install -Dm0644 build/man/pythoncapi_compat.1 ${{targets.destdir}}/usr/share/man/man1/pythoncapi_compat.1

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    description: "${{package.name}} manpages"
    pipeline:
      - uses: split/alldocs
    test:
      pipeline:
        - uses: test/tw/docs

update:
  enabled: true
  git: {}
  schedule:
    period: weekly
    reason: No releases, everything is commit based.

test:
  pipeline:
    - uses: test/tw/no-docs
    - name: "verify header exists"
      runs: stat /${{vars.header}}
