package:
  name: selinux-policy
  version: "42.24"
  epoch: 0
  description: "SELinux policy"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      # fixfiles needs these
      - coreutils
      - grep
      - merged-sbin
      - wolfi-baselayout

vars:
  common-args: -O -j $(nproc) V=1 VERBOSE=1 DISTRO=redhat UBAC=n DIRECT_INITRC=n MONOLITHIC=n MLS_CATS=1024 MCS_CATS=1024 UNK_PERMS=allow NAME=targeted TYPE=mcs

environment:
  contents:
    packages:
      - build-base
      - busybox
      - checkpolicy
      - coreutils
      - m4
      - policycoreutils
      - py3.13-sepolgen
      - python-3.13
      - semodule-utils

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fedora-selinux/selinux-policy
      tag: v${{package.version}}
      expected-commit: 08735516ec1c70d4a1de713c6af4b7c7de0de20b

  - uses: git-checkout
    with:
      repository: https://github.com/GoogleCloudPlatform/guest-oslogin.git
      tag: "20240701.00"
      expected-commit: 2170de85a8a11c3eabd4d853940b7810a677560b
      destination: guest-oslogin

  - uses: git-checkout
    with:
      repository: https://github.com/containers/container-selinux.git
      tag: "v2.245.0"
      expected-commit: 3f7c37e93e172f531de233f40a58a1b8ec6ff17d
      destination: container-selinux
      cherry-picks: |
        main/ca81cea9466e8e7f485da725331e3ef317dfaf68: Fix XML to avoid build errors

  - runs: |
      git -c "user.name=Melange Build" -c "user.email=melange-build@cgr.dev" am *.patch

  - runs: |
      # join guest-oslogin policy; create missing interface file
      cp guest-oslogin/selinux/oslogin.* policy/modules/contrib
      touch policy/modules/contrib/oslogin.if
      {
        echo
        echo "# Layer: services"
        echo "# Module: oslogin"
        echo "oslogin = module"
        echo
      } >>dist/targeted/modules.conf

      # join container-selinux policy; remove stub interfaces
      cp container-selinux/container.* policy/modules/contrib
      {
        echo
        echo "# Layer: services"
        echo "# Module: container"
        echo "container = module"
        echo
      } >>dist/targeted/modules.conf

      # lots of dir/file creation
      # create policy defaults
      make ${{vars.common-args}} bare
      make ${{vars.common-args}} conf
      # install policy defaults
      install -p -m0644 ./dist/targeted/booleans.conf ./policy/booleans.conf
      install -p -m0644 ./dist/targeted/modules.conf ./policy/modules.conf
      make ${{vars.common-args}} base.pp
      make ${{vars.common-args}} SEMOD_EXP="semodule_expand -a " validate
      make ${{vars.common-args}} modules
      make ${{vars.common-args}} DESTDIR=${{targets.contextdir}} install
      make ${{vars.common-args}} DESTDIR=${{targets.contextdir}} install-appconfig
      mkdir -p ${{targets.contextdir}}/var/lib/selinux/targeted
      make ${{vars.common-args}} DESTDIR=${{targets.contextdir}} SEMODULE="semodule -p ${{targets.contextdir}} -X 100 " load
      : > ${{targets.contextdir}}/etc/selinux/config
      echo SELINUX=enforcing >> ${{targets.contextdir}}/etc/selinux/config
      echo SELINUXTYPE=targeted >> ${{targets.contextdir}}/etc/selinux/config

subpackages:
  - name: ${{package.name}}-permissive
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/etc/selinux
          : > ${{targets.contextdir}}/etc/selinux/config
          echo SELINUX=permissive >> ${{targets.contextdir}}/etc/selinux/config
          echo SELINUXTYPE=targeted >> ${{targets.contextdir}}/etc/selinux/config

update:
  enabled: true
  github:
    identifier: fedora-selinux/selinux-policy
    use-tag: true
    tag-filter: v
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/contains-files
      with:
        dir: "/var/lib/selinux/targeted/active/modules/100/powerprofiles/"
        name: "*"
