package:
  name: siderolabs-kubelet-1.32
  version: "1.32.13"
  epoch: 0
  description: Siderolabs Kubelet meta package with slim dependencies for Talos Linux
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - siderolabs-kubelet=${{package.full-version}}
    runtime:
      - ca-certificates
      - iptables
      - keyutils
      - kubelet-1.32
      - libcap-utils
      - mount
      - nftables
      - util-linux

environment:
  contents:
    packages:
      - busybox

pipeline:
  - runs: |
      cp Dockerfile /tmp/expected-Dockerfile

  - uses: git-checkout
    with:
      repository: https://github.com/siderolabs/kubelet
      tag: v${{package.version}}
      expected-commit: b378b1eca366388557dad31122de10b0b6619c52

  - name: Verify upstream Dockerfile hasn't changed
    runs: |
      diff -u /tmp/expected-Dockerfile Dockerfile

test:
  pipeline:
    - uses: test/metapackage

subpackages:
  - name: ${{package.name}}-compat
    description: Siderolabs Kubelet 1.32 compat symlink
    dependencies:
      provides:
        - siderolabs-kubelet-compat=${{package.full-version}}
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/local/bin" "${{targets.subpkgdir}}/var"
          ln -sf /usr/bin/kubelet-1.32 "${{targets.subpkgdir}}/usr/local/bin/kubelet"
    test:
      pipeline:
        - uses: test/tw/symlink-check
          with:
            allow-absolute: true
        - runs: |
            stat /usr/local/bin/kubelet

update:
  enabled: true
  github:
    identifier: siderolabs/kubelet
    strip-prefix: v
    tag-filter-prefix: v1.32.
