package:
  name: temporal-fips
  version: "1.6.1"
  epoch: 0 # GHSA-9h8m-3fm2-qjrq
  description: Command-line interface for running Temporal Server and interacting with Workflows, Activities, Namespaces, and other parts of Temporal
  copyright:
    - license: MIT
  dependencies:
    runtime:
      # for fips config & fips-provider
      - openssl-config-fipshardened
      # either melange SCA should provide these
      # or we should make go-fips shared link on these
      - so:libcrypto.so.3
      - so:libssl.so.3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/temporalio/cli
      tag: v${{package.version}}
      expected-commit: 9a1a4eb18dbf8719f950207a8d026ee48fe33dbd

  - uses: go/bump
    with:
      deps: |-
        filippo.io/edwards25519@v1.1.1
        go.opentelemetry.io/otel/sdk@v1.40.0

  - uses: go/build
    with:
      packages: ./cmd/temporal
      output: temporal
      go-package: go-fips-1.26

  - uses: strip

subpackages:
  - name: temporal-compat-fips
    description: "Compat package for temporal"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/temporal "${{targets.contextdir}}"/usr/local/bin
    test:
      pipeline:
        - runs: |
            readlink -v /usr/local/bin/temporal

update:
  enabled: true
  github:
    identifier: temporalio/cli
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - uses: test/go-fips-check
    - runs: |
        temporal --help
    - runs: temporal --version
