package:
  name: volsync-fips
  version: "0.14.0"
  epoch: 2 # CVE-2025-61730
  description: Asynchronous data replication for Kubernetes volumes
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - acl
      - openssh
      - openssh-client
      - openssh-server
      - openssl
      - openssl-config-fipshardened
      - perl
      - rsync
      - stunnel # rclone, restic, syncthing will be added at image level since those are not required at runtime for volsync to work

environment:
  contents:
    packages:
      - rsync

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/backube/volsync
      tag: v${{package.version}}
      expected-commit: 6cbd2baf9ff1000a8aa96ff5f6b5a4fb4638ba48

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.45.0

  - uses: go/build
    with:
      ldflags: -X=main.volsyncVersion=v${{package.version}}
      packages: ./cmd
      output: manager
      go-package: go-fips-md5

  - name: "copy mover scripts"
    runs: |
      mkdir -p ${{targets.contextdir}}/mover-rclone \
               ${{targets.contextdir}}/mover-restic \
               ${{targets.contextdir}}/mover-rsync \
               ${{targets.contextdir}}/mover-rsync-tls \
               ${{targets.contextdir}}/mover-syncthing

      # copy rclone scripts
      cp mover-rclone/active.sh ${{targets.contextdir}}/mover-rclone/
      chmod a+rx ${{targets.contextdir}}/mover-rclone/*.sh

      # copy restic scripts
      cp mover-restic/entry.sh ${{targets.contextdir}}/mover-restic/
      chmod a+rx ${{targets.contextdir}}/mover-restic/*.sh

      # copy rsync(ssh) scripts
      cp mover-rsync/source.sh ${{targets.contextdir}}/mover-rsync/
      cp mover-rsync/destination.sh ${{targets.contextdir}}/mover-rsync/
      cp mover-rsync/destination-command.sh ${{targets.contextdir}}/mover-rsync/
      chmod a+rx ${{targets.contextdir}}/mover-rsync/*.sh

      mkdir -p "${{targets.contextdir}}/etc/ssh/sshd_config.d" \
             "${{targets.contextdir}}/usr/local/bin"

      install -m0755 /usr/bin/rrsync "${{targets.contextdir}}/usr/local/bin/rrsync" && \

      cat > "${{targets.contextdir}}/etc/ssh/sshd_config.d/volsync.conf" <<EOF
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      AllowTcpForwarding no
      X11Forwarding no
      PermitTunnel no
      PidFile /tmp/sshd.pid
      UsePAM no
      HostKey /etc/ssh/ssh_host_rsa_key
      EOF

      # copy rsync-tls scripts
      cp mover-rsync-tls/client.sh ${{targets.contextdir}}/mover-rsync-tls/
      cp mover-rsync-tls/server.sh ${{targets.contextdir}}/mover-rsync-tls/
      chmod a+rx ${{targets.contextdir}}/mover-rsync-tls/*.sh

      # copy syncthing scripts + templates
      cp mover-syncthing/config-template.xml ${{targets.contextdir}}/mover-syncthing/
      cp mover-syncthing/stignore-template ${{targets.contextdir}}/mover-syncthing/
      cp mover-syncthing/entry.sh ${{targets.contextdir}}/mover-syncthing/
      chmod a+r ${{targets.contextdir}}/mover-syncthing/config-template.xml
      chmod a+r ${{targets.contextdir}}/mover-syncthing/stignore-template
      chmod a+rx ${{targets.contextdir}}/mover-syncthing/*.sh

  - name: "test"
    runs: |
      test -f "${{targets.contextdir}}/etc/ssh/sshd_config.d/volsync.conf"
      test -x "${{targets.contextdir}}/mover-rclone/active.sh"
      test -x "${{targets.contextdir}}/mover-restic/entry.sh"
      test -x "${{targets.contextdir}}/mover-rsync/source.sh"
      test -x "${{targets.contextdir}}/mover-rsync/destination.sh"
      test -x "${{targets.contextdir}}/mover-rsync/destination-command.sh"
      test -x "${{targets.contextdir}}/mover-rsync-tls/client.sh"
      test -x "${{targets.contextdir}}/mover-rsync-tls/server.sh"
      test -x "${{targets.contextdir}}/mover-syncthing/entry.sh"

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"
          ln -s ./usr/bin/manager "${{targets.contextdir}}/manager"
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
          with:
            allow-absolute: "true"

  - name: volsync-cli-fips
    description: CLI for volsync
    pipeline:
      - uses: go/build
        with:
          ldflags: -X=main.volsyncVersion=v${{package.version}}
          packages: ./kubectl-volsync
          output: kubectl-volsync
          go-package: go-fips-md5
    test:
      pipeline:
        - uses: test/go-fips-check
        - name: "basic test"
          runs: |
            # (TODO): grep for version. right now it returns 0.0.0 even after setting ldflags. same behaviour with upstream
            kubectl-volsync --version

  - name: ${{package.name}}-diskrsync-tcp
    description: CLI for volsync
    pipeline:
      - uses: go/build
        with:
          ldflags: |
            -X=main.volsyncVersion=v${{package.version}}
          packages: ./diskrsync-tcp
          output: diskrsync-tcp
          go-package: go-fips-md5
    test:
      pipeline:
        - uses: test/go-fips-check
        - uses: test/daemon-check-output
          with:
            start: |
              diskrsync-tcp --target --port 9000 --verbose --no-compress --control-file /tmp/diskrsync.done /tmp/recv.raw
            timeout: 20
            expected_output: "Listening for tcp connection"

update:
  enabled: true
  github:
    identifier: backube/volsync
    strip-prefix: v
    use-tag: true
  ignore-regex-patterns:
    - "-rc"
    - "helm-"

test:
  environment:
    environment:
      EXTERNAL_SNAPSHOTTER_VERSION: "release-6.0"
    contents:
      packages:
        - helm
        - curl
        - wait-for-it
  pipeline:
    - uses: test/go-fips-check
    - uses: test/kwok/cluster
    - uses: test/daemon-check-output
      with:
        setup: |
          helm repo add backube https://backube.github.io/helm-charts/
          helm template backube/volsync \
            --version ${{package.version}} \
            --set manageCRDs=true \
            --show-only templates/volsync.backube_replicationdestinations.yaml \
            --show-only templates/volsync.backube_replicationsources.yaml \
          | kubectl apply -f -
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${EXTERNAL_SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${EXTERNAL_SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${EXTERNAL_SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
        start: |
          timeout 2s manager --kubeconfig="$KUBECONFIG" --metrics-bind-address=127.0.0.1:18080 --health-probe-bind-address=127.0.0.1:18081
        timeout: 20
        expected_output: "Registered Movers"
        post: |
          wait-for-it localhost:18080 -t 15
          curl -fsSL http://localhost:18080/metrics | grep "volsync"
