package:
  name: yace-fips
  version: "0.63.0"
  epoch: 0 # CVE-2025-47906
  description: Prometheus exporter for AWS CloudWatch.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/yet-another-cloudwatch-exporter
      tag: v${{package.version}}
      expected-commit: a3f067d8a19470dade70f15615bde9cc83c72e82

  - uses: go/build
    with:
      packages: ./cmd/yace
      ldflags: |-
        -X github.com/prometheus/common/version.Version=${{package.version}}
        -X github.com/prometheus/common/version.Revision=$(git rev-parse HEAD)
        -X github.com/prometheus/common/version.Branch=v${{package.version}}
        -X github.com/prometheus/common/version.BuildUser=$(whoami)@$HOSTNAME
        -X github.com/prometheus/common/version.BuildDate=$(date -u -d "@$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")
      output: yace
      go-package: go-fips

  - runs: |
      mkdir -p ${{targets.destdir}}/etc/yace
      mv examples/ec2.yml ${{targets.destdir}}/etc/yace/config.yml

update:
  enabled: true
  github:
    identifier: prometheus-community/yet-another-cloudwatch-exporter
    strip-prefix: v

test:
  pipeline:
    - uses: test/go-fips-check
    - name: Verify yace installation
      runs: |
        yace version
        yace --version
        yace --help
    - name: Verify Sample config file
      runs: |
        test -s "../../etc/yace/config.yml"
