#!/usr/bin/env bash
declare  -ra prohibited_kmods=(
	atm
	bluetooth
	can
	cramfs
	dccp
	firewire-core
	freevxfs
	hfs
	hfsplus
	jffs2
	rds
	sctp
	squashfs
	tipc
	udf
	usb-storage
)

declare -a sysctl_common=(
	"kernel.randomize_va_space = 2"
	"kernel.yama.ptrace_scope = 1"
	"net.ipv6.conf.all.accept_ra = 0"
	"net.ipv6.conf.all.accept_redirects = 0"
	"net.ipv6.conf.all.accept_source_route = 0"
	"net.ipv6.conf.all.forwarding = 0"
	"net.ipv6.conf.default.accept_ra = 0"
	"net.ipv6.conf.default.accept_redirects = 0"
	"net.ipv6.conf.default.accept_source_route = 0"
	"net.ipv4.conf.all.accept_redirects = 0"
	"net.ipv4.conf.all.accept_source_route = 0"
	"net.ipv4.conf.all.log_martians = 1"
	"net.ipv4.conf.all.rp_filter = 1"
	"net.ipv4.conf.all.secure_redirects = 0"
	"net.ipv4.conf.default.accept_redirects = 0"
	"net.ipv4.conf.default.accept_source_route = 0"
	"net.ipv4.conf.default.log_martians = 1"
	"net.ipv4.conf.default.rp_filter = 1"
	"net.ipv4.conf.default.secure_redirects = 0"
	"net.ipv4.icmp_echo_ignore_broadcasts = 1"
	"net.ipv4.icmp_ignore_bogus_error_responses = 1"
	"net.ipv4.tcp_syncookies = 1"
	"net.ipv4.conf.all.send_redirects = 0"
	"net.ipv4.conf.default.send_redirects = 0"
	"net.ipv4.ip_forward = 0"
)

usage()
{
	cat << EOF
usage: ${0##*/} --profile PROFILE [--runtime-remediate] [--sysroot SYSROOT]

  Apply system hardening measures to a directory tree.

    options:

      -h | --help               show this help text
           --profile PROFILE    which set of hardening measures to apply,
                                only valid profile currently is: cis-level-1
           --runtime-remediate  restart services, reload configuration
           --sysroot SYSROOT    filesystem root of the system to harden,
                                defaults to /
EOF
}

bad_usage()
{
	{
		echo "error: $*"
		echo
		usage
	} >&2
	exit 1
}

stderr()
{
	echo "$*" >&2
}

bail()
{
	stderr "FATAL: $*"
	exit 1
}

harden_cis_l1_fs_permissions()
{
	if [ -e "${sysroot}/etc/shadow" ]; then
		chmod 0000 "${sysroot}/etc/shadow"
	fi
	if [ -e "${sysroot}/etc/shadow-" ]; then
		chmod 0000 "${sysroot}/etc/shadow-"
	fi
}

apply_sshd_config()
{
	local -r option=$1 value=$2

	local -r sshd_config="${sysroot}/etc/ssh/sshd_config"
	local -r expected="${option} ${value}"

	sed -Ei "s|^#?${option}\s.*|${expected}|" "${sshd_config}"
	if grep -Eq "^${expected}$" "${sshd_config}"; then
		return 0
	fi

	printf '%s\n' "${expected}" >> "${sshd_config}"
}

harden_cis_l1_sshd()
{
	local -Ar settings=(
		[ClientAliveCountMax]=1 # TODO: update policy: 3
		[ClientAliveInterval]=900 # TODO: update policy: 15
		[HostbasedAuthentication]=no
		[PermitEmptyPasswords]=no
		[IgnoreRhosts]=yes
		[PermitRootLogin]=no
		[PermitUserEnvironment]=no
		[UsePAM]=yes
		[Banner]=/etc/issue.net
		[AllowUsers]="ec2-user linky" # TODO: customize or fix policy check
		[LoginGraceTime]=60
		[LogLevel]=VERBOSE
		[MaxAuthTries]=4
		[MaxSessions]=10
		[MaxStartups]=10:30:60
	)

	for option in "${!settings[@]}"; do
		local value=${settings[${option}]}
		if ! apply_sshd_config "${option}" "${value}"; then
			bail "Failed to configure sshd with '${option} ${value}'"
		fi
	done

	chmod 0600 "${sysroot}/etc/ssh/sshd_config" # TODO: do in openssh-server package by default
	chmod -R 0600 "${sysroot}/etc/ssh/sshd_config.d" # TODO: do in openssh-server package by default

	if [[ ${runtime_remediate} == yes ]]; then
		sudo systemctl restart sshd.service
	fi
}

harden_cis_l1_login_banners()
{
	echo 'Authorized users only. All activity may be monitored and reported.' > "${sysroot}/etc/issue"
	echo 'Authorized users only. All activity may be monitored and reported.' > "${sysroot}/etc/issue.net"
}

harden_cis_l1_sysctl()
{
	local -r sysctl_config="${sysroot}/usr/lib/sysctl.d/90-cis.conf"

	{
		for tunable in "${sysctl_common[@]}"; do
			echo "${tunable}"
		done
	} > "${sysctl_config}"

	# Uncomment other distro-owned sysctl settings that would compete with
	# the ones just written.
	# TODO: enhance rule checks to take into account ordering of fragments
	local -a sysctls
	mapfile -t sysctls < <(awk '$2 == "=" && $1 !~ /^-/ { print $1 }' "${sysctl_config}")

	local sysctl_fragment
	for sysctl_fragment in "$(dirname "${sysctl_config}")"/*; do
		if [[ "$(basename "${sysctl_config}")" == "$(basename "${sysctl_fragment}")" ]]; then
			continue
		fi

		for sysctl in "${sysctls[@]}"; do
			sed -i "s/^${sysctl} =/# CIS: ${sysctl} = /" "${sysctl_fragment}"
		done
	done

	if [[ ${runtime_remediate} == yes ]]; then
		sudo systemctl restart systemd-sysctl.service
	fi
}

harden_cis_l1_shell_profile()
{
	# TODO: enhance rule check for TMOUT to recognize POSIX-compliant setting

	cat << "EOF" > "${sysroot}/etc/profile"

# CIS
umask 077

: <<COMMENT
The OVAL check in ComplianceAsCode is looking for a literal

   declare -xr TMOUT=600

but this is not POSIX compliant and not supported by busybox' shell. Use only
POSIX behavior instead:
COMMENT
readonly TMOUT=600; export TMOUT
EOF
}

harden_cis_l1_bash()
{
	local -r bashrc="${sysroot}/etc/bash.bashrc"

	cat << "EOF" >> "${bashrc}"

# CIS
umask 077
EOF
	# TODO: See https://github.com/chainguard-dev/complianceascode-content/pull/2
	# TODO: and https://github.com/chainguard-dev/internal-dev/issues/20223
	local -r compat_symlink="${bashrc%/*}/bashrc"
	ln -sf bash.bashrc "${compat_symlink}"
}

apply_journald_config()
{
	local -r option=$1 value=$2

	local -r journald_config="${sysroot}/etc/systemd/journald.conf"
	local -r expected="${option}=${value}"

	sed -Ei "s|^#?${option}\s.*|${expected}|" "${journald_config}"
	if grep -Eq "^${expected}$" "${journald_config}"; then
		return 0
	fi

	printf '%s\n' "${expected}" >> "${journald_config}"
}

harden_cis_l1_journald()
{
	apply_journald_config Storage persistent
	apply_journald_config Compress yes
	apply_journald_config ForwardToSyslog no

	ln -sf /dev/null "${sysroot}/etc/systemd/system/systemd-journal-remote.socket"
	if [[ ${runtime_remediate} == yes ]]; then
		sudo systemctl restart systemd-journald.service
	fi
}

harden_cis_l1_mount_options()
{
	cat << "EOF" >> "${sysroot}/etc/fstab"
tmpfs /dev/shm tmpfs nodev,noexec,nosuid 0 0
tmpfs /tmp tmpfs nodev,noexec,nosuid 0 0
EOF
	if [[ ${runtime_remediate} == yes ]]; then
		mount -o remount,nodev,noexec,nosuid /dev/shm
		mount -o remount,nodev,noexec,nosuid /tmp
	fi
}

harden_cis_l1_kmods()
{
	{
		for kmod in "${prohibited_kmods[@]}"; do
			echo "blacklist ${kmod}"
			echo "install ${kmod} /bin/false"
		done
	} > "${sysroot}/etc/modules-load.d/cis.conf"
}

harden_cis_l1_coredumps()
{
	local -r coredump_config="${sysroot}/etc/systemd/coredump.conf.d/90-cis.conf"

	mkdir -p "$(dirname "${coredump_config}")"
	cat << "EOF" > "${coredump_config}"
[Coredump]
Storage = none
ProcessSizeMax = 0
EOF
}

harden_cis_l1_sudo()
{
	cat << "EOF" > "${sysroot}/etc/sudoers.d/10-cis.conf"
Defaults use_pty
Defaults timestamp_timeout = 15
EOF
}

harden_cis_level_1()
{
	harden_cis_l1_fs_permissions
	harden_cis_l1_sshd
	harden_cis_l1_login_banners
	harden_cis_l1_sysctl
	harden_cis_l1_shell_profile
	harden_cis_l1_bash
	harden_cis_l1_journald
	harden_cis_l1_mount_options
	harden_cis_l1_kmods
	harden_cis_l1_coredumps
	harden_cis_l1_sudo
}

harden_stig_sshd()
{
	local -Ar settings=(
		[ClientAliveCountMax]=1 # TODO: update policy: 3
		[ClientAliveInterval]=600 # TODO: update policy: 15
		[HostbasedAuthentication]=no
		[PermitEmptyPasswords]=no
		[IgnoreRhosts]=yes
		[PermitRootLogin]=no
		[PermitUserEnvironment]=no
		[UsePAM]=yes
		[Banner]=/etc/issue
		[AllowUsers]="ec2-user linky" # TODO: customize or fix policy check
		[LoginGraceTime]=60
		[LogLevel]=VERBOSE
		[MaxAuthTries]=4
		[MaxSessions]=10
		[MaxStartups]=10:30:60
		[Compression]=no
		[GSSAPIAuthentication]=no
		[IgnoreUserKnownHosts]=yes
		[KerberosAuthentication]=no
		[PrintLastLog]=yes
		[PubkeyAuthentication]=yes
		[RekeyLimit]="1G 1h"
		[StrictModes]=yes
		[X11Forwarding]=no
		[X11UseLocalhost]=yes
	)

	for option in "${!settings[@]}"; do
		local value=${settings[${option}]}
		if ! apply_sshd_config "${option}" "${value}"; then
			bail "Failed to configure sshd with '${option} ${value}'"
		fi
	done

	chmod 0600 "${sysroot}/etc/ssh/sshd_config" # TODO: do in openssh-server package by default
	chmod -R 0600 "${sysroot}/etc/ssh/sshd_config.d" # TODO: do in openssh-server package by default

	if [[ ${runtime_remediate} == yes ]]; then
		sudo systemctl restart sshd.service
	fi
}

harden_stig_mount_options()
{
	harden_cis_l1_mount_options
}

harden_stig_login_banners()
{
	echo "I've read & consent to terms in IS user agreem't." > "${sysroot}/etc/issue"
}

harden_stig_sysctl()
{
	local -r sysctl_config="${sysroot}/usr/lib/sysctl.d/91-stig.conf"

	{
		for tunable in "${sysctl_common[@]}"; do
			echo "${tunable}"
		done
	} > "${sysctl_config}"

	declare -ra sysctl_stig=(
		"fs.protected_hardlinks=1"
		"fs.protected_symlinks=1"
		"kernel.core_pattern=|/bin/false"
		"kernel.dmesg_restrict=1"
		"kernel.kexec_load_disabled=1"
		"kernel.kptr_restrict = 1"
		"kernel.perf_event_paranoid=2"
		"kernel.randomize_va_space=2"
		"kernel.unprivileged_bpf_disabled=1"
		"kernel.yama.ptrace_scope=1"
		"net.core.bpf_jit_harden=2"
		"net.ipv4.conf.all.accept_redirects=0"
		"net.ipv4.conf.all.accept_source_route=0"
		"net.ipv4.conf.all.forwarding=0"
		"net.ipv4.conf.all.log_martians=1"
		"net.ipv4.conf.all.rp_filter=1"
		"net.ipv4.conf.all.send_redirects=0"
		"net.ipv4.conf.default.accept_redirects=0"
		"net.ipv4.conf.default.accept_source_route=0"
		"net.ipv4.conf.default.log_martians=1"
		"net.ipv4.conf.default.rp_filter=1"
		"net.ipv4.conf.default.send_redirects=0"
		"net.ipv4.icmp_echo_ignore_broadcasts=1"
		"net.ipv4.icmp_ignore_bogus_error_responses=1"
		"net.ipv4.tcp_invalid_ratelimit=500"
		"net.ipv4.tcp_syncookies=1"
		"net.ipv6.conf.all.accept_ra=0"
		"net.ipv6.conf.all.accept_redirects=0"
		"net.ipv6.conf.all.accept_source_route=0"
		"net.ipv6.conf.all.forwarding=0"
		"net.ipv6.conf.default.accept_ra=0"
		"net.ipv6.conf.default.accept_redirects=0"
		"net.ipv6.conf.default.accept_source_route=0"
	)

	{
		for tunable in "${sysctl_stig[@]}"; do
			echo "${tunable}"
		done
	} >> "${sysctl_config}"

	# Uncomment other distro-owned sysctl settings that would compete with
	# the ones just written.
	# TODO: enhance rule checks to take into account ordering of fragments
	local -a sysctls
	mapfile -t sysctls < <(awk '$2 == "=" && $1 !~ /^-/ { print $1 }' "${sysctl_config}")

	local sysctl_fragment
	for sysctl_fragment in "$(dirname "${sysctl_config}")"/*; do
		if [[ "$(basename "${sysctl_config}")" == "$(basename "${sysctl_fragment}")" ]]; then
			continue
		fi

		for sysctl in "${sysctls[@]}"; do
			sed -i "s/^${sysctl} =/# STIG: ${sysctl} = /" "${sysctl_fragment}"
		done
	done

	# Remove conflicting configuration
	if [ -e "${sysroot}/usr/lib/sysctl.d/50-coredump.conf" ]; then
		sed -i 's|^kernel.core_pattern.*||g' "${sysroot}/usr/lib/sysctl.d/50-coredump.conf"
	fi

	if [[ ${runtime_remediate} == yes ]]; then
		sudo systemctl restart systemd-sysctl.service
	fi
}

harden_stig_kmods()
{
	{
		for kmod in "${prohibited_kmods[@]}"; do
			echo "blacklist ${kmod}"
			echo "install ${kmod} /bin/false"
		done
	} > "${sysroot}/etc/modules-load.d/stig.conf"
}

harden_stig_systemd_target()
{
	ln -sf /usr/lib/systemd/system/multi-user.target "${sysroot}/etc/systemd/system/default.target"
}

apply_pwquality_config()
{
	local -r option=$1 value=$2

	local -r pwquality_config="${sysroot}/etc/security/pwquality.conf"
	local -r expected="${option} = ${value}"

	sed -Ei "s|^#\s*?${option}\s.*|${expected}|" "${pwquality_config}"
	if grep -Eq "^${expected}$" "${pwquality_config}"; then
		return 0
	fi

	printf '%s\n' "${expected}" >> "${pwquality_config}"
}

harden_stig_pam()
{
	declare -Ar pwconfigs=(
		[retry]=3
		[dcredit]=-1
		[dictcheck]=1
		[difok]=8
		[lcredit]=-1
		[maxclassrepeat]=4
		[maxrepeat]=3
		[minclass]=4
		[minlen]=15
		[ocredit]=-1
		[ucredit]=-1
	)

	for option in "${!pwconfigs[@]}"; do
		local value=${pwconfigs[${option}]}
		if ! apply_pwquality_config "${option}" "${value}"; then
			bail "Failed to configure pwquality with '${option} ${value}'"
		fi
	done

	sed -i "s|^# enforce_for_root|enforce_for_root|g" "${sysroot}/etc/security/pwquality.conf"

	sed -i '/^auth.*sufficient.*pam_rootok.so/a auth required pam_wheel.so use_uid' "${sysroot}/etc/pam.d/su"

	sed -i '/^auth.*sufficient.*pam_rootok.so/a auth required pam_wheel.so use_uid' "${sysroot}/etc/pam.d/su"
	for i in base-password base-auth base-account; do
		sed -i '/^password required/i password requisite pam_pwquality.so' "${sysroot}/etc/pam.d/$i"
		sed -i 's|nullok||g' "${sysroot}/etc/pam.d/$i"
		sed -i 's/^\(password.*pam_unix\.so.*\)$/\1 rounds=100000/' "${sysroot}/etc/pam.d/$i"
		sed -i 's/^password.*required.*pam_unix\.so/password sufficient pam_unix.so/' "${sysroot}/etc/pam.d/$i"
		if ! grep -q pam_faillock.so "${sysroot}/etc/pam.d/$i"; then
			echo 'auth        required      pam_faillock.so preauth silent' >> "${sysroot}/etc/pam.d/$i"
			echo 'auth        sufficient    pam_unix.so try_first_pass' >> "${sysroot}/etc/pam.d/$i"
			echo 'auth        required      pam_faillock.so authfail' >> "${sysroot}/etc/pam.d/$i"
			echo 'account     required      pam_faillock.so' >> "${sysroot}/etc/pam.d/$i"
			echo 'account     required      pam_unix.so' >> "${sysroot}/etc/pam.d/$i"
		fi
	done
	# TODO: fix the benchmark to search our own paths
	ln -sf /etc/pam.d/base-password "${sysroot}/etc/pam.d/password-auth"
	ln -sf /etc/pam.d/base-password "${sysroot}/etc/pam.d/system-auth"

	cat > "${sysroot}/etc/pam.d/postlogin" << 'EOF'
#%PAM-1.0
# Display last login/logon information
session     optional      pam_lastlog.so showfailed
EOF
}

harden_stig_systemd_ctrlaltdel()
{
	sed -i "s|^#?*CtrlAltDelBurstAction.*|CtrlAltDelBurstAction=none|g" "${sysroot}/etc/systemd/system.conf"
	ln -sf /dev/null "${sysroot}/etc/systemd/system/ctrl-alt-del.target"
	ln -sf /dev/null "${sysroot}/etc/systemd/system/debug-shell.service"
}

harden_stig_systemd_coredump()
{
	sed -i "s|^#?*Storage.*|Storage=none|g" "${sysroot}/etc/systemd/coredump.conf"
	sed -i "s|^#?*ProcessSizeMax.*|ProcessSizeMax=0|g" "${sysroot}/etc/systemd/coredump.conf"
	ln -sf /dev/null "${sysroot}/etc/systemd/system/systemd-coredump.socket"
}

harden_stig_fixnews()
{
	chown 0:0 "${sysroot}/usr/lib/news"
}

harden_stig_faillock()
{
	sed -i 's|^# dir = .*|dir = /var/log/faillock|' "${sysroot}/etc/security/faillock.conf"
	sed -i 's/^# audit/audit/' "${sysroot}/etc/security/faillock.conf"
	sed -i 's/^# deny = .*/deny = 3/' "${sysroot}/etc/security/faillock.conf"
	sed -i 's/^# even_deny_root/even_deny_root/' "${sysroot}/etc/security/faillock.conf"
	sed -i 's/^# fail_interval.*/fail_interval = 900/' "${sysroot}/etc/security/faillock.conf"
	sed -i 's/^# unlock_time.*/unlock_time = 0/' "${sysroot}/etc/security/faillock.conf"
}

harden_stig_logindefs()
{
	echo "PASS_MAX_DAYS 60" >> "${sysroot}/etc/login.defs"
	echo "PASS_MIN_DAYS 1" >> "${sysroot}/etc/login.defs"
	echo "ENCRYPT_METHOD SHA512" >> "${sysroot}/etc/login.defs"
	echo "FAIL_DELAY 4" >> "${sysroot}/etc/login.defs"
	echo "CREATE_HOME yes" >> "${sysroot}/etc/login.defs"
	echo "UMASK 077" >> "${sysroot}/etc/login.defs"
}

harden_stig_limits()
{
	echo "* hard maxlogins 10" >> "${sysroot}/etc/security/limits.conf"
	echo "* hard core 0" >> "${sysroot}/etc/security/limits.conf"
}

harden_stig_selinux_sudo()
{
	cat << "EOF" > "${sysroot}/etc/sudoers.d/11-stig-selinux.conf"
%wheel ALL=(ALL) TYPE=sysadm_t ROLE=sysadm_r ALL
EOF
}

harden_stig()
{
	harden_stig_sshd
	harden_stig_mount_options
	harden_stig_login_banners
	harden_stig_sysctl
	harden_stig_kmods
	harden_stig_systemd_target
	harden_stig_pam
	harden_stig_systemd_ctrlaltdel
	harden_stig_systemd_coredump
	harden_stig_fixnews
	harden_stig_faillock
	harden_stig_logindefs
	harden_stig_limits
	harden_stig_selinux_sudo
}

main()
{
	local short_opts='h'
	local long_opts='help,profile:,sysroot:,runtime-remediate'
	local getopt_out

	if getopt_out=$(getopt --name "${0##*/}" --options "${short_opts}" --long "${long_opts}" -- "$@"); then
		eval set -- "${getopt_out}"
	else
		Usage 1>&2
		exit 1
	fi

	# Intentionally global
	profile=
	sysroot=/
	runtime_remediate=no

	while [[ $# -ne 0 ]]; do
		cur=$1
		next=$2
		case ${cur} in
			-h | --help)
				usage
				exit 0
				;;
			--profile)
				profile=${next}
				shift
				;;
			--sysroot)
				sysroot=${next}
				shift
				;;
			--runtime-remediate)
				runtime_remediate=yes
				;;
		esac
		shift
	done

	[[ -z ${profile} ]] && bad_usage 'require a --profile to be given'

	sysroot=${sysroot%%/}

	case ${profile} in
		cis-level-1)
			harden_cis_level_1
			;;
		stig)
			harden_stig
			;;
		*)
			bail "invalid --profile '${profile}', valid profiles are 'cis-level-1' or 'stig'"
			;;
	esac
}

main "$@"
