name: export-os

on:
  schedule:
    # Daily @ 2pm UTC, 9am ET, 6am PT
    - cron: "0 14 * * *"
  workflow_dispatch: {}

permissions: {}

jobs:
  export:
    uses: ./.github/workflows/.export-to-staging.yaml
    permissions:
      contents: read
      id-token: write
    with:
      source_path: os
      staging_repo: chainguard-dev/wolfi-staging
      horizon: 'a215544991c495ce03efda17eeb693687d3d6d87'
      # https://github.com/chainguard-dev/stereo/pull/11392 symlinked these out of the os/
      # directory, so we need to exclude them when we export.
      excluded_paths: '[".claude/", ".claude/**", "CLAUDE.md"]'
      octo_sts_identity: 'stereo'
      pr_title_prefix: 'Export stereo/os'
      pr_body_workflow_name: 'export-os'
      create_pr_events: '["schedule"]'
