# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "Reproducible builds Pre-submit check"

on:
  pull_request_target:
    branches:
      - "main"

permissions: {}

jobs:
  reproducible-check:
    if: ${{ github.repository == 'chainguard-dev/wolfi-vm' }}

    runs-on: ubuntu-8-core

    permissions:
      id-token: write # federated identity
      contents: read # read repo

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: chainguard-dev/actions/apt-faster@cd899cc96227b82170571cad1c3d6378d8cba678 # v1.4.15

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - uses: chainguard-dev/setup-chainctl@be0acd273acf04bfdf91f51198327e719f6af978 # v0.4.0
        with:
          identity: "ce2d1984a010471142503340d670612d63ffb9f6/bd9fd6bb14892849"

      - name: Get apk.cgr.dev token
        shell: bash
        run: |
          chainctl auth login --identity=${CG_IDENTITY} --audience=apk.cgr.dev
          cred=$(chainctl auth token --audience=apk.cgr.dev)
          echo "HTTP_AUTH=basic:apk.cgr.dev:user:$cred" >> $GITHUB_ENV
        env:
          CG_IDENTITY: "ce2d1984a010471142503340d670612d63ffb9f6/bd9fd6bb14892849"

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: stable
          check-latest: true

      - name: Install deps
        shell: bash
        run: |
          make install-deps

      - name: make clean
        shell: bash
        run: |
          make clean

      - name: make apkoaas
        shell: bash
        run: |
          make apkoaas

      - name: make builder
        shell: bash
        run: |
          make builder

      - name: make disk 1/2
        shell: bash
        run: |
          mkdir run1
          cd run1 && ../apkoaas build --builder-cpio ../builder/initrd-x86_64 --kernel ../builder/kernel-x86_64 ../configs/test/reproducible/build.yaml
          cd ..

      - name: make disk 2/2
        shell: bash
        run: |
          mkdir run2
          cd run2 && ../apkoaas build --builder-cpio ../builder/initrd-x86_64 --kernel ../builder/kernel-x86_64 ../configs/test/reproducible/build.yaml
          cd ..

      - name: compare artifacts
        shell: bash
        run: |
          cmp run*/apko-x86_64.tar.gz || exit 1
          cmp run*/disk.raw || exit 1
