# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "QEMU Pre-submit check"

on:
  pull_request_target:
    branches:
      - "main"

permissions: {}

jobs:
  qemu-check:

    permissions:
      id-token: write # federated identity
      contents: read # read repo

    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64

    uses: ./.github/workflows/.presubmit.yaml
    with:
      cg_identity: "ce2d1984a010471142503340d670612d63ffb9f6/bd9fd6bb14892849"
      checkout_ref: refs/pull/${{ github.event.pull_request.number }}/merge
      cloud_provider: "qemu"
      arch: ${{ matrix.arch }}
