# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "GCP Pre-submit check"

on:
  pull_request_target:
    branches:
      - "main"

permissions: {}

jobs:
  gcp-check:
    if: ${{ github.repository == 'chainguard-dev/wolfi-vm' }}

    runs-on: ubuntu-8-core

    permissions:
      id-token: write # federated identity
      contents: read # read repo

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - uses: './.github/actions/build-disks'
        with:
          cg_identity: "ce2d1984a010471142503340d670612d63ffb9f6/bd9fd6bb14892849"
          cloud_provider: "gcp"
          arch: '${{ matrix.arch }}'
