name: Wolfictl Check Updates

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Check Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Get changed files
      id: files
      uses: tj-actions/changed-files@0874344d6ebbaa00a27da73276ae7162fadcaf69 # v44.3.0
      with:
        separator: ' '
        files: "*.yaml"

    - name: Check
      id: check
      uses: wolfi-dev/actions/wolfictl-check-updates@main # main
      if: ${{ steps.files.outputs.all_changed_files != '' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        changed_files: ${{ steps.files.outputs.all_changed_files }}
