name: Wolfictl Check Updates

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Check Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.0
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Get changed files
      id: files
      uses: tj-actions/changed-files@e9772d140489982e0e3704fea5ee93d536f1e275 # v45.0.1
      with:
        separator: ' '
        files: "*.yaml"
        files_ignore: ".yam.yaml"

    - name: Check
      id: check
      uses: wolfi-dev/actions/wolfictl-check-updates@main # main
      if: ${{ steps.files.outputs.all_changed_files != '' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        changed_files: ${{ steps.files.outputs.all_changed_files }}
