name: Wolfictl Check Updates

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Check Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - name: Get changed files
      id: files
      uses: tj-actions/changed-files@aa08304bd477b800d468db44fe10f6c61f7f7b11 # v42.1.0
      with:
        separator: ' '
        files: "*.yaml"

    - name: Check
      id: check
      uses: wolfi-dev/actions/wolfictl-check-updates@main
      if: ${{ steps.files.outputs.all_changed_files != '' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        changed_files: ${{ steps.files.outputs.all_changed_files }}
